(function () {
'strict'
var markdownContent = ''
+ "# Anti-HIV & Antiviral Agents\n"
+ "\n"
+ "<hr>\n"
+ "\n"
+ "[Hour 1](#/hour1) | [Hour 2](#/hour2)\n"
+ "\n"
+ "Hao Chen, Ph.D\n"
+ "\n"
+ "hchen@uthsc.edu Dept. Pharmacology, UTHSC\n"
+ "\n"
+ "Please use the live online version at http://chen42.github.io/slides/antiviral.html\n"
+ "\n"
+ "Or download the [**Printable version that can be saved as a pdf file**](http://chen42.github.io/slides/antiviral.html?print-pdf#/).\n"
+ "\n"
+ "<b>Last update: Oct 28th, 2025</b>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Formatting conventions\n"
+ "\n"
+ "### used in this document\n"
+ "\n"
+ "- Color and style guide:\n"
+ "  - Drug name: <span id=\"drug\"> Enfuvirtide</span>\n"
+ "  - Links: [Clinicalkey](https://www.clinicalkey.com/#!/).\n"
+ "    - Shade change when mousing over indicates the image or text has a link\n"
+ "    - You need to login via your UTHSC netid when off campus to use e-textbooks.\n"
+ "    - [VPN](http://uthsc.edu/vpn/) provides a better experience.\n"
+ "- Open link in a new browser tab:\n"
+ "\n"
+ "```\n"
+ "CTRL click\n"
+ "```\n"
+ "\n"
+ "- Navigate the slides:\n"
+ "\n"
+ "```\n"
+ "<- or ->\n"
+ "Space_bar\n"
+ "Page_down or Page_up\n"
+ "Home or End\n"
+ "```\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"hour1\">\n"
+ "\n"
+ "## Agents for the treatment of virus infections\n"
+ "\n"
+ "### [Hour 1](#/hiv)\n"
+ "\n"
+ "- <a href=\"#/hiv\">Retrovirus (HIV)</a>\n"
+ "  - Fusion inhibitors <span id=\"drug\">[Enfuvirtide](#/Enfuvirtide)</span>\n"
+ "  - Nucleoside reverse transcriptase inhibitors <span id=\"drug\">[Lamivudine, Emtricitabine, Abacavir](#/nrti)</span>\n"
+ "  - Nucleotide inhibitors <span id=\"drug\">[Tenofovir](#/Tenofovir)</span>\n"
+ "  - Non-nucleoside reverse transcriptase inhibitors <span id=\"drug\">[Nevirapine](#/nnrti)</span>\n"
+ "  - Integrase strand transfer inhibitor <span id=\"drug\">[Bictegravir, Dolutegravir, Cabotegravir ](#/Integrase) </span>\n"
+ "  - Protease inhibitors <span id=\"drug\">[Darunavir, Ritonavir](#/pi) </span>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Objectives\n"
+ "\n"
+ "- Identify the <span id=\"yb\">steps in the viral replication process</span> that provide targets for antiviral therapy.\n"
+ "\n"
+ "- Understand the <span id=\"yb\">current guidline for HIV/AIDS treatment. </span>\n"
+ "\n"
+ "- Understand the <span id=\"yb\">current Initial Combination Regimens</span> for drug naive patent.\n"
+ "\n"
+ "- Describe the mechanism of action and significant pharmacological properties of the <span id=\"yb\">six major classes</span> of anti-HIV agents\n"
+ "\n"
+ "Note:\n"
+ "Try to come up a few questions for the yellow highlighted sections.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"hiv\">\n"
+ "\n"
+ "## Human Immunodeficiency Viruses\n"
+ "\n"
+ "<img src=\"./images/antiviral/hiv_structural_highlight.png\" width=60%>\n"
+ "\n"
+ "<div id=\"greyText\">\n"
+ "single, positive strand RNA \n"
+ "<br>\n"
+ "HIV-1 widely distributed, more pathogenic | HIV-2 restricted to Central and West africa\n"
+ "</div>\n"
+ "\n"
+ "Note:\n"
+ "Viral envelope, capsid is cone shaped, see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4876022/, Fig 1. legend\n"
+ "\n"
+ "Drug targets are highlighted using redish background\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## [Stages of AIDS](https://www.clinicalkey.com/#!/content/book/3-s2.0-B9780323611794000107?scrollTo=%23t0015)\n"
+ "\n"
+ "- Primary infection.\n"
+ "  - About 90% of patients develop a flu-like illness, which coincides with <a href=\"https://clinicalinfo.hiv.gov/en/glossary/seroconversion\" target=\"_new\"> seroconversion</a> (detectable HIV antibodies in blood), between 2 and 4 weeks post exposure. Symptoms include fever, night sweats, sore throat, lymphadenopathy, diarrhea. The illness is self-limiting.\n"
+ "- Asymptomatic phase.\n"
+ "  - Of variable duration, from 2 to 10 years. Patients are clinically well, but infectious.\n"
+ "- Acquired Immunodeficiency Syndrome (AIDS). Features:\n"
+ "  - Constitutional symptoms: fever, diarrhea, weight loss, skin rashes.\n"
+ "  - Immunodeficiency: increased susceptibility to opportunistic infections\n"
+ "  - Neurological disease: dementia, myelopathy, peripheral neuropathy\n"
+ "  - Rare malignancies: Kaposi sarcoma, oral hairy leukoplakia, or lymphoma\n"
+ "\n"
+ "Note:\n"
+ "\n"
+ "- seroconversion: antibody test is positive.\n"
+ "- should patents be treated if they are sympton free?\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## AIDS Timeline\n"
+ "\n"
+ "## <td> <img src=\"./images/antiviral/hiv_untreated.png\" width=80%> </td>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Current [guidelines](https://clinicalinfo.hiv.gov/en/guidelines/adult-and-adolescent-arv/initiation-antiretroviral-therapy?view=full)\n"
+ "\n"
+ "<b> The <span id=\"yb\"> Initiation </span> of Antiretroviral Therapy </b>\n"
+ "\n"
+ "- Antiretroviral therapy (ART) is recommended for all persons with HIV\n"
+ "\n"
+ "  - reduce morbidity and mortality\n"
+ "  - prevent the transmission of HIV to others\n"
+ "\n"
+ "- The Panel recommends initiating ART immediately after HIV diagnosis\n"
+ "\n"
+ "  - increase the uptake of ART and linkage to care,\n"
+ "  - decrease the time to viral suppression for individual patients,\n"
+ "  - improve the rate of virologic suppression among persons with HIV.\n"
+ "\n"
+ "- Educate patients\n"
+ "  - the benefits of ART\n"
+ "  - to deploy strategies to optimize care engagement\n"
+ "  - treatment adherence\n"
+ "\n"
+ "[HAART - cART - ART](https://clinicalinfo.hiv.gov/en/glossary/antiretroviral-therapy-art)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## HIV Life Cycle\n"
+ "\n"
+ "<table> <tr><td 50%>\n"
+ "<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/eS1GODinO8w\" frameborder=\"0\" allowfullscreen></iframe>\n"
+ "</td><td>\n"
+ "\n"
+ "<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/GR9d9wrOl5E\" frameborder=\"0\" allowfullscreen></iframe>\n"
+ "</td></tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## [HIV Lifecycle](https://en.wikipedia.org/wiki/Discovery_and_development_of_HIV-protease_inhibitors#Life_cycle_of_HIV)\n"
+ "\n"
+ "<img src=\"./images/antiviral/hiv_life_cycle_khan.png\" width=70%>\n"
+ "\n"
+ "1. _Initiation_: attachment, penetration, uncoating\n"
+ "2. _Replication_: genome synthesis, RNA production, protein synthesis\n"
+ "3. _Release_: assembly, maturation, exit from cell\n"
+ "\n"
+ "Note:\n"
+ "which stages of viral replication can be targeted for treatment?\n"
+ "The drug must kill the viral without kill the patient.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"recommend\">\n"
+ "\n"
+ "### [Current Guideline](https://clinicalinfo.hiv.gov/en/guidelines/adult-and-adolescent-arv/what-start-initial-combination-regimens-antiretroviral-naive?view=brief)\n"
+ "\n"
+ "<small>As of Sept 12, 2024, updated almost yearly in the last decade</small>\n"
+ "\n"
+ "<hr>\n"
+ "\n"
+ "##### Initial Regimens for most people with HIV who do not have a history of long-acting <span id=\"drug\"> Cabotegravir </span> use as PrEP\n"
+ "\n"
+ "- <span id=\"drug\"> Bictegravir </span> plus <span id=\"drug\"> tenofovir alafenamide </span> plus <span id=\"drug\"> emtricitabine </span>\n"
+ "- <span id=\"drug\"> Dolutegravir </span> plus (<span id=\"drug\">tenofovir alafenamide</span> or<span id=\"drug\"> tenofovir disoproxil fumarate</span>) plus (<span id=\"drug\">emtricitabine </span> or <span id=\"drug\"> lamivudine</span>)\n"
+ "- <span id=\"drug\"> Dolutegravir </span> plus <span id=\"drug\"> lamivudine </span>\n"
+ "  - except for\n"
+ "    - individuals with HIV RNA >500,000 copies/mL\n"
+ "    - HBV co-infection\n"
+ "    - ART is to be started before the results of HIV genotypic resistance testing for reverse transcriptase or HBV testing are available.\n"
+ "\n"
+ "<hr>\n"
+ "\n"
+ "##### For people who have a history of <span id=\"drug\">CAB-LA</span> use as PrEP, integrase strand transfer inhibitor genotype resistance testing should be performed before starting ART. If ART is to be started before results of genotypic testing results, the following regimen is recommended:\n"
+ "\n"
+ "- (<span id=\"drug\">Darunavir/cobicistat</span> or <span id=\"drug\">darunavir/Ritonavir</span>) plus (<span id=\"drug\">tenofovir alafenamide</span> or<span id=\"drug\"> tenofovir disoproxil fumarate</span>) plus (<span id=\"drug\">emtricitabine </span> or <span id=\"drug\"> lamivudine</span>)\n"
+ "\n"
+ "<hr>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## General principle of ART\n"
+ "\n"
+ "An antiretroviral regimen for a treatment-naive patient generally consists of\n"
+ "\n"
+ "- two reverse transcriptase inhibitors (one nucleo<font color=\"red\">s</font>ide and one nucleo<font color=\"red\">t</font>ide) in combination with a third active drug from one of three drug classes:\n"
+ "  - an integrase strand transfer inhibitor\n"
+ "  - a protease inhibitor with a pharmacokinetic enhancer (also known as a booster)\n"
+ "  - a non-nucleoside reverse transcriptase inhibitor (less common)\n"
+ "\n"
+ "Note:\n"
+ "\n"
+ "- ART is cART, a combination of drugs targeting multiple viral replication pathways.\n"
+ "- Past recommendation includes protease inhibitors. Current recommendation all include INSTI\n"
+ "- Need to understand the exceptions as well.\n"
+ "- click on the title link to read the full recommendation, DTG = dolutegravir; 3TC = lamivudine; TAF = tenofovir alafenamide (no need to memorize these acronyms)\n"
+ "- <span id=\"drug\"> Dolutegravir </span> plus <span id=\"drug\"> abacavir </span> plus <span id=\"drug\"> lamivudine </span> — only for individuals who are HLA-B\\*5701 negative and without chronic hepatitis B virus (HBV) coinfection\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"Integrase\">\n"
+ "\n"
+ "## In<font color=\"darkred\">tegra</font>se Inhibitor\n"
+ "\n"
+ "Bic<font color=\"darkred\">tegra</font>vir (Biktarvy) |\n"
+ "Dolu<font color=\"darkred\">tegra</font>vir (Tivicay) |\n"
+ "Cabo<font color=\"darkred\">tegra</font>vir (Vocabria) |\n"
+ "Ral<font color=\"darkred\">tegra</font>vir (Isentress) |\n"
+ "Elvi<font color=\"darkred\">tegra</font>vir\n"
+ "\n"
+ "<table><tr><td width=30%>\n"
+ "<img src=\"./images/antiviral/hiv_integration.png\"</img>\n"
+ "    <p>\n"
+ "    <a href=\"https://www.nature.com/articles/s41579-021-00586-9/figures/1\"> Nat rev microbiology</a>\n"
+ "\n"
+ "</td> <td>\n"
+ "<ul>\n"
+ "<li> <a href=\"#/sd\">Mechanism of action</a>\n"
+ "<ul>\n"
+ " <li> Binds to HIV-1 integrase and prevents strand transfer <br>\n"
+ " <li> Prevents insertion of viral DNA into host genome <p>\n"
+ " </ul>\n"
+ "\n"
+ "<li> ADME\n"
+ " <ul>\n"
+ " <li> Oral drug (one tablet daily)\n"
+ " <li> <span id=\"drug\">Cabotegravir</span> is also available as long-acting injectable. \n"
+ " <li> Glucuronidation and by CYP3A<br>\n"
+ " 	<li> <span id=drug> <a href=\"https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-5011\">Bictegravir </a> </span> is a substrate of P-glycoprotein. \n"
+ "	<li> Eliminated in both feces and urine <p>\n"
+ "</ul>\n"
+ "\n"
+ "<li> Resistance\n"
+ "<ul>\n"
+ "<li> <span id=\"drug\"> Dolutegravir </span> and <span id=\"drug\"> Bictegravir </span> potently inhibit most mutants selected by <span id=\"drug\">  Raltegravir </span> and <span id=\"drug\"> Elvitegravir </span>. \n"
+ "</ul>\n"
+ "</ul>\n"
+ "</td> </tr></table>\n"
+ "\n"
+ "Note:\n"
+ "\n"
+ "- <li> <span id=\"drug\"> Elvitegravir </span> is mainly metabolized by CYP3A4 <br>\n"
+ "- this class of drug is named by its MoA\n"
+ "- this class of drug is safer because human host cells do not integrate new DNA into its genome, so human cells do not use integrase.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Integrase Inhibitor\n"
+ "\n"
+ "- Indication\n"
+ "  - <a href=\"#/recommend\">Recommended</a> for naive patients as part of combination ART\n"
+ "  - <span id=\"drug\"> Cabotegravir </span> injecable once a month for pre-exposure prophylaxis (PrEP) in HIV naive individuals ([news report on FDA approval](https://www.statnews.com/pharmalot/2021/01/21/fda-hiv-aids-injectable/))\n"
+ "- Adverse effects\n"
+ "  - Diarrhea, nausea, headache, and fever\n"
+ "  - <a href=\"https://pubmed.ncbi.nlm.nih.gov/34524918/\">Hypersensitivity</a> to <span id=\"drug\"> Dolutegravir </span> include serious rash, blisters/peeling of skin, hepatitis, facial edema, angioedema, difficulty breathing, or eosinophilia.\n"
+ "- Drug interactions\n"
+ "  - Metabolized by UDP glucuronosyltransferase (UGT)\n"
+ "  - <span id=\"drug\"> Rifampin </span> (antibiotic) induces UGT, thus requires higher <span id=\"drug\"> Raltegravir / Dolutegravir </span> dose\n"
+ "\n"
+ "Note:\n"
+ "Among the five drugs, B and D are in the recommendations, C is a new drug (expensive injectable), R is relatively worese in drug resistance, E is a substrate of CYP3A4\n"
+ "<span id=drug>Bictegravir</span> displays a high resistance barrier and has an improved phenotypic resistance profile compared to <span id=drug>dolutegravir (DTG), raltegravir (RAL) and elvitegravir (EVG). Bictegravir </span> has a longer dissociation half-life from both wild-type and mutant HIV-1 integrase/DNA complexes compared with DTG, RAL, and EVG\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Commonly used integrase strand trasnfer inhibitors\n"
+ "\n"
+ "| Characteristic        | Bictegravir (BIC)                                                                                                  | Dolutegravir (DTG)                                                                                                      |\n"
+ "| --------------------- | ------------------------------------------------------------------------------------------------------------------ | ----------------------------------------------------------------------------------------------------------------------- |\n"
+ "| **Half-life**         | ~17 hours                                                                                                          | ~14 hours                                                                                                               |\n"
+ "| **Metabolism**        | <a href=\"https://pubmed.ncbi.nlm.nih.gov/33626178/\">CYP3A4 and UGT1A1 </a>                                         | <a href=\"https://pmc.ncbi.nlm.nih.gov/articles/PMC3719771/\"> UGT1A1 and minor CYP3A4 involvement </a>                   |\n"
+ "| **Drug Interactions** | Interacts with CYP3A4/UGT1A1 substrates                                                                            |\n"
+ "| **Side Effects**      | Headache, nausea, diarrhea, <a href=\"https://pubmed.ncbi.nlm.nih.gov/28219610/\">fewer neuropsychiatric effects</a> | Insomnia, headache, weight gain, <a href=\"https://pubmed.ncbi.nlm.nih.gov/39022519/\">more neuropsychiatric effects </a> |\n"
+ "| **Resistance**        | High barrier to resistance, effective against resistant strains                                                    | High barrier to resistance, but specific mutations (R263K) may cause resistance                                         |\n"
+ "| **Clinical Use**      | Commonly used in first-line treatment (e.g., Biktarvy: BIC/TAF/FTC)                                                | Widely used in both first-line and second-line treatment (e.g., DTG/3TC, TDF/FTC/DTG)                                   |\n"
+ "| **Role in Pregnancy** | Insufficient safety data, not recommended                                                                          | Preferred in pregnancy, with caution in early pregnancy                                                                 |\n"
+ "\n"
+ "<a href=\"#recommend\">Current guideline</a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"nrti\">\n"
+ "\n"
+ "## Nucleoside Reverse Transcriptase Inhibitors (NRTIs)\n"
+ "\n"
+ "- NRTIs\n"
+ "  - <span id=\"drug\" style=\"background-color:#ff9\">**Emtricitabine**</span> (Emtriva, FTC)\n"
+ "  - <span id=\"drug\" style=\"background-color:#ff9\">**Lamivudine**</span> (Epivir, 3TC)\n"
+ "  - <span id=\"drug\" style=\"background-color:#ff9\">**Abacavir**</span> (Ziagen, ABC)\n"
+ "  - many more available, some are no longer in use.\n"
+ "\n"
+ "Note:\n"
+ "\n"
+ "- <span id=\"drug\">Zidovudine</span> (Retrovir, azidothymidine [ZVD], Apo-Zidovudine, Novo-AZT)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Mechanism of action - NRTIs\n"
+ "\n"
+ "<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/cC9kyoAo1ac?start=65&list=PLMO1589WRspykVPiy6SgKi3OPKbe9b0El\" frameborder=\"0\" allowfullscreen></iframe>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"hostcell\">\n"
+ "\n"
+ "## Mechanisms of Action - NRTIs\n"
+ "\n"
+ "- Analogs of naturally occurring [nucleosides](http://static.newworldencyclopedia.org/b/b9/Nucleotides.png)\n"
+ "- NRTIS are converted to their active triphosphate metabolites (i.e. a nucleotide) by <span id=\"yb\">host cell </span>kinases\n"
+ "- Competitive inhibitor of viral reverse transcriptase\n"
+ "- Cause DNA chain termination\n"
+ "- Also inhibit host cell DNA polymerase\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nucleoside Reverse Transcriptase Inhibitors (NRTIs)\n"
+ "\n"
+ "- Indications\n"
+ "  - First line treatment of HIV infection as components of ART\n"
+ "  - Prevent acute infection of susceptible cells\n"
+ "  - Little effect on cells already infected by HIV\n"
+ "- Resistance\n"
+ "  - Drugs select for different mutations of the reverse transcriptase gene at the level of specific codons\n"
+ "\n"
+ "Note:\n"
+ "\n"
+ "- <span id=\"drug\"> Zidovudine </span>\n"
+ "  - <span id=\"yb\">passes placenta rapidly, reduce the rate of maternal-fetal HIV-1 transmission from <a href=\"https://www.nejm.org/doi/full/10.1056/nejm199411033311801\">25% to 8%</a> </a>\n"
+ "  - also used in neonates to <a href=\"https://clinicalinfo.hiv.gov/en/guidelines/pediatric-arv/zidovudine\">prevent perinatal transmission of HIV </a>.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Pharmacological Properties of NRTIs\n"
+ "\n"
+ "- Good oral absorption\n"
+ "- Crosses blood-brain barrier (NeuroAIDs)\n"
+ "- Metabolism plays limited role in clearance\n"
+ "- Excreted unchanged in urine\n"
+ "- <span id=\"drug\"> Abacavir </span> metabolized by alcohol dehydrogenase\n"
+ "\n"
+ "Note:\n"
+ ", except:\n"
+ "\n"
+ "- <span id=\"drug\"> Zidovudine </span> is metabolized to glucuronide\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Adverse Effects of NRTIs\n"
+ "\n"
+ "- Common toxicities\n"
+ "  - [Mitochondrial toxicity](https://www.uptodate.com/contents/mitochondrial-toxicity-of-hiv-nucleoside-reverse-transcriptase-inhibitors/) is a major adverse effect of nucleoside analogues, which can lead to myopathy, peripheral neuropathy, and hepatic steatosis with lactic acidosis\n"
+ "  - [Lactic acidosis](https://hivinfo.nih.gov/understanding-hiv/fact-sheets/hiv-and-lactic-acidosis), [hepatic steatosis](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6550355/)\n"
+ "  - [Lipodystrophy](https://www.ncbi.nlm.nih.gov/PubMed/10509567): fat loss or buildup or both.\n"
+ "    - Including central obesity, dorsocervical fat enlargement [(buffalo hump)](https://www.clinicalkey.com/#!/content/medline/2-s2.0-9525364), peripheral wasting, accumulation of facial fat, [lipomas](http://www.mayoclinic.org/diseases-conditions/lipoma/basics/definition/con-20024646), breast enlargement, [gynecomastia](http://www.mayoclinic.org/diseases-conditions/gynecomastia/home/ovc-20257576)\n"
+ "  - Rash; Gastrointestinal distress\n"
+ "- Drug specific side effects\n"
+ "  - <span id=\"drug\">Abacavir</span>: **hypersensitivity** reaction due to genetic predisposition (multi-organ autoimmune response, potentially life threatening)\n"
+ "    - <span id=\"yb\"><a href=\"http://genome.ucsc.edu/cgi-bin/hgTracks?db=hg38&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr6%3A31353875%2D31367067&hgsid=1488421281_ALYL8AoN0EV3FOejojvgWHHHoDaa\">HLA-B\\*5701</a> screening before starting therapy </span> [NEJM](http://www.nejm.org/doi/full/10.1056/NEJMoa0706135#t=article)\n"
+ "  - <span id=\"drug\"> Emtricitabine </span>: psychiatric reactions, depression, dizziness, insomnia\n"
+ "\n"
+ "Note:\n"
+ "These drugs inhibit DNA polymerase gamma, which replicates the mt genome.\n"
+ "https://journals.sagepub.com/doi/full/10.1177/0192623313503519\n"
+ "\n"
+ "- older generations suppresses bone marrow (e.g. Zidovudine)\n"
+ "- muscle has a lot of mtDNA\n"
+ "- these drugs penetrate the BBB\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"FTC\">\n"
+ "\n"
+ "## Most commonly used NRTI\n"
+ "\n"
+ "| Characteristic                  | Lamivudine (3TC)                                            | Emtricitabine (FTC)                                   |\n"
+ "| ------------------------------- | ----------------------------------------------------------- | ----------------------------------------------------- |\n"
+ "| **Bioavailability**             | ~85%                                                        | ~93%                                                  |\n"
+ "| **<a href=\"#/sd\">MoA</a>**      | Nucleoside analog that inhibits reverse transcriptase       |                                                       |\n"
+ "| **Dosing Frequency**            | Once or twice daily                                         | Once daily                                            |\n"
+ "| **Excretion**                   | Renal (requires dose adjustment in renal impairment)        |                                                       |\n"
+ "| **Common Side Effects**         | Pancreatitis, peripheral neuropathy, lactic acidosis (rare) | Skin discoloration, headache, gastrointestinal issues |\n"
+ "| **Resistance (M184V mutation)** | Confers resistance                                          |\n"
+ "| **Clinical Use**                | Used in combination ART regimens, DTG/3TC regimen           | Used in combination ART regimens, BIC/TAF/FTC regimen |\n"
+ "\n"
+ "[Current Recommendations](#/recommend)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"Tenofovir\">\n"
+ "\n"
+ "## Nucleo<font color=\"darkorange\">t</font>ide Reverse Transcriptase Inhibitor\n"
+ "\n"
+ "[Teno<font color=\"darkorange\">fo</font>vir disoproxil (Viread)](https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-2477)\n"
+ "\n"
+ "<span id=\"mem\"> fo=pho=phosphate</mem>\n"
+ "\n"
+ "- Properties\n"
+ "  - Tenofovir is an analogue of adenosine- <font color=\"darkorange\">5'-monophosphate </font>, with low oral bioavailability.\n"
+ "  - <span id=\"drug\"> Tenofovir disoproxil </span> is a prodrug. It is hydrolyzed to release tenofovir, increasing bioavailability.\n"
+ "  - Requires two intracellular phosphorylation steps for activation\n"
+ "  - Weak inhibitor of mammalian DNA and mt polymerase\n"
+ "  - Included in many <a href=\"#/recommend\"> first-line ART regimens</a>\n"
+ "  - Also indicated for <span id=\"bg\"> hepatitis B </span>\n"
+ "- <a href=\"#/sd\">Mechanism of action</a>\n"
+ "  - Inhibits viral reverse transcriptase by chain termination\n"
+ "- Resistance\n"
+ "  - <span id='bg'>Does not tend to select the K65R mutation when used with <span id=\"drug\">Emtricitabine</span></span> [PubMed](https://www.ncbi.nlm.nih.gov/pubmed/23027713)\n"
+ "  - Not affected by <span id=\"drug\"> lamivudine-abacavir </span> associated mutations\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Tenofovir\n"
+ "\n"
+ "- Administration\n"
+ "  - Once daily dosing\n"
+ "  - Increased bioavailability taken with a high fat meal\n"
+ "- Metabolism\n"
+ "  - Substrate of P-glycoprotein\n"
+ "  - Not substrate for P450\n"
+ "  - T&frac12; = 17 h\n"
+ "- Adverse effect\n"
+ "  - Most common: nausea, vomiting, diarrhea, flatulence, abdominal pain, dyspepsia, and anorexia with weight loss\n"
+ "  - CNS: depression, anxiety, headache\n"
+ "  - Hepatotoxicity: elevated hepatic enzymes\n"
+ "  - Exacerbates renal impairment\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Tenofovir and Emtricitabine\n"
+ "\n"
+ "### (Truvada or Descovy)\n"
+ "\n"
+ "- Better than Abacavir-Lamivudine for initial therapy\n"
+ "  - Extending time to [virologic failure](https://clinicalinfo.hiv.gov/en/glossary/virologic-failure) and first adverse event\n"
+ "  - [NEJM Dec 3 2009](https://www.ncbi.nlm.nih.gov/pubmed/?term=19952143)\n"
+ "- Effective as antiretroviral <span id='bg'>chemoprophylaxis </span>before exposure (PrEP)\n"
+ "  - [NEJM Dec 30 2010](https://www.ncbi.nlm.nih.gov/pubmed/21091279)\n"
+ "  - [NIH guideline, last updated July 3, 2025](https://hivinfo.nih.gov/understanding-hiv/fact-sheets/pre-exposure-prophylaxis-prep)\n"
+ "- <a href=\"#/recommend\">Recommended for treatment naive patients</a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"pi\">\n"
+ "\n"
+ "## Protease Inhibitors, PIs\n"
+ "\n"
+ "<div id=\"left\">\n"
+ "\n"
+ "- Rito<u>navir</u> (Norvir)\n"
+ "- Daru<u>navir</u> (Prezista)\n"
+ "- And many many more\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "<div id=\"right50\">\n"
+ "<iframe width=\"560\" height=\"400\" src=\"https://www.youtube.com/embed/MK2r8J7SCSg?start=20&amp;stop=60\" frameborder=\"0\" allowfullscreen></iframe>\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Protease Inhibitors\n"
+ "\n"
+ "- Mechanism of Action\n"
+ "  - Selective, competitive inhibitors of HIV proteases\n"
+ "  - Bind reversibly to protease active site\n"
+ "  - Prevent cleavage of polyprotein and block viral maturation\n"
+ "  - Early stages of HIV-1 replication cycle not affected\n"
+ "- Resistance\n"
+ "  - Each drug selects for different mutations in protease gene at level of specific codons\n"
+ "- Indications\n"
+ "  - Treatment of HIV as part of combination therapy\n"
+ "  - Effective in both acutely and chronic HIV-1 infected cells\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Protease inhibitors\n"
+ "\n"
+ "- ADME\n"
+ "  - Oral absorption varies\n"
+ "  - Bind extensively to plasma proteins\n"
+ "  - Renal excretion is minimal\n"
+ "    - No adjustments needed for renal dysfunctions\n"
+ "  - Metabolized by cytochrome P-450 system\n"
+ "    - Concurrent use of potent P-450 inducer (e.g. <span id=\"drug\"> rifampin </span> ) leads to decreased PI concentration\n"
+ "  - <span style=\"background-color:#ff9\"> <span id=\"drug\"> Ritonavir </span> is a potent inhibitors of CYP3A4</span>\n"
+ "    - used to increase (i.e. \"boost\") plasma concentration of other PIs except <span id=\"drug\"> nelfinavir </span> (CYP2C19)\n"
+ "    - Toxic adverse effects related to drug accumulation due to PI-mediated inhibition of hepatic P450 system\n"
+ "\n"
+ "note: rifampin is a bacterial RNA polymerase inhibitor\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Protease inhibitors\n"
+ "\n"
+ "- Common Adverse Effects\n"
+ "  - Hyperlipidemia\n"
+ "  - May be more dramatic with <span id=\"drug\"> ritonavir </span> due to interference in lipid metabolism.\n"
+ "  - [Lipodystrophy](https://www.ncbi.nlm.nih.gov/PubMed/9652687) Including central obesity, dorsocervical fat enlargement [(buffalo hump)](https://www.clinicalkey.com/#!/content/medline/2-s2.0-9525364), peripheral wasting, accumulation of facial fat, [lipomas](http://www.mayoclinic.org/diseases-conditions/lipoma/basics/definition/con-20024646), breast enlargement, [gynecomastia](http://www.mayoclinic.org/diseases-conditions/gynecomastia/home/ovc-20257576)\n"
+ "  - Insulin resistance and diabetes\n"
+ "  - Elevated liver function\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"Darunavir\">\n"
+ "\n"
+ "## Darunavir\n"
+ "\n"
+ "- <a href=\"#/sd\">Mechanism of action</a>\n"
+ "  - Inhibits the protease enzyme, preventing the cleavage of viral polyproteins into functional protein\n"
+ "- Achieves faster virologic response than other protease inhibitors(PI). [PubMed](https://www.ncbi.nlm.nih.gov/pubmed/21692667)\n"
+ "- Can be used to treat patients resist to other PIs.\n"
+ "  - <span id=\"drug\"> darunavir </span> retains activity against 90% of HIV-1 isolates that are resistant to other protease inhibitors, exhibiting 10-fold decrease in susceptibility.\n"
+ "- Must be used in combination in an antiviral regimen.\n"
+ "  - Requires an enhancer (i.e. low does <span id=\"drug\"> ritonavir </span> or [cobicistat](https://www.ncbi.nlm.nih.gov/pubmed/26566368) )\n"
+ "- No longer for treatment-naive patients (2017)\n"
+ "- <a href=\"#/recommend\">Recommended </a> for treating patients with integrase PrEP history, before testing results is available (2024)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"nnrti\">\n"
+ "\n"
+ "## Non Nucleoside Reverse Transcriptase Inhibitors (NNRTIs)\n"
+ "\n"
+ "[Nevirapine (Viramune)](https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-432)\n"
+ "\n"
+ "- Indications\n"
+ "  - HIV-1 infections\n"
+ "    - Do not have significant activity against HIV-2\n"
+ "- <a href=\"#/sd\">Mechanism of action</a>\n"
+ "  - Bind directly to a hydrophobic pocket of the reverse transcriptase\n"
+ "  - Induce conformational change in active site and block enzyme activity\n"
+ "  - Do not require intracellular phosphorylation for activity\n"
+ "- Resistance\n"
+ "  - Resistant HIV emerges rapidly when used as monotherapy.\n"
+ "  - Each drug selects for different mutations of the RT gene at the level of specific codons.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## NNRTIs\n"
+ "\n"
+ "<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/RUUyd5bE9vQ?start=108&stop=150\" frameborder=\"0\" allowfullscreen></iframe>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"Enfuvirtide\">\n"
+ "\n"
+ "## <font color=\"darkorange\">Fu</font>sion inhibitors\n"
+ "\n"
+ "[En<font color=\"darkorange\">fu</font>vir<font color=\"darkorange\">tide</font> (Fuzeon, T20)](https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-2752)\n"
+ "\n"
+ "<table><tr><td width=60% >\n"
+ "\n"
+ "- Structure\n"
+ "\n"
+ "  - a synthetic pep<font color=\"darkorange\">tide</font> with <a href=\"https://www.drugbank.ca/drugs/DB00109\">36 amino acids </a>\n"
+ "\n"
+ "- <a href=\"#/sd\">Mechanism of action</a>\n"
+ "  - Binds to <a href=\"https://en.wikipedia.org/wiki/Gp41#Function\">gp41</a> of the viral envelope; prevents conformational change and impedes the fusion of the viral and host cell membranes.\n"
+ "- Indications\n"
+ "  - Reserved as salvage therapy for treatment resistant patients.\n"
+ "  - Prophylasis after occupational HIV exposure.\n"
+ "  - Not part of 1st line ART (injection site reaction, high cost).\n"
+ "\n"
+ "</td><td>\n"
+ "\n"
+ "![](./images/antiviral/coreceptor.jpg)[video](https://youtu.be/eS1GODinO8w?t=57s)\n"
+ "\n"
+ "</td></tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Enfuvirtide\n"
+ "\n"
+ "- ADME\n"
+ "  - Administered subcutaneously (synthetic peptide)\n"
+ "  - Bound to plasma protein\n"
+ "  - Metabolized by proteolytic hydrolysis\n"
+ "  - T&frac12; = 4 h\n"
+ "- Adverse effect\n"
+ "  - Injection-site pain or infection\n"
+ "  - Hypersensitivity reaction (rash, fever, peripheral edema, acute respiratory distress, etc.)\n"
+ "- Resistance\n"
+ "  - gp41 mutations may develop when drug is given at suboptimal doses as monotherapy; No cross-resistance with other HIV Agents\n"
+ "  - Ineffective for HIV-2\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Antiretroviral Drug Selectivity\n"
+ "\n"
+ "- NRTIs\n"
+ "  - Once phosphorylated by cellular kinases, NRTIs have greater affinity for viral reverse transcriptase than for cellular DNA polymerases.\n"
+ "- PIs\n"
+ "  - Greater affinity for HIV aspartyl protease than for human protease.\n"
+ "- Integrase Inhibitors\n"
+ "  - Much higher selectivity than other classes of anti-HIV drugs.\n"
+ "\n"
+ "Note:\n"
+ "\n"
+ "- NNRTIs\n"
+ "  - Do not undergo phosphorylation\n"
+ "  - Have greater affinity for viral reverse transcriptase than for cellular DNA polymerases\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## [What not to use, updated Feb 2024](https://clinicalinfo.hiv.gov/sites/default/files/guidelines/archive/adult-adolescent-arv-2024-02-27.pdf)\n"
+ "\n"
+ "- Drugs\n"
+ "  - <span id=drug>delavirdine, didanosine, indinavir, nelfinavir, stavudine</span>\n"
+ "- Monotheray\n"
+ "- Dual-NRTI regimens\n"
+ "- Tripple-NRTI regimens\n"
+ "- Specific drug combinations\n"
+ "  - <span id=\"drug\"> Cobicistat </span> plus <span id=\"drug\"> Ritonavir </span> (both are CYP3A4 inhibitors)\n"
+ "  - <span id=\"drug\"> Emtricitabine </span> plus <span id=\"drug\"> Lamivudine </span> (these two drugs are very similar)\n"
+ "  - <span id=\"drug\"> Darunavir </span> without boosting (anti-viral effect unclear without boosting)\n"
+ "\n"
+ "These are just a few examples. Detailed list available from the link above\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"hour2\">\n"
+ "\n"
+ "## Agents for the treatment of virus infections\n"
+ "\n"
+ "### Hour 2\n"
+ "\n"
+ "- <a href=\"#/hsv\">Herpes Simplex Virus</a> and Varicella Zoster Virus\n"
+ "  - <span id=\"drug\">[Acyclovir, Valacyclovir](#/Acyclovir), [Tenofovir](#/Tenofovir2), [Famciclovir, Penciclovir](#/Penciclovir)</span>\n"
+ "- <a href=\"#/cmv\">Cytomegalovirus</a>\n"
+ "  - <span id=\"drug\">[Ganciclovir, Valganciclovir](#/Ganciclovir), [Cidofovir](#/Cidofovir), [Foscarnet](#/Foscarnet)</span>\n"
+ "- <a href=\"#/hbv\">Hepatitis Virus B </a> | <a href=\"#/hcv\"> Hepatitis Virus C</a>\n"
+ "  - <span id=\"drug\"> [Entecavir](#/Entecavir), [Interferon alpha](#/Interferon), [Sofosbuvir](#/sofosbuvir)\n"
+ "- <a href=\"#/flu\">Influenza Virus </a>\n"
+ "  - Viral release inhibitors <span id=\"drug\"> [Zanamivir, Oseltamivir](#/flurelease)</span>\n"
+ "  - Cap-dependent endonuclease inhibitor <span id=\"drug\"> [Baloxavir](#/flucap)</span>\n"
+ "- <a href=\"#/covid\">SARS-CoV-2 </a>\n"
+ "  - <span id=\"drug\">[Nirmatrelvir](#/Nirmatrelvir)</span>\n"
+ "  - <span id=\"drug\">[Remdesivir](#/remdesivir)</span>\n"
+ "  - <span id=\"drug\">[Molnupiravir](#/molnupiravir)</span>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Objectives\n"
+ "\n"
+ "- For each virus, understand the <span id=\"yb\"> major classes </span> of available antiviral agents.\n"
+ "- Describe the <span id=\"yb\">mechanisms of action</span> for antiviral agents against HSV, CMV, HBV, HCV, SARS-CoV-2, and <span id=\"yb\">mechanisms of viral resistance</span> to these agents.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Agents to treat HSV, VZV and CMV\n"
+ "\n"
+ "| Virus                                           | Disease                       |\n"
+ "| ----------------------------------------------- | ----------------------------- |\n"
+ "| Herpes simplex virus, human herpesvirus 1 and 2 | herpes genitalis              |\n"
+ "|                                                 | herpes labialis               |\n"
+ "|                                                 | herpetic keratoconjunctivitis |\n"
+ "|                                                 | herpetic encephalitis         |\n"
+ "| Varicella-zoster virus, human herpesvirus-3     | chickenpox (varicella)        |\n"
+ "|                                                 | shingles (herpes zostr)       |\n"
+ "| Cytomegalovirus, human herpesvirus-5            | retinitis &dagger;            |\n"
+ "|                                                 | esophagitis &dagger;          |\n"
+ "|                                                 |\n"
+ "\n"
+ "&dagger; most often in immunocompromised (e.g. AIDS) patients.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"hsv\">\n"
+ "\n"
+ "## Herpes Simplex virus\n"
+ "\n"
+ "<img src=\"./images/antiviral/shutterstock_hsv.png\" width=60%>\n"
+ "\n"
+ "<div id=\"greyText\">\n"
+ "Double stranded DNA virus\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Life cycle of HSV\n"
+ "\n"
+ "<img src=\"./images/antiviral/dna_virus.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nucleoside Analogs and others\n"
+ "\n"
+ "<table><tr><td width=40%>\n"
+ "\n"
+ "<ul>\n"
+ "<li><span id=\"drug\">Acyclovir</span> (Zovirax)\n"
+ "<li><span id=\"drug\">Valacyclovir</span> (Valtrex)\n"
+ "<hr>\n"
+ "<li><span id=\"drug\">Penciclovir</span> (Denavir)\n"
+ "<li><span id=\"drug\">Famciclovir</span> (Famvir)\n"
+ "<hr>\n"
+ "<li><span id=\"drug\">Ganciclovir</span> (Cytovene)\n"
+ "<li><span id=\"drug\">Valganciclovir</span> (Valcyte)\n"
+ "<hr>\n"
+ "<hr>\n"
+ "<li><span id=\"drug\">Cido<span id='bg'>fo</span>vir</span> (Vistide)\n"
+ "<li><span id=\"drug\">Foscarnet</span> (Foscavir)\n"
+ "</ul>\n"
+ "\n"
+ "</td><td>\n"
+ "<ul>\n"
+ "<li> Mechanism of action \n"
+ "<ul><li> Inactivation of viral DNA polymerase through direct binding and competition for dNTPs.\n"
+ "<li> Inducing viral DNA chain termination \n"
+ "</ul>\n"
+ "</td></tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Mechanisms of Activation of [Nucleoside](http://static.newworldencyclopedia.org/b/b9/Nucleotides.png) Analogs\n"
+ "\n"
+ "c.f. <a href=#/hostcell>NRTI for HIV</a>\n"
+ "\n"
+ "<img src=\"./images/antiviral/nucleoside_activation2.png\" width=40%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nucleoside analogues\n"
+ "\n"
+ "- Drug selectivity:\n"
+ "  - The <span id=\"yb\">virus in infected cells activates the drug to an active form</span>\n"
+ "    - Uninfected cells do not activate these drugs.\n"
+ "  - Preferential affinity of acyclovir triphosphate for viral DNA polymerase rather than cellular enzyme.\n"
+ "- Resistance:\n"
+ "  - Altered viral thymidine kinase substrate specificity\n"
+ "  - Absence of viral thymidine kinase\n"
+ "  - Mutated viral DNA polymerase\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"Acyclovir\">\n"
+ "\n"
+ "## Acyclovir\n"
+ "\n"
+ "### [Valacyclovir](https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-636) (L-valyl ester prodrug of acyclovir)\n"
+ "\n"
+ "- <a href=\"#/sd\">Mechanism of action</a>\n"
+ "  - <span id=\"drug\"> acyclovir </span> is phosphorylated intracellularly by viral thymidine kinases (TK), then by cellular kinases to the triphosphate state, which terminates DNA replication when incorported into the viral DNA.\n"
+ "  - Only effective against actively replicating virus. Does not eliminate the viral genome.\n"
+ "- ADME\n"
+ "  - <span id=\"drug\"> acyclovir </span> has low oral bioavailability (10-20%). (i.v. or topical)\n"
+ "  - <span id=\"drug\"> Valacyclovir </span> is hydrolyzed to acyclovir in intestine or liver. Increase bioavailability (3.3 - 5 X)\n"
+ "- Indication:\n"
+ "  - HSV keratitis, herpes labialis, genital herpes, HSV encephalitis\n"
+ "  - VZV\n"
+ "  - CMV-positive bone marrow transplant recipients\n"
+ "- Adverse effects\n"
+ "  - Headache, nausea, diarrhea\n"
+ "  - Following high IV dose: Reversible renal dysfunction (crystalline nephropathy), Neurologic toxicity (tremors, delirium, seizures)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"Penciclovir\">\n"
+ "\n"
+ "## Penciclovir\n"
+ "\n"
+ "### [Famciclovir](https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-240) (diacetyl ester prodrug)\n"
+ "\n"
+ "- ADME\n"
+ "  - <span id=\"drug\"> Penciclovir </span> is for topical application only.\n"
+ "  - <span id=\"drug\"> Famciclovir </span> is oral, has longer intracellular half-life than <span id=\"drug\"> Acyclovir </span>, but with lower affinity for the viral enzyme\n"
+ "  - Not a CYP450 substrate\n"
+ "- <a href=\"#/sd\">Mechanism of action</a>\n"
+ "  - Selective substrate of HSV VZV thymidine kinase\n"
+ "  - Competitive inhibition of viral DNA polymerase\n"
+ "- Indications\n"
+ "  - Alternative to Acyclovir\n"
+ "  - Infection of HSV, VZV.\n"
+ "- Adverse effects\n"
+ "  - Well tolerated\n"
+ "  - Headaches, nausea, diarrhea\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"cmv\">\n"
+ "\n"
+ "## Cytomegalovirus\n"
+ "\n"
+ "<img src=\"./images/antiviral/cmv.png\" width=60%>\n"
+ "\n"
+ "<div id=\"greyText\">\n"
+ "Double stranded DNA virus\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"Ganciclovir\">\n"
+ "\n"
+ "## Ganciclovir\n"
+ "\n"
+ "### [Valganciclovir](https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-2584) (L-valyl ester prodrug)\n"
+ "\n"
+ "- <a href=\"#/sd\">Mechanism of Action </a>\n"
+ "  - Ganciclovir is phosphorylated to ganciclovir monophosphate by <a href=\"https://pubmed.ncbi.nlm.nih.gov/1319560/\">a viral kinase</a>\n"
+ "  - Ganciclovir triphosphate inhibits viral DNA synthesis\n"
+ "    - competing for a position in the viral DNA\n"
+ "    - terminating DNA synthesis once incorporated\n"
+ "- ADME\n"
+ "  - <span id=\"drug\"> Valganciclovir </span> is hydrolyzed by esterases following oral administration to <span id=\"drug\"> ganciclovir </span>\n"
+ "- Indications\n"
+ "  - CMV retinitis in AIDS patients\n"
+ "    - Activity 100 x greater than <span id=\"drug\"> Acyclovir </span>\n"
+ "  - CMV prophylaxis (e.g., liver transplant patients)\n"
+ "- Adverse effects\n"
+ "  - Bone marrow suppression, neutropenia, anemia,\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"Cidofovir\">\n"
+ "\n"
+ "## [Cido<font color=\"darkorange\">fo</font>vir](https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-125)\n"
+ "\n"
+ "<span id=\"mem\">fo=pho=phospho=nucleotide</span>\n"
+ "\n"
+ "- <a href=\"#/sd\">Mechanism of action</a>\n"
+ "  - Cytidine nucleo<font color=\"darkorange\">t</font>ide analog\n"
+ "  - Not phosphorylated by viral thymidine kinase\n"
+ "  - Inhibits herpevirus DNA polymerase >> human DNA polymerase\n"
+ "  - Induce DNA fragmentation and Caspase-3 activity\n"
+ "- ADME\n"
+ "  - Once weekly i.v. <u>injection</u>\n"
+ "- Indications\n"
+ "  - <span id=\"drug\"> Ganciclovir, foscarnet, </span> and <span id=\"drug\"> acyclovir </span> -resistant CMV strains\n"
+ "  - <span id=\"drug\"> cidofovir </span> i.v. delays progression of CMV retinitis in HIV+ patients\n"
+ "- <a href=\"#/adverse\"> Adverse effects</a>\n"
+ "  - Nephrotoxicity, neutropeina, ocular hypotony, alopecia\n"
+ "  - Potential human carcinogen\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"Foscarnet\">\n"
+ "\n"
+ "## [<font color=\"darkorange\">Fos</font>carnet (Foscavir)](https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-267)\n"
+ "\n"
+ "### Non-nucleoside Anti-HSV Agent\n"
+ "\n"
+ "- <a href=\"#/sd\">Mechanism of Action</a>\n"
+ "  - Inorganic pyro<font color=\"darkorange\">phos</font>phate analog\n"
+ "  - Inhibits HSV DNA polymerase and HIV-1 reverse transcriptase\n"
+ "  - Binds to <a href=\"https://en.wikipedia.org/wiki/Pyrophosphate\">pyrophosphate </a> binding site of polymerase\n"
+ "  - <a href=\"https://en.wikipedia.org/wiki/Nucleoside_triphosphate#/media/File:DNA_synthesis_EN.png\">Inhibits cleavage of pyrophosphate from dNTP</a>\n"
+ "  - Blocks viral DNA synthesis\n"
+ "- Indications\n"
+ "  - Nucleoside-resistant HSV, VZV, and CMV infections\n"
+ "  - Effective in CMV retinitis, and acyclovir and ganciclovir-resistant strains of HSV and VZV\n"
+ "  - Has been used as [salvage therapy](https://www.ncbi.nlm.nih.gov/PubMed/16964823) for multi-drug resistant HIV\n"
+ "- Adverse effects\n"
+ "  - Renal failure or dysfunction\n"
+ "  - Seizure, depression, confusion, and anxiety (high CSF/plasma ratio)\n"
+ "- one marrow suppression\n"
+ "  - Nausea, vomiting, and fatigue\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Inhibitors of Viral DNA Replication\n"
+ "\n"
+ "### Summary\n"
+ "\n"
+ "- Indications\n"
+ "  - HSV, VZV, and CMV infections\n"
+ "- Mechanism of action\n"
+ "  - Inhibit viral DNA polymerases\n"
+ "- Resistance\n"
+ "  - Mutations of the viral polymerase gene\n"
+ "  - Deficiency of viral tyrosine kinase\n"
+ "- ADME\n"
+ "  - Bioavailability varies.\n"
+ "  - Renal excretion of unmetabolized parent drug through glomerular filtration -- Adjust dose\n"
+ "- Adverse effects\n"
+ "  - Generally well tolerated\n"
+ "  - Ganciclovir -- myelosuppressant and has teratogenic potential\n"
+ "  - Cidofovir and Foscarnet -- nephrotoxic\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"hbv\">\n"
+ "\n"
+ "## Hepatitis B Virus\n"
+ "\n"
+ "<img src=\"./images/antiviral/shutterstock_hbv.png\" width=50%>\n"
+ "\n"
+ "<div id=\"greyText\">\n"
+ "Partially double-stranded DNA virus\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## HBV life cycle\n"
+ "\n"
+ "<iframe width=\"700\" height=\"500\" src=\"https://www.youtube.com/embed/sVpiXaEMs7I?start=342\" frameborder=\"0\" allowfullscreen></iframe>\n"
+ "\n"
+ "partial DNA enters nucleus -> cccDNA -> RNA -> <span id='bg'>HBV polymerase</span> -> DNA (negative strand) -> DNA (positive strand)\n"
+ "\n"
+ "<b>ccc</b>: covalently closed circular\n"
+ "\n"
+ "HBV polymerase has reverse transcription activity\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Anti-Hepatitis Agents\n"
+ "\n"
+ "### [treatment guideline](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5975958/)\n"
+ "\n"
+ "- <span id=\"drug\">Entecavir</span> (Baraclude)\n"
+ "- <span id=\"drug\">Tenofovir</span> (Viread)\n"
+ "- <span id=\"drug\">Interferon alfa-2a</span> (Roferon) and -2b (Intron A)\n"
+ "- <span id=\"drug\">Peginterferon alfa-2a</span> (Pegasys) and alfa-2b (PegIntron)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"Entecavir\">\n"
+ "\n"
+ "## [Entecavir](https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-3427) (Baraclude)\n"
+ "\n"
+ "- <a href=\"#/sd\">Mechanism of action</a>\n"
+ "  - Nucleoside analog of <b>G</b>uanosine\n"
+ "  - Inhibits all 3 activities of HBV polymerase\n"
+ "    - Base priming ([GAA](https://youtu.be/sVpiXaEMs7I?t=6m12s)) [PubMed](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4399241/)\n"
+ "    - Reverse transcription of the negative DNA strand\n"
+ "    - DNA synthesis of positive strand\n"
+ "- Indication\n"
+ "  - Effective in treatment naive HBV patients\n"
+ "  - Equally active against <span id=\"drug\"> lamivudine</span>-resistant HBV\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Entecavir\n"
+ "\n"
+ "- ADME\n"
+ "  - Oral bioavailability is 37-80%\n"
+ "  - Not metabolized - not substrate for CYP450\n"
+ "  - Excreted by kidneys (both glomerular filtration and tubular secretion)\n"
+ "    - With CrCl < 50 ml/min, dose should be modified\n"
+ "- Adverse effects\n"
+ "  - Generally well tolerated\n"
+ "  - **HBV exacerbation upon discontinuation of treatment**\n"
+ "  - Elevation of hepatic enzymes may occur, lactic acidosis\n"
+ "  - Most commonly reported: headache, fatigue, dizziness\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"Tenofovir2\">\n"
+ "\n"
+ "## Tenofovir\n"
+ "\n"
+ "- <a href=\"#/sd\">Mechanism of action</a>\n"
+ "  - A nucleotide analog of adenosine monophosphate\n"
+ "  - First nucleotide reverse transcriptase inhibitor\n"
+ "  - Inhibits viral reverse transcriptase\n"
+ "- Resistance\n"
+ "  - Thymidine analogue mutations\n"
+ "  - Not effected by <span id=\"drug\"> lamivudine-abacavir </span> associated mutationse\n"
+ "- Metabolism\n"
+ "  - Not substrate for P450\n"
+ "- Adverse effect:\n"
+ "  - Most commonly (>3%) in clinical trials: nausea, diarrhea, asthenia, headache, vomiting, flatulence, abdominal pain, and anorexia.\n"
+ "  - Increase in liver enzymes\n"
+ "  - watch for hepatitis flare if discontinued in patients with chronic HBV infection.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Common to all the nucleoside analogs for HBV\n"
+ "\n"
+ "<span id=\"drug\">Entecavir </span> <span id=\"drug\">Adefovir </span> <span id=\"drug\">Tenofovir </span>\n"
+ "\n"
+ "- Severe acute exacerbations of hepatitis B have been reported in patients who have stopped taking the drug.\n"
+ "- Lactic acidosis and severe hepatomegaly with steatosis is a more common adverse effect of the nucleoside analogs in the treatment of HIV, where they are always used in combination therapy, but these effects are much <u>less</u> likely to occur with monotherapy for treatment of hepatitis B.\n"
+ "\n"
+ "Bonus question: Why is monotherapy used for HBV but combination therapy is needed for HIV?\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Immunoregulators\n"
+ "\n"
+ "- [Interferons](https://www.clinicalkey.com/#!/content/book/3-s2.0-B9780323080583000137?scrollTo=%23hl0000129) (IFNs)\n"
+ "  - Potent cytokines that posses antiviral, antiproliferation (antineoplastic) and immunomodulating actions\n"
+ "    - Activates ribonucleases to degrade viral RNA\n"
+ "    - Inhibition of viral replication\n"
+ "    - Blocks protein synthesis &mdash; inhibits translation initiation complex\n"
+ "  - Three major classes of human IFNs\n"
+ "\n"
+ "| Interferon | Type    | Receptor | Effect           |\n"
+ "| ---------- | ------- | -------- | ---------------- |\n"
+ "| &alpha;    | Type I  | IFNAR    | Antiviral        |\n"
+ "| &beta;     | Type I  | IFNAR    | Antiviral        |\n"
+ "| &gamma;    | Type II | IFNGR    | Immunomodulation |\n"
+ "|            |\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Interferons\n"
+ "\n"
+ "- Type I has more potent antiviral effect.\n"
+ "\n"
+ "  - It can be produced in almost any cell type when infected with a virus.\n"
+ "  - Triggered by molecular patterns characteristic of viral but not host components (e.g. viral 5'-triphosphorylated ssRNA and dsRNA) [PubMed](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1472073/)\n"
+ "\n"
+ "- Interferon alpha is generally active against the following viruses <i> in vitro</i>: \\* <span style=\"font-weight:normal; font-size: 0.6em\"> adenovirus; coronavirus; encephalomyocarditis virus; hepatitis B virus; hepatitis C virus (HCV); hepatitis D virus; herpes simplex virus type 1; herpes simplex virus type 2; human immunodeficiency virus (HIV); papillomavirus; poliovirus; rhinovirus; vaccinia virus; varicella-zoster virus; vesicular stomatitis virus; human T-lymphotropic virus type I (HTLV-I).\n"
+ "  </span>\n"
+ "\n"
+ "- Induces immune responses, alter the expression of genes, cell surface markers, phagocytic activity, cytotoxicity, etc.\n"
+ "\n"
+ "- HBV is weak IFN inducer. <a href=\"https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6058040/\" target=\"_new\">PubMed</a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"Interferon\">\n"
+ "\n"
+ "## [Interferon alpha-2a](https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-2508)\n"
+ "\n"
+ "## [peginterferon alpha-2a](https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-2634)\n"
+ "\n"
+ "- <a href=\"#/sd\">Mechanism of Action</a>\n"
+ "  - Immune stimulation: Enhances natural killer cells, cytotoxic T lymphocytes, and antigen presentation.\n"
+ "  - Direct antiviral effects: Inhibits HBV replication, mRNA transcription, and viral particle assembly.\n"
+ "  - Antiproliferative effects: Limits hepatocyte proliferation, reducing the risk of liver fibrosis and cancer.\n"
+ "  - Immunomodulation: Shifts immune response towards Th1-mediated viral clearance.\n"
+ "  - cccDNA reduction: Indirectly reduces the activity of cccDNA, leading to lower viral persistence.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## [Interferon alpha-2a](https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-2508)\n"
+ "\n"
+ "- Indications\n"
+ "  - Chronic HBV, HPV and (Kaposi sarcoma, human herpesvirus-8)\n"
+ "  - HCV\n"
+ "    - <span id='bg'> <span id=\"drug\"> peginterferon </span> in combination with <span id=\"drug\"> Ribavirin </span></span>\n"
+ "- ADME\n"
+ "  - Administered i.m. or s.c.\n"
+ "  - High bioavailability\n"
+ "  - Proteolytic degradation in the Kidney is the main site of metabolism\n"
+ "  - Eliminated in the urine ( IFN-&alpha;2 T&frac12; = 5.1 h)\n"
+ "  - Peginterferon has much longer T&frac12; ( 80 h)\n"
+ "    - IFN-&alpha;2a is no longer produced in the USA\n"
+ "\n"
+ "<small>\n"
+ "* PEG = bis-monomethoxy polyethylene glycol \n"
+ "</small>\n"
+ "---\n"
+ "\n"
+ "## Interferon alpha-2\n"
+ "\n"
+ "- <a href=\"#/adverse\">Adverse effects</a>\n"
+ "  - Flu-like syndrome: nausea, vomiting, anorexia\n"
+ "  - Bone marrow suppression (95% patients)\n"
+ "  - Psychiatric effects: depression, homicidal and suicidal ideation\n"
+ "  - Injection site reaction\n"
+ "  - Should not be administered during pregnancy\n"
+ "- Drug interactions\n"
+ "  - Increases in the level of many drugs:\n"
+ "    - <span id=\"drug\"> theophylline </span> (for asthema) by 100%\n"
+ "    - <span id=\"drug\"> zidovudine </span> by 93%.\n"
+ "  - Co-administration with <span id=\"drug\"> zidovudine </span> can [increase severity of myelosuppression](#/zidovudine).\n"
+ "  - Additive myelosuppressive effects when combined with some anticancer agents or immunosuppressives.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## IFN-α vs. Entecavir\n"
+ "\n"
+ "|                             | Interferon-Alpha                                                              | Entecavir                                                          |\n"
+ "| --------------------------- | ----------------------------------------------------------------------------- | ------------------------------------------------------------------ |\n"
+ "| **Treatment goal**          | Finite treatment with the potential for long-term remission (functional cure) | Long-term or indefinite viral suppression                          |\n"
+ "| **Treatment duration**      | Fixed, finite course, typically 48 weeks                                      | Long-term or indefinite                                            |\n"
+ "| **Mechanism of action**     | Immunomodulatory                                                              | Suppress viral replication                                         |\n"
+ "| **Route of administration** | Subcutaneous injection                                                        | Oral tablet                                                        |\n"
+ "| **Adverse effects**         | Frequent and severe (fever, fatigue, depression, bone marrow suppression)     | Rare, potent antiviral effect, and well-tolerated by most patients |\n"
+ "\n"
+ "Functional cure: undetectable HBsAg and unquantifiable serum HBV DNA for at least 24 weeks after a finite course of therapy <a href=\"https://pmc.ncbi.nlm.nih.gov/articles/PMC11249939/\" target=\"_new\">PubMed</a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"hcv\">\n"
+ "\n"
+ "## Hepatitis C\n"
+ "\n"
+ "<img src=\"https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Hegasy_Hep_C_Virus_EN-01.jpg/495px-Hegasy_Hep_C_Virus_EN-01.jpg\">\n"
+ "\n"
+ "<div id=\"greyText\">\n"
+ "a single-stranded, positive-sense RNA \n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## HCV life cycle\n"
+ "\n"
+ "<a href=\"https://www.nature.com/articles/nm.3248/figures/3\">\n"
+ "<img src=\"https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fnm.3248/MediaObjects/41591_2013_Article_BFnm3248_Fig3_HTML.jpg?as=webp\" width=50%>\n"
+ "\n"
+ "</a>\n"
+ "\n"
+ "Viral RNA replication occurs near the ER, requirs nonstructural protein NS5B/NS5A, <a href=\"https://en.wikipedia.org/wiki/RNA-dependent_RNA_polymerase\">RNA-dependent RNA-polymerases</a>.\n"
+ "\n"
+ "Note:\n"
+ "\n"
+ "https://www.wjgnet.com/1007-9327/full/v27/i28/4555.htm\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## <a href=\"https://www.ncbi.nlm.nih.gov/books/NBK531720/\"> WHO Hepatitis C treatment guideline</a>\n"
+ "\n"
+ "- 9 HCV genotypes, type 1 is most common in the US.\n"
+ "\n"
+ "- <span id=\"drug\">sofosbuvir/ledipasvir </span> for genotypes 1, 4, 5 and 6 (1st line treatment)\n"
+ "- <span id=\"drug\"> sofosbuvir/ribavirin </span> for genotype 2 and 3\n"
+ "\n"
+ "- Antiviral medicines can <b>cure</b> more than 95% of persons with hepatitis C infection\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"sofosbuvir\">\n"
+ "\n"
+ "## Sofosbuvir\n"
+ "\n"
+ "- <a href=\"#/sd\">Mechanims of Action </a>\n"
+ "\n"
+ "  - nucleotide analogue inhibitor\n"
+ "  - a direct-acting antiviral agent\n"
+ "  - NS5B is an <a href=\"https://en.wikipedia.org/wiki/RNA-dependent_RNA_polymerase\"> RNA-dependent RNA polymerase</a>\n"
+ "  - incorporated into HCV RNA by the NS5B polymerase and acts as a chain terminator\n"
+ "  - interferes with the HCV lifecycle, restraining viral replication.\n"
+ "\n"
+ "- ADME\n"
+ "  - oral\n"
+ "  - mainly eliminated in urine\n"
+ "- Toxicity\n"
+ "  - very mild (headache and fatigue)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"Ledipasivir\">\n"
+ "\n"
+ "## Ledipasvir\n"
+ "\n"
+ "- <a href=\"#/sd\">Mechanism of Action </a>\n"
+ "\n"
+ "  - a direct-acting antiviral agent\n"
+ "  - NS5A is an RNA-dependent RNA polymerase\n"
+ "  - Ledipasivir prevent hyperphosphorylation of NS5A polymerase\n"
+ "  - restraining viral replication.\n"
+ "  - there has been little drug resistance\n"
+ "\n"
+ "- ADME\n"
+ "  - oral\n"
+ "  - mainly eliminated in feces\n"
+ "- Toxicity\n"
+ "  - very mild (headache and fatigue)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"Ribavirin\">\n"
+ "\n"
+ "## [Ribavirin](https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-542)\n"
+ "\n"
+ "(Copegus | Moderiba | Rebetol | RibaPak | RibaTab | Ribasphere | Virazole)\n"
+ "\n"
+ "- <a href=\"#/sd\">Mechanism of Action</a>\n"
+ "  - Nucleoside analog of guanosine\n"
+ "  - Increase mutation of viral <a href=\"#/molnupiravir\"> <span id=\"yb\">RNA/DNA</span></a> and leads to \"**error catastrophe**\"\n"
+ "  - Interference with synthesis of GTP / Increase production of cytokine\n"
+ "- Indication\n"
+ "  - Treat <u>Hepatitis C</u> in combination with <span id=\"drug\"> Sofosbuvir </span>\n"
+ "  - <u>Respiratory syncytial virus</u>: aerosolized form\n"
+ "  - <u>Hantaan virus</u>: intravenous\n"
+ "- Adverse effects\n"
+ "  - Bone morrow suppression\n"
+ "  - Psychiatric effects: depression, insomnia, anxiety.\n"
+ "  - Teratogenic in animals\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"flu\">\n"
+ "\n"
+ "## Influenza virus\n"
+ "\n"
+ "<img src=\"./images/antiviral/shutterstock_influenza.png\" width=60%>\n"
+ "\n"
+ "<div id=\"greyText\"> Single negative strand, segmented (8) RNA virus || Type A H18N10, Type B or C </div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Life cycle\n"
+ "\n"
+ "<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/2RMNwLdtRhw?si=MtlsQERrl-O3eTE8\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>\n"
+ "\n"
+ "[Life cycle review](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2794490/)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Mechanism of Action of Antiinfluenza Agents\n"
+ "\n"
+ "<table><tr><td>\n"
+ "<img src=\"./images/antiviral/flu.png\" width=100%>\n"
+ "</td><td width=50%>\n"
+ "\n"
+ "- Life cycle\n"
+ "  - virus enter the cell via H spikes. In the endosome, low pH in the endosome trigger the <span id='bg'> fusion of membranes</span>.\n"
+ "  - viral ribonucleoprotein and viral RNA enters the cell\n"
+ "  - viral RNA is replicated by RNA-dependent RNA polymerase.\n"
+ "  - viral RNA acquires the 5'cap of of cellular RNA (important for making protein) and exported into the cytoplasm.\n"
+ "  - viral protein is made and virus is packaged on cell surface\n"
+ "  - the N spikes cleave the H spikes and releases the viron.\n"
+ "  </td>\n"
+ "  </tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Antiinfluenza Agents\n"
+ "\n"
+ "- Virus release inhibitors\n"
+ "\n"
+ "  - <span id=\"drug\"> Zanamivir</span> (Relenza)\n"
+ "  - <span id=\"drug\"> Oseltamivir</span> (Tamiflu)\n"
+ "\n"
+ "- Cap-dependent endonuclease inhibitor\n"
+ "\n"
+ "  - <span id=\"drug\"> Baloxavir </span> (Xofluza)\n"
+ "\n"
+ "- Uncoating inhibitors\n"
+ "  - most current strains of flu virus are resistant to these drugs\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"flurelease\">\n"
+ "\n"
+ "## [Zanamivir](https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-2259) and [oseltamivir](https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-2450)\n"
+ "\n"
+ "### Inhibitors of Virus Release\n"
+ "\n"
+ "Sialic acid analog inhibitors of influenza A and B neuraminidase\n"
+ "\n"
+ "- <a href=\"#/sd\">Mechanism of action</a>\n"
+ "  - Competitive <a href=\"https://youtu.be/caMne7nQUL8?t=94\"> inhibitors of influenza neuraminidase</a>.\n"
+ "- Indications\n"
+ "  - Effective against influenza A and B viruses.\n"
+ "  - Patients who have been symptomatic for no more than 48 hours.\n"
+ "- Resistance\n"
+ "  - HA or neuraminidase mutations\n"
+ "- Adverse effects:\n"
+ "  - Zanamivir is orally inhaled and causes nasal and throat discomfort.\n"
+ "  - Oseltamivir is taken orally and can cause nausea and vomiting.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"flucap\">\n"
+ "\n"
+ "## Baloxavir marboxil (Xofluza)\n"
+ "\n"
+ "- Approved by the [FDA on October 24, 2018](https://www.fda.gov/NewsEvents/Newsroom/PressAnnouncements/ucm624226.htm)\n"
+ "  - The first oral, single-dose antiviral\n"
+ "  - The first medicine with a novel mechanism of action to treat the flu in nearly 20 years\n"
+ "- ADME\n"
+ "  - Effective against influenza A and B viruses\n"
+ "- Initiate treatment within 48 h of symptom onset\n"
+ "  - A single oral dose\n"
+ "  - Only for those aged 12 or more initialy, subsequent clinical trails found to be safe for children as well.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"Baloxavir\">\n"
+ "\n"
+ "## <span id=\"drug\"> Baloxavir marboxil (Xofluza) </span>\n"
+ "\n"
+ "<div id=\"left\">\n"
+ "\n"
+ "<a href=\"https://www.virology.ws/2018/10/25/a-new-drug-for-influenza/\">\n"
+ "\n"
+ "<img src=\"./images/antiviral/capedrna.png\">\n"
+ "\n"
+ "</a>\n"
+ "\n"
+ "brown: 5'cap. red arrow: endonuclease. light green: new copy of viral RNA.\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "<div id=\"right\">\n"
+ "\n"
+ "- <a href=\"#/sd\"> Mechanism of Action </a>\n"
+ "  - Cellular mRNA has a [5' methylated cap and a polyA tail](https://www.neb.com/-/media/nebus/page-images/tools-and-resources/feature-articles/fa_mindcaps_fig1_initiationloop.jpg)\n"
+ "  - Viral mRNA does not have a cap.\n"
+ "  - Cap-dependent endonuclease binds to the 5' methylated caps of cellular mRNAs\n"
+ "    and cleaves the cellular mRNAs' 10 to 15 nucleotides 3' to the cap structure. This cellular capped RNA fragment is used by the viral polymerase to prime the synthesis of viral mRNA.\n"
+ "  - Baloxavir is an inhibitor of this cap-dependent endonuclease\n"
+ "- Adverse effects:\n"
+ "  - headache, diarrhea, bronchitis\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"covid\">\n"
+ "\n"
+ "## SARS-CoV-2 virus\n"
+ "\n"
+ "<a href=\"https://www.nature.com/articles/d41586-021-02039-y\">\n"
+ "<img src=\"images/antiviral/coronavirus.jpg\" width=80%></a>\n"
+ "\n"
+ "<div id=\"greyText\">\n"
+ "Single stranded RNA virus\n"
+ "</div>\n"
+ "\n"
+ "The RNA genome is [30 kilo bases](https://genome.ucsc.edu/cgi-bin/hgTracks?db=wuhCor1&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=NC_045512v2%3A1%2D29903&hgsid=1203179451_8263g5HiGW1R07rmnBegtA4EAf7w)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Life cycle of SARS-CoV-2\n"
+ "\n"
+ "<div id=\"left\">\n"
+ "\n"
+ "<a href=\"https://www.nature.com/articles/s41579-020-00468-6\">\n"
+ "<img src=\"./images/antiviral/sars-cov-2_life_cycle.png\" width=90%>\n"
+ "</a>\n"
+ "    <br>\n"
+ "Color legend: Orange boxes -> life cycle | \n"
+ "	Red boxes -> therapeutic options under investigation\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "<div id=\"right\">\n"
+ "\n"
+ "- Infecting bronchial epithelial cells, pneumocytes and upper respiratory tract cells\n"
+ "- Spike protein <a href=\"https://pubs.acs.org/cms/10.1021/acs.jpcb.1c02048/asset/images/medium/jp1c02048_0002.gif\">binds</a> to <a href=\"https://alphafold.ebi.ac.uk/entry/Q9BYF1\">ACE2</a>\n"
+ "- Viral replication is particularly active early in COVID-19\n"
+ "- Antiviral therapy have greatest impact before disease progresses to the hyperinflammatory stage\n"
+ "\n"
+ "Acronyms: <b>An</b>: 3′ polyA sequence; <b>ACE2</b>: angiotensin-converting enzyme 2; <b>RdRP</b>: RNA-dependent RNA polymerase; <b>TMPRSS2</b>: a cell surface serine protease\n"
+ "\n"
+ "<hr>\n"
+ "\n"
+ "<a href=\"https://media.nature.com/lw800/magazine-assets/d41586-021-02039-y/d41586-021-02039-y_19394008.png\">\n"
+ "Another version of SARS-CoV-2 life cycle</a>\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## [Recommendations on Antiviral Drugs for SARS-CoV-2](https://www.cdc.gov/covid/hcp/clinical-care/outpatient-treatment.html)\n"
+ "\n"
+ "(last update: Jun 11, 2025)\n"
+ "\n"
+ "#### Nonhospitalized Adults With Mild to Moderate COVID-19 Who Do Not Require Supplemental Oxygen\n"
+ "\n"
+ "- All patients\n"
+ "  - symptom management\n"
+ "  - against the use of systemic corticosteroids\n"
+ "- For patients who are at high risk of progression to severe COVID-19 (Preferred therapies, listred in order of preference)\n"
+ "  - <span id=\"drug\">Ritonavir</span>-boosted <span id=\"drug\">nirmatrelvir</span> (Paxlovid)\n"
+ "  - <span id=\"drug\">Remdesivir (Veklury)</span>\n"
+ "  - <span id=\"drug\">Molnupiravir (Lagevrio)</span>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"Nirmatrelvir\">\n"
+ "\n"
+ "## Nirmatrelvir\n"
+ "\n"
+ "- <a href=\"#/sd\">Mechanism of Action</a>\n"
+ "  - protease inhibitor\n"
+ "  - inhibits the maturation of nonstructural proteins (including proteases)\n"
+ "- ADME\n"
+ "  - orally bioavailable (thus can be given to patients without hospitalization).\n"
+ "  - substrate of CYP3A4.\n"
+ "  - undergoes minimal metablolism when administered with <span id=\"drug\">Ritonavir</span>\n"
+ "  - <span id=\"drug\">Paxlovid </span> = <span id=\"drug\">Nirmatrelvir + Ritonavir </span>\n"
+ "- Indications\n"
+ "  - Used for the treatment of mild-to-moderate COVID-19 in patients at high risk of severe illness\n"
+ "- Timing of administration\n"
+ "  - Most effective when administered within 5 days of symptom onset.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"Remdesivir\">\n"
+ "\n"
+ "### Remdesivir (Veklury)\n"
+ "\n"
+ "<table> <tr><td width=35%>\n"
+ "<a href=\"https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7566896/\">\n"
+ "<img src=\"./images/antiviral/remdesivir.png\" width=80%>\n"
+ "</a>\n"
+ "\n"
+ "[FDA approves Remdesivir on Oct 22, 2020](https://www.fda.gov/news-events/press-announcements/fda-approves-first-treatment-covid-19)\n"
+ "\n"
+ "</td><td width=65%>\n"
+ "\n"
+ "- <a href=\"#/sd\">Mechanism of Action</a>\n"
+ "  - Nucleoside analog of Adenosine\n"
+ "  - It is a prodrug, metabolized by carboxylesterase I to its triphosphate active form\n"
+ "  - Coronaviruses replication requires _RNA-dependent RNA polymerase_. These enzymes can incorporate remdesivir into new RNA strands. Shortly after adding remdesivir, the enzyme stops being able to function. This halts viral genome replication.\n"
+ "- ADME ([review article](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8308800/))\n"
+ "  - Administered as a slow i.v. infusion of a loading dose followed by a maintenance dose for 5 or 10 days\n"
+ "  - Eliminated in urine\n"
+ "- Adverse effects\n"
+ "  - GI symptoms, elevated transaminase levels (liver function), hypersensitivity\n"
+ "- Indication\n"
+ "  - Treatment of COVID-19 in hospitalized adult and pediatric patients\n"
+ "\n"
+ "</td></tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"Molnupiravir\">\n"
+ "\n"
+ "## Molnupiravir\n"
+ "\n"
+ "- Received FDA emergency use auth on Dec 23, 2021\n"
+ "- <a href=\"#/sd\">Mechanism of Action</a>\n"
+ "  - nucleoside analoge\n"
+ "  - [promotes SARS-CoV-2 mutagenesis via the <a href=\"#/Ribavirin\"><span id=\"yb\">RNA</a></a> template](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8110631/)\n"
+ "    - [can mimic either cytosine or uridine after incorporated into viral RNA template, causing mutations of the viral RNA](https://www.nature.com/articles/d41586-021-02783-1)\n"
+ "- [Clinical trial](https://www.science.org/doi/10.1126/scitranslmed.abl7430)\n"
+ "  - 202 outpatients with confirmed SARS-CoV-2 infection\n"
+ "  - Sympton onset within 7 days\n"
+ "  - Placebo, molnupiravir 200 mg, 400 mg, 800 mg\n"
+ "  - At Day 5, virus was not isolated from any participants receiving 400 or 800 mg (11.1% virus positive in placebo)\n"
+ "  - Adverse effect\n"
+ "    - headache, insomnia, increase alanine aminotransferase\n"
+ "- Indication\n"
+ "  - when other treatments are not suitable\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Antiviral Agent Summary\n"
+ "\n"
+ "- Understand the genome of the virus\n"
+ "  - RNA\n"
+ "  - double stranded DNA\n"
+ "  - partially double stranded DNA\n"
+ "- Understand the life cycle of the virus\n"
+ "  - entry\n"
+ "  - replication\n"
+ "  - protein synthesis\n"
+ "  - release\n"
+ "- Understand the MoA of treatments\n"
+ "- Understand the how mutation of virus can evade the action of treatment agents.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"sd\">\n"
+ "\n"
+ "## Summary of MoA\n"
+ "\n"
+ "| Virus               | HIV                                                                | Herpes                                                                       | Cytomegalo.                             | Hep. B                               | Hep. C                      | Flu                                    | COVID                                                      |\n"
+ "| ------------------- | ------------------------------------------------------------------ | ---------------------------------------------------------------------------- | --------------------------------------- | ------------------------------------ | --------------------------- | -------------------------------------- | ---------------------------------------------------------- |\n"
+ "| **Genome**          | ssRNA                                                              | dsDNA                                                                        | dsDNA                                   | partial dsDNA                        | ssRNA                       | ssRNA (x8)                             | ssRNA                                                      |\n"
+ "| **Entry**           | <a href=\"#/Enfuvirtide\">Enfuvirtide </a>                           |                                                                              |                                         |                                      |                             |                                        |                                                            |\n"
+ "| **Nucleoside**      | <a href=\"#/FTC\">Emtricitabine, Lamivudine</a>                      | <a href=\"#/Acyclovir\">Acyclovir</a>, <a href=\"#/Penciclovir\">Penciclovir</a> | <a href=\"#/Ganciclovir\">Ganciclovir</a> | <a href=\"#/Entecavir\">Entecavir</a>  | [Ribavirin](#/Ribavirin)    |                                        | [Remdesivir](#/Remdesivir), [Molnupiravir](#/Molnupiravir) |\n"
+ "| **Nucleotide**      | <a href=\"#/Tenofovir\"> Tenofovir </a>                              |                                                                              | [Cidofovir](#/Cidofovir)                | <a href=\"#/Tenofovir2\">Tenofovir</a> | [Sofosbuvir](#/sofosbuvir)  |                                        |                                                            |\n"
+ "| **Non-Nucleoside**  | <a href=\"#/nnrti\">Nevirapine</a>                                   |                                                                              | [Foscarnet](#/Foscarnet)                |                                      |                             |                                        |                                                            |\n"
+ "| **Integrase**       | <a href=\"#/Integrase\">Bictegravir, Dolutegravir, Cabotegravir </a> |                                                                              |                                         |                                      |                             |                                        |                                                            |\n"
+ "| **Protease**        | [Darunavir, Ritonavir](#/Darunavir)                                |                                                                              |                                         |                                      |                             |                                        | [Nirmatrelvir](#/Nirmatrelvir)                             |\n"
+ "| **Immunoregulator** |                                                                    |                                                                              |                                         | [Interferons](#/Interferon)          |                             |                                        |                                                            |\n"
+ "| **NS5A**            |                                                                    |                                                                              |                                         |                                      | [Ledipasvir](#/Ledipasivir) |                                        |                                                            |\n"
+ "| **Cap-dependent**   |                                                                    |                                                                              |                                         |                                      |                             | [Baloxavir](#/Baloxavir)               |                                                            |\n"
+ "| **Neuraminidase**   |                                                                    |                                                                              |                                         |                                      |                             | [Zanamivir, Oseltamivir](#/flurelease) |                                                            |\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## NotebookLM study guide\n"
+ "\n"
+ "### <a href=\"https://notebooklm.google.com/notebook/a45a17ff-93b3-4e83-bcfc-a305d432c7ea?authuser=1\">NotebookLM for this lecture</a>\n"
+ "\n"
+ "- Lecture slides\n"
+ "- Treatment guidelines\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Additional Reading\n"
+ "\n"
+ "- [Gene editing for HIV enters into human testing](https://www.fiercebiotech.com/biotech/excision-hiv-crispr-gene-editing-therapy-cleared-for-human-studies-by-fda)\n"
+ "- [Combination anti-HIV antibodies provide sustained virological suppression for up to 43 weeks](https://www.nature.com/articles/s41586-022-04797-9)\n"
+ "- [Is drug enough for Hepatitis-C?](https://www.nytimes.com/2024/04/28/health/hepatitis-c.html)\n"
;
var script = document.querySelector('script[src="antiviral.js"]');
var section = document.createElement('section');
script.parentNode.appendChild(section);
section.appendChild(document.createTextNode(markdownContent));
[].forEach.call(script.attributes, function (attr) {
    section.setAttribute(attr.name, script.getAttribute(attr.name));
});
section.setAttribute('data-markdown', '');
})();
