(function () {
'strict'
var markdownContent = ''
+ "----\n"
+ "# Anti-HIV & Antiviral Agents\n"
+ "----\n"
+ "\n"
+ "[Hour 1](#/hour1) | [Hour 2](#/hour2)\n"
+ "\n"
+ "Hao Chen, Ph.D\n"
+ "\n"
+ "hchen@uthsc.edu Dept. Pharmacology, UTHSC\n"
+ "\n"
+ "### Last update: *Nov 9, 2021*\n"
+ "\n"
+ "Please use the live online version at http://chen42.github.io/slides/antiviral.html\n"
+ "\n"
+ "Or download the [**Printable version**](http://chen42.github.io/slides/antiviral_dental.html?print-pdf#/) before class.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Formatting conventions \n"
+ "### used in this document \n"
+ "\n"
+ "* Color and style guide: \n"
+ "	* Drug name: <span id=\"drug\"> Enfuvirtide</span>\n"
+ "	* Links: [Clinicalkey](https://www.clinicalkey.com/#!/). \n"
+ "		* Shade change when mousing over indicates the image or text has a link\n"
+ "		* You need to login via your UTHSC netid when off campus to use e-textbooks. \n"
+ "		* [VPN](http://uthsc.edu/vpn/) provides a better experience. \n"
+ "* Open link in a new browser tab:\n"
+ "```\n"
+ "CTRL click\n"
+ "```\n"
+ "* Navigate the slides:\n"
+ "```\n"
+ "<- or -> \n"
+ "Space_bar \n"
+ "Page_down or Page_up \n"
+ "Home or End\n"
+ "```\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"hour1\">\n"
+ "\n"
+ "## Agents for the treatment of virus infections \n"
+ "### [Hour 1](#/hiv) \n"
+ "* <a href=\"#/hiv\">Retrovirus (HIV)</a>\n"
+ "	* Fusion inhibitors <span id=\"drug\">[Enfuvirtide](#/Enfuvirtide), [Maraviroc](#/Maraviroc)</span>\n"
+ "	* Nucleoside reverse transcriptase inhibitors <span id=\"drug\">[Zidovudine, Lamivudine, Abacavir, Emtricitabine](#/nrti)</span>\n"
+ "	* Nucleotide inhibitors <span id=\"drug\">[Tenofovir](#/Tenofovir)</span>\n"
+ "	* Non-nucleoside reverse transcriptase inhibitors <span id=\"drug\">[Nevirapine, Efavirenz](#/nnrti)</span>\n"
+ "	* Integrase strand transfer inhibitor <span id=\"drug\">[Bictegravir, Raltegravir, Dolutegravir](#/Integrase) </span>\n"
+ "	* Protease inhibitors <span id=\"drug\">[Ritonavir, Darunavir](#/pi) </span> \n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Objectives\n"
+ "\n"
+ "1. Identify the <span id=\"yb\">steps in the viral replication process</span> that provide targets for antiviral therapy.\n"
+ "\n"
+ "2. Understand the <span id=\"yb\">current guidline for HIV/AIDS treatment. </span>\n"
+ "\n"
+ "3. Understand the <span id=\"yb\">current Initial Combination Regimens</span> for drug naive patent.\n"
+ "\n"
+ "4. Describe the mechanism of action and significant pharmacological properties of the <span id=\"yb\">six major classes</span> of anti-HIV agents\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"hiv\">\n"
+ "\n"
+ "## Human Immunodeficiency Viruses\n"
+ "\n"
+ "<img src=\"./images/antiviral/hiv_structural_highlight.png\" width=60%>\n"
+ "\n"
+ "<div id=\"greyText\">\n"
+ "single, positive strand RNA \n"
+ "<br>\n"
+ "HIV-1 widely distributed, more pathogenic | HIV-2 restricted to Central and West africa\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## [Stages of AIDS](https://www.clinicalkey.com/#!/content/book/3-s2.0-B9780323611794000107?scrollTo=%23t0015)\n"
+ "\n"
+ "<ol> <li> <b>Primary infection.</b> About 90% of patients develop a flu-like illness, which coincides with <a href= https://clinicalinfo.hiv.gov/en/glossary/seroconversion> seroconversion</a>, between 2 and 4 weeks post exposure. Symptoms include fever, night sweats, sore throat, lymphadenopathy, diarrhea. The illness is self-limiting.\n"
+ "\n"
+ "<li> <b>Asymptomatic phase.</b> Of variable duration, from 2 to 10 years. Patients are clinically well, but infectious.\n"
+ "\n"
+ "<li> <b>Acquired Immunodeficiency Syndrome (AIDS). </b>Features:\n"
+ "	<ol>\n"
+ "		<li> Constitutional symptoms: fever, diarrhea, weight loss, skin rashes.\n"
+ "		<li> Immunodeficiency: increased susceptibility to opportunistic infections	\n"
+ "		<li> Neurological disease: dementia, myelopathy, peripheral neuropathy	\n"
+ "		<li> Rare malignancies: Kaposi sarcoma, oral hairy leukoplakia, or lymphoma\n"
+ "	</ol>\n"
+ "</ol>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## AIDS Timeline \n"
+ "\n"
+ "\n"
+ "<td> <img src=\"./images/antiviral/hiv_untreated.png\" width=80%> </td>\n"
+ "---\n"
+ "\n"
+ "### Current [guidelines](https://clinicalinfo.hiv.gov/en/guidelines/adult-and-adolescent-arv/initiation-antiretroviral-therapy?view=full)\n"
+ "\n"
+ "#### The <span id=\"yb\"> Initiation </span> of Antiretroviral Therapy \n"
+ "\n"
+ "* Antiretroviral therapy (ART) is recommended for all persons with HIV \n"
+ "	* reduce morbidity and mortality (AI) \n"
+ "	* prevent the transmission of HIV to others (AI).\n"
+ "\n"
+ "* The Panel recommends initiating ART immediately after HIV diagnosis\n"
+ "	* increase the uptake of ART and linkage to care, \n"
+ "	* decrease the time to viral suppression for individual patients, \n"
+ "	* improve the rate of virologic suppression among persons with HIV (AII).\n"
+ "\n"
+ "* Educate patients (AIII)\n"
+ "	* the benefits of ART\n"
+ "	* to deploy strategies to optimize care engagement \n"
+ "	* treatment adherence \n"
+ "\n"
+ "Rating of Recommendations: A = Strong; \n"
+ "Rating of Evidence: I = Data from randomized controlled trials; II = Data from well-designed nonrandomized trials or observational cohort studies with long-term clinical outcomes; III = Expert opinion\n"
+ "\n"
+ "\n"
+ "[HAART - cART - ART](https://www.verywell.com/cart-hiv-combination-antiretroviral-therapy-48921)\n"
+ "\n"
+ "---\n"
+ "## HIV Life Cycle \n"
+ "\n"
+ "<table> <tr><td 50%>\n"
+ "<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/eS1GODinO8w\" frameborder=\"0\" allowfullscreen></iframe>\n"
+ "</td><td>\n"
+ "\n"
+ "<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/GR9d9wrOl5E\" frameborder=\"0\" allow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n"
+ "</td></tr></table>\n"
+ "\n"
+ "---\n"
+ "## [HIV Lifecycle](https://en.wikipedia.org/wiki/Discovery_and_development_of_HIV-protease_inhibitors#Life_cycle_of_HIV)\n"
+ "\n"
+ "<img src=\"./images/antiviral/hiv_life_cycle_khan.png\" width=70%> \n"
+ "\n"
+ "1. *Initiation*: attachment, penetration, uncoating\n"
+ "2. *Replication*: genome synthesis, RNA production, protein synthesis\n"
+ "3. *Release*: assembly, maturation, exit from cell\n"
+ "---\n"
+ "\n"
+ "<section id=\"recommend\">\n"
+ "\n"
+ "### [Current Guideline](https://clinicalinfo.hiv.gov/en/guidelines/adult-and-adolescent-arv/what-start-initial-combination-regimens-antiretroviral-naive?view=brief)\n"
+ "\n"
+ "#### for treatment-naive patients\n"
+ "\n"
+ "updated on Jun 03, 2021\n"
+ "\n"
+ "* Integrase inhibitor-based regimens \n"
+ " * <span id=\"drug\"> Bictegravir </span> plus <span id=\"drug\"> tenofovir alafenamide </span> plus <span id=\"drug\"> emtricitabine </span> \n"
+ " * <span id=\"drug\"> Dolutegravir </span> plus <span id=\"drug\"> abacavir </span> plus <span id=\"drug\"> lamivudine </span> — only for individuals who are HLA-B*5701 negative and without chronic hepatitis B virus (HBV) coinfection \n"
+ " * <span id=\"drug\"> Dolutegravir </span> plus (<span id=\"drug\"> emtricitabine </span> or <span id=\"drug\"> lamivudine </span> ) plus (<span id=\"drug\"> tenofovir alafenamide</span> or<span id=\"drug\"> tenofovir disoproxil fumarate</span>) \n"
+ " * <span id=\"drug\"> Dolutegravir </span> plus <span id=\"drug\"> lamivudine </span> —except for individuals with HIV RNA >500,000 copies/mL, HBV co-infection, or in whom ART is to be started before the results of HIV genotypic resistance testing for reverse transcriptase or HBV testing are available.\n"
+ "\n"
+ "<small>An antiretroviral (ARV) regimen for a treatment-naive patient generally consists of two nucleoside reverse transcriptase inhibitors (NRTIs) administered in combination with a third active ARV drug from one of three drug classes: an integrase strand transfer inhibitor (INSTI), a non-nucleoside reverse transcriptase inhibitor (NNRTI), or a protease inhibitor (PI) with a pharmacokinetic (PK) enhancer (also known as a booster; the two drugs used for this purpose are cobicistat and ritonavir). </small>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"Integrase\">\n"
+ "\n"
+ "## In<font color=\"darkred\">tegra</font>se Inhibitor\n"
+ " Bic<font color=\"darkred\">tegra</font>vir (Biktarvy) | Ral<font color=\"darkred\">tegra</font>vir (Isentress) | Dolu<font color=\"darkred\">tegra</font>vir (Tivicay) \n"
+ "<table><tr><td>\n"
+ "<img src=\"./images/antiviral/hiv_integration.png\"</img>\n"
+ "</td> <td>\n"
+ "<ul>\n"
+ "<li>Mechanism of action\n"
+ "<ul>\n"
+ " <li> Inhibits HIV-1 integrase enzyme <br>\n"
+ " <li> Prevents insertion of viral DNA into host genome <p>\n"
+ " </ul>\n"
+ "\n"
+ "<li> ADME\n"
+ " <ul>\n"
+ " <li> Oral drug\n"
+ " <li> Glucuronidation and by CYP3A<br>\n"
+ " 	<li> <span id=drug> <a href=\"https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-5011\">Bictegravir </a> </span> is a substrate of P-glycoprotein. \n"
+ "	<li> <span id=\"drug\"> Elvitegravir </span> is mainly metabolized by CYP3A4 <br>\n"
+ "	<li> Eliminated in both feces and urine <p>\n"
+ "</ul> \n"
+ "\n"
+ "<li> Resistance\n"
+ "<ul>\n"
+ "<li>	<span id=\"drug\"> <a href=\"https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-3823\">Dolutegravir </a></span> has less resistance overlap with <span id=\"drug\"> Raltegravir </span> than does <span id=\"drug\"> elvitegravir </span> . \n"
+ "</ul>\n"
+ "</ul>\n"
+ "</td> </tr></table>\n"
+ "\n"
+ "<span id=drug>Bictegravir</span> displays a high resistance barrier and has an improved phenotypic resistance profile compared to <span id=drug>dolutegravir (DTG), raltegravir (RAL) and elvitegravir (EVG) . Bictegravir </span> has a longer dissociation half-life from both wild-type and mutant HIV-1 integrase/DNA complexes compared with DTG, RAL, and EVG\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Integrase Inhibitor \n"
+ "\n"
+ "* Indication\n"
+ " * <a href=\"#/recommend\">Recommended</a> for naive patients as part of combination ART \n"
+ "* Adverse effects\n"
+ " * Diarrhea, nausea, headache, and fever\n"
+ " * Hypersensitivity to <span id=\"drug\"> Dolutegravir </span> include serious rash, blisters/peeling of skin, hepatitis, facial edema, angioedema, difficulty breathing, or eosinophilia.\n"
+ "* Drug interactions\n"
+ " * Not inducer, inhibitor or substrate of CYP3A4 (exeption: <span id=\"drug\"> Elvitegravir </span> )\n"
+ " * Metabolized by UDP glucuronosyltransferase (UGT)\n"
+ " * <span id=\"drug\"> Rifampin </span> (antibiotic) induces UGT, thus requires higher <span id=\"drug\"> Raltegravir / Dolutegravir </span> dose\n"
+ "---\n"
+ "\n"
+ "<section id=\"nrti\">\n"
+ "\n"
+ "## Nucleoside Reverse Transcriptase Inhibitors (NRTIs)\n"
+ "\n"
+ "* NRTIs\n"
+ "	* <span id=\"drug\">Zidovudine</span> (Retrovir, azidothymidine [ZVD], Apo-Zidovudine, Novo-AZT)\n"
+ "	* <span id=\"drug\" style=\"background-color:#ff9\">**Abacavir**</span> (Ziagen, ABC)\n"
+ "	* <span id=\"drug\" style=\"background-color:#ff9\">**Lamivudine**</span> (Epivir, 3TC)\n"
+ "	* <span id=\"drug\" style=\"background-color:#ff9\">**Emtricitabine**</span> (Emtriva, FTC)\n"
+ "	* many more available, some are no longer in use. \n"
+ "---\n"
+ "## mechanism of action - NRTIs \n"
+ "<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/cC9kyoAo1ac?start=65&list=PLMO1589WRspykVPiy6SgKi3OPKbe9b0El\" frameborder=\"0\" allowfullscreen></iframe>\n"
+ "\n"
+ "---\n"
+ "<section id=\"hostcell\">\n"
+ "\n"
+ "## Mechanisms of Action - NRTIs \n"
+ "* Analogs of naturally occurring [nucleosides](http://static.newworldencyclopedia.org/b/b9/Nucleotides.png)\n"
+ "* NRTIS are converted to their active triphosphate metabolites (i.e. a nucleotide) by <span id=\"yb\">host cell </span>kinases\n"
+ "* MoA\n"
+ " * Competitive inhibitor of viral reverse transcriptase\n"
+ " * Cause DNA chain termination \n"
+ " * Also inhibit host cell DNA polymerase\n"
+ "\n"
+ "\n"
+ "---\n"
+ "## NRTIs\n"
+ "\n"
+ "* [Zidovudine](https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-653) (ZDV, AZT) \n"
+ "	* Analogs of pyrimidine nucleoside (T) \n"
+ "	* Phosphorylated to active triphosphate forms\n"
+ "	* Competes with deoxythymidine triphosphate for incorporation into DNA\n"
+ "* [Lamivudine ](https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-339) (3TC), [Emtricitabine](https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-2465) (FTC)\n"
+ "	* Analogs of pyrimidine nucleoside (C)\n"
+ "* [Abacavir](https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-2332) (ABC)\n"
+ "	* Analog of purine nucleosides (G) \n"
+ "\n"
+ "---\n"
+ "## Nucleoside Reverse Transcriptase Inhibitors (NRTIs)\n"
+ "* Indications\n"
+ "	* First line treatment of HIV infection as components of ART\n"
+ "	* Prevent acute infection of susceptible cells\n"
+ "	* Little effect on cells already infected by HIV\n"
+ "	* <span id=\"drug\"> Zidovudine </span> \n"
+ "		* <span id=\"yb\">Only NRTI shown to reduce perinatal HIV transmission</a>\n"
+ "* Resistance\n"
+ "	* Drugs select for different mutations of the reverse transcriptase gene at the level of specific codons \n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Pharmacological Properties of NRTIs\n"
+ "* Good oral absorption\n"
+ "* Crosses blood-brain barrier\n"
+ "* Metabolism plays limited role in clearance \n"
+ "* Excreted unchanged in urine, except:\n"
+ "	* <span id=\"drug\"> Zidovudine </span> is metabolized to glucoronide\n"
+ "	* <span id=\"drug\"> Abacavir </span> metabolized by alcohol dehydrogenase \n"
+ "\n"
+ "---\n"
+ "\n"
+ "## <a href=\"#/adverse\">Adverse Effects</a> of NRTIs\n"
+ "* Common toxicities\n"
+ "	* Rash; Gastrointestinal distress\n"
+ "	* [Lactic acidosis](https://hivinfo.nih.gov/understanding-hiv/fact-sheets/hiv-and-lactic-acidosis), [hepatic steatosis](https://www.ncbi.nlm.nih.gov/pubmed/22760655) \n"
+ "	* [Lipodystrophy](https://www.ncbi.nlm.nih.gov/PubMed/10509567): fat loss or buildup or both. \n"
+ "		* Including central obesity, dorsocervical fat enlargement [(buffalo hump)](https://www.clinicalkey.com/#!/content/medline/2-s2.0-9525364), peripheral wasting, accumulation of facial fat, [lipomas](http://www.mayoclinic.org/diseases-conditions/lipoma/basics/definition/con-20024646), breast enlargement, [gynecomastia](http://www.mayoclinic.org/diseases-conditions/gynecomastia/home/ovc-20257576)\n"
+ "	*  [Mitochondrial toxicity](https://www.uptodate.com/contents/mitochondrial-toxicity-of-hiv-nucleoside-reverse-transcriptase-inhibitors/) is a major adverse effect of nucleoside analogues,  which can lead to myopathy, peripheral neuropathy, and hepatic steatosis with lactic acidosis\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## <a href=\"#/adverse/\">Adverse Effects </a>of NRTIs\n"
+ " \n"
+ "* Toxicities\n"
+ "	* <span id=\"drug\">Zidovudine</span>: bone marrow suppression; anemia, neutropenia; myopathy (mtDNA); \n"
+ "	* <span id=\"drug\">Abacavir</span>: **hypersensitivity** reaction due to genetic predisposition (multi-organ autoimmune response, potentially life threatening) \n"
+ "		* <span id=\"yb\">HLA-B\\*5701	screening before starting therapy </span> [NEJM](http://www.nejm.org/doi/full/10.1056/NEJMoa0706135#t=article)\n"
+ "	* <span id=\"drug\"> Emtricitabine </span>: psychiatric reactions, depression, dizziness, insomnia <span id=\"mem\"> EmtriPSYtabine</span>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"zidovudine\">\n"
+ "\n"
+ "## Drug Interactions of NRTIs\n"
+ " \n"
+ "* <span id=\"drug\"> Zidovudine </span> \n"
+ "	* Avoid co-administration bone marrow suppressive drugs\n"
+ "		* <span id=\"drug\">Ganciclovir, interferon alpha, dapsone, flucytosine, vincristine, vinblastine</span>\n"
+ "\n"
+ "* <span id=\"drug\"> Abacavir </span> \n"
+ "	* Ethanol significantly increases plasma levels (metabolized by alcohol dehydrogenase)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## NRTIs \n"
+ "\n"
+ "### Summary \n"
+ "\n"
+ "* Indications \n"
+ "	* First line treatment of HIV as part of ART\n"
+ "* Mechanism of action \n"
+ "	* Inhibit viral reverse transcriptase\n"
+ "* Resistance \n"
+ "	* Mutations in reverse transcriptase gene\n"
+ "* ADME \n"
+ "	* Well absorbed by the GI tract; good oral bioavailability\n"
+ "	* Excreted unchanged by the kidney; except\n"
+ "		* <span id=\"drug\"> zidovudine </span> (metabolized into glucoronide)\n"
+ "		* <span id=\"drug\"> Abacavir </span> (metabolized by alcohol dehydrogenase)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## NRTIs \n"
+ "### Summary \n"
+ "* Adverse effects\n"
+ "	* All cause GI distress\n"
+ "	* Lactic acidosis with hepatic steatosis due to mitochondrial toxicity \n"
+ "* Drug-Drug interactions\n"
+ "	* Can be severe due to synergistic effects on myelosuppression and peripheral neuropathy\n"
+ " \n"
+ "[Current Recommendations](#/recommend)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"Tenofovir\">\n"
+ "\n"
+ "## Nucleo<font color=\"darkorange\">t</font>ide Reverse Transcriptase Inhibitor\n"
+ "\n"
+ "[Teno<font color=\"darkorange\">fo</font>vir disoproxil (Viread)](https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-2477)\n"
+ "\n"
+ "<span id=\"mem\"> fo=pho=phosphate</mem>\n"
+ "\n"
+ "* Properties\n"
+ "	* <span id=\"drug\"> Tenofovir disoproxil </span> is a prodrug. It is hydrolyzed to release tenofovir\n"
+ "	* Tenofovir is an analogue of adenosine- <font color=\"darkorange\">5'-monophosphate </font>\n"
+ "	* Requires two intracellular phosphorylation steps for activation\n"
+ "	* Weak inhibitor of mammalian DNA and mt polymerase\n"
+ "	* Included in many <a href=\"#/recommend\"> first-line ART regimens</a>\n"
+ "	* Also indicated for <span id=\"bg\"> hepatitis B </span>\n"
+ "* Mechanism of action\n"
+ "	* Inhibits viral reverse transcriptase by chain termination\n"
+ "* Resistance\n"
+ "	* <span id='bg'>Does not tend to select the K65R mutation when used with <span id=\"drug\">Emtricitabine</span></span> [PubMed](https://www.ncbi.nlm.nih.gov/pubmed/23027713)\n"
+ "	* Cross resistance with preexisting <span id=\"drug\"> zidovudine </span> associated mutations\n"
+ "	* Not affected by <span id=\"drug\"> lamivudine-abacavir </span> associated mutations\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Tenofovir\n"
+ "\n"
+ "* Administration\n"
+ "	* Once daily dosing\n"
+ "	* Increased bioavailability taken with a high fat meal\n"
+ "* Metabolism\n"
+ "	* Substrate of P-glycoprotein \n"
+ "	* Not substrate for P450\n"
+ "	* T&frac12; = 17 h \n"
+ "* <a href=\"#/adverse\">Adverse effect </a>\n"
+ "	* Most common: nausea, vomiting, diarrhea, [flatulence](https://www.clinicalkey.com/#!/content/book/3-s2.0-B9781455770052000676?scrollTo=%23hl0000349), abdominal pain, dyspepsia, and anorexia with weight loss\n"
+ "	* CNS: depression, anxiety, headache\n"
+ "	* Hepatotoxicity: elevated hepatic enzymes \n"
+ "	* Exacerbates renal impairment \n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Tenofovir disoproxil and Emtricitabine \n"
+ "### (Truvada)\n"
+ "\n"
+ "* Better than Abacavir-Lamivudine for initial therapy \n"
+ "	* Extending time to [virologic failure](https://clinicalinfo.hiv.gov/en/glossary/virologic-failure) and first adverse event \n"
+ "	* [NEJM Dec 3 2009](https://www.ncbi.nlm.nih.gov/pubmed/?term=19952143)\n"
+ "* Effective as antiretroviral <span id='bg'>chemoprophylaxis </span>before exposure (PrEP)\n"
+ "	* [NEJM Dec 30 2010](https://www.ncbi.nlm.nih.gov/pubmed/21091279)\n"
+ "	* [CDC page on PrEP](https://www.cdc.gov/hiv/risk/prep/index.html)\n"
+ "	* [full guideline pdf, updated in 2017](https://www.cdc.gov/hiv/pdf/risk/prep/cdc-hiv-prep-guidelines-2017.pdf)\n"
+ "* <a href=\"#/recommend\">Recommended for treatment naive patients</a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"pi\">\n"
+ "\n"
+ "## Protease Inhibitors, PIs\n"
+ "\n"
+ "<div id=\"left50\">\n"
+ "Ataza<u>navir</u> (Reyataz)\n"
+ "<br>\n"
+ "Indi<u>navir</u> (Crixivan)\n"
+ "<br>\n"
+ "Nelfi<u>navir</u> (Viracept)\n"
+ "<br>\n"
+ "Saqui<u>navir</u> (Fortovase)\n"
+ "<br>\n"
+ "Fosampre<u>navir</u> (Lexiva)\n"
+ "<br>\n"
+ "<b>Rito<u>navir</u></b> (Norvir)\n"
+ "<br>\n"
+ "<b>Daru<u>navir</u></b> (Prezista)\n"
+ "<br>\n"
+ "PIs can be peptidomimetic (structural similarities to the cleavage site of HIV polyproteins) or not <span id=\"drug\"> (nelfinavir) </span>.\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "<div id=\"right50\">\n"
+ "<iframe width=\"560\" height=\"400\" src=\"https://www.youtube.com/embed/MK2r8J7SCSg?start=20&amp;stop=60\" frameborder=\"0\" allowfullscreen></iframe>\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Protease Inhibitors\n"
+ "\n"
+ "* Indications\n"
+ "	* Treatment of HIV as part of combination therapy\n"
+ "	* Effective in both acutely and chronic HIV-1 infected cells\n"
+ "	* Effective in monocytes and macrophages \n"
+ "		* Not affected by RT inhibitors\n"
+ "* Mechanism of Action\n"
+ "	* Selective, competitive inhibitors of HIV proteases\n"
+ "	* Bind reversibly to protease active site\n"
+ "	* Prevent cleavage of polyprotein and block viral maturation\n"
+ "	* Early stages of HIV-1 replication cycle not affected\n"
+ "* Resistance\n"
+ "	* Each drug selects for different mutations in protease gene at level of specific codons\n"
+ " \n"
+ "---\n"
+ "\n"
+ "## Protease inhibitors\n"
+ "\n"
+ "* ADME\n"
+ "	* Oral absorption varies\n"
+ "	* Bind extensively to plasma proteins\n"
+ "	* Renal excretion is minimal\n"
+ "		* No adjustments needed for renal dysfunctions\n"
+ "	* Metabolized by cytochrome P-450 system\n"
+ "		* Concurrent use of potent P-450 inducer (e.g. <span id=\"drug\"> rifampin </span> ) leads to decreased PI concentration\n"
+ "	* <span style=\"background-color:#ff9\"> <span id=\"drug\"> Ritonavir </span> is a potent inhibitors of CYP3A4</span>\n"
+ "		* used to increase (i.e. \"boost\") plasma concentration of other PIs except <span id=\"drug\"> nelfinavir </span> (CYP2C19) \n"
+ "		* Toxic adverse effects related to drug accumulation due to PI-mediated inhibition of hepatic P450 system\n"
+ "		 \n"
+ "note: rifampin is a bacterial RNA polymerase inhibitor\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Protease inhibitors\n"
+ "* Common <a href=\"#/adverse\">Adverse Effects</a>\n"
+ "	* Hyperlipidemia \n"
+ "		* May be more dramatic with <span id=\"drug\"> ritonavir </span> due to interference in lipid metabolism. \n"
+ "	* [Lipodystrophy](https://www.ncbi.nlm.nih.gov/PubMed/9652687)\n"
+ "		* Including central obesity, dorsocervical fat enlargement [(buffalo hump)](https://www.clinicalkey.com/#!/content/medline/2-s2.0-9525364), peripheral wasting, accumulation of facial fat, [lipomas](http://www.mayoclinic.org/diseases-conditions/lipoma/basics/definition/con-20024646), breast enlargement, [gynecomastia](http://www.mayoclinic.org/diseases-conditions/gynecomastia/home/ovc-20257576)\n"
+ "	* Insulin resistance and diabetes\n"
+ "	* Elevated liver function\n"
+ "*Specific Adverse Effects \n"
+ "	* Ritonavir \n"
+ "		* Hepatotoxicity at high doses\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"Darunavir\">\n"
+ "\n"
+ "## Darunavir\n"
+ "\n"
+ "* Achieves faster virologic response than control PIs. [PubMed](https://www.ncbi.nlm.nih.gov/pubmed/21692667) \n"
+ "* Can be used to treat patients resist to other PIs. \n"
+ "	* <span id=\"drug\"> darunavir </span> displays a < 10-fold decreased susceptibility against 90% of HIV-1 isolates resistant to <span id=\"drug\"> amprenavir, atazanavir, indinavir, lopinavir, nelfinavir, ritonavir, saquinavir, </span> and/or <span id=\"drug\"> tipranavir </span> . 	\n"
+ "* Must be used in combination in an antiviral regimen.\n"
+ "	* Requires an enhancer (i.e. low does <span id=\"drug\"> ritonavir </span> or [cobicistat](https://www.ncbi.nlm.nih.gov/pubmed/26566368) )\n"
+ "* Was <a href=\"#/recommend\">Recommended</a> for treatment-naive patients\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Protease Inhibitors \n"
+ "### Summary \n"
+ "\n"
+ "* Indications\n"
+ "	* Treatment of HIV infection as part of combination therapy\n"
+ "* Mechanism of action \n"
+ "	* Inhibition of HIV protease\n"
+ "* Resistance\n"
+ "	* Mutations of the protease gene \n"
+ "		*	<span id=\"drug\"> Indinavir, ritonavir </span> and <span id=\"drug\"> lopinavir </span> acquire more mutations than other PIs\n"
+ "* ADME\n"
+ "	* Poor systemic bioavailability (need 'boost')\n"
+ "	* All PIs metabolized in liver by P450 enzymes\n"
+ "* Adverse effects\n"
+ "	* GI distress, diarrhea and vomiting\n"
+ "	* Increase bleeding hemophilia A or B\n"
+ "	* Hyperglycemia, insulin resistance and hyperlipidemia\n"
+ "	* Fat wasting, reaccumulation, and redistribution -- lipodystropy\n"
+ "* Drug interactions\n"
+ "	* Can be severe due to effects on P450 enzymes\n"
+ " \n"
+ "---\n"
+ "\n"
+ "<section id=\"nnrti\">\n"
+ "\n"
+ "## Non Nucleoside Reverse Transcriptase Inhibitors (NNRTIs)\n"
+ "\n"
+ " [Nevirapine (Viramune)](https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-432)\n"
+ "|| [Efavirenz (Sustiva)](https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-2244)\n"
+ "\n"
+ "* Indications\n"
+ "	* HIV-1 infections\n"
+ "		* Do not have significant activity against HIV-2\n"
+ "* Mechanism of action\n"
+ "	* Bind directly to a hydrophobic pocket of the reverse transcriptase \n"
+ "	* Induce conformational change in active site and block enzyme activity\n"
+ "	* Do not require intracellular phosphorylation for activity\n"
+ "* Resistance\n"
+ "	* Resistant HIV emerges rapidly when used as monotherapy.\n"
+ "	* Each drug selects for different mutations of the RT gene at the level of specific codons. \n"
+ "\n"
+ "---\n"
+ "\n"
+ "## NNRTIs\n"
+ "\n"
+ "<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/RUUyd5bE9vQ?start=108&stop=150\" frameborder=\"0\" allowfullscreen></iframe>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## NNRTIs\n"
+ "\n"
+ "* ADME\n"
+ "	* Excellent oral absorption.\n"
+ "	* Metabolized by the cytochrome P-450 system\n"
+ "		* Drug interactions are significant\n"
+ "	* <span id=\"drug\"> Efavirenz </span> and <span id=\"drug\"> Nevirapine </span>: CYP3A4 inducer\n"
+ "		* Reduces PIs, rifabutin, clarithromycin, methadone and ethinyl estradiol plasma levels\n"
+ "* <a href=\"#/adverse\">Adverse effects</a> \n"
+ "	* Common toxicities\n"
+ "		* Maculopapular rashes in the trunk and extremities\n"
+ "		* Hepatotoxicity \n"
+ "	* Unique toxicities \n"
+ "		* <span id=\"drug\"> Nevirapine </span> \n"
+ "			* Fever, fatigue, headache, drowsiness, nausea\n"
+ "		* <span id=\"drug\"> Efavirenz </span> \n"
+ "			* Penetrate the blood brain barrier \n"
+ "			* Neuropsychiatric (headache, dizziness, abnormal dreams, psychosis, suicidal ideation)\n"
+ "			* Teratogenic in nonhuman primates ([Pregnancy Category D](https://en.wikipedia.org/wiki/Pregnancy_category))\n"
+ "	 \n"
+ "---\n"
+ "## NNRTIs \n"
+ "### Summary \n"
+ "\n"
+ "* Indications\n"
+ "	* Treatment of HIV infection as part of combination therapy\n"
+ "	* Not effective against HIV-2\n"
+ "* Mechanism of action \n"
+ "	* Inhibit viral reverse transcriptase\n"
+ "* Resistance\n"
+ "	* Mutations in viral reverse transcriptase\n"
+ "* ADME\n"
+ "	* Well absorbed by the GI tract\n"
+ "	* Good oral bioavailability\n"
+ "	* Metabolized in the liver 	\n"
+ "	* Excreted in the urine as glucoronidated metabolites\n"
+ "* Adverse effects\n"
+ "	* All NNRTIs cause rash\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"Enfuvirtide\">\n"
+ "\n"
+ "## <font color=\"darkorange\">Fu</font>sion inhibitors\n"
+ "\n"
+ "[En<font color=\"darkorange\">fu</font>vir<font color=\"darkorange\">tide</font> (Fuzeon, T20)](https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-2752)\n"
+ "\n"
+ "<table><tr><td width=60% valign=\"top\">\n"
+ "<b>Structure</b> <Br>\n"
+ "<ul>\n"
+ "<li> a synthetic pep<font color=\"darkorange\">tide</font> with <a href=\"https://www.drugbank.ca/drugs/DB00109\">36 amino acids </a>\n"
+ "</ul>\n"
+ "<p>\n"
+ "\n"
+ "<b>Mechanism of action</b><br>\n"
+ "<ul>\n"
+ "<li> Binds to <a href=\"https://en.wikipedia.org/wiki/Gp41#Function\">gp41</a> of the viral envelope; prevents conformational change and impedes the fusion of the viral and host cell membranes. \n"
+ "</ul>\n"
+ "</p>\n"
+ "<b>Indications</b> <br>\n"
+ "<ul>\n"
+ "<li>Reserved as salvage therapy for treatment resistant patients. \n"
+ "<li>Prophylasis after occupational HIV exposure. \n"
+ "<li>Not part of 1st line ART (due to the self-injection method, injection site reaction, and high cost). \n"
+ "</ul>\n"
+ "</td>\n"
+ "\n"
+ "<td>\n"
+ "\n"
+ "![](./images/antiviral/coreceptor.jpg)[video](https://youtu.be/eS1GODinO8w?t=57s)\n"
+ "</td></tr></table>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Enfuvirtide \n"
+ "\n"
+ "* ADME\n"
+ "	* Administered subcutaneously (synthetic peptide)\n"
+ "	* Bound to plasma protein\n"
+ "	* Metabolized by proteolytic hydrolysis\n"
+ "	* T&frac12; = 4 h \n"
+ "* <a href=\"#/adverse\">Adverse effect</a>\n"
+ "	* Injection-site pain or infection \n"
+ "	* Pancreatitis\n"
+ "	* Hypersensitivity reaction (rash, fever, peripheral edema, acute respiratory distress, etc.) \n"
+ "	* Initial report of increased bacterial pneumonia (but no longer significant after adjusting for monitoring duration)\n"
+ "* Resistance \n"
+ "	* gp41 mutations may develop when drug is given at suboptimal doses as monotherapy; No cross-resistance with other HIV Agents\n"
+ "	* Ineffective for HIV-2\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"Maraviroc\">\n"
+ "\n"
+ "## Fusion inhibitors\n"
+ "\n"
+ "[Maraviroc (<font color=\"orange\">Sel</font>z<font color=\"darkred\">entry</font>) ](https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-3567)\n"
+ " \n"
+ "\n"
+ "<div id=\"right50\">\n"
+ "\n"
+ "![](./images/antiviral/coreceptor.jpg)\n"
+ "\n"
+ "</div>	\n"
+ "\n"
+ "<div id=\"left50\">\n"
+ "\n"
+ "**Mechanism of action** <br>\n"
+ "\n"
+ "[Chemokine](https://www.ncbi.nlm.nih.gov/pubmed/7548618) receptor 5 antagonist<br>\n"
+ "Binds to CCR5 co-receptor<br>\n"
+ "Prevents virus from entering the host cell <br>\n"
+ "<p> \n"
+ "\n"
+ "**ADME** <br>\n"
+ "	Oral<br>\n"
+ "	Substrate for both [CYP3A4](https://en.wikipedia.org/wiki/CYP3A4#Function) and [P-glycoprotein](https://en.wikipedia.org/wiki/P-glycoprotein) <br>\n"
+ "	T&frac12;=14~18 h<br>\n"
+ "	Both urine and feces\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Maraviroc (Selzentry)\n"
+ " \n"
+ "* Indication\n"
+ "	* Treatment of CCR5-tropic HIV-1 (not CXCR4)\n"
+ "	* Coreceptor (i.e. CCR5 vs CXCR4) tropism assay must be performed \n"
+ "	* In combination for patients failing other antiretroviral drugs\n"
+ "* <a href=\"#/adverse\">Adverse effects</a>\n"
+ "	* Rash\n"
+ "	* Elevated hepatic enzyme, hepatitis \n"
+ "	* Systemic allergic reaction, cough, fever \n"
+ "* Drug interactions\n"
+ "	* CYP3A inhibitors or inducers\n"
+ "		* Reduce dosage when <span id=\"drug\"> ritonavir </span> or <span id=\"drug\"> cobicistat </span> is coadministered \n"
+ "		* Increase dosage with <span id=\"drug\"> efavirenz </span> \n"
+ " \n"
+ "<a href=\"https://www.nature.com/articles/d41586-019-01739-w\">Human genome editing on CCR5</a>\n"
+ "---\n"
+ "\n"
+ "## Antiretroviral Drug Selectivity\n"
+ "\n"
+ "* NRTIs\n"
+ "	* Once phosphorylated by cellular kinases, NRTIs have greater affinity for viral reverse transcriptase than for cellular DNA polymerases.\n"
+ "* NNRTIs\n"
+ "	* Do not undergo phosphorylation\n"
+ "	* Have greater affinity for viral reverse transcriptase than for cellular DNA polymerases\n"
+ "* PIs\n"
+ "	* Greater affinity for HIV aspartyl protease than for human protease.\n"
+ "* Integrase Inhibitors\n"
+ "	* Much higher selectivity than other classes of anti-HIV drugs.\n"
+ "---\n"
+ "\n"
+ "### [Current Guideline](https://clinicalinfo.hiv.gov/en/guidelines/adult-and-adolescent-arv/what-start-initial-combination-regimens-antiretroviral-naive?view=brief)\n"
+ "\n"
+ "#### for treatment-naive patients\n"
+ "\n"
+ "* Integrase inhibitor-based regimens \n"
+ " * <span id=\"drug\"> Bictegravir </span> plus <span id=\"drug\"> tenofovir alafenamide </span> plus <span id=\"drug\"> emtricitabine </span> \n"
+ " * <span id=\"drug\"> Dolutegravir </span> plus <span id=\"drug\"> abacavir </span> plus <span id=\"drug\"> lamivudine </span> — only for individuals who are HLA-B*5701 negative and without chronic hepatitis B virus (HBV) coinfection \n"
+ " * <span id=\"drug\"> Dolutegravir </span> plus (<span id=\"drug\"> emtricitabine </span> or <span id=\"drug\"> lamivudine </span> ) plus (<span id=\"drug\"> tenofovir alafenamide</span> or<span id=\"drug\"> tenofovir disoproxil fumarate</span>) \n"
+ " * <span id=\"drug\"> Dolutegravir </span> plus <span id=\"drug\"> lamivudine </span> —except for individuals with HIV RNA >500,000 copies/mL, HBV co-infection, or in whom ART is to be started before the results of HIV genotypic resistance testing for reverse transcriptase or HBV testing are available.\n"
+ "\n"
+ "An antiretroviral (ARV) regimen for a treatment-naive patient generally consists of two nucleoside reverse transcriptase inhibitors (NRTIs) administered in combination with a third active ARV drug from one of three drug classes: 1. an integrase strand transfer inhibitor (INSTI), 2. a non-nucleoside reverse transcriptase inhibitor (NNRTI), 3. a protease inhibitor (PI) with a pharmacokinetic (PK) enhancer (also known as a booster; the two drugs used for this purpose are cobicistat and ritonavir). \n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "### [Current negative Recommendations]\n"
+ "## [What not to use](https://clinicalinfo.hiv.gov/en/guidelines/adult-and-adolescent-arv/what-not-use?view=full)\n"
+ "\n"
+ "* Drugs\n"
+ "	* <span id=drug>delavirdine, didanosine, indinavir, nelfinavir, stavudine</span> \n"
+ "* Monotheray\n"
+ "* Dual-NRTI regimens\n"
+ "* Tripple-NRTI regimens\n"
+ "* Specific drug combinations\n"
+ "	* <span id=\"drug\"> Cobicistat </span> plus <span id=\"drug\"> Ritonavir </span> (both are CYP3A4 inhibitors)\n"
+ "	* <span id=\"drug\"> Emtricitabine </span> plus <span id=\"drug\"> Lamivudine </span> (these two drugs are very similar)\n"
+ "	* <span id=\"drug\"> Darunavir </span> without boosting (anti-viral effect unclear without boosting) \n"
+ "\n"
+ "These are just a few examples. Detailed list available from the link above\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"hour2\">\n"
+ "\n"
+ "## Agents for the treatment of virus infections \n"
+ "### [Hour 2](#/hour2) \n"
+ "* <a href=\"#/hsv\">Herpes Simplex Virus</a> and Varicella Zoster Virus\n"
+ "	* <span id=\"drug\">[Acyclovir, Valacyclovir](#/Acyclovir), [Tenofovir](#/Tenofovir2), [Famciclovir, Penciclovir](#/Penciclovir)</span>\n"
+ "* <a href=\"#/cmv\">Cytomegalovirus</a>\n"
+ "	* <span id=\"drug\">[Ganciclovir, Valganciclovir](#/Ganciclovir), [Cidofovir](#/Cidofovir), [Foscarnet](#/Foscarnet)</span>\n"
+ "* <a href=\"#/hbv\">Hepatitis Virus B </a> | Hepatitis Virus C \n"
+ "	* <span id=\"drug\"> [Entecavir](#/Entecavir), [Ribavirin](#/Ribavirin), [Interferon alpha](#/Interferon) \n"
+ "* <a href=\"#/flu\">Influenza Virus </a>\n"
+ "	* Viral release inhibitors <span id=\"drug\"> [Zanamivir, Oseltamivir](#/flurelease)</span>\n"
+ "	* Cap-dependent endonuclease inhibitor <span id=\"drug\"> [Baloxavir](#/flucap)</span>\n"
+ "* <a href=\"#/covid\">SARS-CoV-2 </a>\n"
+ "	* <span id=\"drug\">[Remdesivir](#/remdesivir)</span>\n"
+ "	* <span id=\"drug\">[Molnupiravir](#/molnupiravir)</span>\n"
+ "	* antibody drugs\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Objectives \n"
+ "\n"
+ "1. For each virus, understand the <span id=\"yb\"> major classes </span> of available antiviral agents.\n"
+ "2. Describe the <span id=\"yb\">mechanisms of action</span> for HSV, CMV, and HBV antiviral agents and <span id=\"yb\">mechanisms of viral resistance</span> to these agents.\n"
+ "3. Describe the common and unique adverse effects of the distinct classes of antiviral agents\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Agents to treat HSV, VZV and CMV\n"
+ "|Virus| Disease| \n"
+ "|---|---|\n"
+ "|Herpes simplex virus, human herpesvirus 1 and 2 | herpes genitalis | \n"
+ "|| herpes labialis | \n"
+ "|| herpetic keratoconjunctivitis |\n"
+ "|| herpetic encephalitis|\n"
+ "|Varicella-zoster virus, human herpesvirus-3 | chickenpox (varicella)|\n"
+ "|| shingles (herpes zostr)|\n"
+ "|Cytomegalovirus, human herpesvirus-5 | retinitis &dagger;| \n"
+ "|| esophagitis &dagger;| \n"
+ "||\n"
+ "&dagger; most often in immunocompromised (e.g. AIDS) patients.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"hsv\">\n"
+ "\n"
+ "## Herpes Simplex virus\n"
+ "\n"
+ "<img src=\"./images/antiviral/shutterstock_hsv.png\" width=60%>\n"
+ "\n"
+ "<div id=\"greyText\">\n"
+ "Double stranded DNA virus\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Life cycle of HSV\n"
+ "\n"
+ "<img src=\"./images/antiviral/dna_virus.png\" width=70%>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "## Nucleoside Analogs and others\n"
+ "\n"
+ "<table><tr><td width=40%>\n"
+ "\n"
+ "<ul>\n"
+ "<li><span id=\"drug\">Acyclovir</span> (Zovirax)\n"
+ "<li><span id=\"drug\">Valacyclovir</span> (Valtrex)\n"
+ "<hr>\n"
+ "<li><span id=\"drug\">Penciclovir</span> (Denavir)\n"
+ "<li><span id=\"drug\">Famciclovir</span> (Famvir)\n"
+ "<hr>\n"
+ "<li><span id=\"drug\">Ganciclovir</span> (Cytovene)\n"
+ "<li><span id=\"drug\">Valganciclovir</span> (Valcyte)\n"
+ "<hr>\n"
+ "<hr>\n"
+ "<li><span id=\"drug\">Cido<span id='bg'>fo</span>vir</span> (Vistide)\n"
+ "<li><span id=\"drug\">Foscarnet</span> (Foscavir)\n"
+ "</ul>\n"
+ "\n"
+ "</td><td>\n"
+ "<ul>\n"
+ "<li> Mechanism of action \n"
+ "<ul><li> Inactivation of viral DNA polymerase through direct binding and competition for dNTPs.\n"
+ "<li> Inducing viral DNA chain termination \n"
+ "</ul>\n"
+ "</td></tr></table>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Mechanisms of Activation of [Nucleoside](http://static.newworldencyclopedia.org/b/b9/Nucleotides.png) Analogs\n"
+ "\n"
+ "c.f. <a href=#/hostcell>NRTI for HIV</a>\n"
+ "\n"
+ "<img src=\"./images/antiviral/nucleoside_activation2.png\" width=40%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nucleoside analogues\n"
+ "\n"
+ "* Drug selectivity:\n"
+ "	* The <span id=\"yb\">virus in infected cells activates the drug to an active form</span>\n"
+ "		* Uninfected cell does not activate drug.\n"
+ "	* Preferential affinity of acyclovir triphosphate for viral DNA polymerase rather than cellular enzyme. \n"
+ "* Resistance: \n"
+ "	* Altered viral thymidine kinase substrate specificity\n"
+ "	* Absence of viral thymidine kinase \n"
+ "	* Mutated viral DNA polymerase \n"
+ "\n"
+ "---\n"
+ "<section id=\"Acyclovir\">\n"
+ "\n"
+ "## Acyclovir \n"
+ "### [Valacyclovir](https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-636) (L-valyl ester prodrug of acyclovir)\n"
+ "	\n"
+ "\n"
+ "* Mechanism of action \n"
+ "	* <span id=\"drug\"> acyclovir </span> is phosphorylated intracellularly by viral thymidine kinases (TK), then by cellular kinases to the triphosphate state, which terminates DNA replication when incorported into the viral DNA. \n"
+ "	* Only effective against actively replicating virus. Does not eliminate the viral genome. \n"
+ "* ADME\n"
+ "	* <span id=\"drug\"> acyclovir </span> has low oral bioavailability (10-20%). (i.v. or topical) \n"
+ "	* <span id=\"drug\"> Valacyclovir </span> is hydrolyzed to acyclovir in intestine or liver. Increase bioavailability (3.3 - 5 X) \n"
+ "	* competitive inhibition of viral DNA polymerase; chain termination. \n"
+ "* Indication: * HSV keratitis, herpes labialis, genital herpes, HSV encephalitis\n"
+ "	* VZV \n"
+ "	* CMV-positive bone marrow transplant recipients\n"
+ "* Adverse effects\n"
+ "	* Headache, nausea, diarrhea\n"
+ "	* Following high IV dose: Reversible renal dysfunction (crystalline nephropathy), Neurologic toxicity (tremors, delirium, seizures)\n"
+ "\n"
+ "---\n"
+ "<section id=\"Penciclovir\">\n"
+ "\n"
+ "\n"
+ "## Penciclovir\n"
+ "### [Famciclovir](https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-240) (diacetyl ester prodrug)\n"
+ "\n"
+ "* ADME\n"
+ "	* <span id=\"drug\"> Penciclovir </span> is for topical application only.\n"
+ "	* <span id=\"drug\"> Famciclovir </span> is oral, has longer intracellular half-life than <span id=\"drug\"> Acyclovir </span>, but with lower affinity for the viral enzyme \n"
+ "	* Not a CYP450 substrate\n"
+ "* Mechanism of action \n"
+ "	* Selective substrate of HSV VZV thymidine kinase\n"
+ "	* Competitive inhibition of viral DNA polymerase\n"
+ "* Indications\n"
+ "	* Alternative to Acyclovir\n"
+ "	* Infection of HSV, VZV. \n"
+ "* Adverse effects\n"
+ "	* Well tolerated\n"
+ "	* Headaches, nausea, diarrhea\n"
+ "\n"
+ "---\n"
+ "<section id=\"cmv\">\n"
+ "\n"
+ "## Cytomegalovirus\n"
+ "\n"
+ "<img src=\"./images/antiviral/cmv.png\" width=60%>\n"
+ "\n"
+ "<div id=\"greyText\">\n"
+ "Double stranded DNA virus\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "<section id=\"Ganciclovir\">\n"
+ "\n"
+ "## Ganciclovir\n"
+ "### [Valganciclovir](https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-2584) (L-valyl ester prodrug)\n"
+ "\n"
+ "* MoA\n"
+ "	* Ganciclovir is phosphorylated to ganciclovir monophosphate by a viral protein kinase\n"
+ "	* Ganciclovir triphosphate inhibits viral DNA synthesis \n"
+ "		* competing for a position in the viral DNA\n"
+ "		* terminating DNA synthesis once incorporated \n"
+ "* ADME\n"
+ "	* <span id=\"drug\"> Valganciclovir </span> is hydrolyzed by esterases following oral administration to <span id=\"drug\"> ganciclovir </span> \n"
+ "* Indications\n"
+ "	* CMV retinitis in AIDS patients\n"
+ "		* Activity 100 x greater than <span id=\"drug\"> Acyclovir </span> <span id='mem'>Gangbuster drug for a gigantic virus</span> \n"
+ "	* CMV prophylaxis (e.g., liver transplant patients) \n"
+ "* <a href=\"#/adverse\">Adverse effects</a>\n"
+ "	* Bone marrow suppression, neutropenia, anemia, \n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"Cidofovir\">\n"
+ "\n"
+ "## [Cido<font color=\"darkorange\">fo</font>vir](https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-125)\n"
+ "\n"
+ "<span id=\"mem\">fo=pho=phospho=nucleotide</span>\n"
+ "\n"
+ "* Mechanism of action \n"
+ "	* Cytidine nucleo<font color=\"darkorange\">t</font>ide analog\n"
+ "	* Not phosphorylated by viral TK\n"
+ "	* Inhibits herpevirus DNA polymerase >> human DNA polymerase\n"
+ "	* Induce DNA fragmentation and Caspase-3 activity\n"
+ "* ADME	\n"
+ "	* Once weekly i.v. <u>injection</u> \n"
+ "* Indications\n"
+ "	* <span id=\"drug\"> Ganciclovir, foscarnet, </span> and <span id=\"drug\"> acyclovir </span> -resistant CMV strains	\n"
+ "	* <span id=\"drug\"> cidofovir </span> i.v. delays progression of CMV retinitis in HIV+ patients\n"
+ "* <a href=\"#/adverse\"> Adverse effects</a>\n"
+ "	* Nephrotoxicity, neutropeina, ocular hypotony, alopecia\n"
+ "	* Potential human carcinogen\n"
+ "	\n"
+ "\n"
+ "---\n"
+ "<section id=\"Foscarnet\">\n"
+ "\n"
+ "## [<font color=\"darkorange\">Fos</font>carnet (Foscavir)](https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-267)\n"
+ "### Non-nucleoside Anti-HSV Agent\n"
+ "\n"
+ "* Mechanism of Action\n"
+ "	* Inorganic pyro<font color=\"darkorange\">phos</font>phate analog\n"
+ "	* Inhibits HSV DNA polymerase and HIV-1 reverse transcriptase \n"
+ "	* Binds to pyrophosphate binding site of polymerase\n"
+ "	* <a href=\"https://en.wikipedia.org/wiki/Nucleoside_triphosphate#/media/File:DNA_synthesis_EN.png\">Inhibits cleavage of pyrophosphate from deoxyribonucleotide triphosphate (dNTP)</a>\n"
+ "	* Blocks viral DNA synthesis\n"
+ "* Indications\n"
+ "	* Nucleoside-resistant HSV, VZV, and CMV infections\n"
+ "	* Effective in CMV retinitis, and acyclovir and ganciclovir-resistant strains of HSV and VZV\n"
+ "	* Has been used as [salvage therapy](https://www.ncbi.nlm.nih.gov/PubMed/16964823) for multi-drug resistant HIV\n"
+ "* <a href=\"#/adverse\">Adverse effects</a>\n"
+ "	* Renal failure or dysfunction \n"
+ "	* Seizure, depression, confusion, and anxiety (high CSF/plasma ratio)\n"
+ " * one marrow suppression\n"
+ "	* Nausea, vomiting, and fatigue\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Inhibitors of Viral DNA Replication \n"
+ "\n"
+ "### Summary \n"
+ "* Indications\n"
+ "	* HSV, VZV, and CMV infections \n"
+ "* Mechanism of action\n"
+ "	* Inhibit viral DNA polymerases\n"
+ "* Resistance\n"
+ "	* Mutations of the viral polymerase gene\n"
+ "	* Deficiency of viral tyrosine kinase \n"
+ "* ADME\n"
+ "	* Bioavailability varies. \n"
+ "	* Renal excretion of unmetabolized parent drug through glomerular filtration -- Adjust dose\n"
+ "* <a href=\"#/adverse\">Adverse effects</a>\n"
+ "	* Generally well tolerated\n"
+ "	* Ganciclovir -- myelosuppressant and has teratogenic potential\n"
+ "	* Cidofovir and Foscarnet -- nephrotoxic\n"
+ "\n"
+ "---\n"
+ "<section id=\"hbv\">\n"
+ "\n"
+ "## Hepatitis B Virus\n"
+ "\n"
+ "<img src=\"./images/antiviral/shutterstock_hbv.png\" width=50%>\n"
+ "\n"
+ "<div id=\"greyText\">\n"
+ "Partially double-stranded DNA virus\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## HBV life cycle\n"
+ "\n"
+ "<iframe width=\"700\" height=\"500\" src=\"https://www.youtube.com/embed/sVpiXaEMs7I?start=342\" frameborder=\"0\" allowfullscreen></iframe>\n"
+ "\n"
+ "partial DNA enters nucleus -> cccDNA -> RNA -> <span id='bg'>HBV polymerase</span> -> DNA (negative strand) -> DNA (positive strand)\n"
+ "\n"
+ "<b>ccc</b>: covalently closed circular\n"
+ "\n"
+ "HBV polymerase has reverse transcription activity\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Anti-Hepatitis Agents\n"
+ "\n"
+ "* <span id=\"drug\">Entecavir</span> (Baraclude)\n"
+ "* <span id=\"drug\">Adefovir</span> (Hepsera)\n"
+ "* <span id=\"drug\">Tenofovir</span> (Viread)\n"
+ "* <span id=\"drug\">Interferon alfa-2a</span> (Roferon) and -2b (Intron A)\n"
+ "* <span id=\"drug\">Peginterferon alfa-2a</span> (Pegasys) and alfa-2b (PegIntron)\n"
+ "\n"
+ "---\n"
+ "<section id=\"Entecavir\">\n"
+ "\n"
+ "## [Entecavir](https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-3427) (Baraclude)\n"
+ "\n"
+ "* Mechanism of action \n"
+ "	* Nucleoside analog of <b>G</b>uanosine\n"
+ "	* Inhibits all 3 activities of HBV polymerase\n"
+ "		* Base priming ([GAA](https://youtu.be/sVpiXaEMs7I?t=6m12s)) [PubMed](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4399241/) \n"
+ "		* Reverse transcription of the negative DNA strand \n"
+ "		* DNA synthesis of positive strand\n"
+ "* Indication \n"
+ "	* Effective in treatment naive HBV patients\n"
+ "	* Equally active against <span id=\"drug\"> lamivudine</span>-resistant HBV\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Entecavir\n"
+ "\n"
+ "* ADME\n"
+ "	* Oral bioavailability is 37-80%\n"
+ "	* Tablets and liquid form are interchangeable\n"
+ "	* Absorption is affected by food (decreased <40%)\n"
+ "		* Take on empty stomach (2 hrs before or 2 hrs after meal)\n"
+ "	* Not metabolized - not substrate for CYP450\n"
+ "		* No dosage alteration for hepatic impairment\n"
+ "	* Excreted by kidneys (both glomerular filtration and tubular secretion)\n"
+ "		* With CrCl < 50 ml/min, dose should be modified\n"
+ "		* Co-administration with other drugs that reduce renal function, may increase conc of <span id=\"drug\"> entecavir </span> or other drug\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Entecavir\n"
+ "\n"
+ "* Adverse effects\n"
+ "	* Generally well tolerated\n"
+ "	* **HBV exacerbation upon discontinuation of treatment**\n"
+ "	* Elevation of hepatic enzymes may occur, lactic acidosis \n"
+ "		* Monitor hepatic function for several months and re-initiate therapy if warranted\n"
+ "	* Most commonly reported: headache, fatigue, dizziness\n"
+ "---\n"
+ "\n"
+ "<section id=\"Tenofovir2\">\n"
+ "\n"
+ "## Tenofovir \n"
+ "\n"
+ "* Mechanism of action\n"
+ "	* A nucleotide analog of adenosine monophosphate\n"
+ "	* First nucleotide reverse transcriptase inhibitor\n"
+ "	* Inhibits viral reverse transcriptase\n"
+ "* Resistance\n"
+ "	* Thymidine analogue mutations\n"
+ "		* Cross resistance with preexisting <span id=\"drug\"> zidovudine</span>-associated mutations\n"
+ "	* Not effected by <span id=\"drug\"> lamivudine-abacavir </span> associated mutationse\n"
+ "---\n"
+ "## Tenofovir\n"
+ "* Administration\n"
+ "	* Once daily dosing\n"
+ "	* Increased bioavailability taken with a meal\n"
+ "* Metabolism\n"
+ "	* Not substrate for P450\n"
+ "	* No adverse drug interactions with other P450 substrate drugs\n"
+ "* Adverse effect: \n"
+ "	* Most commonly (>3%) in clinical trials: nausea, diarrhea, asthenia, headache, vomiting, flatulence, abdominal pain, and anorexia. \n"
+ "	* Increase in liver enzymes\n"
+ "	* watch for hepatitis flare if discontinued in patients with chronic HBV infection.\n"
+ "---\n"
+ "<section id=\"Adefovir\">\n"
+ "\n"
+ "## [Ade<font color=\"darkorange\">fo</font>vir](https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-2233)(Hepsera)\n"
+ "\n"
+ "* Mechanism of action \n"
+ "	* Nucleo<font color=\"darkorange\">t</font>ide analog of deoxy<font color=\"darkorange\">ade</font>nosine monophosphate\n"
+ "	* Following formation of the diphosphate by cellular kinases, it inhibits HBV DNA polymerase\n"
+ "	* ~10-fold more active for viral DNA polymerase than for the human DNA polymerase\n"
+ "	* No cross resistance of <span id=\"drug\"> lamivudine</span>-resistant HBV strains\n"
+ "* Indication\n"
+ "	* chronic hepatitis B\n"
+ "* <a href=\"#/adverse\">Adverse Effects</a>\n"
+ "	* Exacerbations of hepatitis after discontinuation of treatment \n"
+ "	* Nephrotoxicity \n"
+ "	* Lactic acidosis/severe hepatomegaly with steatosis\n"
+ "* [No longer](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5975958/) a preferred drug for HBV\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"Ribavirin\">\n"
+ "\n"
+ "## [Ribavirin](https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-542)\n"
+ "(Copegus | Moderiba | Rebetol | RibaPak | RibaTab | Ribasphere | Virazole)\n"
+ "\n"
+ "* MoA \n"
+ "	* Nucleoside analog of guanosine\n"
+ "	* Increase mutation of viral <a href=\"#/molnupiravir\"> <span id=\"yb\">DNA</span></a> and leads to \"**error catastrophe**\"\n"
+ "	* Interference with synthesis of GTP / Increase production of cytokine\n"
+ "* Indication \n"
+ "	* Treat <u>Hepatitis C</u> in combination with <span id=\"drug\"> peginterferon alpha </span> \n"
+ "	* Weight-based dosing results in a higher sustained virologic response \n"
+ "	* <u>Respiratory syncytial virus</u>: aerosolized form \n"
+ "	* <u>Hantaan virus</u>: intravenous \n"
+ "* Adverse effects\n"
+ "	* Dose dependent hemolytic anemia (10-20% of patients) with systemic use\n"
+ "		* Extravascular hemolysis\n"
+ "	* Bone morrow suppression\n"
+ "	* Psychiatric effects: depression, insomnia, anxiety.\n"
+ "	* Aerosolized form well tolerated\n"
+ "		* Possible mild conjunctival irritation\n"
+ "		* Reversible deterioration in pulmonary function\n"
+ "	* Teratogenic in animals\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Common to all the nucleoside analogs\n"
+ "\n"
+ "<span id=\"drug\">Entecavir </span> <span id=\"drug\">Adefovir </span> <span id=\"drug\">Tenofovir </span> \n"
+ "\n"
+ "* Lactic acidosis and severe hepatomegaly with steatosis is a more common adverse effect of the nucleoside analogs in the treatment of HIV, where they are always used in combination therapy, but these effects are much <u>less</u> likely to occur with monotherapy for treatment of hepatitis B. \n"
+ "\n"
+ "* Severe acute exacerbations of hepatitis B have been reported in patients who have stopped taking the drug.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Immunoregulators\n"
+ "\n"
+ "* [Interferons](https://www.clinicalkey.com/#!/content/book/3-s2.0-B9780323080583000137?scrollTo=%23hl0000129) (IFNs)\n"
+ "	* Potent cytokines that posses antiviral, antiproliferation (antineoplastic) and immunomodulating actions\n"
+ "		* Activates ribonucleases to degrade viral RNA\n"
+ "		* Inhibition of viral replication\n"
+ "		* Blocks protein synthesis &mdash; inhibits translation initiation complex\n"
+ "	* Three major classes of human IFNs\n"
+ "\n"
+ "|Interferon|Type| Receptor| Effect|\n"
+ "|---|---|---|---|\n"
+ "|&alpha;|Type I | IFNAR &dagger;| Antiviral|\n"
+ "|&beta;| Type I | IFNAR| Antiviral| \n"
+ "|&gamma;|Type II| IFNGR &Dagger;|Immunomodulation|\n"
+ "||\n"
+ "\n"
+ "<small>\n"
+ " &dagger; composed of two subunits IFNAR1 and IFNAR2. &Dagger; composed of two subunits IFNGR1 and IFNGR2\n"
+ " </small>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Interferons \n"
+ "### Antiviral effect \n"
+ "\n"
+ "* Type I has more potent antiviral effect. It can be produced in almost any cell type when it is infected with a virus. It is triggered by molecular patterns of characteristic of viral but not host components (e.g. viral 5'-triphosphorylated ssRNA and dsRNA). \n"
+ "	* dsRNA is produced by positive-strand RNA viruses and DNA viruses, but not detectable by negative-strand RNA Viruses [PubMed](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1472073/)\n"
+ "\n"
+ "* Interferon alpha is generally active against the following viruses <i> in vitro</i>: \n"
+ "	* <span style=\"font-weight:normal; font-size: 0.6em\"> adenovirus; coronavirus; encephalomyocarditis virus; hepatitis B virus; hepatitis C virus (HCV); hepatitis D virus; herpes simplex virus type 1; herpes simplex virus type 2; human immunodeficiency virus (HIV); papillomavirus; poliovirus; rhinovirus; vaccinia virus; varicella-zoster virus; vesicular stomatitis virus; human T-lymphotropic virus type I (HTLV-I).\n"
+ "</span>\n"
+ "\n"
+ "* Induces immune responses, alter the expression of genes, cell surface markers, phagocytic activity, cytotoxicity, etc. \n"
+ "\n"
+ "* Exact mechanism remain unclear, but may include the induction of enzymes that interfer with key steps in the HBV life cycle, include those that degrade foreign, but not host DNA ([PubMed](https://www.ncbi.nlm.nih.gov/pubmed?term=24557838)) \n"
+ "---\n"
+ "\n"
+ "<section id=\"Interferon\">\n"
+ "\n"
+ "## [Interferon alpha-2a](https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-2508) \n"
+ "## [peginterferon alpha-2a](https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-2634)\n"
+ "\n"
+ "* Indications\n"
+ "	* Chronic HBV, HPV and (Kaposi sarcoma, human herpesvirus-8)\n"
+ "	* HCV \n"
+ "		* <span id='bg'> <span id=\"drug\"> peginterferon </span> in combination with <span id=\"drug\"> Ribavirin </span></span>\n"
+ "* ADME\n"
+ "	* Administered i.m. or s.c.\n"
+ "	* High bioavailability\n"
+ "	* Proteolytic degradation in the Kidney is the main site of metabolism\n"
+ "	* Eliminated in the urine ( IFN-&alpha;2 T&frac12; = 5.1 h)\n"
+ "	* Peginterferon has much longer T&frac12; ( 80 h) \n"
+ "		* IFN-&alpha;2a is no longer produced in the USA\n"
+ "\n"
+ "<small>\n"
+ "* PEG = bis-monomethoxy polyethylene glycol \n"
+ "</small>\n"
+ "---\n"
+ "\n"
+ "## Interferon alpha-2\n"
+ "\n"
+ "* <a href=\"#/adverse\">Adverse effects</a>\n"
+ "	* Flu-like syndrome: nausea, vomiting, anorexia\n"
+ "	* Bone marrow suppression (95% patients)\n"
+ "	* Psychiatric effects: depression, homicidal and suicidal ideation\n"
+ "	* Injection site reaction\n"
+ "	* Should not be administered during pregnancy\n"
+ "* Drug interactions\n"
+ "	* Increases in the level of many drugs:\n"
+ "		* <span id=\"drug\"> theophylline </span> (for asthema) by 100% \n"
+ "		* <span id=\"drug\"> zidovudine </span> by 93%. \n"
+ "	* Co-administration with <span id=\"drug\"> zidovudine </span> can [increase severity of myelosuppression](#/zidovudine).\n"
+ "	* Additive myelosuppressive effects when combined with some anticancer agents or immunosuppressives.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"flu\">\n"
+ "\n"
+ "## Influenza virus\n"
+ "\n"
+ "<img src=\"./images/antiviral/shutterstock_influenza.png\" width=60%>\n"
+ "\n"
+ "<div id=\"greyText\"> Single negative strand, segmented (8) RNA virus || Type A H18N10, Type B or C </div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Life cycle\n"
+ "\n"
+ "\n"
+ "<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/2RMNwLdtRhw\" frameborder=\"0\" allow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n"
+ "\n"
+ "[Life cycle review](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2794490/)\n"
+ "---\n"
+ "\n"
+ "## Mechanism of Action of Antiinfluenza Agents\n"
+ "\n"
+ "<table><tr><td>\n"
+ "<img src=\"./images/antiviral/flu.png\" width=100%>\n"
+ "</td><td width=50%>\n"
+ "<ol>\n"
+ "<li> virus enter the cell via H spikes. In the endosome, low pH in the endosome trigger the <span id='bg'> fusion of membranes</span>.\n"
+ "<li> viral ribonucleoprotein and viral RNA enters the cell nucleus, replicate the viral genome. \n"
+ "<li> viral RNA is also made and steals the 5'cap of of cellular RNA (important for making protein) and exported into the cytoplasm.\n"
+ "<li> viral protein is made and virus is packaged on cell surface\n"
+ "<li> the N spikes cleave the H spikes and releases the viron.\n"
+ "</ol>\n"
+ "</td>\n"
+ "</tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Antiinfluenza Agents\n"
+ "\n"
+ "* Virus release inhibitors\n"
+ "	* <span id=\"drug\"> Zanamivir</span> (Relenza)\n"
+ "	* <span id=\"drug\"> Oseltamivir</span> (Tamiflu)\n"
+ "\n"
+ "* Cap-dependent endonuclease inhibitor\n"
+ "	* <span id=\"drug\"> Baloxavir </span> (Xofluza)\n"
+ "\n"
+ "* Uncoating inhibitors \n"
+ "	* most current strains of flu virus are resistant to these drugs\n"
+ "	* <span id=\"drug\"> Amantadine</span> (Symadine, Symmetrel)\n"
+ "	* <span id=\"drug\"> Rimantadine</span> (Flumadine)\n"
+ " \n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"flurelease\">\n"
+ "\n"
+ "## [Zanamivir](https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-2259) and [oseltamivir](https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-2450)\n"
+ "\n"
+ "### Inhibitors of Virus Release\n"
+ "\n"
+ "Sialic acid analog inhibitors of influenza A and B neuraminidase \n"
+ "\n"
+ "* Mechanism of action\n"
+ "	* Competitive <a href=\"https://youtu.be/caMne7nQUL8?t=94\"> inhibitors of influenza neuraminidase</a>. \n"
+ "* Indications\n"
+ "	* Effective against influenza A and B viruses.\n"
+ "	* Patients who have been symptomatic for no more than 48 hours. \n"
+ "* Resistance\n"
+ "	* HA or neuraminidase mutations\n"
+ "* Adverse effects: \n"
+ "	* Zanamivir is orally inhaled and causes nasal and throat discomfort. \n"
+ "	* Oseltamivir is taken orally and can cause nausea and vomiting.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"flucap\">\n"
+ "\n"
+ "## <span id=\"drug\"> Baloxavir marboxil (Xofluza) </span> \n"
+ "\n"
+ "* Approved by the [FDA on October 24, 2018](https://www.fda.gov/NewsEvents/Newsroom/PressAnnouncements/ucm624226.htm)\n"
+ "	* The first oral, single-dose antiviral\n"
+ "	* The first medicine with a novel mechanism of action to treat the flu in nearly 20 years\n"
+ "* ADME	\n"
+ "	* Effective against influenza A and B viruses\n"
+ " * Initiate treatment within 48 h of symptom onset\n"
+ "	* A single oral dose\n"
+ "	* Only for those aged 12 or more initialy, subsequent clinical trails found to be safe for children as well.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "\n"
+ "\n"
+ "## <span id=\"drug\"> Baloxavir marboxil (Xofluza) </span> \n"
+ "\n"
+ "<div id=\"left\">\n"
+ "\n"
+ "<a href=\"https://www.virology.ws/2018/10/25/a-new-drug-for-influenza/\">\n"
+ "\n"
+ "<img src=\"./images/antiviral/capedrna.png\">\n"
+ "\n"
+ "</a>\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "<div id=\"right\">\n"
+ "\n"
+ "* MoA	\n"
+ "	* Cellular mRNA has a [5' methylated cap and a polyA tail](https://www.neb.com/-/media/nebus/page-images/tools-and-resources/feature-articles/fa_mindcaps_fig1_initiationloop.jpg)\n"
+ "	* Viral mRNA does not have a cap.\n"
+ "	* Cap-dependent endonuclease binds to the 5' methylated caps of cellular mRNAs\n"
+ "	and cleaves the cellular mRNAs' 10 to 15 nucleotides 3' to the cap structure. This cellular capped RNA fragment is used by the viral polymerase to prime the synthesis of viral mRNA. 	\n"
+ "	* Baloxavir is an inhibitor of this cap-dependent endonuclease\n"
+ "* Adverse effects:\n"
+ "	* headache, diarrhea, bronchitis\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"covid\">\n"
+ "\n"
+ "## SARS-CoV-2 virus\n"
+ "\n"
+ "<a href=\"https://www.nature.com/articles/d41586-021-02039-y\">\n"
+ "<img src=\"images/antiviral/coronavirus.jpg\" width=80%></a>\n"
+ "\n"
+ "<div id=\"greyText\">\n"
+ "Single stranded RNA virus\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Life cycle of SARS-CoV-2 \n"
+ "\n"
+ "<div id=\"left\">\n"
+ "\n"
+ "<a href=\"https://www.nature.com/articles/s41579-020-00468-6\">\n"
+ "<img src=\"./images/antiviral/sars-cov-2_life_cycle.png\" width=90%>\n"
+ "</a>\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "<div id=\"right\">\n"
+ "\n"
+ "* Infecting bronchial epithelial cells, pneumocytes and upper respiratory tract cells\n"
+ "* The RNA genome is [30 kilo bases](https://genome.ucsc.edu/cgi-bin/hgTracks?db=wuhCor1&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=NC_045512v2%3A1%2D29903&hgsid=1203179451_8263g5HiGW1R07rmnBegtA4EAf7w) \n"
+ "* Spike protein binds to ACE2\n"
+ "* Viral replication is particularly active early in COVID-19\n"
+ "* Antiviral therapy have greatest impact before disease progresses to the hyperinflammatory stage\n"
+ "* Acronyms\n"
+ "	* <b>An</b>: 3′ polyA sequence; \n"
+ "	* <b>ACE2</b>: angiotensin-converting enzyme 2;\n"
+ "	* <b>RdRP</b>: RNA-dependent RNA polymerase;\n"
+ "	* <b>TMPRSS2</b>: a cell surface serine protease\n"
+ "* Color legend\n"
+ "	* Orange boxes -> life cycle \n"
+ "	* Red boxes -> therapeutic options under investigation\n"
+ "\n"
+ "<hr>\n"
+ "\n"
+ "<a href=\"https://media.nature.com/lw800/magazine-assets/d41586-021-02039-y/d41586-021-02039-y_19394008.png\">\n"
+ "Another version of SARS-CoV-2 life cycle</a>\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## [Summary Recommendations on Antiviral Drugs for SARS-CoV-2](https://www.covid19treatmentguidelines.nih.gov/therapies/antiviral-therapy/summary-recommendations/) \n"
+ "\n"
+ "by NIH COVID-19 Treatment Guidelines Panel \n"
+ "\n"
+ "* Nucleioside analog\n"
+ "	* <span id=\"drug\">Remdesivir (Veklury)</span>\n"
+ "		* The only FDA approved drug for COVID-19\n"
+ "* Monoclonal antibodies (mAb) \n"
+ "	* received emergency use authorization\n"
+ "	* <span id=\"drug\">Sotrovimab</span>\n"
+ "	* <span id=\"drug\">Bamlanivimab</span> plus <span id=\"drug\"> etesevimab </span>\n"
+ "	* <span id=\"drug\">Casirivimab</span> plus <span id=\"drug\">imdevimab</span>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"remdesivir\">\n"
+ "\n"
+ "### <span id=\"drug\">Remdesivir (Veklury)</span>\n"
+ "\n"
+ "<div id=\"left\">\n"
+ "\n"
+ "<a href=\"https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7566896/\">\n"
+ "<img src=\"./images/antiviral/remdesivir.png\" width=80%>\n"
+ "</a>\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "<div id=\"right\">\n"
+ "\n"
+ "* [FDA approves Remdesivir on 2020-10-22](https://www.fda.gov/news-events/press-announcements/fda-approves-first-treatment-covid-19)\n"
+ "* Indication\n"
+ "	* Treatment of COVID-19 in hospitalized adult and pediatric patients\n"
+ "* MoA \n"
+ "	* Originally developed to treat Ebola virus \n"
+ "	* Nucleoside analog of Adenosine\n"
+ "	* It is a prodrug, metabolized by carboxylesterase I to its triphosphate active form\n"
+ "	* Coronaviruses replication requires **RNA-dependent RNA polymerase**. These enzymes can incorporate remdesivir into new RNA strands. Shortly after adding remdesivir, the enzyme stops being able to add more RNA subunits. This halts viral genome replication.\n"
+ "* ADME ([review article](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8308800/))\n"
+ "	* Administered as a slow i.v. infusion of a loading dose followed by a maintenance dose for 5 or 10 days\n"
+ "	* Eliminated in urine\n"
+ "* Adverse effects\n"
+ "	* GI symptoms, elevated transaminase levels (liver function), hypersensitivity\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## SARS-CoV-2\n"
+ "\n"
+ "### Monoclonal antibodies \n"
+ " \n"
+ "[NIH panel recommendation on mAB for SARS-CoV-2](https://www.covid19treatmentguidelines.nih.gov/therapies/anti-sars-cov-2-antibody-products/anti-sars-cov-2-monoclonal-antibodies/) \n"
+ "* Indications\n"
+ "	* Treat nonhospitalized patients \n"
+ "		* with mild to moderate COVID-19 who are at high risk of clinical progression \n"
+ "			* Aged ≥65 years | Obesity (BMI >30) |  Diabetes  | Cardiovascular disease (including congenital heart disease) or hypertension | Chronic lung diseases (e.g., chronic obstructive pulmonary disease, moderate-to-severe asthma, interstitial lung disease, cystic fibrosis, pulmonary hypertension) \n"
+ "	* Use one of the three combinations (AII)\n"
+ "* Anti-SARS-CoV-2 mAB received emergency use authorization from FDA \n"
+ "	* <span id=\"drug\">Sotrovimab</span>\n"
+ "	* <span id=\"drug\">Bamlanivimab</span> plus <span id=\"drug\"> etesevimab </span>\n"
+ "	* <span id=\"drug\">Casirivimab</span> plus <span id=\"drug\">imdevimab</span>\n"
+ "* Route of administration\n"
+ "	* i.v. infusion\n"
+ "	* <span id=\"drug\">Casirivimab</span> plus <span id=\"drug\">imdevimab</span> can be administered as SQ injection when iv is not an option\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## <span id=\"drug\">Sotrovimab</span>\n"
+ "\n"
+ "* MoA \n"
+ "	* Derived from the memory B cell of a patient recovered from SARS in 2003\n"
+ "	* It targets an epitope in the <a href=\"https://www.nature.com/articles/s41586-020-2180-5\">Receptor Binding Domain</a> (<a href=\"https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41586-020-2180-5/MediaObjects/41586_2020_2180_Fig1_HTML.png?as=webp\">RBD</a>) of the spike protein conserved between SARS-CoV and SARS-CoV-2\n"
+ "	* Dual action monoclonal antibody ([review](https://www.nature.com/articles/s41551-020-00660-2))\n"
+ "		* neutralizing against the spike protein\n"
+ "		* activates the antibody-dependent cellular cytotoxicity ([ADCC](https://en.wikipedia.org/wiki/Antibody-dependent_cellular_cytotoxicity)) and antibody-dependent cellular phagocytosis ([ADCP](https://www.frontiersin.org/articles/10.3389/fimmu.2019.00332/full)) pathways\n"
+ "	* [500 mg, 1-hour infusion](https://www.nejm.org/doi/full/10.1056/NEJMoa2107934)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "<div id=\"left\">\n"
+ "\n"
+ "## <span id=\"drug\">Bamlanivimab</span> plus <span id=\"drug\"> etesevimab </span>\n"
+ "* MoA\n"
+ "	* Neutralizing mAbs that bind to different, but overlapping, epitopes in the spike protein RBD of SARS-CoV-2.\n"
+ "	* Gamma and Beta variants have reduced susceptibility to these mAbs.\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "<div id=\"right\">\n"
+ "\n"
+ "##	 <span id=\"drug\">Casirivimab</span> plus <span id=\"drug\">imdevimab</span>\n"
+ "* MoA \n"
+ "	* Recombinant human mAbs that bind to nonoverlapping epitopes of the spike protein RBD of SARS-CoV-2\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## What [NOT to use for COVID-19](https://www.covid19treatmentguidelines.nih.gov/therapies/antiviral-therapy/summary-recommendations/)\n"
+ "\n"
+ "* <span id=\"drug\">Nitazoxanide </span>\n"
+ "* <span id=\"drug\">Hydroxychloroquine </span> or <span id=\"drug\"> Chloroquine </span>\n"
+ "* <span id=\"drug\">Azithromycin </span>\n"
+ "* <span id=\"drug\">Lopinavir/Ritonavir </span> and Other HIV Protease Inhibitors\n"
+ " \n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"molnupiravir\">\n"
+ "\n"
+ "## <span id=\"drug\">Molnupiravir</span>\n"
+ "\n"
+ "* received approval in  UK on [Nov 4 2021](https://www.reuters.com/business/healthcare-pharmaceuticals/britain-approves-mercks-oral-covid-19-pill-2021-11-04/)\n"
+ "* MoA\n"
+ "	* nucleoside analoge \n"
+ "	* [promotes SARS-CoV-2 mutagenesis via the <a href=\"#/Ribavirin\"><span id=\"yb\">RNA</a></a> template](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8110631/)\n"
+ "		* [can mimic either cytosine or uridine after incorporated into viral RNA template, causing mutations of the viral RNA](https://www.nature.com/articles/d41586-021-02783-1)\n"
+ "* [Clinical trial](https://www.medrxiv.org/content/10.1101/2021.06.17.21258639v1)\n"
+ "	* Outpatients with confirmed SARS-CoV-2 infection\n"
+ "	* Symton onset within 7 days\n"
+ "	* Placebo, monupiravir 200 mg, 400 mg, 800 mg\n"
+ "	* 202 treated patients \n"
+ "	* At Day 5, virus was not isolated from any participants receiving 400 or 800 mg (11.1% virus positive in placebo)\n"
+ "	* Adverse effect\n"
+ "		* headache, insomnia, incrase alanine aminotransferase\n"
+ "---\n"
+ "\n"
+ "## Additional reading \n"
+ "\n"
+ "\n"
+ "* [Pfizer antiviral slashes COVID-19 hospitalizations](https://www.science.org/content/article/pfizer-antiviral-slashes-covid-19-hospitalizations)\n"
+ "\n"
+ "* [How the coronavirus infects cells — and why Delta is so dangerous - Nature news feature](https://www.nature.com/articles/d41586-021-02039-y)\n"
+ "\n"
+ "* A single injection of a drug called cabotegravir every month was so successful in preventing HIV that the clinical trial wrapped up ahead of schedule.\n"
+ "	* [Report by NPR](https://www.npr.org/sections/goatsandsoda/2020/11/11/933415492/protecting-women-against-hiv-just-got-9-times-easier)\n"
+ "	* [Report by STAT](https://www.statnews.com/pharmalot/2021/01/21/fda-hiv-aids-injectable/)\n"
+ "* [Gene editing for HIV enters into human testing](https://www.fiercebiotech.com/biotech/excision-hiv-crispr-gene-editing-therapy-cleared-for-human-studies-by-fda)\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"adverse\">\n"
+ "\n"
+ "## Antiviral Drugs with Overlapping toxicities\n"
+ "\n"
+ "#### Not an exhaustive list\n"
+ "\n"
+ "|Bone Marrow suppression|Peripheral neuropathy|Pancreatitis| Nephrotoxicity | Hepatoxicity| Lipodystrophy |Psychiatric CNS |Fever|Alopecia|\n"
+ "|---|---|---|---|---|---|---|---|---|\n"
+ "| | | Enfuvirtide | | Maraviroc| | | Maraviroc| | \n"
+ "|Zidovudine|Zidovudine Didanosine Stavudine|Didanosine Stavudine Lamivudine (children) || Stavudine Didanosine Tenofovir|Stavudine Zidovudine Didanosine Lamivudine Abacavir|Abacavir Emtricitabine Tenofovir|Zidovudine Emtricitabine|Lamivudine|\n"
+ "|||||Nevirapine Efavirenz ||Efavirenz|||\n"
+ "|||||Dolutegravir|||||\n"
+ "||||Indinavir |Ritonavir|Indinavir Nelfinavir Fosamprenavir Darunavir Ritonavir|||Indinavir|\n"
+ "|Ganciclovir Cidofovir Foscarnet|||Cidofovir Foscarnet |||Foscarnet||Cidofovir|\n"
+ "|Ribavirin Peginterferon alpha2a|||Adefovir|Entecavir Adefovir||Ribavirin Peginterferon alpha2a|Ribavirin|Peginterferon alpha2a|\n"
+ "\n"
+ "[Abacavir](#/nrti)||\n"
+ "[Acyclovir](#/Acyclovir)||\n"
+ "[Adefovir](#/Adefovir)||\n"
+ "[Cidofovir](#/Cidofovir)||\n"
+ "[Darunavir](#/Darunavir)||\n"
+ "[Dolutegravir](#/Integrase)||\n"
+ "[Efavirenz](#/nnrti)||\n"
+ "[Emtricitabine](#/nrti)||\n"
+ "[Enfuvirtide](#/Enfuvirtide)||\n"
+ "[Entecavir](#/Entecavir)||\n"
+ "[Foscarnet](#/Foscarnet)||\n"
+ "[Ganciclovir](#/Ganciclovir)||\n"
+ "[Lamivudine](#/nrti)||\n"
+ "[Maraviroc](#/Maraviroc)||\n"
+ "[Nevirapine](#/nnrti)||\n"
+ "[Oseltamivir](#/flurelease)||\n"
+ "[Peginterferon](#/Interferon)||\n"
+ "[Penciclovir](#/Penciclovir)||\n"
+ "[Ribavirin](#/Ribavirin)||\n"
+ "[Ritonavir](#/pi)||\n"
+ "[Tenofovir](#/Tenofovir)||\n"
+ "[Zanamivir](#/flurelease)||\n"
+ "[Zidovudine](#/nrti)|| \n"
+ "\n"
+ "\n"
;
var script = document.querySelector('script[src="antiviral_dental.js"]');
var section = document.createElement('section');
script.parentNode.appendChild(section);
section.appendChild(document.createTextNode(markdownContent));
[].forEach.call(script.attributes, function (attr) {
    section.setAttribute(attr.name, script.getAttribute(attr.name));
});
section.setAttribute('data-markdown', '');
})();
