(function () {
'strict'
var markdownContent = ''
+ "## A Rube Goldbergian Approach to Scheduling Rodent Behavior Experiments and Data Collection\n"
+ "\n"
+ "### Hao Chen \n"
+ "\n"
+ "#### Department of Pharmacology, Addiction Science, and Toxicology\n"
+ "#### University of Tennessee Health Science Center\n"
+ "\n"
+ "\n"
+ "<center>\n"
+ "<a href=https://www.timeforkids.com/g34/rube-goldberg/>\n"
+ "<img src=\"./images/behavflow/RubeGoldberg.png\" width=40%>\n"
+ "<br>\n"
+ "<font size=1>\n"
+ "Source: TIME for kiDS\n"
+ "</font>\n"
+ "</a>\n"
+ "</center>\n"
+ "<p>\n"
+ "\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Long term behavioral experiments have complicated logistics \n"
+ "\n"
+ "* Many animals, many unique IDs\n"
+ "* Many stages in the behavioral pipeline\n"
+ "	* Each stage has a different set of parameters \n"
+ "	* Animals may need to start on certain age\n"
+ "* Several groups of animal may have overlapping schedule\n"
+ "* Animals started on the same day may get out of sync in their schedule \n"
+ "* Data need to be processed uniformly on a timely manner\n"
+ "* Breeding drastically increases the complexity of data logging \n"
+ "* Many, many places things can go wrong\n"
+ "* Rube Golberg can help\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Settingup MedPC\n"
+ "\n"
+ "<img src=\"./images/behavflow/medpc_screenshot.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## MedPC macro files can be generated from spreadsheets\n"
+ "\n"
+ "```\n"
+ "LOAD BOX 1 SUBJ DCCD00D4 EXPT oxy_rcc_lmf1f GROUP 0.05mg_mloxy_vis_fr5_4h PROGRAM R_FRx_oxycodone_visual\n"
+ "SET W VALUE 214.000 MAINBOX 1 BOXES 1\n"
+ "SET O VALUE 1 MAINBOX 1 BOXES 1\n"
+ "SET R VALUE 5 MAINBOX 1 BOXES 1\n"
+ "SET T VALUE 240 MAINBOX 1 BOXES 1\n"
+ "```\n"
+ "<img src=\"./images/behavflow/ns016.png\" width=60%>\n"
+ "\n"
+ "<br>\n"
+ "<a href=\"https://github.com/chen42/behavflow/blob/master/linuxServerScripts/medmacro.pl\">source code</a>\n"
+ "<br>\n"
+ "<img src=\"./images/behavflow/macrofiles.png\" width=60%\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Add a rocket, a sickle, and a pendulum \n"
+ "<p class=\"fragment roll-in\"> Dropbox allows Script A and Spreadsheet to be located on a different computer as MedPC </p>\n"
+ "<p class=\"fragment roll-in\"> <a href=\"https://github.com/chen42/behavflow/blob/master/linuxServerScripts/update_macro_auto.sh\">Script B </a> monitors Spreadsheet to automatically run Script A when Spreadsheet is saved </p>\n"
+ "<p class=\"fragment roll-in\"> <a href=\"https://github.com/chen42/behavflow/blob/master/linuxServerScripts/warn_about_conflicted_versions.sh\">Script C</a> monitors the folder where Spreadsheet is to send a message when there is a \"conflicted version\" of Spreadsheet \n"
+ "</p>\n"
+ "<p class=\"fragment roll-in\"> \n"
+ "<img src=\"./images/behavflow/conflicted_vesions.png\" width=60%></p>\n"
+ "</p>\n"
+ "<p class=\"fragment roll-in\"> Setup a server that runs Script B and Script C automatically on startup</p>\n"
+ "<p class=\"fragment roll-in\"> <img src=\"./images/behavflow/rc.local.png\" width=60%> </p>\n"
+ "<p class=\"fragment roll-in\"> Time for a worry-free vacation! </p>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Messaging system: Slack\n"
+ "\n"
+ "* user data can be downloaded for archival purposes\n"
+ "* apps are easy to program \n"
+ "	* incoming webhook	\n"
+ "	```\n"
+ "	POST https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX\n"
+ "Content-type: application/json\n"
+ "{\n"
+ " \"text\": \"Hello, world.\"\n"
+ "}\n"
+ "```\n"
+ "	* <a href=\"https://api.slack.com/interactivity/slash-commands\">slash commands</a> adds more function \n"
+ "		* saves data (think lab notebook!)\n"
+ "		* needs a server that can be access by slack.com (i.e. outside campus firewall) \n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Realtime checking of operant data \n"
+ "\n"
+ "* Setup MedPC to save data to a folder (rawdata) in Dropbox\n"
+ "* Write a Script that monitors that folder, when new files appear \n"
+ "\n"
+ "<img src=\"./images/behavflow/session_done.png\" width=60%>\n"
+ "<img src=\"./images/behavflow/session_short.png\" width=60%>\n"
+ "<img src=\"./images/behavflow/zerolick.png\" width=60%>\n"
+ "\n"
+ "```\n"
+ "2021-09-06	17:36:37	DD1DCD2361	rat 2361 active and inactive spout ok\n"
+ "2021-09-06	17:37:07	DD1DCD2365	rat 2365 inactive fails. Fasten the screw\n"
+ "```\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## ID validation with /note\n"
+ "\n"
+ "<img src=\"./images/behavflow/note_id_not_found.png\" width=60%>\n"
+ "<img src=\"./images/behavflow/note_muliple_IDmatching.png\" width=60%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Preprocessing of operant data \n"
+ "\n"
+ "\n"
+ "<table> <tr height=20%><td>\n"
+ "\n"
+ "```\n"
+ "Start Date: 08/16/21\n"
+ "End Date: 08/16/21\n"
+ "Subject: DD1DCD22C3\n"
+ "Experiment: p50B21_F\n"
+ "Group: SacGrapeCS2nic15noavfr10_2.5h\n"
+ "Box: 2\n"
+ "Start Time: 10:48:58\n"
+ "End Time: 13:21:51\n"
+ "MSN: R_FRx_IR_noAV_041416\n"
+ "A:       0.000\n"
+ "B:      27.000\n"
+ "C:       0.000\n"
+ "D:       2.000\n"
+ "I:      15.900\n"
+ "J:       0.000\n"
+ "K:       0.000\n"
+ "L:      10.000\n"
+ "M:      51.000\n"
+ "N:      51.000\n"
+ "O:       0.500\n"
+ "P:       0.000\n"
+ "Q:       0.000\n"
+ "R:      10.000\n"
+ "S:    9000.000\n"
+ "T:     150.000\n"
+ "W:     159.000\n"
+ "\n"
+ "```\n"
+ "\n"
+ "</td>\n"
+ "</tr>\n"
+ "<tr><td>\n"
+ "\n"
+ "\n"
+ "<img src=\"./images/behavflow/oxy_self-admin_data.png\">\n"
+ "\n"
+ "</td></tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nightly data processing, error checking, scheduling\n"
+ "\n"
+ "* check each animal's data and generate notifications  \n"
+ "	<img src=\"./images/behavflow/schedule_change.png\" width=60%>\n"
+ "\n"
+ "* automatically run at 3AM everyday (via crontab on Linux)\n"
+ "\n"
+ "```\n"
+ "0 3 * * * bash runNightlyAnalyst.sh\n"
+ "```\n"
+ "---\n"
+ "\n"
+ "## Labnotes to database entries\n"
+ "\n"
+ "<img src=\"./images/behavflow/brevital_slacknote.png\" width=70%>\n"
+ "\n"
+ "```\n"
+ "Angel	2021-07-31	16:47:32	3B9AD442	HXB10XWMI_F received baytril today\n"
+ "Angel	2021-08-02	16:43:03	3B9AD442	HXB10XWMI_F received baytril today\n"
+ "Angel	2021-08-24	16:10:54	3B9AD442	passed brevital test\n"
+ "Angel	2021-08-27	13:39:29	3B9AD442	rat D442 died. For the past couple of days it showed weakness, rough fur, and inactiveness\n"
+ "```\n"
+ "\n"
+ "<img src=\"./images/behavflow/brevital_in_database.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Labnotes to schedule changes\n"
+ "\n"
+ "<img src=\"./images/behavflow/reinstatement_message.png\" width=70%>\n"
+ "<img src=\"./images/behavflow/reinstatement_schedule.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Using relational database for breeding and other data  \n"
+ "\n"
+ "### Foreign key \n"
+ "\n"
+ "<img src=\"./images/behavflow/foreign_key.png\" width=50%>\n"
+ "\n"
+ "<a href=\"https://sqlitestudio.pl/\">SQLiteStudio</a>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Using relational database for breeding and other data  \n"
+ "\n"
+ "### Table setup \n"
+ "\n"
+ "<img src=\"./images/behavflow/database_setup.png\" width=70%>\n"
+ "\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Using relational database for breeding and other data  \n"
+ "\n"
+ "### Data Table \n"
+ "\n"
+ "<img src=\"./images/behavflow/breeding_table_data.png\" width=70%>\n"
+ "\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Notifications based on breeding database \n"
+ "\n"
+ "<img src=\"./images/behavflow/breeding_notification.png\" width=50%>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "## Overview of Services\n"
+ "\n"
+ "\n"
+ "\n"
+ "* Convert Spreadsheet to MedPC macros for each session and all individual rats. A pdf file is also generated for record keeping\n"
+ "* Generate notifications when each operant run is finished\n"
+ "* Extract MedPC data into Spreadsheet, add session number\n"
+ "* Generate notifications when change in operant schedules are needed (e.g. dose, extinction, reinstatement)\n"
+ "* Generate warnings on exceptions (e.g body weight loss, unrealistic body weights, multiple animals have exactly same body weights).\n"
+ "* Generate daily schedule changes in the format that can be pasted into the Spreadsheet.\n"
+ "* Generate “notes” that can be pasted into slack once some procedures are done (e.g. Baytril).\n"
+ "* Generate reminders for starting experiments (until the experiment is started, i.e, data files exist)\n"
+ "* Generate reminders for missing data in database (e.g. DOW, assignment of experiment treatment)\n"
+ "* Update database when certain procedures are done (e.g. Brevital test)\n"
+ "* Maintain a log of periodic tasks (prepare drugs, cleaning chambers, etc.)\n"
+ "* We still have one manually maintained Spreadsheet for experiment planning.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Advantages\n"
+ "\n"
+ "* Reducing experimental error \n"
+ "* Convert user friendly format (Spreadsheet) to machine loadable exp file in MedPC.\n"
+ "* “Macros” and pdf files are archived automatically.\n"
+ "* Use foreign key in database\n"
+ "* Check against existing animal ID in the /note app\n"
+ "* Automatic reminder of schedule change\n"
+ "* Automatic check against common errors\n"
+ "* Automatic check for missing information\n"
+ "* Automatic database entry from notes entered in browser\n"
+ "* Standardized experimental record for miscellaneous notes for each animal\n"
+ "* Entered on a computer or smartphone\n"
+ "* Animal ID verified. \n"
+ "* Name of technician and dates are automatically recorded\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Disadvantages\n"
+ "\n"
+ "* Somewhat fragile (many components)\n"
+ "* Need backup plan when system is down\n"
+ "* Need programming skills \n"
+ "* Still several manual processes (e.g. schedule change still needs to be copy-pasted).\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## BehavFlow: many attempts to simply the life of technicians \n"
+ "\n"
+ "https://github.com/chen42/behavflow\n"
+ "\n"
+ "<img src=\"./images/behavflow/automateBehaviorWorkflow.svg\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
;
var script = document.querySelector('script[src="behavflow.js"]');
var section = document.createElement('section');
script.parentNode.appendChild(section);
section.appendChild(document.createTextNode(markdownContent));
[].forEach.call(script.attributes, function (attr) {
    section.setAttribute(attr.name, script.getAttribute(attr.name));
});
section.setAttribute('data-markdown', '');
})();
