(function () {
'strict'
var markdownContent = ''
+ "\n"
+ "#### Anat 841 Behavior Neuroscience\n"
+ "\n"
+ "# Automating rodent behavior experiments \n"
+ "## The DIY way  \n"
+ "\n"
+ "<hr>\n"
+ "\n"
+ "\n"
+ "### Hao Chen, Department of Pharmacology, UTHSC\n"
+ "\n"
+ "\n"
+ "https://chen42.github.io/slides/behaut.html\n"
+ "\n"
+ "<small> Written using [Reveal.js](https://github.com/hakimel/reveal.js) and [markdown](https://help.github.com/categories/writing-on-github/) </small>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Outline\n"
+ "\n"
+ "* Analysis of rodent behaviors and approaches for automation\n"
+ "* Know your tools\n"
+ "* Example systems\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Typical rodent behavior experiments\n"
+ "\n"
+ "* Only visual observation --> camera \n"
+ "  * Open field, plus maze, object interaction, social interaction\n"
+ "  * Video analysis\n"
+ "* Measure a specific reaction --> sensor\n"
+ "  * Tail immersion\n"
+ "  * Tremor\n"
+ "* Operant conditioning  --> sensor + motor\n"
+ "  * Lever pressing (switch)\n"
+ "  * Nose poking (RFID or IR)\n"
+ "  * Licking or touching (capatitive sensor)\n"
+ "* Rodent identification\n"
+ "  * RFID system\n"
+ "* What kind of behavior are you intersted in studing? \n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Single board computers\n"
+ "\n"
+ "## Raspberry Pi Family\n"
+ "\n"
+ "<a href=\"https://maker.pro/raspberry-pi/tutorial/how-to-get-started-with-your-first-raspberry-pi\" ><img src=\"https://raspi.tv/wp-content/uploads/2018/03/Pi-Family-Photo-Master-Mar2018-1500-1-939x1024.jpg\" width=50%, style=\"transform:rotate(270deg);\"></a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Raspberry Pi 3B+\n"
+ "\n"
+ "<img src=\"https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Raspberry_Pi_3_B%2B_%2839906369025%29.png/1280px-Raspberry_Pi_3_B%2B_%2839906369025%29.png\">\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## GPIO (general purpose input-output)\n"
+ "\n"
+ "<img src=\"https://www.raspberrypi-spy.co.uk/wp-content/uploads/2012/06/Raspberry-Pi-GPIO-Layout-Model-B-Plus-rotated-2700x900.png\">\n"
+ "\n"
+ "* Ground (grey), 5V (pink), 3V(orange),\n"
+ "* GPIO (either input or output, green)\n"
+ "* Special I/O protocols\n"
+ "  *  I2C (magenta)\n"
+ "  *  serial (purple)\n"
+ "  *  SPI (blue)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Operating system for the RPi\n"
+ "\n"
+ "* Raspbian is the official OS \n"
+ "  * graphical user interface (GUI) \n"
+ "  * command line interface (CLI)\n"
+ "  * derived from Debian Linux\n"
+ "* Why you should learn some Linux commands \n"
+ "  * Servers\n"
+ "  * Mac OS \n"
+ "  * Supercomputer\n"
+ "  * Windows\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Sensors: Camera\n"
+ "\n"
+ "<img src=\"https://www.raspberrypi.org/homepage-9df4b/static/621b26de7977c5b8d765b3003b341a49/8924f/68fe7e4cb53767ad6c033bf3b46da3452188a24a_pi-camera-front-1-1426x1080.jpg\"> \n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Sensors: Temperature \n"
+ "\n"
+ "<a href=\"https://pimylifeup.com/raspberry-pi-temperature-sensor/\"><img src=\"https://cdn.pimylifeup.com/wp-content/uploads/2016/03/Raspberry-Pi-Temperature-Sensor-Diagram-v2.png\"></a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Sensors: Temperature\n"
+ "\n"
+ "<a href=\"https://raspberrypi.stackexchange.com/questions/48357/connecting-ds18b20-temperature-sensor-with-rj45-connector\">\n"
+ "<img src=\"https://i.stack.imgur.com/5EKzW.png\" width=70%></a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Sensors: Capacitive touch sensor\n"
+ "\n"
+ "<iframe width=\"780\" height=\"560\" src=\"https://www.youtube.com/embed/Wk76UPRAVxI?start=15\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>\n"
+ "\n"
+ "<a href=\"https://www.forbes.com/profile/limor-fried/?list=top-tech-women-america#2077af9a4ecc\">America's top 50 women in tech, 2018</a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Radio frequency ID\n"
+ "\n"
+ "<img src=\"https://pragra.files.wordpress.com/2008/06/tag-specification.jpg\" width=60%>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## RFID reader (Serial) \n"
+ "\n"
+ "<img src=\"https://camo.githubusercontent.com/9d22b7aceaceae905d17ced4b82858834b00cfab/687474703a2f2f7777772e736565656473747564696f2e636f6d2f646f63756d656e742f706963732f3132354b687a253230554152542e6a7067\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## RFID reader  (USB)\n"
+ "\n"
+ "<img src=\"https://images-na.ssl-images-amazon.com/images/I/41T9IPdHVtL._AC_.jpg\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Infrared sensor and emitter\n"
+ "#### \"beam break\"\n"
+ "<a href=\"https://tutorials-raspberrypi.com/build-raspberry-pi-infrared-light-barrier-and-measure-speed/\">\n"
+ "<img src=\"https://tutorials-raspberrypi.com/wp-content/uploads/lichtschranke_Steckplatine-1024x789.png\" width=60%></a>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Output: LED\n"
+ "\n"
+ "<a href=\"https://thepihut.com/blogs/raspberry-pi-tutorials/27968772-turning-on-an-led-with-your-raspberry-pis-gpio-pins\">\n"
+ "\n"
+ "<img src=\"https://cdn.shopify.com/s/files/1/0176/3274/files/LEDs-BB400-1LED_bb_grande.png?6398700510979146820\" width=40% style=\"transform:rotate(270deg);\"></a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Output: Buzzer \n"
+ "\n"
+ "<a href=\"https://www.sunfounder.com/learn/sensor-kit-v2-0-for-raspberry-pi-b-plus/lesson-10-buzzer-module-sensor-kit-v2-0-for-b-plus.html\">\n"
+ "<img src=\"https://www.sunfounder.com/media/wysiwyg/swatches/sensor_kit_v2_0_for_b_plus/lesson-10-buzzer-module/fdsfdsfd.png\" width=50%> </a>\n"
+ "---\n"
+ "\n"
+ "## Output: Touch Pad  \n"
+ "\n"
+ "<iframe width=\"780\" height=\"560\" src=\"https://www.youtube.com/embed/Fj3wq98pd20?start=30\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Output: e-link display \n"
+ "\n"
+ "\n"
+ "<img src=\"https://m.media-amazon.com/images/I/61XxYE+JHEL._AC_UY327_QL65_.jpg\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Output: motor\n"
+ "\n"
+ "<a href=\"https://projects.raspberrypi.org/en/projects/physical-computing/16\">\n"
+ "<img src=\"https://projects-static.raspberrypi.org/projects/physical-computing/0cb2cbd34292a05a668aeea3f291ceb3c7d9cd83/en/images/mcb-wiring.png\"></a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Many many more \n"
+ "\n"
+ "<a href=\"https://tutorials-raspberrypi.com/raspberry-pi-sensors-overview-50-important-components/\"><img src=https://tutorials-raspberrypi.com/wp-content/uploads/2016/11/50-Raspberry-Pi-Sensors-and-Components.jpg width=50%> </a>\n"
+ "---\n"
+ "\n"
+ "## Microcontrollers\n"
+ "\n"
+ "### Arduino\n"
+ "\n"
+ "<img src=\"https://cdn.sparkfun.com/assets/9/1/e/4/8/515b4656ce395f8a38000000.png\">\n"
+ "\n"
+ "<a href=\"https://www.arduino.cc/en/Guide/Introduction\"> Input-Output Coupling</a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## 3D printing\n"
+ "\n"
+ "<iframe width=\"780\" height=\"560\" src=\"https://www.youtube.com/embed/ZcohRrFfmvc?start=404\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Example 1: RFID reader\n"
+ "\n"
+ "<a href=\"https://github.com/chen42/openbehavior/tree/master/RFID\">\n"
+ "<img src=\"./images/behaut/rpi_rfid_reader.jpg\"></a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Example 2: Improved RFID reader\n"
+ "\n"
+ "<a href=\"https://github.com/chen42/openbehavior/tree/master/RFID\">\n"
+ "<img src=\"./images/behaut/rfid_scanner.jpg\"></a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Example 3: Environment sensor\n"
+ "\n"
+ "<a href=\"https://github.com/chen42/openbehavior/tree/master/envSensors\">\n"
+ "\n"
+ "<img src=\"https://raw.githubusercontent.com/chen42/openbehavior/master/envSensors/images/envSensor4.jpg\" width=60%>\n"
+ "\n"
+ "</a>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Example 4: Operant Licking\n"
+ "\n"
+ "<a href=\"https://github.com/chen42/openbehavior/blob/master/operantLicking/Assembly.md\"> \n"
+ "<img src=\"https://raw.githubusercontent.com/chen42/openbehavior/master/operantLicking/images/assembled.jpg\" width=50%> \n"
+ "</a>\n"
+ "\n"
+ "<a href=\"https://peerj.com/articles/2981/\"> Peer J Article </a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Example 5. Tremor \n"
+ "\n"
+ "<a href=\"https://github.com/chen42/openbehavior/tree/master/ratremor\">\n"
+ "\n"
+ "<img src=\"https://github.com/chen42/openbehavior/raw/master/ratremor/ratremor_prototype.jpg\" width=70%></a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Example 6. TailTimer (prototype)\n"
+ "\n"
+ "<a href=\"https://github.com/chen42/openbehavior/tree/master/RFID\">\n"
+ "<img src=\"./images/behaut/rpi_tail_immersion.jpg\" width=80%>\n"
+ "</a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Example 7. PeerPub \n"
+ "\n"
+ "<img src=\"./images/behaut/PeerPub.jpg\">\n"
+ "\n"
+ "---\n"
+ "## PeerPub Spout Holder\n"
+ "\n"
+ "<img src=\"./images/behaut/rfid_spout_door.jpg\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## PeerPub Syringe Pump\n"
+ "\n"
+ "<img src=\"./images/behaut/new_syringe_pump.jpg\" width=60%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Example 8: Record video\n"
+ "\n"
+ "<img src=\"./images/behaut/rpi_camera_tripod.jpg\" width=60%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Example 9. Analyze social behavior\n"
+ "\n"
+ "#### Use 3D printed ear tag with different colors to identify individual rats\n"
+ "\n"
+ " <img src=\"./images/behaut/many_colorful_eartags.jpg\" width=60%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Social interaction between rats \n"
+ "\n"
+ "<iframe width=\"500\" height=\"500\" src=\"https://www.youtube.com/embed/mJglzLs3RNo\" frameborder=\"0\" allow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Three chamber social interaction test\n"
+ "\n"
+ "<img src=\" https://www.stoeltingco.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/6/0/60450_catalog_web.jpg\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Object recognition\n"
+ "\n"
+ "<img src=\" https://www.researchgate.net/profile/Kedar_Potdar/publication/329217107/figure/fig4/AS:697578261852162@1543327026650/Object-detection-in-a-dense-scene.ppm\">\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Neural Network\n"
+ "### Modeling one neuron \n"
+ "\n"
+ "<img src=\"https://cdn-images-1.medium.com/max/1600/1*v88ySSMr7JLaIBjwr4chTw.jpeg\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Deep Neural Network\n"
+ "\n"
+ "### Fully connected\n"
+ "\n"
+ "<img src=\"https://www.oreilly.com/library/view/tensorflow-for-deep/9781491980446/assets/tfdl_0401.png\" width=50%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Deep Neural network\n"
+ "\n"
+ "### Training the network\n"
+ "\n"
+ "<a href=\"https://theclevermachine.wordpress.com/tag/backpropagation/\">\n"
+ "<img src=\"./images/deepvar/fprop_bprop5.png\" width=70%>\n"
+ "\n"
+ "</a>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "## Live demo of DNN\n"
+ "\n"
+ "<a href=\"https://lecture-demo.ira.uka.de/neural-network-demo/?preset=Three%20classes%20test\" target=_new ><img src=\"./images/deepvar/neuralnet.png\"></a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Convolution\n"
+ "\n"
+ "![](https://ujwlkarn.files.wordpress.com/2016/07/screen-shot-2016-07-24-at-11-25-13-pm.png?w=150&h=136)\n"
+ "![](https://ujwlkarn.files.wordpress.com/2016/07/screen-shot-2016-07-24-at-11-25-24-pm.png?w=74&h=64) \n"
+ "![](https://ujwlkarn.files.wordpress.com/2016/07/convolution_schematic.gif?w=268&h=196&zoom=2)\n"
+ "\n"
+ "https://ujjwalkarn.me/2016/08/11/intuitive-explanation-convnets/\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Convolution as feature detector\n"
+ "\n"
+ "![](https://ujwlkarn.files.wordpress.com/2016/08/screen-shot-2016-08-05-at-11-03-00-pm.png?w=342&h=562)\n"
+ "\n"
+ "https://ujjwalkarn.me/2016/08/11/intuitive-explanation-convnets/\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Deep Neural network\n"
+ "\n"
+ "### ConvNet, CNN\n"
+ "\n"
+ "![](https://www.mathworks.com/content/mathworks/www/en/discovery/convolutional-neural-network/jcr:content/mainParsys/image_copy.adapt.full.high.jpg/1523891796216.jpg)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Visual example of a ConvNet\n"
+ "\n"
+ "<a href=\"http://scs.ryerson.ca/~aharley/vis/conv/\"><img src=\"https://ujwlkarn.files.wordpress.com/2016/08/conv_all.png?w=1024\"></a>\n"
+ "\n"
+ "\n"
+ "Author: [Adam Harley](http://www.cs.cmu.edu/~aharley/)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## YOLO (2016)\n"
+ "\n"
+ "![](https://cdn-images-1.medium.com/max/1040/1*ZbmrsQJW-Lp72C5KoTnzUg.jpeg)\n"
+ "\n"
+ "S x S grid, each grid predict a few bounding boxes. Each bounding box has x, y, w, h, confidence, and class probability. \n"
+ "\n"
+ "---\n"
+ "\n"
+ "## YOLO v3 (2018)\n"
+ "\n"
+ "![](https://cdn-images-1.medium.com/max/1300/1*d4Eg17IVJ0L41e7CTWLLSg.png)\n"
+ "\n"
+ "[towarddatascience.com](https://towardsdatascience.com/yolo-v3-object-detection-53fb7d3bfe6b)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## YoRodents: Labeling images\n"
+ "\n"
+ "<img src=\"./images/deep_learning/labelRatBodyParts.png\" width=60% >\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Training a custom YOLO network\n"
+ "\n"
+ "<img src=\"./images/deep_learning/training_progression.png\" width=40%>\n"
+ "\n"
+ "```\n"
+ "darknet detector train rat12class.data yolo_12_class.cfg darknet19_448.conv.23 \n"
+ "```\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Detecting objects using the trained network\n"
+ "\n"
+ "<img src=\"./images/deep_learning/epoc30000_whiteEartags1_0001482.jpg\" width=40%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Prediction probability of 9 classes\n"
+ "\n"
+ "<img src=\"./images/deep_learning/prob_comparison_dualGPU40k.svg\" width=60%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Reconstructing behavior \n"
+ "\n"
+ "* Re-assemble bounding boxes into **individuals** based on ear tag color in python\n"
+ "* Slightly compress time course (30fps -> 10fps) by taking the median \n"
+ "* Imput missing body parts using Amelie package in R\n"
+ "* Smooth the imputed data using Lowess in R \n"
+ "\n"
+ "---\n"
+ "\n"
+ "## From bounding box to behavior \n"
+ "\n"
+ "* Distance and velocity \n"
+ "	* Calculate distances between different objects (nose-nose, nose-anog, etc)\n"
+ "	* Calculate speed and direction of travel\n"
+ "* Social behavior\n"
+ "	* Nose-nose \n"
+ "	* Nose-body\n"
+ "	* Nose-anogenital \n"
+ "	* Follow \n"
+ "	* Grouping (active join, passive joing, leaving) \n"
+ "	* Huddle \n"
+ " \n"
+ "---\n"
+ "\n"
+ "## Putting everything together \n"
+ "\n"
+ "<iframe width=80% height=\"450\" src=\"https://www.youtube.com/embed/Lwfg2t9nXcI?start=45\" frameborder=\"0\" allow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Visualization is good for detecting errors\n"
+ "\n"
+ "<img src=\"./images/deep_learning/socialgraph.png\" width=80%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Time course of behaviors \n"
+ "\n"
+ "<img src=\"./images/deep_learning/circos.png\" width=50%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Mask R-CNN (2017)\n"
+ "\n"
+ "![](https://cdn-images-1.medium.com/max/2000/1*6CClgIKH8zhZjmcftfNoEQ.png)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Summary\n"
+ "\n"
+ "* Rodent behavior are complicated but can be digitized. \n"
+ "* Single board computers are useful for automating many rodent behavioral experiments\n"
+ "	* Rodent identification is critical for large scale experiments\n"
+ "		* RFID chips are cheap ($0.55)\n"
+ "	* Many types of sensors can be used. \n"
+ "	* Motors or lights or tone generators can be used to provide stimulus.\n"
+ "* 3D printers can be used to make various parts \n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Hands on \n"
+ "\n"
+ "* Linux command line \n"
+ "	* <a href=\"https://chen42.github.io/slides/linux.html\"> Hao's tutorial </a> \n"
+ "* 3D design using openscad\n"
+ "	* <a href=\"https://www.makeuseof.com/tag/beginners-guide-openscad-programming-3d-printed-models/\">Makeuseof.com tutorial</a>\n"
+ "	* <a href=\"http://edutechwiki.unige.ch/en/OpenScad_beginners_tutorial#Primitive_Solids\"> EduTech Wiki</a>\n"
+ "	* <a href=\"https://www.youtube.com/playlist?list=PLDhWPyde5E_Rz7LghBXmnhhY9F8X7k503\">Patrick Conner YouTube series</a>\n"
+ "\n"
+ "* 3D design using FreeCAD\n"
+ "	* <a href=\"https://www.youtube.com/watch?v=sxnij3CkkdU\">Youtube: FreeCAD for beginners</a>\n"
+ "	* <a href=\"https://wiki.freecadweb.org/Tutorials\">Official Tutorials</a>\n"
+ "\n"
;
var script = document.querySelector('script[src="behaut.js"]');
var section = document.createElement('section');
script.parentNode.appendChild(section);
section.appendChild(document.createTextNode(markdownContent));
[].forEach.call(script.attributes, function (attr) {
    section.setAttribute(attr.name, script.getAttribute(attr.name));
});
section.setAttribute('data-markdown', '');
})();
