(function () {
'strict'
var markdownContent = ''
+ "# Genetic and genomic factors influencing voluntary nicotine intake in rats\n"
+ "\n"
+ "<hr>\n"
+ "\n"
+ "## Hao Chen\n"
+ "\n"
+ "### Department of Pharmacology, Addiction Science and Toxicology\n"
+ "\n"
+ "### UTHSC\n"
+ "\n"
+ "Dec 3rd, 2024\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Cigarette smoking and lung cancer\n"
+ "\n"
+ "- Cigarette smoking accounts for over 90% of lung cancer cases\n"
+ "- Risk of lung cancer increases with duration of smoking\n"
+ "- Passive smokers are also at higher risk of lung cancer\n"
+ "- Mutagens and carcinogens in cigarette smoke promotes cancer\n"
+ "- Vaping products and e-cigs also contain carcinogens\n"
+ "- Nicotine may also promote tumor growth\n"
+ "\n"
+ "Note: although long-term effects require further investigation.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Voluntary nicotine consumption in rats\n"
+ "\n"
+ "<table><tr><td width=60%>\n"
+ "\n"
+ "<img src=\"https://cdn.prod.website-files.com/621e95f9ac30687a56e4297e/65fe5b2cd66dbfa42d97c3df_V2_1710439253930_9f9152ed-eed6-46f5-8850-0a0f664868cc_HIGH_RES.png\">\n"
+ "\n"
+ "Credit: biorender\n"
+ "\n"
+ "</td>\n"
+ "<td>\n"
+ "\n"
+ "- Operant nicotine self-administration\n"
+ "  - lever pressing models\n"
+ "  - nose poke models\n"
+ "  - lick models\n"
+ "\n"
+ "</td>\n"
+ "\n"
+ "</tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Outline\n"
+ "\n"
+ "- GWAS on socially-acquired nicotine self-administration\n"
+ "  - outbred\n"
+ "  - Hi-C\n"
+ "  - eQTL\n"
+ "- QTL mapping on menthol cue for nicotine self-administration\n"
+ "  - inbred\n"
+ "  - whole genome sequencing\n"
+ "  - T2T assemblies, pangenome\n"
+ "  - direct RNA-seq\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nicotine is primarily aversive in non-smokers\n"
+ "\n"
+ "<table>\n"
+ " <tr>\n"
+ " <td width=50%>\n"
+ " <img width=100% src=\"images/titlepages/eissenberg.png\">\n"
+ " </td>\n"
+ " <td width=90%>\n"
+ " <img width=100% src=\"images/titlepages/dkalman.png\">\n"
+ " </td>\n"
+ " </tr>\n"
+ " <tr>\n"
+ " <td>\n"
+ " Coughing, nausea, dizziness, sickness, burning throat, headache.\n"
+ " </td>\n"
+ " <td>\n"
+ " Nicotine induces drug high only in <em>significantly nicotine-deprived smokers</em>. \n"
+ " </td>\n"
+ " </tr>\n"
+ "</table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nicotine conditioned taste aversion in rats\n"
+ "\n"
+ "<img src=\"./images/nicotine_cta_bjpharm1983.png\" width=70%>\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Kumar, et. al., Br J Pharmac 1983</span>\n"
+ "\n"
+ "Note: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2044849/?page=3\n"
+ "flavors: sodium sacchaine vs sodium chloride\n"
+ "water access were limited to 1 h per day. flavors were presented every other day, followed by nicotine vs saline injections, s.c.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<span id=\"solo\">\n"
+ "\n"
+ "## Flavor cues conditioned to self-administered nicotine is aversive\n"
+ "\n"
+ "<a href=\"#/demo\">\n"
+ "<img height:auto width=90% src=\"images/p50/flavorcue_conditioned_aversion.png\">\n"
+ "</a>\n"
+ "\n"
+ "<p align=\"left\">\n"
+ "<span id=\"cite\"> Chen, et al., Neuropsychopharmacology, 2011 </span>\n"
+ "\n"
+ "Note:\n"
+ "We previously reported that\n"
+ "adolescent rats developed conditioned aversion to an appetitive flavor cue (saccharine + grape odor) associated with self-administered i.v. nicotine. In this operant <i>licking</i> model, oral flavor cue and <strong>i.v.</strong> nicotine were delivered simultaneously upon the completion of a fixed-ratio 5 reinforcement schedule.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Social influence is a key factor in smoking initiation\n"
+ "\n"
+ "<div id=\"left50\" >\n"
+ "<img width=100% src=\"images/titlepages/hoffman.png\"> \n"
+ "</div>\n"
+ "<div id=\"right50\">\n"
+ "<img width=100% src=\"images/titlepages/jfowler.png\"> \n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Social transmission of food preference in rats\n"
+ "\n"
+ "<img src=\"images/galef.protocol.narrower.png\" width=50%>\n"
+ "\n"
+ "<p align=\"left\">\n"
+ "<span id=\"cite\">Galef,  Curr Protoc Neurosci, 2003</span>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<span id=\"demo\">\n"
+ "\n"
+ "## Social learning enables nicotine self-administration\n"
+ "\n"
+ "<a href=\"#/solo\">\n"
+ "<img height:auto width=100% src=\"images/socially_acquired_nicotine_ivsa.png\">\n"
+ "</a>\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Chen, et al., Neuropsychopharmacology, 2011 </span>\n"
+ "\n"
+ "Note:\n"
+ "However, with the presence of a \"demonstrator\" rat consuming the same flavor cue, nicotine i.v. self-administration was established.\n"
+ "No water or food deprivation or operant pretraining is needed. Thus the model is appropriate for studying smoking initiation in adolescents.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Flavor cue with greater appetitiveness does not support nicotine IVSA\n"
+ "\n"
+ "<img src=\"./images/p50/fig4.saccGluSolo_flavor.png\">\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Chen, et al., Neuropsychopharmacology, 2011 </span>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Social learning supports nicotine IVSA with an aversive flavor cue\n"
+ "\n"
+ "<img width=90% src=\"images/quinine/ise_nse_aversivecue.png\">\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Wang, et al., Psychopharmacology, 2016 </span>\n"
+ "</p>\n"
+ "\n"
+ "Note:\n"
+ "We further reported that even when an aversive (i.e. quinine) flavor was used in place of the appetitive flavor, adolescent rats obtained nicotine IVSA, with the presence of a demonstrator consuming a flavor cue containing the same odor as the nicotine cue (i.e. inducive social environemnt (<b>ISE</b>). The number of nicotine infusions were almost identical between the two cues. <b>Therefore, licking on the active spout is most likely motivated by nicotine in this model</b> The reduced licks on the active spout was due to the reduction of licking during the timeout period following nicotine and cue delivery.\n"
+ "\n"
+ "<b>NSE</b>: neutral social environemnt, i.e., the presence of a companion rat.\n"
+ "<b>ISE</b>: indusive social environment, i.e., the presences of a companion rat who has access to the flavor cue.\n"
+ "<b>AV</b>: audiovisual cue\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Aversive vs appetitive flavor cue\n"
+ "\n"
+ "<img width=50% src=\"images/quinine/pres.sacc_quinine.png\">\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Wang, et al., Psychopharmacology, 2016 </span>\n"
+ "</p>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## What is transmitted from the demonstrator?\n"
+ "\n"
+ "<img src=\"./images/Fig1.social.rats.withdemo.svg\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Social learning is mediated by Carbon Disulfide (CS<sub>2</sub>) in rats\n"
+ "\n"
+ "<div id=\"left50\">\n"
+ "<img height:auto width=90% src=\"images/galef.protocol.narrower.png\"> \n"
+ "<br>\n"
+ "</div>\n"
+ "\n"
+ "<div id=\"right50\">\n"
+ "<img height:auto width=90% src=\"images/titlepages/cs2.png\">\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Both CS<sub>2</sub> and flavor cue are necessary for socially acquired nicotine IVSA\n"
+ "\n"
+ "<img width=100% height=\"auto\" src=\"images/p50/cs2_1rat.png\">\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Wang, et al., PLoS One, 2014 </span>\n"
+ "</p>\n"
+ "\n"
+ "Note:\n"
+ "We confirmed that neither nicotine associated flavor cue nor carbon disulfide alone supported nicotine IVSA. However, their combination was sufficient to replicate the behavior induced by live demonstrator rats.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"cta1\">\n"
+ "\n"
+ "## Social learning facilitates the extinction of conditioned nicotine aversion\n"
+ "\n"
+ "<a href=\"#/cta0\">\n"
+ "<img src=\"./images/p50/correlation_ext_cta_nicotine.png\" >\n"
+ "</a>\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Han, et al., Sci Report, 2017 </span>\n"
+ "</p>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nicotine intake is heritable\n"
+ "\n"
+ "### h<sup>2</sup>=0.54-0.65 estimated using 12 isogenic strains across two doses\n"
+ "\n"
+ "<img src=\"./images/social_nicotine_dose_isogenic_strain.png\" width=80%>\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Han, et al., Sci Report, 2017 </span>\n"
+ "</p>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "### Summary\n"
+ "\n"
+ "## Socially acquired nicotine IVSA in adolescent rats\n"
+ "\n"
+ "- Nicotine has both aversive and reinforcing properties\n"
+ "- Flavor cues are associated with the aversive property of nicotine\n"
+ "- Social learning facilitates nicotine intake by\n"
+ "  - enhancing the extinction of nicotine CFA, and not by\n"
+ "  - increasing the appetitiveness of the flavor cue\n"
+ "- Operant responding is driven by the rewarding property of nicotine\n"
+ "  - dose response to nicotine across multiple strains\n"
+ "  - nicotine can be self-administered with an aversive flavor cue\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Heterogeneous stock rats\n"
+ "\n"
+ "### Leah Solberg Woods, Wake Forest School of Medicine\n"
+ "\n"
+ "<table><tr><td width=20%>\n"
+ "</b>\n"
+ "</td>\n"
+ "<td width=80%>\n"
+ "<img src=\"./images/p50/hs_rats.png\" width=80%>\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Garret and Korstanje, Trends Genet, 2020</span>\n"
+ "</td>\n"
+ "</tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Socially acquired nicotine self-administration in HS rats\n"
+ "\n"
+ "### 52 adult males and 48 adult females\n"
+ "\n"
+ "<div id=\"left50\">\n"
+ "<img width=90% height=\"auto\" src=\"images/p50/fig4.g2b.figure.male.vs.female.nicSA.cummulative.png\">\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Wang, et al., Gene Brain Behav, 2014</span>\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "<div id=\"right50\">\n"
+ "<img width=83% height=\"auto\" src=\"images/p50/fig_demo.lick.by.sex.png\">\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Experimental design\n"
+ "\n"
+ "<div id=\"left50\">\n"
+ "<font size=3>\n"
+ "\n"
+ "| Age        | Test                                              |\n"
+ "| ---------- | ------------------------------------------------- |\n"
+ "| PND21      | Wean, Body weight                                 |\n"
+ "| PND31      | Open field                                        |\n"
+ "| PND32      | Novel object                                      |\n"
+ "| PND33      | Social interaction in the same arena as openfield |\n"
+ "| PND34      | Elevated plus maze                                |\n"
+ "| PND38      | Surgery                                           |\n"
+ "| PND39 - 41 | Recovery                                          |\n"
+ "| PND42 - 51 | Socially acquired nicotine IVSA                   |\n"
+ "| PND52      | Progressive ratio test                            |\n"
+ "| PND53 - 56 | Extinction                                        |\n"
+ "| PND57      | Contextual cue induced reinstatement              |\n"
+ "| PND59      | Tissue Collection                                 |\n"
+ "\n"
+ "</font>\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "<div id=\"right50\">\n"
+ "<center>\n"
+ "<table width=80%><tr><td>\n"
+ "We phenotyped 1600 adolescent heterogeneous stock rats on socially acquired nicotine IVSA using an flavor cue containing CS<sub>2</sub>. We also collected other behavioral traits before nicotine IVSA was started. Spleen from each rat was collected for genotyping once behavioral tests were completed. \n"
+ "</td></tr></table>\n"
+ "</center>\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nicotine self-administration\n"
+ "\n"
+ "Adolescent HS rats (711 F, 711 M)\n"
+ "\n"
+ "<img width=75% height=\"auto\" src=\"images/gwasv3/nicotine_fr10_phaseone_all_data.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Genotyping and GWAS\n"
+ "\n"
+ "### Abraham Palmer, UCSD\n"
+ "\n"
+ "<table> <tr>\n"
+ "	<td width=50%>\n"
+ "		<p align=\"center\"> <img src=\"./images/p50/AGileta_G3.png\" width=60%> </p>\n"
+ "		<p align=left>\n"
+ "		<span id=\"cite\"> Gileta et al., G3, 2020. </span>\n"
+ "		</p>\n"
+ "	</td>\n"
+ "	<td width=50%>\n"
+ "		<p align=center>\n"
+ "		<br>\n"
+ "		</p>\n"
+ "		<p>\n"
+ "		<ul>	\n"
+ "			<li> 3.5 million SNPs per individual (estimated error rate <1%)\n"
+ "			<li> GCTA with liner mixed model\n"
+ "			<li> Leave one chromosome out procedure\n"
+ "			<li> Genome-wide significance level set by permuation: -log10(p) > 5.6 \n"
+ "		</ul>\n"
+ "	</td>\n"
+ "</tr>\n"
+ "</table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Summary of GWAS\n"
+ "\n"
+ "| Behavior                        | Sample size  | N traits | N sig. QTL |\n"
+ "| ------------------------------- | ------------ | -------: | ---------: |\n"
+ "| open field                      | 626 M, 620 F |        6 |          9 |\n"
+ "| novel object interaction        | 623 M, 622 F |        6 |          7 |\n"
+ "| social interaction              | 664 M, 664 F |       11 |         14 |\n"
+ "| elevated plus maze              | 659 M, 658 F |       10 |          8 |\n"
+ "| socially acquired nicotine IVSA | 711 M, 711 F |       63 |         30 |\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## GWAS on behaviors tested before nicotine IVSA\n"
+ "\n"
+ "<table><tr><td>\n"
+ "\n"
+ "OFT\n"
+ "\n"
+ "<img src=\"./images/p50/porcupine_plot_OFT.png\">\n"
+ "\n"
+ "</td>\n"
+ "\n"
+ "<td>\n"
+ "\n"
+ "NOIT\n"
+ "\n"
+ "<img src=\"./images/p50/porcupine_plot_NOIT.png\">\n"
+ "</td>\n"
+ "</tr><td>\n"
+ "\n"
+ "SIT\n"
+ "\n"
+ "<img src=\"./images/p50/porcupine_plot_SIT.png\">\n"
+ "</td>\n"
+ "\n"
+ "<td>\n"
+ "\n"
+ "EPM\n"
+ "\n"
+ "<img src=\"./images/p50/porcupine_plot_EPM.png\">\n"
+ "</td></tr></table>\n"
+ "\n"
+ "<p align=\"left\">\n"
+ "<span id=\"cite\">Gunturkun, et.al., Front Psychiatry, 2022</a>\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Candidate genes for OFT, NOIT, SIT\n"
+ "\n"
+ "<div id=\"left\">\n"
+ "<img src=\"./images/p50/openfieldtablep1.png\">\n"
+ "</div>\n"
+ "<div id=\"right\">\n"
+ "<img src=\"./images/p50/openfieldtablep2.png\">\n"
+ "\n"
+ "<p align=\"left\">\n"
+ "<span id=\"cite\">Gunturkun, et.al., Front Psychiatry, 2022</a>\n"
+ "</div>\n"
+ "\n"
+ "Note:\n"
+ "We identified 17 candidate genes (Adarb2, Ankrd26, Cacna1c, Cacng4, Clock, Ctu2, Cyp26b1, Dnah9, Gda, Grxcr1, Eva1a, Fam114a1, Kcnj9, Mlf2, Rab27b, Sec11a, and Ube2h) for these traits. Many of these genes have been implicated by human GWAS of various psychiatric or drug abuse related traits.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Porcupine plot: socially acquired nicotine IVSA\n"
+ "\n"
+ "<img src=\"./images/p50/hs_gwas_nicsa_porcupine.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Slope of nicotine intake chr8:4459578\n"
+ "\n"
+ "<div id=\"left50\">\n"
+ "<img src=\"./images/p50/gria4_locuszoom.png\">\n"
+ "\n"
+ "There are 32 known genes in this 5.1 Mb interval. Gria4 is a candidate gene.\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "<div id=\"right50\">\n"
+ "\n"
+ "- Prioritizing candidate genes\n"
+ "  - mis-sense variants\n"
+ "  - expressed in relevant brain regions\n"
+ "  - cis-eQTL\n"
+ "  - relevant biological function\n"
+ "  - associated with related traits in human GWAS\n"
+ "  - chromatin interaction\n"
+ "  </div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<center>\n"
+ "<a href=\"https://ratgtex.org/\" target=_new> <img src=\"https://ratgtex.org/assets/images/RatGTExPortal.png\" width=30%> </a>\n"
+ "\n"
+ "<table> <tr>\n"
+ "<td width=40%>\n"
+ "	<center>\n"
+ "	<img src=\"./images/p50/five_brain_regions_for_eQTL.png\" width=100%>\n"
+ "                <br>\n"
+ "	<img src=\"./images/p50/expression_level_of_nic_candiate_genes.svg\" width=100%>\n"
+ "	</center>\n"
+ "</td>\n"
+ "<td width=60%>\n"
+ "	<img src=\"./images/p50/violinplot0-cyp26b1.svg\" width=100% >\n"
+ "</td>\n"
+ "</tr></table>\n"
+ "\n"
+ "</center>\n"
+ "\n"
+ "<span id=\"cite\"> Munro, et al., Nucleic Acids Research 2022</span>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## GeneCup for literature mining\n"
+ "\n"
+ "<a href=\"http://rats.pub/cytoscape/?rnd=tmpzcBObC&genequery=Gfra1_Nhlrc2_Hspa12a_Vti1a_Shtn1_Tcf7l2_Adrb1_Nrap_Gpam_Casp7\" target=_new>\n"
+ "<img src=\"./images/gwasv3/active_lick_gwas_smoking_genes_ratspub.svg\" width=50%>\n"
+ "</a>\n"
+ "\n"
+ "http://genecup.org is designed to take a list of gene symbols and mine the PubMed and GWAS catalog for sentences pertain to addiction.\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Gunturkun, et. al., G3, 2022</span>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## The genome is 3D\n"
+ "\n"
+ "<a href=\"https://www.nature.com/articles/s41580-021-00362-w/figures/1\" >\n"
+ "<img src=\"./images/hic/3D_genome_structure.png\" width=80%> </a>\n"
+ "\n"
+ "Source: Nature Reviews Molecular Cell Biology v22, p511–528 (2021)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Hi-C experimental procedures\n"
+ "\n"
+ "<img src=\"./images/hic/hi-c_protocol.png\" width=70%>\n"
+ "\n"
+ "Source: Aaron T.L. Lun & Gordon K. Smyth BMC Bioinformatics 2015\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Hi-C is a method to find 3D interactions\n"
+ "\n"
+ "### Rob Williams (GGI), Burt Sharp (GGI)\n"
+ "\n"
+ "### Rachel Ward, Panjun Kim (Chen Lab)\n"
+ "\n"
+ "<img src=\"./images/hic/hi-c_genomewide_heatmap.png\" width=40%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Hi-C is a method to find 3D interactions\n"
+ "\n"
+ "<img src=\"./images/hic/hi-c_heatmap0.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Hi-C is a method to find 3D interactions\n"
+ "\n"
+ "<img src=\"./images/hic/hi-c_heatmap.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Loops from PFC of 10 inbred rats\n"
+ "\n"
+ "<img src=\"./images/hic/hao_loop_size_after_remove_duplicate_loops.png\">\n"
+ "\n"
+ "31,773 loops detected\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Overlap between loop & CTCF\n"
+ "\n"
+ "<img src=\"./images/hic/hao_ctcf.hist.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Overlap between loop & TSS\n"
+ "\n"
+ "<img src=\"./images/hic/hao_absolute_position_of_tss_to_loop.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Overlap between loop & Promoter\n"
+ "\n"
+ "<img src=\"./images/hic/hao_position_of_promoter_to_loop.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Loops supported by CTCF and has TSS or Promoter\n"
+ "\n"
+ "<img src=\"./images/hic/hao_loops_common_venn_diagram.png\" width=50%>\n"
+ "\n"
+ "18,216 / 31,773 = 0.57\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Loops help identify candidate genes\n"
+ "\n"
+ "<img src=\"./images/hic/ist1_with_loop.png\" width=70%>\n"
+ "\n"
+ "Both Ist1 and Dhx38 have cis-eQTL. Ist1 is a human smoking initiation gene. Ist1 is involved in endosomal sorting.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Candidate gene: LINC02337\n"
+ "\n"
+ "Human GWAS: Pack years\n"
+ "\n"
+ "PackYears: Cigarettes per day divided by 20, multiplied by number of years smoking\n"
+ "\n"
+ "Rat GWAS: Total nicotine infusion\n"
+ "\n"
+ "Common: total overall exposure to tobacco/nicotine.\n"
+ "\n"
+ "<table> <tr> <td width=50%>\n"
+ "<img src=\"./images/p50/arhgef7_locuszoom.png\" width=100%>\n"
+ "\n"
+ "</td>\n"
+ "<td>\n"
+ "\n"
+ "![](./images/gwasv3/tex29_gwas_pack_years.png)\n"
+ "\n"
+ "<a href=\"https://www.ebi.ac.uk/gwas/variants/rs2026174\" target=_new> LINC02337 </a>\n"
+ "\n"
+ "<a href=\"http://genome.ucsc.edu/cgi-bin/hgTracks?db=hg38&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr13%3A110979763%2D112075449&hgsid=1385374851_DFWqHgcyTThiDJV0a0SLgElBbEDP\" target=_new> Is Arhgef7 more likely?</a> Arhgef7 expression is FPKM=30 in our dataset. It is involed in spine morphogenesis. Loss of Arhgef7 results in extensive loss of axons (PMID:30683798, PMID:29891904)\n"
+ "\n"
+ "<p align=left>\n"
+ "Exome Chip Meta-analysis Fine Maps Causal Variants and Elucidates the Genetic Architecture of Rare Coding Variants in Smoking and Alcohol Use \n"
+ "<span id=\"cite\">Brazel, et. al., Biol Psychiatry 2019</span>\n"
+ "\n"
+ "</td></tr></table>\n"
+ "\n"
+ "Note:\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Candidate genes: Cacna1c\n"
+ "\n"
+ "### Brendan Tunstall, Dean Kirson (PHAST)\n"
+ "\n"
+ "<table> <tr><td width=70%>\n"
+ "<img src=\"./images/p50/cacna1c_talk.svg\">\n"
+ "\n"
+ "</td><td width=30%>\n"
+ "\n"
+ "<a href=\"https://genecup.org/cytoscape/?rnd=tmpexEhqs&genequery=Cacna1c\" target=_new>\n"
+ "<img src=\"./images/p50/Cacna1c_genecup.svg\" width=100%>\n"
+ "</a>\n"
+ "</td></tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Multi-species validation\n"
+ "\n"
+ "- C.elegans (Changhoon Jee, PHAST)\n"
+ "- Zebrafish (Thiru Vaithianathan, PHAST)\n"
+ "- Rat CRISPR/Cas9 (Burt Sharp, GGI)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Gria4 null mutation abolishes nicotine CCP\n"
+ "\n"
+ "<img src=\"./images/p50/celegans2.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Zebrafish Nicotine Conditioned Place Preference Test\n"
+ "\n"
+ "<table><tr><td width=50%>\n"
+ "\n"
+ "<img src=\"./images/zebrafish_chamber.png\">\n"
+ "\n"
+ "</td><td>\n"
+ "\n"
+ "<img src=\"./images/zebrafish_nicotine_cpp_30um_3day.png\">\n"
+ "\n"
+ "</td></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Generating gene knockout zebrafish using base editor\n"
+ "\n"
+ "<img src=\"./images/zebrafish_cbe_tyr_15dpf.png\" width=50%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Validating causal relationship using cell-type specific genome editing\n"
+ "\n"
+ "<table><tr>\n"
+ "\n"
+ "<td width=50%>\n"
+ "<img src=\"./images/pde4b/percent_mutation_pde4b_gRNA.png\">\n"
+ "</td>\n"
+ "<td>\n"
+ "<img src=\"./images/pde4b/pde4b_aav_nac.png\">\n"
+ "</td>\n"
+ "\n"
+ "</tr></table>\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Sharp et. al., Scientific Report, 2024</span>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## The cooling sensation of menthols is a conditioned cue for nicotine reward\n"
+ "\n"
+ "<img src=./images/menthol/fig_menthol_u01.png width=70%>\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Wang et. al., Front Behav Neurosci. 2014 </span>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Using the hybrid rat diversity panel for mapping\n"
+ "\n"
+ "#### Mindy Dwinell, Anne Kwitek (MCW), Laura Saba (Univ Colorado), Rob Williams (UTHSC)\n"
+ "\n"
+ "<img src=\"https://rgd.mcw.edu/common/images/HRDP_1000x357.png\" width=90%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Whole genome sequencing of the HRDP\n"
+ "\n"
+ "<img src=\"https://cdn.ncbi.nlm.nih.gov/pmc/blobs/18c8/11019364/cd39cc65d019/fx1.jpg\" width=50%>\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> de Jong, et al. Cell Genomics, 2024 </span>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Phylogenetic tree of laboratory rats\n"
+ "\n"
+ "<img src=\"./images/ratGenome/Figure6_phylogenetic_tree_color.png\" width=60%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## First rat pangenome\n"
+ "\n"
+ "### Flavia Villani, Andrea Gurracino, Erik Garrison, Enza Colonna (GGI)\n"
+ "\n"
+ "<img src=\"./images/ratGenome/rat_pangenome_graphical.svg\" width=50%>\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Villani, et al. iScience, in press </span>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nanopore Sequencing\n"
+ "\n"
+ "<img src=\"./images/directrna/nanopore.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## ONT ultralong sequencing of SHR x BN-Lx F1\n"
+ "\n"
+ "### Rob Williams, Burt Sharp, Erik Garrison (GGI)\n"
+ "\n"
+ "<img src=\"./images/ratGenome/SHRXBNLxF1_ONT_Sequencing_stats.png\" width=80%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Initial T2T assembly\n"
+ "\n"
+ "### Andrea Guarracino, Erik Garrison (GGI)\n"
+ "\n"
+ "<img src=\"./images/ratGenome/shrbnlx_assembly.png\" width=80%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Direct RNA-seq using ONT\n"
+ "\n"
+ "<table><tr><td>\n"
+ "\n"
+ "<h3>via cDNA</h3>\n"
+ "\n"
+ "- Lost of base modification\n"
+ "- Lost of polyA tail length\n"
+ "- Short reads\n"
+ "- Potential PCR bias\n"
+ "\n"
+ "</td><td>\n"
+ "\n"
+ "<h3> Native RNA</h3>\n"
+ "\n"
+ "- Base modification\n"
+ "- PolyA length\n"
+ "- Long (full length) reads\n"
+ "- No PCR bias\n"
+ "\n"
+ "</td></tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Rat Accumbens direct RNA\n"
+ "\n"
+ "<img src=\"./images/directrna/directRNA_basic_stats.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Ncam1 Transcripts (Jbrowse2)\n"
+ "\n"
+ "<img src=\"./images/directrna/jbrowse_ncam_3prime_plain.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Ncam1 Transcripts (Jbrowse2)\n"
+ "\n"
+ "<img src=\"./images/directrna/jbrowse_ncam_3prime_transcript.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Ncam1 Transcripts (Jbrowse2)\n"
+ "\n"
+ "<img src=\"./images/directrna/jbrowse_ncam_3prime.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Modified RNA base on Chr1\n"
+ "\n"
+ "<img src=\"./images/directrna/RNA_mods_chr1.png\">\n"
+ "\n"
+ "A-I mod is mediated by the <a href=\"https://www.ebi.ac.uk/gwas/genes/ADAR\">ADAR</a> enzyme\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Acknowledgments\n"
+ "\n"
+ "<table width=80% ><tr align=center>\n"
+ "<td width=25%>\n"
+ "<img src=\"./images/lab/caroline.png\">\n"
+ "\n"
+ "<p align=\"center\"> Caroline Jones</a>\n"
+ "\n"
+ "</td>\n"
+ "\n"
+ "<td width=25%>\n"
+ "<img src=\"./images/lab/shuangying.jpg\">\n"
+ "<p align=\"center\"> Shuangying Leng</p>\n"
+ "</td>\n"
+ "\n"
+ "<td width=25%>\n"
+ "<img src=\"./images/lab/rachel.jpg\">\n"
+ "\n"
+ "<p align=\"center\"> Rachel Ward</a>\n"
+ "\n"
+ "</td>\n"
+ "\n"
+ "<td width=25%>\n"
+ "<img src=\"./images/lab/jun.jpg\">\n"
+ "\n"
+ "<p align=\"center\"> Jun Huang </a>\n"
+ "\n"
+ "</td>\n"
+ "\n"
+ "</tr>\n"
+ "</table>\n"
+ "\n"
+ "  <!--- REHU students Abigale Salinero (2015) | Cindy Tay (2016) | Raven David (2017) | Christian Hurt (2018) | Gwen Johnson (2021) | Olivia Harrison (2022, 2023) | Ryan Luib (2023)\n"
+ "    --->\n"
+ "\n"
+ "- P50 collaborators\n"
+ "  - Abraham Palmer | Oksana Polesskaya | Thiago Sanches | Apurva Chitre | Leah Solberg-Woods\n"
+ "- PhD students\n"
+ "  - Panjun Kim | Mallory Udell | Paige Lemen\n"
+ "- UTHSC collaborators\n"
+ "  - Changhoon Jee | Burt Sharp | Thirumalini Vaithianathan | Rob Williams | Brendan Tunstall | Dean Kirson | Erik Garrison | Enza Colonna\n"
+ "- Past technicians and analysts\n"
+ "  - _Tengfei Wang_ | _Xia Hong_ | _Jie Shen_ | _Wenyan Han_ | _Pawandeep Kaur_ | _Yanyan Lin_ | _Xinyu Fan_ | _Mallory Udell_ | _Gwen Johnson_ | _Hakan Gunturkun_ | _Angel Garcia Martinez_ |\n"
+ "\n"
+ "Funding: NIDA P50DA037844 (Chen) U01DA053672 and U01DA057530 (Sharp, Chen, Williams)\n"
;
var script = document.querySelector('script[src="cancer.js"]');
var section = document.createElement('section');
script.parentNode.appendChild(section);
section.appendChild(document.createTextNode(markdownContent));
[].forEach.call(script.attributes, function (attr) {
    section.setAttribute(attr.name, script.getAttribute(attr.name));
});
section.setAttribute('data-markdown', '');
})();
