(function () {
'strict'
var markdownContent = ''
+ "## Pharmacology \n"
+ "----\n"
+ "# Cholinergic Antagonists \n"
+ "----\n"
+ "\n"
+ "Dr. Hao Chen \n"
+ "\n"
+ "Dept. Pharmacology, UTHSC\n"
+ "\n"
+ "hchen@uthsc.edu\n"
+ "\n"
+ "URL: http://chen42.github.io/slides/cho_at.html\n"
+ "\n"
+ "Aug 15, 2019, 11-12  AM\n"
+ "\n"
+ "Aug 16, 2018, 1-2 PM\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Conventions \n"
+ "#### used in this document \n"
+ "\n"
+ "* Color and style theme: \n"
+ "	* Drug name: <span id=\"drug\"> Enfuvirtide</span>\n"
+ "	* Links: [Clinicalkey](https://www.clinicalkey.com/#!/). \n"
+ "		* You need to login via your UTHSC netid when off campus to use e-textbooks. \n"
+ "		* [VPN](http://uthsc.edu/vpn/index.php) provides a better experience. \n"
+ "	* [Printable](http://chen42.github.io/slides/cho_at.html?print-pdf#/) version \n"
+ "* Open link in a new browser tab:\n"
+ "```\n"
+ "CTRL click\n"
+ "```\n"
+ "* Navigate the slides:\n"
+ "```\n"
+ "<- or -> \n"
+ "Space_bar \n"
+ "Page_down or Page_up \n"
+ "Home or End\n"
+ "```\n"
+ "* To zoom in or out:\n"
+ "``` \n"
+ "CTRL + or CTRL -\n"
+ "CTRL mouse_wheel_up or CTRL mouse_wheel_down \n"
+ "```\n"
+ "\n"
+ "\n"
+ "<small>\n"
+ "\n"
+ "Written using <a href=\"https://github.com/hakimel/reveal.js\"> Reveal.js </a> and <a href=\"https://guides.github.com/features/mastering-markdown/\"> Markdown</a>\n"
+ "\n"
+ "</small>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Textbook chapters used\n"
+ "\n"
+ "[Cholinoceptor-Blocking Drugs](http://accessmedicine.mhmedical.com/content.aspx?bookid=1193&sectionid=69104442) Katzung and Trevor, Basic & Clinical Pharmacology, 13e\n"
+ "\n"
+ "[Acetylcholine Receptor Agonists](https://www.clinicalkey.com/#!/content/book/3-s2.0-B9780323391665000074) Brenner and Stevens, Pharmacology, 5e. \n"
+ "\n"
+ "Supplemental materials: [Drug Monographs](https://www.clinicalkey.com/#!/browse/drugs),  PubMed articles \n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Learning Objectives\n"
+ "\n"
+ "* Describe classes of anticholinergics.\n"
+ "* Describe effects of anticholinergics on organ systems.\n"
+ "* Describe therapeutic uses of anticholinergics.\n"
+ "	* Explain the rationale for the therapeutic use of muscarinic antagonists in diseases such as bronchoconstriction, excessive salivation, and motion sickness. \n"
+ "	* Explain the rationale for the therapeutic use to produce mydriasis and cycloplegia.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Learning Objectives\n"
+ "* Describe side effects and drug interactions of anticholinergics.\n"
+ "	* Explain why muscarinic antagonists cause xerostomia, blurred vision, photophobia, tachycardia, anhidrosis, difficulty in micturition, hyperthermia, glaucoma and mental confusion in the elderly.\n"
+ "	* Explain why muscarinic antagonists are contraindicated in glaucoma, obstructive disease of the gastrointestinal tract or urinary tract, intestinal atony.\n"
+ "	* List the adverse effects of drug acting at autonomic ganglia.\n"
+ "* Describe the use of neuromuscular blockers in general anesthesia\n"
+ "	* Explain the selection criterior of neuromuscular blockers \n"
+ "	* Explain the cause of hyperkalemia and malignant hyperthermia\n"
+ "* Describe the principles of treating cholinergic poisoning\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Drug List \n"
+ "\n"
+ "<table><tr><td>\n"
+ "\n"
+ "<b> Muscarinic Antagonists</b> <p>\n"
+ "Atropine<br>\n"
+ "Cyclopentolate (Cyclogyl)<br>\n"
+ "Darifenacin (Enablex)<br>\n"
+ "Dicyclomine (Bentyl)<br>\n"
+ "Glycopyrrolate (Robinul)<br>\n"
+ "Hyoscyamine (Anaspaz)<br>\n"
+ "Ipratropium (Atrovent)<br>\n"
+ "Oxybutynin (Ditropan)<br>\n"
+ "Scopolamine<br>\n"
+ "Solifenacin (Vesicare)<br>\n"
+ "Tiotropium (Spiriva)<br>\n"
+ "Tolterodine (Detrol)<br>\n"
+ "Tropicamide (Mydriacyl Ophthalmic)<br>\n"
+ "Trospium (Spasmex)<br>\n"
+ "<br>\n"
+ "</td>\n"
+ "\n"
+ "<td>\n"
+ "<b>Ganglionic Blockers</b><p>\n"
+ "Mecamylamine (Inversine)<br>\n"
+ "\n"
+ "<b>Neuromuscular Blockers</b><p>\n"
+ "Atracurium (Tracrium)</br>\n"
+ "Cisatracurium (Nimbex)</br>\n"
+ "Pancuronium (Pavulon) </br>\n"
+ "Rocuronium (Zemuron)</br>\n"
+ "Succinylcholine (Anectine, Quelicin)</br>\n"
+ "Vecuronium (Norcuron)</br>\n"
+ "\n"
+ "</td></tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## outline\n"
+ "<ol>\n"
+ "<li> Cholinoreceptors\n"
+ "<li> Antimuscarinic\n"
+ "	<ol type=\"a\"><li> Organ System Drug Effects\n"
+ "		<li> Atropine / Scopolamine\n"
+ "		<li> Synthetic Antimuscarinics\n"
+ "	</ol>\n"
+ "<li> Antinicotinic \n"
+ "	<ol type=\"a\"> \n"
+ "		<li>Nicotinic Ganglionic Blockers\n"
+ "		<li>Nicotinic Neuromuscular Blokers\n"
+ "		</ol>\n"
+ "<li> Cholinergic Poisoning\n"
+ "</ol>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id='diagram'>\n"
+ "\n"
+ "## Sites of drug actions\n"
+ "![](https://i.pinimg.com/736x/e2/6f/d3/e26fd3e77a71e898141dd0b0d9e7b6b6--neuromuscular-junction-action.jpg)\n"
+ "\n"
+ "<br>\n"
+ "\n"
+ "<small>What if sympathetic and parasympathetic system are <a href=\"http://chen42.github.io/slides/cho_ag.html#/vaspara\"> both stimulated</a>?</small>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"alpha7\">\n"
+ "\n"
+ "## Cholinergic receptors\n"
+ "\n"
+ "<a href=\"https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3238081/figure/fig2/\"><img src=\"./images/cholinergic/mnAChR.png\"></a>\n"
+ "\n"
+ "<small>Each mAChR subtype is a seven-transmembrane protein, which belongs to two major functional classes based on G-protein coupling. The M1, M3, and M5 mAChRs selectively couple to the Gq/G11-type G-proteins resulting in the generation of inositol-1,4,5-trisphosphate (IP3) and 1,2-diacylglycerol (DAG) through activation of the phosphoinositide-specific phospholipase-C&beta; leading to increased intracellular calcium levels. The M2 and M4 mAChRs preferentially activate Gi/Go-type G-proteins, thereby inhibiting adenylate cyclase, reducing intracellular concentration of cAMP, and prolonging potassium channel opening. Neuronal nAChRs are pentameric ligand-gated ion channels. The most abundant neuronal subunits are &alpha;4, &beta;2, and &alpha;7, with the heteromeric &alpha;4&beta;2 receptor subtype in highest abundance. </small>\n"
+ "\n"
+ "[Neuropsychopharmacology. 2012 Jan;37(1):16-42.](https://www.ncbi.nlm.nih.gov/pubmed/21956443 )\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## mAChR subtypes\n"
+ "\n"
+ "<a href=\"https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3238081/figure/fig1/\"><img src=\"./images/cholinergic/Ach_synapse.png\" width=70%></a>\n"
+ "<small>\n"
+ "The M2 and M4 mAChRs serve as autoreceptors on cholinergic terminals to suppress ACh release at select synapses in the CNS (left neuron). <font color=\"darkred\">The mAChRs located on non-cholinergic neurons act as heteroceptors controlling the release of other neurotransmitters, such as Dopamine. (not draw) </font> M1, M3, M5, but also M4 mAChRs that are located postsynaptically facilitate slow cholinergic synaptic neurotransmission relative to nAChR subtypes. The alpha7 and alpha4beta2 nAChR subtypes mediate fast synaptic transmission and also use-dependent changes required for neuronal plasticity. These nAChR subtypes can have both pre- and postsynaptic localization. </small>\n"
+ "\n"
+ "// The endogenous ligand of these cholinergic receptors, ACh, is synthesized in cholinergic neurons (left neuron) by the enzyme ChAT through the transfer of acetyl-CoA onto choline. Choline uptake is mediated by presynaptic high-affinity choline transporters (ChT). After synthesis, ACh is packaged into synaptic vesicles by the vesicular ACh transporter (vAChT). After neuronal activation-mediated release into the synaptic cleft, ACh can bind to pre- and postsynaptic receptors, or it can be inactivated through hydrolysis by the AChE enzymes, a process that can be inhibited by different substances (eg, organophosphates, AChE inhibitors) to increase synaptic ACh levels. Once ACh is hydrolyzed, choline is transported through the ChTs into the presynaptic terminal, where it is again synthesized into ACh.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "### cholinergic receptor subtypes \n"
+ "\n"
+ "\n"
+ "<table><thead><tr><th> TYPE OF RECEPTOR </th><th> <font color=\"yellow\">PRINCIPAL</font> LOCATIONS</th> <th> MECHANISM OF SIGNAL TRANSDUCTION</th> <th> EFFECTS</th></tr></thead>\n"
+ "\n"
+ "<tr><td colspan=4><b>Muscarinic</b></td></tr> \n"
+ "<tr><td>M 1 </td><td> Autonomic ganglia, presynaptic nerve terminals, and CNS </td><td>Increased IP 3 </td><td>Modulation of neurotransmission</td></tr>\n"
+ "<tr><td>M 2 </td><td> Cardiac tissue (sinoatrial and atrioventricular nodes) </td><td>Increased potassium efflux or decreased cAMP </td><td>Slowing of heart rate and conduction</td></tr>\n"
+ "\n"
+ "<tr><td>M 3 </td><td>Smooth muscle and glands </td><td>Increased IP 3 Contraction of smooth muscles and stimulation of glandular secretions </td><td> Vascular smooth muscle Increased cGMP as a result of nitric oxide stimulation Vasodilation</td></tr>\n"
+ "\n"
+ "<tr><td colspan=4><b>Nicotinic</b> </td></tr>\n"
+ "\n"
+ "<tr><td>Muscle type </td><td>Neuromuscular junctions </td><td> Increased sodium influx </td><td>Muscle contraction </td></tr>\n"
+ "\n"
+ "<tr><td>Ganglionic type </td><td> Autonomic ganglia </td><td> Increased sodium influx </td><td> Neuronal excitation </td></tr>\n"
+ "\n"
+ "<tr><td>CNS type </td><td>CNS </td><td>Increased sodium influx </td><td>Neuronal excitation\n"
+ "</td></tr>\n"
+ "\n"
+ "</table>\n"
+ "<br> cAMP, cyclic adenosine monophosphate; cGMP, cyclic guanosine monophosphate; CNS, central nervous system; IP 3 , inositol triphosphate </br>\n"
+ "</a>\n"
+ "\n"
+ "<section id=\"receptorSubtype\">\n"
+ "---\n"
+ "\n"
+ "## Major Groups of cholinergic blockers\n"
+ "\n"
+ "antimuscarinic = <font color=\"gray\">parasympatholytic </font>\n"
+ "\n"
+ "* Muscarinic Receptor Antagonists\n"
+ "	* Belladonna Alkaloids\n"
+ "		* <span id=\"drug\"> Atropine, scopolamine, Hyoscyamine</span> \n"
+ "	* Semisynthetic and Synthetic Muscarinic Receptor Antagonists\n"
+ "		* hundreds available\n"
+ "		* <span id=\"drug\"> Dicyclomine, Glycopyrrolate, Ipratropium, Oxybutynin, Tropicamide</span> \n"
+ "* Nicotinic Receptor Antagonists\n"
+ "	* Neuromuscular Blocking Agents\n"
+ "		* Nondepolarizing Neuromuscular Blocking Agents\n"
+ "			* <span id=\"drug\"> Rocuronium, Cisatracurium, Pancuronium</span>\n"
+ "		* Depolarizing Neuromuscular Blocking Agents \n"
+ "			* <span id=\"drug\"> Succinylcholine </span> \n"
+ "---\n"
+ "\n"
+ "## Antimuscarinics: Structure \n"
+ "<table><tr><td width=50% align=right>\n"
+ "<a href=\"http://accessmedicine.mhmedical.com/content.aspx?bookid=1193&sectionid=69104442#1104841776\">\n"
+ "<img src=\"http://accessmedicine.mhmedical.com/data/books/1193/m_kat_ch8_f001.png\">\n"
+ "</a>\n"
+ "</td><td>\n"
+ "<b>Atropine</b>:  oxygen [red] at [1] is missing \n"
+ "<p>\n"
+ "<b>Scopolamine</b>: oxygen present\n"
+ "<p>\n"
+ "<b>Homatropine</b>: the hydroxymethyl at [2] is replaced by a hydroxyl group, and the oxygen at [1] is absent.\n"
+ "\n"
+ "</td><tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Antimuscarinics: ADME\n"
+ "\n"
+ "* Absorption \n"
+ "	* tertiary antimuscarinic drugs are well absorbed\n"
+ "	* quaternary antimuscarinic drugs are not well absorbed \n"
+ "* Distribution \n"
+ "	* tertiary antimuscarinics are widely distributed in the body.\n"
+ "		* Significant levels are achieved in the CNS within 30 minutes to 1 hour.\n"
+ "	* quaternary derivatives are poorly taken up by the brain and therefore are relatively free of CNS effects.\n"
+ "* Metabolism \n"
+ "	* the elimination of <span id=\"drug\"> atropine </span> from the blood occurs in two phases: the t1/2 of the rapid phase is 2 hours and that of the slow phase is approximately 13 hours. \n"
+ "	* Effect on parasympathetic function declines rapidly in all organs except the eye, where it can persist for &gt; 72 hours.\n"
+ "* Excretion \n"
+ "	* About 50% of the dose is excreted unchanged in the urine. The rest appears in the urine as hydrolysis and conjugation products. \n"
+ "\n"
+ "---\n"
+ "\n"
+ "## antimuscarinics: MoA\n"
+ "<table><tr><td align=\"right\">\n"
+ "<ul>\n"
+ "<li> Reversible (surmountable) blockade of muscarinic receptor \n"
+ "	<ul>\n"
+ "	<li> representative drug: <span id=\"drug\"> atropine</span>\n"
+ "	<li> can be overcome by ACh or cholinomimetics \n"
+ "	<li> binds to the aspartate in the third transmembrane segment of the heptahelical receptor \n"
+ "	<li> prevents the release of IP3 and inhibits adenylyl cyclase (<a href=\"http://accessmedicine.mhmedical.com/data/books/1193/m_kat_ch1_f003.png\">inverse agonists</a>)\n"
+ "	<li> sensitivity to atropine: salivary, bronchial, sweat glands >> gastric parietal cells \n"
+ "	<li> receptor subtype selectivity\n"
+ "		<ul> <li> <span id=\"drug\"> Atropine </span>: no nAChR activity but  non-selelctive for mAChR\n"
+ "		<li> other: moderately selective on mAChRs \n"
+ "		<li> synthetic antimuscarinics may interact with nAChR or histamine receptors\n"
+ "		</ul>\n"
+ "		</ul>\n"
+ "</td><td>\n"
+ "<a href=\"http://www.nature.com/nrd/journal/v13/n7/full/nrd4295.html\">\n"
+ "<img src=\"http://www.nature.com/nrd/journal/v13/n7/images/nrd4295-f2.jpg\" width=50%></a>\n"
+ "<br>\n"
+ "Nature Reviews Drug Discovery 13, 549-560 (2014) \n"
+ "</td></tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "Antimuscarinics: Organ System Effects\n"
+ "\n"
+ "### Central nervous system\n"
+ "\n"
+ "Compare with [indirect cholinergic agonists](http://chen42.github.io/slides/cho_ag.html#/cns) [Galantamine](http://chen42.github.io/slides/cho_ag.html#/galantamine) \n"
+ "\n"
+ "\n"
+ "* sedative effects, drowsiness, amnesia: <span id=\"drug\"> Atropine, scopolamine </span>\n"
+ "	* initial effect is mild stimulation\n"
+ "* reduce Parkinsons tremor: <span id=\"drug\"> atropine</span> \n"
+ "* motion sickness (vestibular disturbance): <span id=\"drug\"> Scopolamine </span> \n"
+ "* high dose cause an acute confusional state known as [delirium](pdfs/anesthprog00291-0025.pdf), which can be reversed by <span id=\"drug\"> [Physostigmine](http://chen42.github.io/slides/cho_ag.html#/stigmine) ([Antilirium](http://chen42.github.io/slides/cho_ag.html#/6))\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"cycloplegia\">\n"
+ "\n"
+ "Antimuscarinics: Organ System Effects\n"
+ "\n"
+ "### Eye \n"
+ "\n"
+ "Compare with [cholinomimetics ](http://chen42.github.io/slides/cho_ag.html#/eye)\n"
+ "\n"
+ "<table><tr><td>\n"
+ "<ul>\n"
+ "<li> reduce lacrimal secretion (\"sandy\" eyes)\n"
+ "<li> Belladonna (Italian, \"beautiful lady\")\n"
+ "	<ul> <li><a href=\"http://www.e-safe-anaesthesia.org/sessions/15_05/gif/ana_1_011_autonomic_nervous_system_08_t1_01_med.gif\"> mydriasis </a>\n"
+ "	<li> remove parasympathetic opposition to the sympathetic system in the iris\n"
+ "	</ul>\n"
+ "<li> causes cycloplegia \n"
+ "<ul>\n"
+ "	<li> defined as the paralysis of ciliary muscle  \n"
+ "	<li> results in the loss of accomondate (i.e. focus on near objects)\n"
+ "		<ul><li> can cause acute close angle glaucoma\n"
+ "		</ul>\n"
+ "</ul></ul></td><td>\n"
+ "\n"
+ "<img src=\"https://www.sciencelearn.org.nz/system/images/images/000/000/054/original/Theories-of-eye-accommodation20150805-30600-1yqri0r.jpg\">\n"
+ "\n"
+ "<br>\n"
+ "Contraction of ciliary muscle --> accommodation\n"
+ "\n"
+ "</td>\n"
+ "\n"
+ "</tr></table>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "Antimuscarinics: Organ System Effects\n"
+ "\n"
+ "### Cardiac system \n"
+ "\n"
+ "Compare with [cholinomimetics ](http://chen42.github.io/slides/cho_ag.html#/cardiac)\n"
+ "\n"
+ "* sinoatril and atrioventricular nodes\n"
+ "	* blocking the effects of the vagus nerve \n"
+ "		* tachycardia, increase conduction velocity \n"
+ "		* low dose i.v. administration results in initial bradycardia \n"
+ "			* due to block of prejunctiona [M1 auto-receptors](#/9)\n"
+ "			* stimulation of the vagal motor nucleus in the brain stem. \n"
+ "	* reduce [PR interval](https://en.wikipedia.org/wiki/PR_interval#/media/File:SinusRhythmLabels.svg)	of the ECG \n"
+ "\n"
+ "---\n"
+ "\n"
+ "Antimuscarinics: Organ System Effects\n"
+ "\n"
+ "### Vascular system \n"
+ "\n"
+ "Compare with [cholinomimetics ](http://chen42.github.io/slides/cho_ag.html#/vascular)\n"
+ "\n"
+ "* most blood vessels receive no direct innervation from the parasympathetic system\n"
+ "	* except those in the thoracic and abdominal viscera\n"
+ "	* almost all vessles contain [endothelia muscarinic receptors](http://chen42.github.io/slides/cho_ag.html#/18) &rarr; vasodilation\n"
+ "		* blocked by antimuscarinic drugs\n"
+ "\n"
+ "// ### net cardiovascular effect of atropine\n"
+ "* in patients with normal hemodynamics\n"
+ "	* no dramatic effect, tachycardia may occur, but little effect on blood pressure\n"
+ "	* prevent the cardiovascular effect of direct-activing muscarinic agonits\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"COPD\">\n"
+ "\n"
+ "Antimuscarinics: Organ System Effects\n"
+ "\n"
+ "### Respiratory system\n"
+ "\n"
+ "Compare with [cholinomimetics ](http://chen42.github.io/slides/cho_ag.html#/respiratory)\n"
+ "\n"
+ "<table><tr><td width=50%>\n"
+ "<ul><li> potent inhibitors of secretions in the upper and lower respiratory tract.\n"
+ "<li> bronchial smooth muscle relaxation and bronchodilation\n"
+ "<ul><li>	 used before inhalant anesthetics to reduce trachea secretion 	 \n"
+ "</ul><li> chronic obstructive pulmonary disease (COPD)\n"
+ "</ul>\n"
+ "\n"
+ "In COPD, the small airways are narrowed through thickening of the bronchiolar periphery wall by inflammation and fixed narrowing as a result of fibrosis, disruption of alveolar attachments as a result of [emphysema](http://www.webmd.com/lung/emphysema) and luminal occlusion by mucus and inflammatory exudate. \n"
+ "</td><td>\n"
+ "	<img src=\"http://www.livingwellwithcopd.com/DATA/TEXTEDOC/COPD---Obstructive-Chronic-Bronchitis-or-Emphysema.jpg\" width=80%>	\n"
+ "</td><tr></table>\n"
+ "\n"
+ "[COPD review](https://www.ncbi.nlm.nih.gov/pubmed/27189863)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "Antimuscarinics: Organ System Effects\n"
+ "\n"
+ "### Gastrointestinal tract \n"
+ "\n"
+ "Compare with [cholinomimetics](http://chen42.github.io/slidess/cho_ag.html#/urinary)\n"
+ "\n"
+ "* dry mouth is a common side effect of antimuscarinics.\n"
+ "* gastric secretion is not as effectively blocked because [other neurotransmitters](http://accessmedicine.mhmedical.com/data/books/1193/m_kat_ch6_f002.png) are involved. \n"
+ "* gastrointestinal smooth muscle mobility is affected\n"
+ "	* from stomach to colon\n"
+ "	* diminish the tone and propulsive movement\n"
+ "	* relax viscera wall, prolong gastric emptying time.\n"
+ "	* stop diarrhea caused by cholinomimetics. \n"
+ "\n"
+ "---\n"
+ "\n"
+ "Antimuscarinics: Organ System Effects\n"
+ "\n"
+ "### Genitourinary tract \n"
+ "\n"
+ "Compare with [cholinomimetics](http://chen42.github.io/slides/cho_ag.html#/urinary)\n"
+ "\n"
+ "* relaxes smooth muscle of the ureters and bladder ball. \n"
+ "* treating spasm induced by mild inflammation or surgery. \n"
+ "* can precipitate urinary retention \n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "Antimuscarinics: Organ System Effects\n"
+ "\n"
+ "### Sweat glands\n"
+ "\n"
+ "* suppresses thermoregulatory sweating.\n"
+ "* body temperature increase when large dose of Antimuscarinics is given\n"
+ "	* \"Atropine\" fever in infants and children\n"
+ "\n"
+ "// atropic toxicity\n"
+ "\n"
+ "---\n"
+ "<section id=\"scopolamine\">\n"
+ "\n"
+ "\n"
+ "## <span id=\"drug\"> Atropine, Scopolamine</span> \n"
+ "\n"
+ "\n"
+ "### ADME\n"
+ "* <span id=\"drug\"> atropine </span> and <span id=\"drug\"> scopolamine</span> are nonionized tertiary amines. \n"
+ "\n"
+ "	* well absorbed from the gut and are readily distributed to the CNS.\n"
+ "\n"
+ "* <span id=\"drug\"> scopolamine </span> has longer duration of action and stronger CNS effect than <span id=\"drug\"> atropine </span> \n"
+ "\n"
+ "* excreted in the urine with a half-life of about 2 hours. \n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## <span id=\"drug\"> Atropine, Scopolamine </span> \n"
+ "### Ocular Indications\n"
+ "* localized application to produce mydriasis \n"
+ "	* facilitate ophthalmoscopic examination of the peripheral retina\n"
+ "	* effect of <span id=\"drug\"> atropine, scopolamine </span> can last for days \n"
+ "		* they bind to pigments in the iris that slowly release the drugs. People with darker irises bind more atropine and experience a more prolonged effect than do people with lighter irises. \n"
+ "* to produce cycloplegia and permit the accurate determination of refractive errors \n"
+ "* [cyclopentolate](https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-1277) is preferred for inducing cycloplegia and mydriasis (rapid onset of action, lasting a day) for diagnostic purpose. \n"
+ "* should be only used when both mydriasis and cycloplegia or prolonged action is required \n"
+ "	* short-lasting mydriasis can be induced by <span id=\"drug\"> phenylephrine </span>, which does not induce cycloplegia.\n"
+ "* reduce muscle spasm and pain caused by inflammation\n"
+ "	* treat iritis and cyclitis (inflammation of the iris and ciliary muscles) associated with infection, trauma, or surgery.\n"
+ "	* long-lasting effects are valuable\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## <span id=\"drug\"> Atropine, Scopolamine </span> \n"
+ "\n"
+ "### Respiratory Tract Indications\n"
+ "\n"
+ "* to reduce salivary and respiratory secretions, prevent airway obstruction in patients who are receiving general anesthetics. \n"
+ "	* <span id=\"drug\"> scopolamine </span> may cause amnesia associated with surgery \n"
+ "	* [Glycopyrrolate](#/glycopyrrolate) is mostly used for this purpose \n"
+ "\n"
+ "* no longer used for bronchodilation because of its many adverse effects.\n"
+ "	* e.g., impairs ciliary activity, reducing the clearance of mucus from the lungs and causing accumulation of viscid material in the airways. \n"
+ "	* [ipratropium](#/ipratropium) is preferred \n"
+ "	 \n"
+ "---\n"
+ "\n"
+ "## <span id=\"drug\"> Atropine, Scopolamine</span> \n"
+ "\n"
+ "### Gastrointestinal and urinary tract Indications\n"
+ "\n"
+ "* relieve intestinal or uninary bladder spasms and pain \n"
+ "\n"
+ "* not used to treat peptic ulcer due to large adverse effects. \n"
+ "	*	a selective muscarinic [M1 receptor](#/receptorSubtype) blocker, [pirenzepine](#/pirenzepine) can be used.\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## <span id=\"drug\"> Atropine, Scopolamine</span> \n"
+ "\n"
+ "### central nervous system indications\n"
+ "\n"
+ "* motion sickness \n"
+ "	* A transdermal formulation of <span id=\"drug\"> scopolamine</span> can be used to prevent motion sickness. \n"
+ "	* blocking acetylcholine neurotransmission from the vestibular apparatus to the vomiting center in the brain stem. \n"
+ "  \n"
+ "* used in the treatment of Parkinson disease.\n"
+ "	* adjunctive therapy with adverse effects \n"
+ "	* better drugs available\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"bradycardia\">\n"
+ "\n"
+ "## <span id=\"drug\"> Atropine, Scopolamine</span> \n"
+ "\n"
+ "\n"
+ "### Cardiac Indications\n"
+ "* sinus bradycardia with reduced cardiac output and hypotension or ischemia. \n"
+ "	* sometimes occurs after a myocardial infarction. \n"
+ "	* i.v. <span id=\"drug\"> Atropine </span> \n"
+ "		* blocking the effect of vagus nerve on sinoatrial and atriventricular nodes\n"
+ "		* low dose causes a paradoxical slowing of heart rate \n"
+ "		* full dose increase heart rate\n"
+ "		* which drug has the opposite effect[??](http://chen42.github.io/slides/cho_ag.html#/cardiac)		\n"
+ "* symptomatic atrioventricular blocking\n"
+ "	* <span id=\"drug\"> atropine </span>  can be used to increase atriventricular conduction velocity.\n"
+ "* primary use of <span id=\"drug\"> atropine </span> \n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"toxicity\">\n"
+ "\n"
+ "## <span id=\"drug\"> Atropine, Scopolamine</span> \n"
+ "\n"
+ "### Toxicity\n"
+ "\n"
+ "<table><tr><td width=70%>\n"
+ "\n"
+ "<img src=\"https://basicmedicalkey.com/wp-content/uploads/2016/07/B9781455702824000071_f007-001-9781455702824.jpg\">\n"
+ "</td><td width=30%>\n"
+ "<img src=\"https://pbs.twimg.com/media/CD5ErOGVEAAjkB1.jpg\">\n"
+ "</td><tr></table>\n"
+ "\n"
+ "Atropine toxicity: \"dry as a bone, blind as a bat, red as a beet, and mad as a hatter.\" \n"
+ "\n"
+ "Treatment: 1. activated charcoal. 2. [Physostigmine](http://chen42.github.io/slides/cho_ag.html#/stigmine) (a tertiary amine with CNS effects)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Other Muscarinic Receptor Antagonists\n"
+ "\n"
+ "The pharmacologic effects of these agents are similar to those of atropine, their unique pharmacokinetic properties are advantageous in specific situations. \n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"glycopyrrolate\">\n"
+ "\n"
+ "## <span id=\"drug\"> Glycopyrrolate, hyoscyamine </span> \n"
+ "\n"
+ "\n"
+ "adjunctive for general anesthesia\n"
+ "\n"
+ "* AMDE \n"
+ "	* <span id=\"drug\"> glycopyrrolate </span> is synthetic quaternary amine. <span id=\"drug\"> hyoscyamine </span> is optical isomer of <span id=\"drug\"> atropine </span> \n"
+ "	* less CNS effects\n"
+ "	* excreted in the urine with a half-life of about 2 hours. \n"
+ "* Indications\n"
+ "	* <span id=\"drug\"> glycopyrrolate </span> reduce salivary and respiratory secretions, prevent airway obstruction in patients who are receiving general anesthetics. <span id=\"drug\"> hyoscyamine </span> can also be used. \n"
+ "	* <span id=\"drug\"> glycopyrrolate </span> reduces chronic severe drooling in patients aged 3 to 16 years with neurologic conditions such as cerebral palsy.\n"
+ "	* <span id=\"drug\"> Hyoscyamine </span> can be used to control hypermotility of the lower urinary tract. \n"
+ "	* <span id=\"drug\"> hyoscyamine </span> oral or sublingual formations are used to treat intestinal spasms and other gastrointestinal symptoms. Many [other drugs](#/intestinal) are available. \n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"tropicamide\">\n"
+ "\n"
+ "## <span id=\"drug\">cyclopentolate,  Tropicamide</span> \n"
+ "\n"
+ "Eye\n"
+ "\n"
+ "* synthetic drugs\n"
+ "* topical ocular administration as a mydriatic. \n"
+ "* given before ophthalmoscopy to facilitate examination of the peripheral retina. \n"
+ "	* <span id=\"drug\"> cyclopentolate </span> produces maximum mydriatic and cycloplegic effects within 15-60 minutes. The duration of both effects is normally 24 hours. Mydriasis may persist for several days in selected patients. \n"
+ "	* <span id=\"drug\"> tropicamide </span> has a short duration of action (about 1 hour) and is often preferable for short-term mydriasis. \n"
+ "*  Why induce [cycloplegia](#/cycloplegia) to measure refraction error [ref](https://www.omicsonline.org/cycloplegic-refraction-in-children-with-cyclopentolate-versus-atropine-2155-9570.1000239.pdf) \n"
+ "	* refraction power of the eye is determined by \n"
+ "		* static power (cornea, lens)\n"
+ "		* accomondation power (mainly cililary body, contains mAChR)\n"
+ "		* accurate measurement of refraction in children need to eliminate the accomondation component. Adults are less affected.\n"
+ "\n"
+ " <small>There is no statistically significant difference between <span id=\"drug\"> cyclopentolate </span> and <span id=\"drug\"> tropicamide </span> for either cycloplegic retinoscopy or distance subjective refraction.\n"
+ "[Optom Vis Sci. 1993 Dec;70(12):1019-26.](https://www.ncbi.nlm.nih.gov/pubmed/8115124) </small>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"ipratropium\">\n"
+ "\n"
+ "## <span id=\"drug\"> Ipratropium, Tiotropium </span> \n"
+ "\n"
+ "\n"
+ "respiratory tract\n"
+ "\n"
+ "* ADME and MoA\n"
+ "	* quaternary amine derivatives of atropine, structurally similar \n"
+ "		* not well absorbed from the lungs into the systemic circulation,\n"
+ "	* administered by <u>inhalation</u> to patients with obstructive lung diseases. \n"
+ "	* main difference is duration of action. \n"
+ "		* <span id=\"drug\"> Tiotropium </span> *once* daily dosing\n"
+ "		* <span id=\"drug\"> ipratropium </span> requires *four* times daily dosing\n"
+ "* Indications\n"
+ "	* <span id=\"drug\"> Ipratropium </span> is a first line drug for patients with mild stable [COPD](#/COPD), and a second line drug for exercise-induced bronchospasm \n"
+ "	* <span id=\"drug\"> Tiotropium </span> may be used in all groups of COPD patients with varying symptoms and risks of exacerbations as monotherapy.\n"
+ "	* <span id=\"drug\"> Tiotropium </span> is the first long-acting anticholinergic agent to be approved for long-term asthma maintenance therapy in the US. \n"
+ "	* <span id=\"drug\"> Ipratropium </span> and <span id=\"drug\"> Tiotropium </span> are often combined with beta-agonist treatments during severe, acute asthma exacerbations.\n"
+ "\n"
+ "\n"
+ "// atropine ->  trophy -> metal -> chest \n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"intestinal\">\n"
+ "\n"
+ "## <span id=\"drug\"> <u>Di</u>cyclomine </span> \n"
+ "\n"
+ "<u>Di</u>gestive tract\n"
+ "\n"
+ "* ADME \n"
+ "	* synthetic tertiary amine	\n"
+ "	* MoA unclear, likely exert a nonspecific, local, direct musculotropic action on the smooth muscle of the GI tract\n"
+ "	* excreted in urine\n"
+ "	* elimination half-life: 9-10 h\n"
+ "* Indications\n"
+ "	* relieve irritable bowel symptoms, such as intestinal cramping. \n"
+ "* Adverse effects\n"
+ "	* does *not* produce characteristic atropine-like effects on the salivary or sweat glands, or on the cardiovascular system.\n"
+ "	* not used in infants \n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id='pirenzepine'>\n"
+ "\n"
+ "## <span id=\"drug\"> Piren<u>zepine</u> </span>  (Gastro<u>zepin</u>)\n"
+ "\n"
+ "GI tract \n"
+ "\n"
+ "* selective for [M1 receptors](#/receptorSubtype)\n"
+ "* reduce vagally stimulated gastric acid secretion \n"
+ "	* treat	patients with peptic ulcers.  \n"
+ "* it [blocks M1 receptors on paracrine cells](https://image1.slideserve.com/2068049/slide6-n.jpg) and inhibits the release of histamine, a potent gastric acid stimulant. \n"
+ "* Pirenzepine is available in Canada and Europe but not in the United States. \n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"urinary\">\n"
+ "\n"
+ "## <span id=\"drug\"> Oxybutyn<u>in</u></span> (Ditropan), <span id=\"drug\">Trospium </span> (Spasmex)  \n"
+ "\n"
+ "Ur<u>in</u>ary tract\n"
+ "\n"
+ "* ADME and MoA\n"
+ "	* <span id=\"drug\"> oxybutynin </span> is tertiary amine, <span id=\"drug\"> trospium </span> is quaternary amine \n"
+ "	* both are nonselective antimuscarinic\n"
+ "	* both have stronger urinary effect than <span id=\"drug\"> atropine </span> \n"
+ "	\n"
+ "* Indications\n"
+ "	* reduce the four major symptoms of overactive bladder: daytime urinary frequency, nocturia (frequent urination at night), urgency, and incontinence. \n"
+ "	* <span id=\"drug\"> oxybutynin </span> available in both oral and transdermal formulations. \n"
+ "		* side effect: dry mouth\n"
+ "	* <span id=\"drug\"> trospium </span> has fewer side effects (e.g. dry mouth: 4% trospium vs 23% oxybutynin).\n"
+ "	* long-term (1 year) safety and efficacy of <span id=\"drug\"> trospium </span> has been [demonstrated](https://www.ncbi.nlm.nih.gov/pubmed/12811500). Main side effect is dry mouth. \n"
+ "\n"
+ "---\n"
+ "\n"
+ "## <span id=\"drug\"> solifenac<u>in</u>, darifenac<u>in</u>, tolterod<u>in</u> </span> \n"
+ "\n"
+ "Ur<u>in</u>ary tract\n"
+ "\n"
+ "* ADME \n"
+ "	* [competitive](https://en.wikipedia.org/wiki/Receptor_antagonist#Competitive) muscarinic antagonist. \n"
+ "	* <span id=\"drug\"> solifenacin </span> and <span id=\"drug\"> tolterodin </span> are not selective. <span id=\"drug\"> darifenacin</span> has a greater affinity for the M3 receptor than for other known muscarinic receptors 	\n"
+ "	* <span id=\"drug\"> tolterodine </span> very low lipophilicity, greatly limits CNS effect\n"
+ "	* <span id=\"drug\"> solifenacin </span> is primarily metabolized by CYP3A4. <span id=\"drug\"> darifenacin </span> is metabolized by both CYP3A4 and CYP2D6 <span id=\"drug\"> tolterodine </span> is primarily metabolized by CYP2D6\n"
+ "\n"
+ "* Indications\n"
+ "	* reduce the four major symptoms of overactive bladder: daytime urinary frequency, nocturia (frequent urination at night), urgency, and incontinence. \n"
+ "	* <span id=\"drug\"> tolterodine </span> is preferred in the geriatric population \n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nicotinic Receptor Antagonists \n"
+ "\n"
+ "### Ganglionic Blocking Agents\n"
+ "\n"
+ "* Characteristics \n"
+ "	* reduce excessive activity of the sympathetic or parasympathetic nervous system, \n"
+ "	* lack selectivity for sympathetic or parasympathetic ganglia \n"
+ "	* have numerous adverse effects\n"
+ "	* rarely used clinically but still useful for preclinical (i.e., [animal model](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3230486/)) research \n"
+ "* All synthetic amines\n"
+ "	* <span id=\"drug\"> Mecamylamine </span> \n"
+ "		* [a noncompetitive antagonist](https://en.wikipedia.org/wiki/Receptor_antagonist#Non-competitive) of the nAChR\n"
+ "		* a secondary amine, good GI track absorption, has CNS effects\n"
+ "		* the first oral antihypertensive agent. \n"
+ "		* block sympathetic ganglion neurotransmission [diagram](#/diagram) \n"
+ "		* vasodilation, and reduced cardiac output\n"
+ "		* the only drug of this class remain on the market \n"
+ "	* <span id=\"drug\"> Hexamethonium </span>  and  <span id=\"drug\"> Tetraethylammonium </span> \n"
+ "		*  No longer on the market \n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nicotinic Receptor Antagonists \n"
+ "\n"
+ "### Neuromuscular Blocking Agents\n"
+ "\n"
+ "* MoA\n"
+ "	* neuromuscular blocking agents = paralytics = muscle relaxants\n"
+ "	* bind to the muscle type  of nicotinic acetylcholine receptor \n"
+ "	* inhibit neurotransmission at skeletal neuromuscular junctions\n"
+ "	* causing muscle weakness and paralysis.\n"
+ "\n"
+ "* classification\n"
+ "	* nondepolarizing blockers\n"
+ "		* [competitive antagonists](https://en.wikipedia.org/wiki/Receptor_antagonist#Competitive) at the neuromuscular junction\n"
+ "	* depolarizing blocker \n"
+ "		* <span id=\"drug\"> succinylcholine </span> \n"
+ "\n"
+ "\n"
+ "// muscle type: alpha1 beta1\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"muscleDiagram\">\n"
+ "\n"
+ "## Muscle contraction \n"
+ "\n"
+ "<a href=\"http://droualb.faculty.mjc.edu/Course%20Materials/Physiology%20101/Chapter%20Notes/Fall%202011/chapter_12%20Fall%202011.htm\">\n"
+ "<img src=\"http://droualb.faculty.mjc.edu/Course%20Materials/Physiology%20101/Chapter%20Notes/Fall%202007/chapte1.jpg\" width=60%>\n"
+ "</a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"nondepol\">\n"
+ "\n"
+ "Nicotinic Receptor Antagonists \n"
+ "## Neuromuscular Blocking Agents \n"
+ "### Chemistry and Pharmacokinetics \n"
+ "\n"
+ "<table><thead>\n"
+ "<th> Drug </th><th>Depolarizing Agent </th><th>HISTAMINE RELEASE </th><th>GANGLIONIC BLOCKADE </th><th>Effects Reversed by Cholinesterase Inhibitors </th><th>Duration of Action (Minutes) </th><th>Routes of Elimination</th></thead>\n"
+ "<tr><td><a href=\"pdfs/anesthprog00291-0025.pdf\">Atracurium</a> </td><td>No </td><td>Varies </td><td>Low </td><td>Yes </td><td>Intermediate (30-60) </td><td>Plasma esterase</tr>\n"
+ "<tr><td>Cisatracurium </td><td>No </td><td>None </td><td>Low </td><td>Yes </td><td>Intermediate (30-60) </td><td>Spontaneous chemical degradation</tr>\n"
+ "<tr><td>Pancuronium </td><td>No </td><td>None </td><td>Medium </td><td>Yes </td><td>Long (60-120) </td><td>Renal excretion</tr>\n"
+ "<tr><td>Rocuronium </td><td>No </td><td>None </td><td>Low </td><td>Yes </td><td>Intermediate (30-60) </td><td>Biliary and renal excretion</tr>\n"
+ "<tr><td>Vecuronium </td><td>No </td><td>None </td><td>Low </td><td>Yes </td><td>Intermediate (30-60) </td><td>Biliary and renal excretion and hepatic metabolism</tr>\n"
+ "<tr><td>Succinylcholine </td><td>Yes </td><td>Minimal </td><td>None </td><td>No </td><td>Short (5-10) </td><td>Plasma (butyryl) cholinesterase</tr>\n"
+ "</table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "Nicotinic Receptor Antagonists \n"
+ "## Nondepolarizing Neuromuscular Blocking Agents \n"
+ "### ADME \n"
+ "* <span id=\"drug\"> tubocurarine</span>, was extracted from plants used by native South Americans as arrow poisons for hunting wild game. [(which class of drug can save the bird?)](https://chen42.github.io/slides/cho_ag.html#/curare)) \n"
+ "* <b>curariform drugs</b>: <span id=\"drug\"> atracurium, cisatracurium, pancuronium, rocuronium, </span> and <span id=\"drug\"> vecuronium </span>. \n"
+ "	* The curariform drugs are not well absorbed from the gut.\n"
+ "	* administered only by the intravenous route.\n"
+ "* most eliminated by renal and biliary excretion of the unchanged compounds \n"
+ "	* or hepatic metabolites\n"
+ "* most of the isomers of atracurium are hydrolyzed by [plasma esterases](https://en.wikipedia.org/wiki/Butyrylcholinesterase). \n"
+ "* <span id=\"drug\"> cisatracurium </span> spontaneously decomposes by nonenzymatic chemical degradation. \n"
+ "	* preferred paralytic agent for critically ill patients with impaired hepatic and renal function. \n"
+ "\n"
+ "---\n"
+ "Nicotinic Receptor Antagonists \n"
+ "## Nondepolarizing Neuromuscular Blocking Agents \n"
+ "### MoA \n"
+ "\n"
+ "* competitive antagonists of nAChR in skeletal muscle\n"
+ "	* sequence of muscle paralyzing effect \n"
+ "		1. the small and rapidly moving muscles of the eyes and face\n"
+ "		2. the larger muscles of the limbs and trunk\n"
+ "		3. the intercostal muscles and diaphragm, causing respiration to cease. \n"
+ "		4. it enables relaxation of abdominal muscles for surgical procedures without producing apnea. \n"
+ "		5. respiratory function should always be closely monitored\n"
+ "* stimulate the release of histamine from mast cells, block autonomic ganglia and muscarinic receptors.\n"
+ "	* cause bronchospasm, hypotension, and tachycardia. \n"
+ "	* Newer drugs tend to cause less histamine release,  and fewer autonomic side effects than does <span id=\"drug\"> pancuronium </span>.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "Nicotinic Receptor Antagonists \n"
+ "## Nondepolarizing Neuromuscular Blocking Agents \n"
+ "### Indications\n"
+ "\n"
+ "* primarily used to induce muscle relaxation during surgery.\n"
+ "* used as an adjunct to electroconvulsive therapy to prevent injuries that might be caused by involuntary muscle contractions.\n"
+ "* facilitate intubation of the respiratory tract. \n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"postsurgical\">\n"
+ "\n"
+ "Nicotinic Receptor Antagonists \n"
+ "## Nondepolarizing Neuromuscular Blocking Agents \n"
+ "### Adverse effects \n"
+ "\n"
+ "* Residual neuromuscular blockade	\n"
+ "	* causes of postoperative pulmonary and respiratory complications, hypoxia, upper airway obstruction and decreased oxygen saturation\n"
+ "	* increase the incidence of tracheal re-intubation in critical care units\n"
+ "* [neostigmine](http://chen42.github.io/slides/cho_ag.html#/stigmine) can be used to counteract  this effect, but in turn may cause nausea and vomiting, increased secretions, heart rhythm abnormalities and bronchospasm.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "Nicotinic Receptor Antagonists \n"
+ "## Nondepolarizing Neuromuscular Blocking Agents \n"
+ "### Interactions\n"
+ "\n"
+ "* muscle-relaxing effects are potentiated by volatile inhalational anesthetic agents (e.g., <span id=\"drug\"> sevoflurane</span> ) and by the aminoglycoside antibiotics, tetracycline antibiotics, and calcium channel blockers. \n"
+ "\n"
+ "* effects is more pronounced in myasthenia gravis patients.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"sugammadex\">\n"
+ "\n"
+ "Nicotinic Receptor Antagonists \n"
+ "## Nondepolarizing Neuromuscular Blocking Agents \n"
+ "###  selective relaxant binding agents\n"
+ "* <span id=\"drug\">  Sugammadex </span> \n"
+ "	*  A [new drug classs](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3789633/) approved by the FDA [on Dec 15, 2015](https://www.fda.gov/newsevents/newsroom/pressannouncements/ucm477512.htm)\n"
+ "	* selectively bind to <span id=\"drug\"> rocuronium </span> or <span id=\"drug\"> Vecuronium </span> and removes the drug from the neuromuscular junction\n"
+ "	* reverses neuromuscular blockade more rapidly and reliably than acetylcholinesterase inhibitors. \n"
+ "	* reduced all signs of residual postoperative paralysis by 46%  compared with neostigmine in a recent [meta analysis](http://onlinelibrary.wiley.com/enhanced/figures/doi/10.1111/anae.13277#figure-viewer-anae13277-fig-0004) \n"
+ "	* safe to use in patients with neuromuscular disease, [PubMed](https://www.ncbi.nlm.nih.gov/pubmed/20105151/)\n"
+ "	* the end of succinylcholine? [Anesth Analg. 2000;90:S24-8.](https://www.ncbi.nlm.nih.gov/pubmed/10809515), [Can J Anaesth. 2017;64(1):104-106.](https://www.ncbi.nlm.nih.gov/pubmed/27770379)	\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"succinylcholine\">\n"
+ "\n"
+ "Nicotinic Receptor Antagonists \n"
+ "## Depolarizing Neuromuscular Blocking Agents\n"
+ "### <span id=\"drug\"> Succinylcholine</span> \n"
+ "\n"
+ "* ADME and MoA \n"
+ "	* the only depolarizing agent available for clinical use today\n"
+ "	* composed of two covalently linked molecules of acetylcholine.\n"
+ "	* succinylcholine binds to nAChR in skeletal muscle.\n"
+ "		* <span id=\"drug\"> succinylcholine </span> is not a substracte of AChE, it is hydrolyzed by [plasma (pseudo-, or butyryl- ) cholinesterase](https://www.openanesthesia.org/pseudocholinesterase_synthesis/), which is slower than ACh. \n"
+ "		* This causes \"persistent\" depolarization of the NMJ, and unable to respond to subsequent ACh\n"
+ "		* In essence, the endplate and adjacent sarcolemma are refractory to subsequent stimulation. \n"
+ "	* when the drug is first administered, it produces transient muscle contractions called fasciculations, followed by a sustained muscle paralysis. \n"
+ "* Indications \n"
+ "	* the preferred neuromuscular blocker for endotracheal intubation or adults with emergency airway situations.\n"
+ "		* rapid onset (1 min ) and offset (short duration, 5 min)\n"
+ "* Adverse effects \n"
+ "	* repeated application may cause cardiac arrest\n"
+ "	* patients with atypical cholinesterase cannot metabolize <span id=\"drug\"> succinylcholine </span> at normal rates \n"
+ "		* susceptible to prolonged neuromuscular paralysis and apnea \n"
+ "    \n"
+ "---\n"
+ "\n"
+ "Nicotinic Receptor Antagonists \n"
+ "## Depolarizing Neuromuscular Blocking Agents\n"
+ "### <span id=\"drug\"> Succinylcholine</span> \n"
+ "\n"
+ "<table><tr><td>\n"
+ "<ul><li> Interactions and adverse effects\n"
+ "	<ul><li> can cause <u>hyperkalemia </u> &rarr; cardiac arrest \n"
+ "	<li> avoid third-degree burn patients, prolonged chemical denervation (e.g. muscle relaxant), direct muscle trauma \n"
+ "	<li> these conditions increase muscle nAChR, including <a href=#/alpha7>&alpha;7 homomer </a>\n"
+ "	<li> muscle cells do express &alpha;7 nAChR. These receptors do not desensitize. \n"
+ "		<li> choline (metabolite of Ach and Succinylcholine) is a full agonist for muscle &alpha;7 \n"
+ "		<li> activation of &alpha;7 increases K+ outflow\n"
+ "		</ul>\n"
+ "</ul>\n"
+ "\n"
+ "</td><td width=50%>\n"
+ "<img src=\"http://anesthesiology.pubs.asahq.org/data/Journals/JASA/931078/22FF3.png\">\n"
+ "</td></tr></table>\n"
+ "\n"
+ "<br>\n"
+ "\n"
+ "[Anesthesiology 1 2006, Vol.104, 158-169](http://anesthesiology.pubs.asahq.org/article.aspx?articleid=1923491)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "Nicotinic Receptor Antagonists \n"
+ "## Depolarizing Neuromuscular Blocking Agents\n"
+ "### <span id=\"drug\"> Succinylcholine</span> \n"
+ "\n"
+ "* Interactions and adverse effects\n"
+ "	* [malignant hyperthermia:](https://ojrd.biomedcentral.com/articles/10.1186/s13023-015-0310-1) pharmacogenetic disorder of skeletal muscle that presents as a hypermetabolic response to anesthetic gases *or* <span id=\"drug\"> Succinylcholine</span>\n"
+ "	* The classic signs of MH include hyperthermia, tachycardia, tachypnea, increased carbon dioxide production, increased oxygen consumption, acidosis, hyperkalaemia, muscle rigidity, and rhabdomyolysis, all related to a hypermetabolic response.\n"
+ "	* In most cases, the syndrome is caused by a defect in the [ryanodine receptor](http://droualb.faculty.mjc.edu/Course%20Materials/Physiology%20101/Chapter%20Notes/Fall%202007/chapte2.jpg), causes increase Ca2+ in the muscle cells -> generate heat -> produce acid. \n"
+ "	* Likely fatal if untreated. Mortality has decreased from 80 % thirty years ago to <5 % in 2006.\n"
+ "	* <span id=\"drug\"> Dantrolene </span> is a specific treatment for MH. \n"
+ "		* decrease muscle contraction by directly [interfering with calcium ion release ](https://www.clinicalkey.com/#!/content/drug_monograph/6-s2.0-167) from the [sarcoplasmic reticulum](#/muscleDiagram) within skeletal muscle cells.\n"
+ "		\n"
+ "<a href=\"https://ojrd.biomedcentral.com/articles/10.1186/s13023-015-0310-1\">Orphanet J Rare Dis. 2015 Aug 4;10:93</a>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Cholinergic Poisoning\n"
+ "### types of cholinergic poisoning\n"
+ "\n"
+ "* cholinesterase inhibitor  ([cholinergic crisis](https://chen42.github.io/slides/cho_ag.html#/achcrisis))\n"
+ "\n"
+ "* insecticides \n"
+ "\n"
+ "* chemical warfare\n"
+ "\n"
+ "* eating wild mushrooms\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Cholinergic Poisoning\n"
+ "### treatment \n"
+ "\n"
+ "* no treatment for nicotinic effect 	\n"
+ "	* agonists and antagonists cause blockage of transmission (receptor desensitization)\n"
+ "* antimusacrinic therapy\n"
+ "	* muscarinic effect can be blocked by a tertiary amine\n"
+ "		* <span id=\"drug\"> atropine </span> is the preferred drug \n"
+ "	* both peripheral and CNS effects\n"
+ "	* AChE inhibition can lasting for more then 24 or 48 h\n"
+ "	* need large dose, need to give several times \n"
+ "		* dosage must be titrated to the patient's response. \n"
+ "* cholinesterase regenerator \n"
+ "	* [pralidoxime](http://chen42.github.io/slides/cho_ag.html#/39) \n"
+ "		* does not reverse CNS effects\n"
+ "* pretreatment\n"
+ "	* use intermediate-acting enzyme inhibitors to prevent binding of the much longer-acting inhibitor\n"
+ "	* [pyridostigmine](http://chen42.github.io/slides/cho_ag.html#/stigmine) \n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Cholinergic Poisoning\n"
+ "### Mushroom poisoning \n"
+ "\n"
+ "* rapid-onset	\n"
+ "	* apparent 1/2 - 2 h after ingestion\n"
+ "	* can be caused by a variety of toxins\n"
+ "	* some have muscarinc signs (nausea, vomiting, diarrhea, urinary urgency, sweating, salivation, and sometimes bronchoconstriction)\n"
+ "		* treat with <span id=\"drug\"> atropine </span> \n"
+ "	* some will have antimuscarinic signs ([atropine poisoning](#/toxicity)) \n"
+ "* delayed-onset\n"
+ "	* first manifestation 6 - 12 h after ingestion \n"
+ "	* initially nausea and vomiting\n"
+ "	* major toxicity involves hepatic and renal cellular injury by amatoxins that inhibit RNA polymerase. \n"
+ "		* <span id=\"drug\"> atropine </span> has no effect \n"
+ "---\n"
+ "\n"
+ "<table><tr><td width=50%>\n"
+ " <img src=\"http://www.thegasmanhandbook.co.uk/uploads/1/2/6/9/12696516/3262826_orig.png\" width=90%>\n"
+ "</td><td width=50%>\n"
+ "<img src=\"http://www.thegasmanhandbook.co.uk/uploads/1/2/6/9/12696516/3861057.png\" width=90%>\n"
+ "</td><tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Summary of Important Points\n"
+ "\n"
+ "* Muscarinic acetylcholine receptor antagonists relax smooth muscle, increase heart rate and cardiac conduction, and inhibit exocrine gland secretion. They include belladonna alkaloids (e.g., [atropine and scopolamine](#/scopolamine)) and semisynthetic and synthetic drugs (e.g., [ipratropium](#/ipratropium)).\n"
+ "* Muscarinic blockers are used to treat [bradycardia](#/bradycardia), [obstructive lung diseases](#/ipratropium), [intestinal spasms](#/intestinal), and [overactive urinary bladder](#/urinary). They are also used to [reduce salivary and respiratory secretions](#/glycopyrrolate) and to [produce mydriasis and cycloplegia](#/tropicamide).\n"
+ "* <span id=\"drug\"> Atropine </span> [toxicity](#/toxicity) can cause dryness of the mouth and skin, blurred vision, tachycardia, palpitations, urinary retention, delirium, and hallucinations.\n"
+ "* Nicotinic acetylcholine receptor antagonists include nondepolarizing neuromuscular blocking agents known as curariform drugs, such as [rocuronium](#/nondepol) and [cisatracurium](#/nondepol). These drugs are used to produce muscle relaxation during surgery.\n"
+ "* Curariform drugs competitively block nicotinic receptors in skeletal muscle. They do not cause muscle fasciculations, and their effects can be reversed by cholinesterase inhibitors or [Sugammadex](#/sugammadex) .\n"
+ "* [Succinylcholine](#/succinylcholine) is a depolarizing neuromuscular blocking agent with a short duration of action. It produces muscle fasciculations that are followed by muscle paralysis. Its effects are not reversed by cholinesterase inhibitors.\n"
+ "\n"
;
var script = document.querySelector('script[src="cho_at.js"]');
var section = document.createElement('section');
script.parentNode.appendChild(section);
section.appendChild(document.createTextNode(markdownContent));
[].forEach.call(script.attributes, function (attr) {
    section.setAttribute(attr.name, script.getAttribute(attr.name));
});
section.setAttribute('data-markdown', '');
})();
