(function () {
'strict'
var markdownContent = ''
+ "<hr>\n"
+ "\n"
+ "## AI for LifeScience Researchers: A 2025 Snapshot\n"
+ "\n"
+ "# Navigating Literature, PDFs, and Hypotheses with Emerging AI Tools\n"
+ "\n"
+ "<hr>\n"
+ "\n"
+ "### Hao Chen, Ph.D\n"
+ "\n"
+ "### hchen@uthsc.edu\n"
+ "\n"
+ "#### Department of Pharmacology, Addiction Science and Toxicology\n"
+ "\n"
+ "#### University of Tennessee Health Science Center, Memphis, TN, USA\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Are LLMs Finally Getting Citations Right?\n"
+ "\n"
+ "- **The Test:** I asked Gemini 2.5 Pro to pick a suitable research area and generate a literature review prompt.\n"
+ "\n"
+ "  - My additions: make it ~500 words and include PMIDs.\n"
+ "\n"
+ "- **The Contenders:**\n"
+ "\n"
+ "  - Gemini Pro 2.5 (with and without Deep Research)\n"
+ "  - OpenAI GPT-5\n"
+ "  - Claude Sonnet 4.5 (with and without the PubMed connector)\n"
+ "\n"
+ "- **The Question:** How relevant are the PMIDs they generate?\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Need a Tool to Help with the Evaluation\n"
+ "\n"
+ "- Expressing intent is sufficient for some coding tasks:\n"
+ "  - I want to hover over a PMID in a block of text and instantly see the paper's title, authors, and abstract.\n"
+ "  - I want it all in a single, shareable HTML file.\n"
+ "- Getting the Code: Many LLMs can help\n"
+ "  - Gemini CLI\n"
+ "  - Claude Code\n"
+ "  - OpenAI Codex\n"
+ "- Iterating and Refining\n"
+ "  - <a href=\"https://chen42.github.io/SourceCery/\" target=\"_new\"> SourceCery</a>\n"
+ "  - Adding a theme switcher, font size controls, a clear text button.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## The Prompt\n"
+ "\n"
+ "<p align=\"left\">\n"
+ "\n"
+ "Please act as an expert in behavioral neuroscience. Your task is to generate a comprehensive literature review on the animal models designed to operationalize 'addiction-like' behavior by identifying a sub-population of animals that exhibit compulsive drug seeking. The review must be structured around the translational framework that uses **DSM-like criteria** to distinguish this vulnerable subset from the general population of drug-using animals. Please structure your review using the following distinct sections:\n"
+ "\n"
+ "</p>\n"
+ "\n"
+ "<font size=\"1\">\n"
+ "\n"
+ "- **Introduction: The Translational Gap**\n"
+ "\n"
+ "  - Explain the limitations of standard drug self-administration models (e.g., fixed-ratio schedules) in modeling the full spectrum of human addiction.\n"
+ "  - Introduce the conceptual shift toward modeling the _transition_ to compulsion rather than just drug reinforcement.\n"
+ "\n"
+ "- **Defining the 'Addiction-Like' Phenotype: The Three-Criteria Model**\n"
+ "\n"
+ "  - Detail the **three core behavioral criteria** (often associated with the Deroche-Gamonet, Belin, and Piazza labs) used to identify this phenotype.\n"
+ "  - You must specifically define and explain how each is measured:\n"
+ "    - **High Motivation:** (e.g., progressive-ratio schedules).\n"
+ "    - **Continued Seeking Despite No-Drug Periods:** (e.g., resistance to extinction).\n"
+ "    - **Compulsive Seeking:** (e.g., resistance to punishment, such as a footshock contingency).\n"
+ "\n"
+ "- **Key Neurobiological Findings in the 'Addicted' Subset**\n"
+ "\n"
+ "  - Summarize the primary neuroadaptations that have been consistently shown to differentiate this 'addiction-like' cohort from their 'non-addicted' counterparts.\n"
+ "  - Focus on key findings in **prefrontal-striatal circuits** (e.g., changes in the dorsal striatum, hypofrontality).\n"
+ "\n"
+ "- **Significance and Limitations**\n"
+ "  - Conclude by summarizing the major contribution of this model to understanding the neurobiology of vulnerability versus resilience to addiction.\n"
+ "  - Briefly mention any common critiques or limitations of this approach.\"\n"
+ "\n"
+ "</font>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Gemini 2.5 Pro\n"
+ "\n"
+ "#### (Released June 17, 2025)\n"
+ "\n"
+ "<table> <tr> <td width=\"40%\"> <img src=\"./images/ctc2025/2025-10-22-gemini.png\"></td><td>\n"
+ "\n"
+ "- **Without Deep Research:**\n"
+ "  - Cited only four papers, and just one was marginally relevant.\n"
+ "- **With Deep Research:**\n"
+ "  - Produced a much longer report, pulling from about 50 websites and citing 20 web-based papers.\n"
+ "  - When asked to convert links to PMIDs, most citations pointed to just one or two papers, and some PMIDs were irrelevant.\n"
+ "- AI Studio (Grounded with Google Search):\n"
+ "  - Results were similar to Deep Research, linking to webpages, converted PMIDs had the same issues.\n"
+ "\n"
+ "</td></tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## GPT-5\n"
+ "\n"
+ "#### (Released Aug 7, 2025)\n"
+ "\n"
+ "<table> <tr> <td width=\"40%\"> <img src=\"./images/ctc2025/2025-10-22-chatgpt.png\"></td><td>\n"
+ "\n"
+ "- Cited about 10 papers, all of which were relevant.\n"
+ "- The content was somewhat superficial.\n"
+ "\n"
+ "</td></tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Claude Sonnet 4.5\n"
+ "\n"
+ "#### (Released Sept 29, 2025)\n"
+ "\n"
+ "<table> <tr> <td width=\"40%\"> <img src=\"./images/ctc2025/2025-10-22-claude.png\"></td><td>\n"
+ "\n"
+ "- **Default Chat:**\n"
+ "  - <a href=\"https://claude.ai/share/4c7eb3a1-cc97-48df-bc7f-1d24468f8cf1\"  target=\"_new\">The citations were entirely fabricated.</a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## <a href=\"https://www.anthropic.com/news/claude-for-life-sciences\" target=\"_new\">Claude for Life Sciences</a>\n"
+ "\n"
+ "#### (Released Oct 20, 2025)\n"
+ "\n"
+ "<table> <tr> <td width=\"40%\"> <img src=\"./images/ctc2025/2025-10-22-claude-pubmed-connector.png\"></td><td>\n"
+ "\n"
+ "- **With PubMed Connector ($17/mo for a pro account):**\n"
+ "\n"
+ "  - <a href=\"https://claude.ai/public/artifacts/a19a6257-e67a-4375-838c-d35f058a0081\"  target=\"_new\"> Citations were mostly relevant, and covered detailed findings quite well.</a>\n"
+ "  - Still included a few irrelevant citations.\n"
+ "\n"
+ "    </td></tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## LLMs with <font color=\"firebrick\"> tool integration </font> are improving at generating trustworthy literature summaries, but validation remains essential.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Chatting with Your PDFs\n"
+ "\n"
+ "- LLM for your PDFs (or links, videos)\n"
+ "\n"
+ "  - <a href=\"https://notebooklm.google.com\" target=\"_new\">NotebookLM</a>\n"
+ "\n"
+ "- **Potential Use Cases:**\n"
+ "\n"
+ "  - Reading complicated papers\n"
+ "  - Navigating Unfamiliar Domains\n"
+ "\n"
+ "    - <a href=\"https://www.congress.gov/bill/119th-congress/house-bill/27/text\" target=\"_new\">H.R. 27 HALT Fentanyl Act</a>\n"
+ "      - <a href=\"https://notebooklm.google.com/notebook/a2872f10-6ec1-4e15-935c-a18de326087c?authuser=1\"  target=\"_new\">How does this bill affect university researcher studying SUD using controlled substances? </a>\n"
+ "\n"
+ "  - **A Better Teaching Assistant:** Helping students digest dense material.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Hypothesis Generation\n"
+ "\n"
+ "### Found a great QTL, but there are 10 genes under the peak. Need to read all the literature about these genes to generate a hypothesis about the causal gene.\n"
+ "\n"
+ "- Search PubMed\n"
+ "  - Think about a complete list of keywords related to the phenotypes.\n"
+ "  - Search each gene against each of these keywords.\n"
+ "  - Read the abstracts.\n"
+ "  - Take notes on what is relevant.\n"
+ "  - Synthesize the knowledge\n"
+ "  - <a href=\"https://genecup.org\" target=\"_new\">https://genecup.org </a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Hypothesis Prompt Structure\n"
+ "\n"
+ "<table> <tr> <td width=\"30%\"> <img src=\"./images/ctc2025/2025-10-22-genecup-llm.png\"></td><td>\n"
+ "\n"
+ "- Research Context\n"
+ "- Goal\n"
+ "- Required Analysis:\n"
+ "\n"
+ "  - A. Term Disambiguation\n"
+ "    - MADD = MAP kinase-activating death domain protein ? Mothers against drunk driving\n"
+ "  - B. Synthesis of Function and Experimental Context\n"
+ "  - C. Critical Evaluation of Causal Gene Plausibility (with In-text Citations)\n"
+ "    - Assessment of Functional Plausibility\n"
+ "    - Assessment of Tissue/Cell Type Relevance\n"
+ "    - Assessment of Pathway and Network Involvement\n"
+ "    - Assessment of Existing Disease/Trait Associations:\n"
+ "  - D. Balanced Concluding Assessment\n"
+ "\n"
+ "    </td></tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Using Commandline tools to process large texts\n"
+ "\n"
+ "<table> <tr> <td width=\"50%\"> <img src=\"./images/ctc2025/2025-10-22-gemini_cli1.png\"></td><td>\n"
+ "\n"
+ "<img src=\"./images/ctc2025/2025-10-22-gemini_cli2.png\"></td></tr>\n"
+ "\n"
+ "</table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Hypothesis Evaluation Results\n"
+ "\n"
+ "### <a href=\"https://docs.google.com/document/d/1c46UYfp3DVfnEMBhSNb_QWXyWP7SQktOTq0QZZGAoPA/edit?usp=sharing\"  target=\"_new\"> Full report</a>\n"
+ "\n"
+ "Reduced 99 pages of relevant sentences into 2.5 pages of structured summary, with likely valid citations.\n"
+ "\n"
+ "**Summary of Supporting Evidence:**\n"
+ "\n"
+ "The evidence supporting CACNA1C as a plausible causal gene for socially acquired nicotine intravenous self-administration is **substantial**. The strongest lines of evidence are: **1.** Its critical role in reward processing, learning, and memory, which are core components of addiction (PMID: 25290268, 28604818). **2.** Its expression and function in key brain regions of the reward pathway, such as the nucleus accumbens (PMID: 28165117). **3.** Its position as a hub gene in addiction-related molecular networks (PMID: 36744178, 36865068). **4**. Existing genetic associations with nicotine dependence and other substance use disorders in humans (PMID: 25555482, 36551763).\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Acknowledgement\n"
+ "\n"
+ "- Hakan Guntunken\n"
+ "- Jun Huang\n"
+ "- Pjotr Prins\n"
;
var script = document.querySelector('script[src="ctc2025.js"]');
var section = document.createElement('section');
script.parentNode.appendChild(section);
section.appendChild(document.createTextNode(markdownContent));
[].forEach.call(script.attributes, function (attr) {
    section.setAttribute(attr.name, script.getAttribute(attr.name));
});
section.setAttribute('data-markdown', '');
})();
