(function () {
'strict'
var markdownContent = ''
+ "## GWAS on socially acquired nicotine IVSA in heterogeneous stock rats highlights genes implicated in human smoking behavior\n"
+ "\n"
+ "\n"
+ "<hr color=orange>\n"
+ "\n"
+ "\n"
+ "Tengfei Wang<sup>1</sup>, Apurva S. Chitre<sup>2</sup>, Angel Garcia Martinez<sup>1</sup>, Oksana Polesskaya<sup>2</sup>, Leah C. Solberg-Woods<sup>3</sup>, Changhoon Jee<sup>1</sup>, Abraham A. Palmer<sup>2</sup>, Hao Chen<sup>1</sup>\n"
+ "\n"
+ "\n"
+ "<sup>1</sup>Department of Pharmacology, Addiction Science and Toxicology, University of Tennessee Health Science Center; <sup>2</sup>Department of Psychiatry, University of California San Diego; <sup>3</sup>Department of Molecular Medicine, Wake Forest School of Medicine\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Both genetic and social factors contributes to cigarette smoking \n"
+ "\n"
+ "* Many tween studies have found genetic factors contributes to about 50% of the variance in smoking behavior.\n"
+ "* Human GWAS has identified hundreds of genome-wide significant SNPs associated with smoking behavior but most of them with unknown functional significance.\n"
+ "* When teenagers are asked why they smoke cigarettes, \"Because my friends are smoking\" is the most common answer\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Social learning enables nicotine self-administration\n"
+ "\n"
+ "\n"
+ "<img height:auto width=90% src=\"images/socially_acquired_nicotine_ivsa.png\">\n"
+ "\n"
+ "[Chen et al, 2011 Neuropsychopharm](https://pubmed.ncbi.nlm.nih.gov/21796102)\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Social learning supports nicotine IVSA with an aversive cue\n"
+ "\n"
+ "<img width=40% src=\"images/quinine/pres.sacc_quinine.png\">\n"
+ "\n"
+ "\n"
+ "[Wang, et al. Psychopharmacology 2016](https://pubmed.ncbi.nlm.nih.gov/26911379)\n"
+ "\n"
+ "\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Socially acquired nicotine IVSA is hertiable\n"
+ "\n"
+ "<img src=\"https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5556091/bin/41598_2017_8291_Fig3_HTML.jpg\">\n"
+ "\n"
+ "[Han, et al, Sci Rep, 2017](https://pubmed.ncbi.nlm.nih.gov/28808247/)\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Both CS<sub>2</sub> and flavor cue are necessary for socially acquired nicotine IVSA \n"
+ "\n"
+ "<img width=100% height=\"auto\" src=\"images/p50/cs2_1rat.png\">\n"
+ "\n"
+ "[Wang, et al. PLoS One, 2014](https://pubmed.ncbi.nlm.nih.gov/25532105/)\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## GWAS behavior test pipeline \n"
+ "<font size=3>\n"
+ "\n"
+ "| Age | Test |\n"
+ "|---|---|\n"
+ "|PND21|Wean|\n"
+ "|PND31|Open field |\n"
+ "|PND32|Novel object |\n"
+ "|PND33|Social interaction in the same arena as openfield |\n"
+ "|PND34|Elevated plus maze|\n"
+ "|PND38|Surgery|\n"
+ "|PND39 - 41| Recovery|\n"
+ "|PND42 - 51|Socially acquired nicotine IVSA|\n"
+ "|PND52| Progressive ratio test |\n"
+ "|PND53 - 56 |Extinction|\n"
+ "|PND57|Contextual cue induced reinstatement|\n"
+ "|PND59|Tissue Collection|\n"
+ "\n"
+ "</font>\n"
+ "\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Socially acquired nicotine IVSA \n"
+ "\n"
+ "Adolescent heterogeneous rats (711 F, 711 M)\n"
+ "\n"
+ "<img width=75% height=\"auto\" src=\"images/gwasv3/nicotine_fr10_phaseone_all_data.png\">\n"
+ "\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## GWAS summary\n"
+ "\n"
+ "|Behavior | Sample size | N traits | N sig. QTL| \n"
+ "|---|---|---:|---:|\n"
+ "| socially acquired nicotine IVSA| 711 M, 711 F| 63| 30| \n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Number of licks on the active spout in first session: chr1:278524299\n"
+ "\n"
+ "<img src=\"./images/gwasv3/locuszoom_day1_active_licks.png\" width=60%>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Summary of nicotine GWAS\n"
+ "\n"
+ "## Number of licks on the active spout\n"
+ "\n"
+ "|ID |Session|Loc| Genes (n) | Overlapping with human smoking GWAS|\n"
+ "|---|:---:|---|---|---|\n"
+ "|12.20 | day 1 | chr1:278524299| 99 | Gpam&clubs;&diams;, [Vti1a](http://rats.pub/cytoscape/?rnd=tmpUpzbbT&genequery=VTI1A)<font color=\"darkslateblue\">&spades;</font>, Nhlrc2&clubs;&diams;, Adrb1&clubs;, Tcf7l2, [Hspa12a](http://rats.pub/cytoscape/?rnd=tmpFrhLrJ&genequery=HEAT-SHOCK-PROTEIN-FAMILY-A-HSP70-MEMBER-12A_HSPA12A)<font color=\"darkslateblue\">&spades;</font>, [Shtn1](http://rats.pub/cytoscape/?rnd=tmpJiHXFf&genequery=KIAA1598_SHOOTIN-1_SHOOTIN1_SHTN1)<font color=\"darkslateblue\">&spades;</font>&diams;, [Nrap](http://rats.pub/cytoscape/?rnd=tmpaUzTZp&genequery=N-RAP_NEBULIN-RELATED-ANCHORING-PROTEIN_NRAP)<font color=\"darkslateblue\">&spades;</font>, Casp7&diams; Gfra1|\n"
+ "|12.29 | day 2 | chr8:22496077| 29| [Carm1](http://rats.pub/cytoscape/?rnd=tmpaHVoNJ&genequery=carm1) |\n"
+ "|12.24 | day 4 | chr4:145377793| 20| [Emc3](http://rats.pub/cytoscape/?rnd=tmpQXgUzk&genequery=emc3) |\n"
+ "|12.12 | day 5 | chr16:83955432| 23| Tex29| \n"
+ "|12.08 | day 7 | chr16:83489214| 23| Tex29| \n"
+ "|12.02 | day 9 | chr10:32845925| 90| | \n"
+ "|12.22 | day 10 | chr2:247766389|20| [Pkn2, Gtf2b](http://rats.pub/cytoscape/?rnd=tmpPoBkQf&genequery=Pkn2_Gtf2b) |\n"
+ "|12.16 | Reinstatment | chr1:161226950| 28|Usp35, Gab2, Nars2, Tenm4, [Alg8](http://rats.pub/cytoscape/?rnd=tmpJKLgcJ&genequery=Usp35_Gab2_Nars2_Tenm4_Alg8)&diams;&hearts; |\n"
+ "\n"
+ "\n"
+ "<font color=\"darkslateblue\">&spades;</font>: smoking initiation genes\n"
+ "&clubs;: Alcohol consumption genes\n"
+ "&diams;: cis-eQTL\n"
+ "&hearts; missense variants\n"
+ "\n"
+ "\n"
+ " \n"
+ "---\n"
+ "\n"
+ "\n"
+ "#### Summary of nicotine GWAS\n"
+ "\n"
+ "## Number of nicotine infusions\n"
+ "\n"
+ "|ID |Session|Loc| Genes (n) | Overlapping with human smoking GWAS|\n"
+ "|---|:---:|---|---|---|\n"
+ "|12.09 | day 5 | chr16:83500180| 23| Tex29 |\n"
+ "|12.13 | day 5 | chr17:17103044| 1| [ID4](http://rats.pub/cytoscape/?rnd=tmpdaIxug&genequery=ID4) |\n"
+ "|12.11 | day 7 | chr16:83500180| 23| Tex29|\n"
+ "|12.23 | day 7 | chr3:104723116| 8|[Hmgn4, Fmn1](http://rats.pub/cytoscape/?rnd=tmpSBamBX&genequery=Hmgn4_Fmn1) |\n"
+ "|12.15 | day 8 | chr19:26396258| 1| |\n"
+ "|12.03 | median of last 3 days | chr11:17834164|27| | \n"
+ "|12.10 |total infusion | chr16:83500180| 23| [Tex29](http://rats.pub/cytoscape/?rnd=tmpesQlMB&genequery=tex29)|\n"
+ "|12.30 |slope of regression | chr8:4459578| 74| [Gria4](http://rats.pub/cytoscape/?rnd=tmpAjmeXn&genequery=Gria4_Pdgfd_Mmp12)&diams;, Pdgfd&diams;, Mmp12 |\n"
+ "\n"
+ "&diams;: cis-eQTL\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Cross species validation in c.elegans \n"
+ "\n"
+ "### conditioned cue preference (CCP)\n"
+ "\n"
+ "<div id=\"left50\">\n"
+ "\n"
+ "<img src=\"./images/nicotine_ccp_illustration.png\">\n"
+ "\n"
+ "<center>\n"
+ "<h2>SI= (A-B)/(A+B+E)</h2>\n"
+ "</center>\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "<div id=\"right50\">\n"
+ "<img src=\"./images/nicotine_ccp.png\">\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Loss of function of Gria4 impairs nicotine CCP in c.elegans  \n"
+ "\n"
+ "<table>\n"
+ "<tr>\n"
+ "<td> <img src=\"./images/gria4_wildtype.png\"> </td>\n"
+ "<td> <img src=\"./images/gria4_mutant.png\"> </td> \n"
+ "<td> <img src=\"./images/gria4_control.png\"> </td>\n"
+ "</tr>\n"
+ "<table>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Acknowledgements\n"
+ "\n"
+ "* Hao Chen lab\n"
+ "	* 	prior members: Wenyan Han, Pawandeep Kaur, Yanyan Lin, \n"
+ "	* 	current memebers: Angel Garcia Martinez, Shuanying Leng, Hakan Gunturkun\n"
+ "\n"
+ "* Abraham Palmer lab: \n"
+ "	* Apurva Chitre and Oksana Polesskaya and many others\n"
+ "\n"
+ "* Leah C. Solberg-Woods lab \n"
+ "\n"
+ "* Changhong Jee Lab \n"
+ "	* Aziz Eshov\n"
+ "\n"
+ "Funding: NIDA P50DA037844\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Nicotine metabolism\n"
+ "\n"
+ "<img width=60% height=\"auto\" src=\"images/p50/AllCotinine_NicotineHSRats.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Correlation among behavioral measures \n"
+ "\n"
+ "open field, novel object, social interaction, and elevated plus maze\n"
+ "\n"
+ "<img src=\"./images/p50/retreat2018/behav_cor_r_p.png\" width=60% class=\"plain\">\n"
+ "\n"
+ "<p>\n"
+ "<hr align=\"right\" width=15%>\n"
+ "<p align=right>\n"
+ "<cite> <a href=\"https://pubmed.ncbi.nlm.nih.gov/30584246/\">PMID: 30584246</a> </cite>\n"
+ "</p>\n"
+ "\n"
+ "\n"
;
var script = document.querySelector('script[src="ctc_wang.js"]');
var section = document.createElement('section');
script.parentNode.appendChild(section);
section.appendChild(document.createTextNode(markdownContent));
[].forEach.call(script.attributes, function (attr) {
    section.setAttribute(attr.name, script.getAttribute(attr.name));
});
section.setAttribute('data-markdown', '');
})();
