(function () {
'strict'
var markdownContent = ''
+ "## GWAS on socially acquired nicotine IVSA in heterogeneous stock rats highlights genes implicated in human smoking behavior\n"
+ "\n"
+ "\n"
+ "<hr color=orange>\n"
+ "\n"
+ "\n"
+ "Tengfei Wang<sup>1</sup>, Apurva S. Chitre<sup>2</sup>, Angel Garcia Martinez<sup>1</sup>, Oksana Polesskaya<sup>2</sup>, Leah C. Solberg-Woods<sup>3</sup>, Changhoon Jee<sup>1</sup>, Abraham A. Palmer<sup>2</sup>, Hao Chen<sup>1</sup>\n"
+ "\n"
+ "\n"
+ "<sup>1</sup>Department of Pharmacology, Addiction Science and Toxicology, University of Tennessee Health Science Center; <sup>2</sup>Department of Psychiatry, University of California San Diego; <sup>3</sup>Department of Molecular Medicine, Wake Forest School of Medicine\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Both genetic and social factors contributes to cigarette smoking \n"
+ "\n"
+ "* Many tween studies have found genetic factors contributes to about 50% of the variance in smoking behavior.\n"
+ "* Human GWAS has identified hundreds of genome-wide significant SNPs associated with smoking behavior but most of them with unknown functional significance.\n"
+ "* When teenagers are asked why they smoke cigarettes, \"Because my friends are smoking\" is the most common answer\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Social learning enables nicotine self-administration\n"
+ "\n"
+ "\n"
+ "<img height:auto width=90% src=\"images/socially_acquired_nicotine_ivsa.png\">\n"
+ "\n"
+ "[Chen et al, 2011 Neuropsychopharm](https://pubmed.ncbi.nlm.nih.gov/21796102)\n"
+ "\n"
+ "Note:\n"
+ "We established a rat model of nicotine intravenous self-administration in adolescent rats that requires social learning between two rats. In this model, the self-administration rat licks on the active spout to trigger the simultaneous delivery of an oral flavor cue and i.v. nicotine.  A single rat tested using this paradigm develops nicotine conditioned flavor aversion but the presence of a \"demonstrator\" rat consuming the same flavor cue enables the establishment of operant nicotine intravenous self-administration. This procedure does not require water or food deprivation. Therefore it is appropriate for studying smoking initiation in adolescents. \n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Social learning supports nicotine IVSA with an aversive cue\n"
+ "\n"
+ "<img width=40% src=\"images/quinine/pres.sacc_quinine.png\">\n"
+ "\n"
+ "\n"
+ "[Wang, et al. Psychopharmacology 2016](https://pubmed.ncbi.nlm.nih.gov/26911379)\n"
+ "\n"
+ "\n"
+ "Note:\n"
+ "\n"
+ "We further reported that subjective value of the flavor cue does not affect nicotine intake. Here the two upper lines are the number of licks on the active spout and the two lower lines are the number of nicotine infusions. Rats shown with the blue lines were given a sweet saccharine cue and the red lines were given a bitter quinine cue. Although rats received the saccharine cue licked more than those received the quinine cue but the number of infusions are almost identical. The difference in lick count can be attributed to continued licking during the timeout period after iv nicotine was delivered. This and several other lines of evidence demonstrated that nicotine intake in this model is driven by the reinforcing effect of nicotine and not by the subjective value of the oral cue.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Socially acquired nicotine IVSA is hertiable\n"
+ "\n"
+ "<img src=\"https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5556091/bin/41598_2017_8291_Fig3_HTML.jpg\">\n"
+ "\n"
+ "[Han, et al, Sci Rep, 2017](https://pubmed.ncbi.nlm.nih.gov/28808247/)\n"
+ "\n"
+ "Note:\n"
+ "\n"
+ "Using 12 isogenic strains of rats, we confirmed that nicotine intake obtained in our model is heritable, with  h<sup>2</sup> in the range of 0.54-0.65. When we tested these rats using two different doses of nicotine, most of the strains adjusted their licking behavior to maintain the same level of nicotine intake. This dose responses  further confirmed that active licking was primarily motivated by nicotine.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Both CS<sub>2</sub> and flavor cue are necessary for socially acquired nicotine IVSA \n"
+ "\n"
+ "<img width=100% height=\"auto\" src=\"images/p50/cs2_1rat.png\">\n"
+ "\n"
+ "[Wang, et al. PLoS One, 2014](https://pubmed.ncbi.nlm.nih.gov/25532105/)\n"
+ "\n"
+ "Note:\n"
+ "Lastly, we identified that carbon disulfide, a chemical contained in the breach of rats, is a mediator for this effect, and were able to replace the demonstrator rat by adding carbon disulfite into the flavor cue for nicotine. \n"
+ "\n"
+ "---\n"
+ "\n"
+ "## GWAS behavior test pipeline \n"
+ "<font size=3>\n"
+ "\n"
+ "| Age | Test |\n"
+ "|---|---|\n"
+ "|PND21|Wean|\n"
+ "|PND31|Open field |\n"
+ "|PND32|Novel object |\n"
+ "|PND33|Social interaction in the same arena as openfield |\n"
+ "|PND34|Elevated plus maze|\n"
+ "|PND38|Surgery|\n"
+ "|PND39 - 41| Recovery|\n"
+ "|PND42 - 51|Socially acquired nicotine IVSA|\n"
+ "|PND52| Progressive ratio test |\n"
+ "|PND53 - 56 |Extinction|\n"
+ "|PND57|Contextual cue induced reinstatement|\n"
+ "|PND59|Tissue Collection|\n"
+ "\n"
+ "</font>\n"
+ "\n"
+ "\n"
+ "Note: \n"
+ "As part of the P50 that Dr. Palmer introduced on Wed, we conducted a GWAS using about 1,600 adolesecent HS rats. We first put these rats through several behavioral tests. Hakan from our lab will discuss the results of these GWAS immediately following my presentation. The nicotine self-administration procedure includes 10 days of fixed ratio, followed by one session of progressive ratio, extinction and cue induced reinstatement of drug seeking. We collected the spleens and brains at the end and transferred the data to Dr. Palmer's group for genotyping and GWAS.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Socially acquired nicotine IVSA \n"
+ "\n"
+ "Adolescent heterogeneous rats (711 F, 711 M)\n"
+ "\n"
+ "<img width=75% height=\"auto\" src=\"images/gwasv3/nicotine_fr10_phaseone_all_data.png\">\n"
+ "\n"
+ "\n"
+ "Note:\n"
+ "There is a large variation in nicotine behavior in the HS population. We did a median split procedure and found about half of the rats showed a preference for the active spout and half of them avoided the active spout. This large phenotypical variation is what we expect. \n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## GWAS summary\n"
+ "\n"
+ "|Behavior | Sample size | N traits | N sig. QTL| \n"
+ "|---|---|---:|---:|\n"
+ "| socially acquired nicotine IVSA| 711 M, 711 F| 63| 30| \n"
+ "\n"
+ "Note:\n"
+ "\n"
+ "We analyzed 63 nicotine traits and about half of them have a significant QLT\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Number of licks on the active spout in first session: chr1:278524299\n"
+ "\n"
+ "<img src=\"./images/gwasv3/locuszoom_day1_active_licks.png\" width=60%>\n"
+ "\n"
+ "\n"
+ "Note:\n"
+ "\n"
+ "Here is an example of a locus zoom plot. Some of the QTL regions have only one gene but most regions have a lot of genes.\n"
+ "The QLT region is 6.9 Mbp and has 39 known genes. Four genes has missense variants, two genes has cis-eQTL.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Summary of nicotine GWAS\n"
+ "\n"
+ "## Number of licks on the active spout\n"
+ "\n"
+ "|ID |Session|Loc| Genes (n) | Overlapping with human smoking GWAS|\n"
+ "|---|:---:|---|---|---|\n"
+ "|12.20 | day 1 | chr1:278524299| 99 | Gpam&clubs;&diams;, [Vti1a](http://rats.pub/cytoscape/?rnd=tmpUpzbbT&genequery=VTI1A)<font color=\"darkslateblue\">&spades;</font>, Nhlrc2&clubs;&diams;, Adrb1&clubs;, Tcf7l2, [Hspa12a](http://rats.pub/cytoscape/?rnd=tmpFrhLrJ&genequery=HEAT-SHOCK-PROTEIN-FAMILY-A-HSP70-MEMBER-12A_HSPA12A)<font color=\"darkslateblue\">&spades;</font>, [Shtn1](http://rats.pub/cytoscape/?rnd=tmpJiHXFf&genequery=KIAA1598_SHOOTIN-1_SHOOTIN1_SHTN1)<font color=\"darkslateblue\">&spades;</font>&diams;, [Nrap](http://rats.pub/cytoscape/?rnd=tmpaUzTZp&genequery=N-RAP_NEBULIN-RELATED-ANCHORING-PROTEIN_NRAP)<font color=\"darkslateblue\">&spades;</font>, Casp7&diams; Gfra1|\n"
+ "|12.29 | day 2 | chr8:22496077| 29| [Carm1](http://rats.pub/cytoscape/?rnd=tmpaHVoNJ&genequery=carm1) |\n"
+ "|12.24 | day 4 | chr4:145377793| 20| [Emc3](http://rats.pub/cytoscape/?rnd=tmpQXgUzk&genequery=emc3) |\n"
+ "|12.12 | day 5 | chr16:83955432| 23| Tex29| \n"
+ "|12.08 | day 7 | chr16:83489214| 23| Tex29| \n"
+ "|12.02 | day 9 | chr10:32845925| 90| | \n"
+ "|12.22 | day 10 | chr2:247766389|20| [Pkn2, Gtf2b](http://rats.pub/cytoscape/?rnd=tmpPoBkQf&genequery=Pkn2_Gtf2b) |\n"
+ "|12.16 | Reinstatment | chr1:161226950| 28|Usp35, Gab2, Nars2, Tenm4, [Alg8](http://rats.pub/cytoscape/?rnd=tmpJKLgcJ&genequery=Usp35_Gab2_Nars2_Tenm4_Alg8)&diams;&hearts; |\n"
+ "\n"
+ "\n"
+ "<font color=\"darkslateblue\">&spades;</font>: smoking initiation genes\n"
+ "&clubs;: Alcohol consumption genes\n"
+ "&diams;: cis-eQTL\n"
+ "&hearts; missense variants\n"
+ "\n"
+ "Note:\n"
+ "In fact, the previous region I just showed you is one of the most interesting regions because the it contains 10 genes that have been reported in human GWAS on smoking. In addition, many of these genes are associated with very similar phenotypes between rats and human. For example, vti1a, hspa12a, shtn1 and Nrap are all associated with smoking initiation in human, and our phenotype is number of licks during the first nicotine session.\n"
+ "\n"
+ "Also, a region on chromosome 16 is associated with number of active licks and nicotine infusion in sessions 5, and 7, and total nicotine infusion for the entire fixed ratio phase. \n"
+ " \n"
+ "---\n"
+ "\n"
+ "\n"
+ "#### Summary of nicotine GWAS\n"
+ "\n"
+ "## Number of nicotine infusions\n"
+ "\n"
+ "|ID |Session|Loc| Genes (n) | Overlapping with human smoking GWAS|\n"
+ "|---|:---:|---|---|---|\n"
+ "|12.09 | day 5 | chr16:83500180| 23| Tex29 |\n"
+ "|12.13 | day 5 | chr17:17103044| 1| [ID4](http://rats.pub/cytoscape/?rnd=tmpdaIxug&genequery=ID4) |\n"
+ "|12.11 | day 7 | chr16:83500180| 23| Tex29|\n"
+ "|12.23 | day 7 | chr3:104723116| 8|[Hmgn4, Fmn1](http://rats.pub/cytoscape/?rnd=tmpSBamBX&genequery=Hmgn4_Fmn1) |\n"
+ "|12.15 | day 8 | chr19:26396258| 1| |\n"
+ "|12.03 | median of last 3 days | chr11:17834164|27| | \n"
+ "|12.10 |total infusion | chr16:83500180| 23| [Tex29](http://rats.pub/cytoscape/?rnd=tmpesQlMB&genequery=tex29)|\n"
+ "|12.30 |slope of regression | chr8:4459578| 74| [Gria4](http://rats.pub/cytoscape/?rnd=tmpAjmeXn&genequery=Gria4_Pdgfd_Mmp12)&diams;, Pdgfd&diams;, Mmp12 |\n"
+ "\n"
+ "&diams;: cis-eQTL\n"
+ "\n"
+ "Note:\n"
+ "one gene located in this region, tex29, is associated with lifetime cigarette consumption in human. Also, Gria4, which encodes a subunit for the glutamate recepotr, is a candiate gene for the progression of nicotine intake in our study and was mapped to nicotine dependence in human. There are several clinical trials using antagonists for this receptor for alcohol and nicotine dependence. It is very exciting to have identified genes that mapped to the very similar phenotypes between human and rats.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Cross species validation in c.elegans \n"
+ "\n"
+ "### conditioned cue preference (CCP)\n"
+ "\n"
+ "<div id=\"left50\">\n"
+ "\n"
+ "<img src=\"./images/nicotine_ccp_illustration.png\">\n"
+ "\n"
+ "<center>\n"
+ "<h2>SI= (A-B)/(A+B+E)</h2>\n"
+ "</center>\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "<div id=\"right50\">\n"
+ "<img src=\"./images/nicotine_ccp.png\">\n"
+ "</div>\n"
+ "\n"
+ "\n"
+ "Note:\n"
+ "\n"
+ "However, we want to be able to validate the function of most of these candidates. It is possible to use genetic manipulations to create mutant rats but these methods are still labor intensive and expensive. We are lucky to have Dr. Jee in our department, who has established a model of nicotine-conditioned cue preference test in the worm c.elegans. This is very similar to the conditioned place preference test in rodents. In this method, worms are placed in a plate containing nicotine and a natural odor called Hexane for a few hours. Worms are then tested  for their preference for hexane in the absence of nicotine. Knockout animals showed that this preference depends on dopamine and nicotinic receptors.\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Loss of function of Gria4 impairs nicotine CCP in c.elegans  \n"
+ "\n"
+ "<table>\n"
+ "<tr>\n"
+ "<td> <img src=\"./images/gria4_wildtype.png\"> </td>\n"
+ "<td> <img src=\"./images/gria4_mutant.png\"> </td> \n"
+ "<td> <img src=\"./images/gria4_control.png\"> </td>\n"
+ "</tr>\n"
+ "<table>\n"
+ "\n"
+ "Note:\n"
+ "Using this model, we have confirmed that knocking out gria4 impairs conditioned cue preference in c.elegance. The left panel shows that conditioning for 4-8 hours in wild type animals are sufficient for establishing CCP, while CCP is abolished in gria4 knockouts under the same conditions. Lastly, using IAA, which is an attractant to worms, we show that gria4 null mutation does not affect their movement or detection of odor. \n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Acknowledgements\n"
+ "\n"
+ "* Hao Chen lab\n"
+ "	* 	prior members: Wenyan Han, Pawandeep Kaur, Yanyan Lin, \n"
+ "	* 	current memebers: Angel Garcia Martinez, Shuanying Leng, Hakan Gunturkun\n"
+ "\n"
+ "* Abraham Palmer lab: \n"
+ "	* Apurva Chitre and Oksana Polesskaya and many others\n"
+ "\n"
+ "* Leah C. Solberg-Woods lab \n"
+ "\n"
+ "* Changhong Jee Lab \n"
+ "	* Aziz Eshov\n"
+ "\n"
+ "Funding: NIDA P50DA037844\n"
+ "\n"
+ "Note:\n"
+ "Many people from our lab participated the collection and analysis of behavior data\n"
+ "Dr. Palmer's lab genotyped these rats and conducted the GWAS \n"
+ "Dr. SolbergWoods' lab provided us the HS breeders\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Nicotine metabolism\n"
+ "\n"
+ "<img width=60% height=\"auto\" src=\"images/p50/AllCotinine_NicotineHSRats.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Correlation among behavioral measures \n"
+ "\n"
+ "open field, novel object, social interaction, and elevated plus maze\n"
+ "\n"
+ "<img src=\"./images/p50/retreat2018/behav_cor_r_p.png\" width=60% class=\"plain\">\n"
+ "\n"
+ "<p>\n"
+ "<hr align=\"right\" width=15%>\n"
+ "<p align=right>\n"
+ "<cite> <a href=\"https://pubmed.ncbi.nlm.nih.gov/30584246/\">PMID: 30584246</a> </cite>\n"
+ "</p>\n"
+ "\n"
+ "\n"
;
var script = document.querySelector('script[src="ctc_wang.js"]');
var section = document.createElement('section');
script.parentNode.appendChild(section);
section.appendChild(document.createTextNode(markdownContent));
[].forEach.call(script.attributes, function (attr) {
    section.setAttribute(attr.name, script.getAttribute(attr.name));
});
section.setAttribute('data-markdown', '');
})();
