(function () {
'strict'
var markdownContent = ''
+ "## snRNA-seq of NAc\n"
+ "\n"
+ "<img src=\"images/fgf12/snRNAseq_Umap_msn.png\" width=70%>\n"
+ "\n"
+ "<div style=\"text-align: left;\">\n"
+ "  <hr style=\"border: 0; height: 2px; background-color: orange; width: 20%; margin-left: 0;\">\n"
+ "  <span id=\"cite\" style=\"display: block;\"> Y Zuo and F Telese, UCSD </span>\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Cell-type Specific Expression of Oprm1 and Fgf12 in NAc\n"
+ "\n"
+ "<img src=\"images/fgf12/snRNAseq_violion.png\" width=70%>\n"
+ "\n"
+ "<div style=\"text-align: left;\">\n"
+ "  <hr style=\"border: 0; height: 2px; background-color: orange; width: 20%; margin-left: 0;\">\n"
+ "  <span id=\"cite\" style=\"display: block;\"> Y Zuo and F Telese, UCSD </span>\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Cell-type Specific Correlation Between Oprm1 and Fgf12\n"
+ "\n"
+ "<img src=\"images/fgf12/snRNAseq_correlation.png\" width=70%>\n"
+ "\n"
+ "<div style=\"text-align: left;\">\n"
+ "  <hr style=\"border: 0; height: 2px; background-color: orange; width: 20%; margin-left: 0;\">\n"
+ "  <span id=\"cite\" style=\"display: block;\"> Y Zuo and F Telese, UCSD </span>\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Using Bayesian Networks to Infer Causal Architecture\n"
+ "\n"
+ "<font size =-1>\n"
+ "\n"
+ "- The Bayesian Network Webserver\n"
+ "  - Identifies **directed, causal relationships** in genetic, multi-omic and behavioral datasets\n"
+ "- Step 1: Local Scoring:\n"
+ "  - For every potential parent-child pair, calculates a local score based on the conditional probability P(B|A)\n"
+ "  - Uses Conditional Gaussian Distributions to allow discrete variables (e.g., Genotypes) to be the parents of continuous traits (e.g., Gene Expression)\n"
+ "- Step 2: Global Optimization:\n"
+ "  - Assembles these local \"parent-child\" blocks into the single most probable global map of the entire system\n"
+ "- Integrates prior knowledge by enforcing biological flow\n"
+ "  - e.g., Genotype -> Transcripts -> Phenotypes\n"
+ "\n"
+ "</font>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Bayesian Network Webserver\n"
+ "\n"
+ "<img src=\"./images/fgf12/fgf12_oprm1_morphine_locomotion_bayesian_network_settings.png\" width=60%>\n"
+ "\n"
+ "<div style=\"text-align: left;\">\n"
+ "  <hr style=\"border: 0; height: 2px; background-color: orange; width: 20%; margin-left: 0;\">\n"
+ "  <span id=\"cite\" style=\"display: block;\"> Y Cui, et al., UTHSC </span>\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Bayesian Network Analysis for Causality\n"
+ "\n"
+ "<img src=\"images/fgf12/BNW_network_inkscape_fixed.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## OPRM1 and FGF12 in Human Genetics Studies\n"
+ "\n"
+ "<a href=\"https://www.ebi.ac.uk/gwas/genes/OPRM1\">\n"
+ "<img src=\"./images/fgf12/oprm1_fgf12_gwas.png\" width=70%>\n"
+ "</a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Enrichment of OPRM1 and FGF12 Associated Genenework\n"
+ "\n"
+ "<font size=-2>\n"
+ "\n"
+ "- Generating correlation networks\n"
+ "  - Obtain top 500 genes correlated to OPRM1 or FGF12 from GTEx v8 from 8 related tissues\n"
+ "  - Find genes shared between OPRM1 and FGF12 within each tissue\n"
+ "  - Find genes shared between more than 3 tissues.\n"
+ "  - Use MAGMA to conduct enrichment analysis.\n"
+ "\n"
+ "</font>\n"
+ "\n"
+ "| VARIABLE              | NGENES | BETA    | BETA_STD | SE    | P     |\n"
+ "| --------------------- | ------ | ------- | -------- | ----- | ----- |\n"
+ "| OUD                   |        |         |          |       |       |\n"
+ "| Network               | 68     | 0.00197 | 0.00012  | 0.113 | 0.493 |\n"
+ "| Addiction Risk Factor |        |         |          |       |       |\n"
+ "| Network               | 68     | 0.21938 | 0.01348  | 0.124 | 0.039 |\n"
+ "\n"
+ "<div style=\"text-align: left;\">\n"
+ "  <hr style=\"border: 0; height: 2px; background-color: orange; width: 20%; margin-left: 0;\">\n"
+ "  <span id=\"cite\" style=\"display: block;\">A Hatoum, Wash U</span>\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Naloxone Responses\n"
+ "\n"
+ "<img src=\"images/fgf12/fig6_naloxone.png\" width=60%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Many More Loci!\n"
+ "\n"
+ "<img src=\"images/fgf12/list_of_loci.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## GeneCup Literature Mining\n"
+ "\n"
+ "<a href=\"https://genecup2.genenetwork.org/cytoscape/?rnd=tmpvWtwVP&genequery=Adora1_Rgs7_Sema3d_Epha5_Slc6a1_Tenm4_Oprm1_Ywhaq_Ppm1a_Rps6ka5_Slc7a7_Slc7a8\" target=_new>\n"
+ "\n"
+ "<img src=\"images/fgf12/genecup_graph.svg\" width=60%>\n"
+ "    </a>\n"
+ "\n"
+ "<div style=\"text-align: left;\">\n"
+ "  <hr style=\"border: 0; height: 2px; background-color: orange; width: 20%; margin-left: 0;\">\n"
+ "  <span id=\"cite\" style=\"display: block;\"> P Prins, et al., UTHSC </span>\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Structured LLM Literature Summary\n"
+ "\n"
+ "Evaluation of\n"
+ "<a href=\"https://genecup2.genenetwork.org/synonyms?node=Rgs7&rnd=\" target=_new> Rgs7 </a> as a Causal Gene for Morphine-Induced Locomotion in Mice.\n"
+ "\n"
+ "<font size=-1>\n"
+ "\n"
+ "- A. Term Disambiguation\n"
+ "- B. Synthesis of Function and Experimental Context\n"
+ "- C. Critical Evaluation of Causal Gene Plausibility\n"
+ "  - 1. Assessment of Functional Plausibility\n"
+ "  - 2. Assessment of Tissue/Cell Type Relevance\n"
+ "  - 3. Assessment of Pathway and Network Involvement\n"
+ "  - 4. Assessment of Existing Disease/Trait Associations\n"
+ "- D. Balanced Concluding Assessment\n"
+ "  - Supporting Evidence:\n"
+ "  - Limitations and Gaps:\n"
+ "  - Final Judgment:\n"
+ "- Results\n"
+ "  - <a href=\"https://gemini.google.com/share/55a1a9faa9d5\" target=_new> Gemini </a>\n"
+ "  - <a href=\"https://claude.ai/share/6fe1fa08-3c21-4fc0-b736-70b44fa2318b\" target=_new> Claude </a>\n"
+ "\n"
+ "</font>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Assisted Manual Validation of Citations\n"
+ "\n"
+ "<a href=\" https://chen42.github.io/SourceCery/ \" target=\\_new >\n"
+ "<img src=\"images/fgf12/sourcery.png\" width=70%>\n"
+ "</a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Summary\n"
+ "\n"
+ "<font size =-4>\n"
+ "\n"
+ "- Morphine-induced locomotion is governed by a dynamic timeline where _Oprm1_ (Chr 10) dominates the early phase, while the novel _Fgf12_ (Chr 16) locus controls the late phase.\n"
+ "\n"
+ "- A significant but transient gene-gene interaction between _Oprm1_ and _Fgf12_ occurs specifically between 45–90 minutes post-injection, representing a rare demonstration of time-dependent epistasis in mammals.\n"
+ "\n"
+ "- Single-nucleus RNA sequencing identified the D1-MSN-3 neuronal subtype in the Nucleus Accumbens as the likely site of this interaction, where both genes are co-expressed and positively correlated.\n"
+ "\n"
+ "- Bayesian modeling suggests the interaction is mediated through a MAP kinase network, specifically identifying Map3k11 as a potential molecular bridge between opioid receptor signaling and Fgf12.\n"
+ "\n"
+ "- Human GWAS data corroborates the importance of the _FGF12_ locus in substance use disorders, suggesting _Fgf12_ and its interaction with sodium channels as a novel therapeutic target for OUD.\n"
+ "\n"
+ "- This work highlights how FAIR data reanalysis and the merging of human and animal neurogenomic data can facilitate bidirectional translational validation to uncover novel disease variants and molecular networks.\n"
+ "\n"
+ "</font>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Acknowledgment\n"
+ "\n"
+ "<font size =-3>\n"
+ "\n"
+ "## Paige M Lemen, Yanning Zuo, Alexander S Hatoum, Price E Dickson, Guy Mittleman, Arpana Agrawal, Benjamin C Reiner, Wade Berrettini, David G Ashbrook, Mustafa Hakan Gunturkun, Xusheng Wang, Megan K Mulligan, Caleb J Browne, Eric J Nestler, Francesca Telese\n"
+ "\n"
+ "### University of Tennessee Health Science Center, Memphis; University of California San Diego, San Diego; Washington University in St. Louis, St Louis; Marshall University, Huntington; Ball State University, Muncie; University of Pennsylvania, Philadelphia; Nash Family Department of Neuroscience and Friedman Brain Institute, Icahn School of Medicine at Mount Sinai, New York\n"
+ "\n"
+ "</font>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Proteomic Data\n"
+ "\n"
+ "<img src=\"./images/fgf12/protein_fgf12_oprm1.png\" width=60%>\n"
+ "\n"
+ "<div style=\"text-align: left;\">\n"
+ "  <hr style=\"border: 0; height: 2px; background-color: orange; width: 20%; margin-left: 0;\">\n"
+ "  <span id=\"cite\" style=\"display: block;\"> X Wang, UTHSC </span>\n"
+ "</div>\n"
+ "\n"
+ "---\n"
;
var script = document.querySelector('script[src="fgf12.js"]');
var section = document.createElement('section');
script.parentNode.appendChild(section);
section.appendChild(document.createTextNode(markdownContent));
[].forEach.call(script.attributes, function (attr) {
    section.setAttribute(attr.name, script.getAttribute(attr.name));
});
section.setAttribute('data-markdown', '');
})();
