(function () {
'strict'
var markdownContent = ''
+ "## snRNA-seq of NAc\n"
+ "\n"
+ "<img src=\"images/fgf12/snRNAseq_Umap_msn.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## snRNA-seq of NAc\n"
+ "\n"
+ "<img src=\"images/fgf12/snRNAseq_violion.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## snRNA-seq of NAc\n"
+ "\n"
+ "<img src=\"images/fgf12/snRNAseq_correlation.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Bayesian Network Analysis for Causality\n"
+ "\n"
+ "<img src=\"images/fgf12/BNW_network_inkscape_fixed.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Signals in Human Genetics Studies\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Naloxone responses\n"
+ "\n"
+ "<img src=\"images/fgf12/fig6_naloxone.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Many other loci\n"
+ "\n"
+ "<img src=\"images/fgf12/list_of_loci.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## GeneCup Literature Mining\n"
+ "\n"
+ "<img src=\"images/fgf12/genecup_graph.svg\" width=60%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Structured LLM Literature Summary\n"
+ "\n"
+ "Scientific Evaluation of MAP3K5 as a Causal Gene for Morphine-Induced Locomotion in Mice.\n"
+ "\n"
+ "- A. Term Disambiguation\n"
+ "\n"
+ "- B. Synthesis of Function and Experimental Context\n"
+ "\n"
+ "- C. Critical Evaluation of Causal Gene Plausibility\n"
+ "\n"
+ "  - 1. Assessment of Functional Plausibility\n"
+ "\n"
+ "  - 2. Assessment of Tissue/Cell Type Relevance\n"
+ "\n"
+ "  - 3. Assessment of Pathway and Network Involvement\n"
+ "\n"
+ "  - 4. Assessment of Existing Disease/Trait Associations\n"
+ "\n"
+ "- D. Balanced Concluding Assessment\n"
+ "\n"
+ "  - Supporting Evidence:\n"
+ "\n"
+ "  - Limitations and Gaps:\n"
+ "\n"
+ "  - Final Judgment:\n"
+ "\n"
+ "Based on the provided information, MAP3K5 is a plausible candidate gene. It possesses the necessary regional expression and general signaling machinery to influence behavioral traits. However, it cannot be classified as a \"strong\" candidate without specific functional validation (e.g., knockout or knockdown studies) directly targeting morphine-induced locomotor phenotypes in mice.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Assisted Manual Validation of Citations\n"
+ "\n"
+ "<img src=\"images/fgf12/sourcery.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Summary\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Acknowledgment\n"
+ "\n"
+ "#### Paige M Lemen, Yanning Zuo, Alexander S Hatoum, Price E Dickson, Guy Mittleman, Arpana Agrawal, Benjamin C Reiner, Wade Berrettini, David G Ashbrook, Mustafa Hakan Gunturkun, Xusheng Wang, Megan K Mulligan, Caleb J Browne, Eric J Nestler, Francesca Telese\n"
;
var script = document.querySelector('script[src="fgf12.js"]');
var section = document.createElement('section');
script.parentNode.appendChild(section);
section.appendChild(document.createTextNode(markdownContent));
[].forEach.call(script.attributes, function (attr) {
    section.setAttribute(attr.name, script.getAttribute(attr.name));
});
section.setAttribute('data-markdown', '');
})();
