(function () {
'strict'
var markdownContent = ''
+ "# From Humans to Rats: Decoding the Genetic Bases of Opioid Use Disorder\n"
+ "\n"
+ "<hr color=orange>\n"
+ "\n"
+ "## Hao Chen, Ph.D.\n"
+ "#### Professor\n"
+ "\n"
+ "#### Department of Pharmacology, Addiction Science and Toxicology, University of Tennessee Health Science Center\n"
+ "\n"
+ "March 23, 2024\n"
+ "\n"
+ "---\n"
+ "## OUTLINE\n"
+ "\n"
+ "- Human genetic studies on OUD/OD\n"
+ "- Genetic studies on opioid driven behavior in rodents\n"
+ "    - Oral oxycodone self-administration in HRDP\n"
+ "    - Oral oxycodone self-administration in RCC\n"
+ "    - Acute locomotor response to morphine in BXD mice\n"
+ "\n"
+ "---\n"
+ "## Phenotypic variance \n"
+ "\n"
+ "<ul>\n"
+ "    <li > Genetic\n"
+ "        <ul class=\"fragment\"> \n"
+ "        <li > Additive: as the sum of the effect of each allele at all loci which influence the phenotype\n"
+ "        <li > Non-additive:  interaction between alleles\n"
+ "            <ul> <li > at the same locus (dominance) \n"
+ "                <li >  at different loci (epistasis)\n"
+ "           </ul>\n"
+ "       </ul>\n"
+ "<li > Environmental \n"
+ "<ul class=\"fragment\">\n"
+ "\n"
+ "<li > Shared, influence is common to members of a family (e.g., socioeconomic status)\n"
+ "<li > Unique, e.g., difference in parental treatment, prenatal environment, life events\n"
+ "\n"
+ "\n"
+ "</ul>\n"
+ "</ul>\n"
+ "\n"
+ "<p id=cite>\n"
+ "Mayhew, et al., Curr Genomics, 2017\n"
+ "</p>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Heritability\n"
+ "\n"
+ "\n"
+ "<ul>\n"
+ "    <li > The ratio of the genetic variation to the phenotypic variation. \n"
+ "    <li class=\"fragment\"> Narrow-sense (h2) vs Broad-sense (H2)\n"
+ "        <ul>\n"
+ "        <li> h2: the additive genetic component, the degree to which genes transmitted by parents determine the phenotype of their children.\n"
+ "        <li> H2: the ratio of total genetic variance divided by the total phenotypic variance, including gene x gene interactions and dominant effects\n"
+ "        </ul>\n"
+ "    <li class=\"fragment\"> Can be estimated using trait data alone\n"
+ "        <ul>\n"
+ "       <li>  Twins, adoptions, families, etc. \n"
+ "       <li>  Estimated in a variety of ways \n"
+ "       <ul>\n"
+ "        <li> 9 definitions of h2/H2 body mass index from 32 studies </li>\n"
+ "        </ul>\n"
+ "   </ul>\n"
+ "   </ul>\n"
+ "\n"
+ "<p id=cite>\n"
+ "Tenesa, et al., Nat Rev Genetics, 2013; Mayhew, et al., Curr Genomics, 2017\n"
+ "</p>\n"
+ "\n"
+ "---\n"
+ "## Heritability of substance use/dependence\n"
+ "\n"
+ "<img src=\"./images/oxycodone/heritability_oud_kendler.png\">\n"
+ "\n"
+ "<p id=cite>\n"
+ "Kendler, et al., Am J Psychiatry 2003</p>\n"
+ "\n"
+ "---\n"
+ "## Heritability of substance use/dependence\n"
+ "\n"
+ "<img src=\"./images/oxycodone/heritability_oud_tsuang.png\">\n"
+ "\n"
+ "<p id=cite> Tsuang, et al., JAMA Psychiatry</p>\n"
+ "\n"
+ "---\n"
+ "## Genotype-phenotype association\n"
+ "\n"
+ "<table> <tr><td>\n"
+ "<img src=\"./images/oxycodone/g_p_association.png\">\n"
+ "</td><td>\n"
+ "\n"
+ "* Association != Causation \n"
+ "    * Direct genetic effect\n"
+ "    * Indirect genetic effect \n"
+ "        * e.g., CHRNA5 and lung cancer \n"
+ "        \n"
+ "\n"
+ "<p id=cite> Young, et al., Science, 2019</p>\n"
+ "\n"
+ "</td></tr></table>\n"
+ "\n"
+ "---\n"
+ "## Genome-wide association study (GWAS)\n"
+ "\n"
+ "<b>Progression from opioid exposure (n=161) to opioid daily injection (n=1567)</b>\n"
+ "\n"
+ "<img src=\"./images/oxycodone/oud_gwas_cnih3.png\" width=70%>\n"
+ "\n"
+ " <b>CNIH3 encodes a glutamate receptor auxiliary protein that slows AMPA receptor deactivation.</b>\n"
+ "\n"
+ "\n"
+ "<p id=cite>Nelson, et al., Mol Psychiatry, 2016</p>\n"
+ "\n"
+ "Note: Our GWAS analyses compared the ODE group (N=1167 opioid dependent daily injectors) to a group characterized as having opioid use with impeded progression (OUIP) that combined non-dependent opioid misusers (N=88; 69.3% reporting heroin use) and opioid dependent individuals without a history of daily injection (N=73).\n"
+ "\n"
+ "---\n"
+ "## Multi trait analysis of GWAS \n"
+ "\n"
+ "<table><tr><td>\n"
+ "\n"
+ "<img src=\"./images/oxycodone/multi_trait_correlation.png\">\n"
+ "</td>\n"
+ "<td>\n"
+ "<img src=\"./images/oxycodone/multi_trait_OUD_manhattan.png\" >\n"
+ "</td></tr></table>\n"
+ "\n"
+ "<b>When GWAS estimates from different traits are correlated, the effect estimates for each trait can be improved by appropriately incorporating  information contained in the GWAS estimates for the other traits.\n"
+ "\n"
+ "n=5692 EUR & 4918 AFR (Yale-Penn sample) \n"
+ "n=29,054 EUR & 10,265 AFR (Penn Medicine BioBank sample). \n"
+ "\n"
+ "</b>\n"
+ "\n"
+ "<p id=cite>Xu, et al., Addiction, 2022</p>\n"
+ "\n"
+ "---\n"
+ "## Multi-ancestry meta analysis \n"
+ "\n"
+ "<img src=\"./images/oxycodone/multi_ancestry_oud_gwas.png\" width=80%>\n"
+ "\n"
+ "<b> OUD in the Million Veteran Program (N = 425,944)</b>\n"
+ "\n"
+ "<p id=cite>Kember, et al., Nat Neurosci, 2022</p>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Missing heritability \n"
+ "\n"
+ "* SNP heritability\n"
+ "* Missing heritability (the discrepancy between heritability estimates calculated using the classical designs and the amount of variance explained by known genetic variants)\n"
+ "    * sample size  \n"
+ "    * epistasis\n"
+ "    * genetic variant (SNP, Duplication, Insertion, Deletion, Inversion)\n"
+ "\n"
+ "<img src=\"./images/oxycodone/cnv_od.png\">\n"
+ "\n"
+ "n=5152\n"
+ "\n"
+ "<p id=cite> Li, et al., Neuropsychopharmacology, 2015</p>\n"
+ "\n"
+ "---\n"
+ "## Human OUD/OD GWAS Summary\n"
+ "\n"
+ "<img src=\"./images/oxycodone/OUD_OD_ontology_tree_GWAS_catalog.png\" width=100%>\n"
+ "\n"
+ "---\n"
+ "## Human OUD/OD GWAS Summary\n"
+ "<h4> 2023-03 </h4>\n"
+ "\n"
+ "<h4> 14 publications | 123 associations | 100 SNPs | 98 genes  </h3>\n"
+ "\n"
+ "\n"
+ "| Times reported | Genes | \n"
+ "| ---| ---|\n"
+ "| 13 | OPRM1 |\n"
+ "| 7 | ADGRV1 (G-protein coupled receptor superfamily, binds calcium)| \n"
+ "| 6 | FURIN (membrane bound protease) | \n"
+ "| 4 | CDKAL1, KCNN1, LINC00581 |\n"
+ "| 3 | DRD2, FBXW4, NCAM1, SEMA6D | \n"
+ "| 2 | BARHL2, GAPDHP15, KRT18P4, LINC01360, LINC02238, LINC02609, LINC02661, MIR548I2, PDE4B, PLCL2, RABEPK, RBBP4P4, RGMA, RNU6-147P, SEPHS1P2, SLC39A8, TMPRSS5, VPS51P18, YAE1-DT | \n"
+ "| 1 | ADH1B, APOC4-APOC2, ARHGAP15, ATP23, ATP6V0D1-DT, CADM2, CAMKMT, CAPZBP1, CLPTM1, CNIH3, CNOT4, CREB3L1, CTNND1, DPP4, ERC2, FOXP2, FTO, GBF1, GIHCG, GMEB1, GPRIN3, H3C9P, H4C8, HLA-DRA, HMGB3P19, HS6ST3, KDM4A, LINC01414, LINC01833, LINC01965, LINC02057, LINC02837, MAGI2, MCFD2P1, MIR548A1HG, MTMR2, NICN1, OR2H4P, OR2J4P, POR, POU6F2, PPP6C, RIPOR1, RN7SL423P, RNA5SP130, RNU11, RNU1-64P, RNU6-256P, RNU6-289P, RPL21P61, RPL36AP23, RUNX1T1, SMIM15-AS1, SNCA, SORL1, SRP72P1, TANK, TANK-AS1, TCF20, THAP12P5, TMEM120A, TSBP1-AS1, USP4, VN1R68P, VN1R69P, VRK2, ZNF184  | \n"
+ "\n"
+ "\n"
+ "---\n"
+ "## Pathway enrichment for OUD genes\n"
+ "\n"
+ "<img src=\"./images/oxycodone/gProfiler_hsapiens_2024-03-21_10-29-36.png\" width=70%>\n"
+ "\n"
+ "g:Profiler (https://biit.cs.ut.ee)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Human GWAS\n"
+ "<h4>\n"
+ "    Ancestry | Controls | Phenotype | Variants | Sample size\n"
+ "</h4>\n"
+ "\n"
+ "Note: Controls, are they true controls? may have OUD patients; phenotypes, self-reported values are not reliable; variants: 5% common vs rare, SNPs vs structural; large samples are needed to capture variants with small  effect size  \n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Genetic studies using model organisms\n"
+ "\n"
+ "* Inbred animals have their genomes sequenced\n"
+ "* Phenotypes are better defined \n"
+ "* Allow mechanistic studies\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Hybrid rat diversity panel\n"
+ "<img src=\"./images/ratGenome/HRDP_1000x357.png\" width=80%>\n"
+ "\n"
+ "RI panels provide mapping power | Classic inbreds provide mapping resolution\n"
+ "<p align=center>\n"
+ "<span id=\"cite\"> Tabakoff, Saba, et al.,  Methods Mol Biol. 2019 </span>\n"
+ "<br>\n"
+ "Available from Medical College of Wisconsin\n"
+ "\n"
+ "\n"
+ "---\n"
+ "## Whole genome sequencing of the HRDP\n"
+ "<table><tr>\n"
+ "\n"
+ "<td width=50%>\n"
+ "<img src=\"./images/ratGenome/Figure6_phylogenetic_tree_color.png\"> \n"
+ "</td>\n"
+ "\n"
+ "<td>\n"
+ "<img src=\"./images/ratGenome/hrdp_variant_stat.png\" width=60%>\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> de Jong et. al., Cell Genomics, in press</span>\n"
+ "\n"
+ "\n"
+ "</td>\n"
+ "</tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Oxycodone is highly addictive \n"
+ "\n"
+ "<table width=70%><tr><td>\n"
+ "\n"
+ "* Prescription oral oxycodone is a major contributor to the current opioid abuse epidemic.\n"
+ "* Oxycodone has strong addiction liability even when it is delivered orally in controlled-release formulation.\n"
+ "\n"
+ "</td></tr></table>\n"
+ "\n"
+ "Note:\n"
+ "\n"
+ "In both animal and human studies, it has been found that, for abused substances, the route of administration is one of the  determining factors of their abuse liability. Strong euphoria is usually produced by the rapid pharmacokinetics in the brain following intravenous injection or inhalation. \n"
+ "Pharmaceutical companies have argued that the controlled release of oxycodone delivered orally is very safe and widely promoted its clinical use for pain management, which led to the current opioid epidemic.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Oral self-administration of oxycodone in rats\n"
+ "\n"
+ "<table> <tr><td width=40%>\n"
+ "<img src=\"./images/oxycodone/oxycodone_operant_chamber.png\">\n"
+ "</td>\n"
+ "<td>\n"
+ "<ul><ul>\n"
+ "<li> Operant licking procedure, one session per day\n"
+ "<li> Gradual increase in session length and oxycodone dose \n"
+ "<li> No water or food restrictions, no drug pre-exposure\n"
+ "</ul>\n"
+ "</ul>\n"
+ "\n"
+ "<img src=\"./images/oxycodone/oxycodone_hrdp_schedule.png\">\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Sharp et. al., Genes Brain Behav, 2021</span>\n"
+ "\n"
+ "\n"
+ "</td>\n"
+ "</tr></table>\n"
+ "\n"
+ "Note:\n"
+ "To model voluntary oxycodone use in rats, we developed an oral oxycodone self-administration procedure. \n"
+ "\n"
+ "---\n"
+ "## Number of licks, all strains, by sex \n"
+ "\n"
+ "<img src=\"./images/oxycodone/hrdp_oxycodone_oral_operant_self-admin_summary_plot-0.png\" width=80%>\n"
+ "\n"
+ "---\n"
+ "## Rewards and intake, all strains, by sex \n"
+ "\n"
+ "<img src=\"./images/oxycodone/hrdp_oxycodone_oral_operant_self-admin_summary_plot-1.png\" width=80%>\n"
+ "\n"
+ "---\n"
+ "## Strain differences in initiation \n"
+ "\n"
+ "<img src=\"./images/oxycodone/hrdp_oxycodone_oral_operant_self-admin_summary_plot-2.png\" width=80%>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "## Strain differences in stable intake, 4h \n"
+ "\n"
+ "<img src=\"./images/oxycodone/hrdp_oxycodone_oral_operant_self-admin_summary_plot-3.png\" width=80%>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "## Strain differences in escalated intake with extended availability, 16 h \n"
+ "\n"
+ "<img src=\"./images/oxycodone/hrdp_oxycodone_oral_operant_self-admin_summary_plot-4.png\" width=80%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Distinct use patterns with increased drug availability \n"
+ "\n"
+ "<img src=\"./images/oxycodone/wl_strain_selection_for_escalation.png\" width=80%>\n"
+ "\n"
+ "Human oxycodone is metabolised via Cyp3A4 and Cyp2D6. There are 1233 SNPs of these orthologs (Cyp3A2/Cyp3A9/Cyp2D1) in rats.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Time course of drug intake \n"
+ "\n"
+ "<img src=\"./images/oxycodone/hrdp_oxy_hourly_intake_16hr.png\" width=80%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Strain differences in motivation for oxycodone \n"
+ "\n"
+ "<img src=\"./images/oxycodone/MShrdp_oxycodone_oral_operant_self-admin_summary_plot-PR.png\" width=80%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Escalation of drug intake is not due to enhanced motivation\n"
+ "\n"
+ "<img src=\"./images/oxycodone/wl_pr_by_esc_vs_non.png\" width=60%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Individual differences in cue-induced relapse \n"
+ "<img src=\"./images/oxycodone/MShrdp_oxycodone_oral_operant_self-admin_summary_plot-reinstatement.png\" width=80%>\n"
+ "---\n"
+ "\n"
+ "## Correlations between sexes \n"
+ "\n"
+ "<img src=\"./images/oxycodone/oxyu01_correlation_between_sexes_progressreport.png\" width=80%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Correlations between oxycodone and other behavioral traits\n"
+ "\n"
+ "<table><tr><td>\n"
+ "<b>females</b>\n"
+ "<br>\n"
+ "<img src=\"./images/oxycodone/oxy_ethovision_corrrelation_females_36OxyStrains_20CorrStrains.png\">\n"
+ "\n"
+ "</td><td>\n"
+ "<b>males</b>\n"
+ "<br>\n"
+ "<img src=\"./images/oxycodone/oxy_ethovision_corrrelation_males_36OxyStrains_20CorrStrains.png\">\n"
+ "</td></tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Correlations: oxycodone and other behavioral traits\n"
+ "\n"
+ "<img src=\"./images/oxycodone/example_correlations_oxy_behavior_2023-11-20.png\" width=90%>\n"
+ "\n"
+ "<b>higher anxiety-like behavior -> low initial oxycodone intake\n"
+ "<br>\n"
+ "greater tendency to explore  -> higher motivation for oxycodone \n"
+ "</b>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Reduced complexity cross\n"
+ "\n"
+ "<img src=\"./images/oxycodone/rcc_workflow.png\" width=80%>\n"
+ "\n"
+ "<p id=cite> Bryant, et al., Trends Genet, 2020</p>\n"
+ "---\n"
+ "\n"
+ "## WLI - WMI isogenic strains of rats\n"
+ "\n"
+ "<img src=\"./images/oxycodone/wmi_wli_genomes.png\" width=50%>\n"
+ "\n"
+ "\n"
+ "<p id=cite>de Jong et al., Sci Report 2021</p>\n"
+ "---\n"
+ "## Oxycodone intake in WMI/WLI rats\n"
+ "<img src=\"./images/oxycodone/wmiwli-talk-0.png\" width=90%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Oxycodone intake in WMI/WLI rats\n"
+ "<img src=\"./images/oxycodone/wmiwli-talk-1.png\" width=90%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Oxycodone intake WMI/WLI preliminary QTL mapping\n"
+ "<img src=\"./images/oxycodone/rcc_qtl.png\" width=90%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Recombinant inbred mice\n"
+ "\n"
+ "<img src=\"./images/oxycodone/bxd_ri.png\" width=60%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Morphine locomotion in BXD\n"
+ "\n"
+ "<table><tr><td>\n"
+ "<img src=\"./images/oxycodone/morphine_bxd_locomotion_phenotypes_3-0.png\" width=80%>\n"
+ "</td><td>\n"
+ "<img src=\"./images/oxycodone/morphine_bxd_locomotion_phenotypes_3-1.png\" width=80%>\n"
+ "</td></table>\n"
+ "\n"
+ "64 strains\n"
+ "\n"
+ "<p id=cite>Paige, et al., BioRxiv, 2022</p>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## QTL for morphine locomotion\n"
+ "\n"
+ "<img src=\"./images/oxycodone/morphine_locomotion_qtl_all_time_bins_female_male.png\" width=60%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Gene X gene interaction on morphine locomotion \n"
+ "\n"
+ "<img src=\"./images/oxycodone/morphine_bxd_epistasis_horizontal.png\" width=80% >\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Causal modeling using Bayesian network\n"
+ "\n"
+ "<img src=\"./images/oxycodone/BNW_network_inkscape.svg\" width=40%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Identifying the cell-type for  GxG \n"
+ "\n"
+ "<img src=\"./images/oxycodone/oprm1_fgf12_snRNA.png\" width=60%>\n"
+ "\n"
+ "Credit: Francesca Telese, UCSD\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## FGF12 in human GWAS\n"
+ "\n"
+ "<img src=\"./images/oxycodone/fgf12_oud_gene_based_mtag.png\">\n"
+ "\n"
+ "<p id=cite> Deak, et al., Mol Psychiatry, 2022</p>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Zebrafish Conditioned Place Preference Test\n"
+ "\n"
+ "<table><tr><td width=50%>\n"
+ "\n"
+ "<img src=\"./images/zebrafish_chamber.png\">\n"
+ "\n"
+ "</td><td>\n"
+ "\n"
+ "<img src=\"./images/zebrafish_nicotine_cpp_30um_3day.png\">\n"
+ "\n"
+ "</td></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Base Editing Zebrafish Genome \n"
+ "\n"
+ "<table><tr><td width=50%>\n"
+ "\n"
+ "<img src=\"./images/zebrafishknockout_vs_wildtype.png\">\n"
+ "\n"
+ "</td>\n"
+ "<td width=50%>\n"
+ "<img src=\"./images/p50/zebrafish_pamless.png\">\n"
+ "</td></tr>\n"
+ "\n"
+ "</td></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Validating causal relationship using cell-type specific genome editing\n"
+ "\n"
+ "<table><tr>\n"
+ "\n"
+ "<td width=50%>\n"
+ "<img src=\"./images/pde4b/percent_mutation_pde4b_gRNA.png\">\n"
+ "</td>\n"
+ "<td>\n"
+ "<img src=\"./images/pde4b/pde4b_aav_nac.png\">\n"
+ "</td>\n"
+ "\n"
+ "</tr></table>\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Sharp et. al., Scientific Report, 2024</span>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Acknowledgements\n"
+ "\n"
+ "<table><tr align=center>\n"
+ "\n"
+ "<td width=16.7%>\n"
+ "<img src=\"./images/lab/angel.jpg\">\n"
+ "Angel G Martinez\n"
+ "</td>\n"
+ "<td width=16.7%>\n"
+ "<img src=\"./images/lab/shuangying.jpg\">\n"
+ "Shuangying Leng\n"
+ "</td>\n"
+ "<td width=16.7%>\n"
+ "<img src=\"./images/lab/caroline.png\">\n"
+ "Caroline Jones\n"
+ "</td>\n"
+ "<td width=1>\n"
+ "\n"
+ "<td width=16.7%>\n"
+ "<img src=\"./images/lab/tomi.jpeg\">\n"
+ "Tomomi Green\n"
+ "</td>\n"
+ "\n"
+ "\n"
+ "<td width=16.7%>\n"
+ "<img src=\"./images/lab/rachel.jpg\">\n"
+ "Rachel Ward\n"
+ "</td>\n"
+ "\n"
+ "<td width=16.7%>\n"
+ "<img src=\"./images/lab/jun.jpg\">\n"
+ "Jun Huang\n"
+ "</td>\n"
+ "\n"
+ "</tr>\n"
+ "</table>\n"
+ "\n"
+ "\n"
+ "* Past technicians and analysts \n"
+ "	* *Xia Hong* | *Jie Shen* | *Wenyan Han* | *Pawandeep Kaur* | *Yanyan Lin* | *Xinyu Fan* | *Mallory Udell* | *Gwen Johnson* | *Hakan Gunturkun* | *Tengfei Wang* |\n"
+ "* UTHSC collaborators\n"
+ "	*  Burt Sharp | Thirumalini Vaithianathan | Rob Williams | Megan Mulligan | \n"
+ "\n"
+ "#### Funding: NIDA U01DA053672 | U01U01DA047638 | 1U01DA057530 | P50DA037844 | R01DA048017\n"
+ "\n"
+ "\n"
+ "\n"
+ "---\n"
+ "## Quantifying social interaction between rats \n"
+ "\n"
+ "<iframe width=\"1080\" height=\"630\" src=\"https://www.youtube.com/embed/9cmLqHrcnQM\" frameborder=\"0\" allow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Changes in social behavior during oxycodone withdrawal\n"
+ "\n"
+ "<img src=\"./images/oxycodone/social_deficit.png\" width=70%>\n"
+ "\n"
+ "\n"
+ "\n"
+ "---\n"
+ "##  Literature mining for candidate genes |  https://genecup.org \n"
+ "\n"
+ "<a href=\"https://genecup.org/cytoscape/?rnd=tmpBLXVZb&genequery=OPRM1_ADGRV1_FURIN_LINC00581_KCNN1_CDKAL1_SEMA6D_NCAM1_FBXW4_DRD2\" target=_new>\n"
+ "\n"
+ "<img src=\"./images/oxycodone/genecup_graph.svg\" width=40%>\n"
+ "\n"
+ "</a>\n"
+ "\n"
+ "<p align=center>\n"
+ "<span id=\"cite\"> Gunturkun, et. al., G3, 2022</span>\n"
+ "\n"
+ "---\n"
+ "\n"
;
var script = document.querySelector('script[src="genetics_oud.js"]');
var section = document.createElement('section');
script.parentNode.appendChild(section);
section.appendChild(document.createTextNode(markdownContent));
[].forEach.call(script.attributes, function (attr) {
    section.setAttribute(attr.name, script.getAttribute(attr.name));
});
section.setAttribute('data-markdown', '');
})();
