(function () {
'strict'
var markdownContent = ''
+ "# Genetic factors influence voluntary nicotine intake in a social setting in adolescent rats \n"
+ "\n"
+ "<hr color=orange >\n"
+ "\n"
+ "## Hao Chen, Ph.D.\n"
+ "\n"
+ "\n"
+ "### Department of Pharmacology, Addiction Science and Toxicology\n"
+ "### University of Tennessee Health Science Center\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Outline\n"
+ "\n"
+ "* Behavior model\n"
+ "* Genetic studies using this model\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nicotine is primarily aversive in non-smokers \n"
+ "\n"
+ "<table>\n"
+ " <tr>\n"
+ " <td width=50%>\n"
+ " <img width=100% src=\"images/titlepages/eissenberg.png\">\n"
+ " </td>\n"
+ " <td width=90%>\n"
+ " <img width=100% src=\"images/titlepages/dkalman.png\">\n"
+ " </td>\n"
+ " </tr>\n"
+ " <tr>\n"
+ " <td>\n"
+ " Nausea, dizziness, sickness, headache, burning throat, coughing, etc..\n"
+ " </td>\n"
+ " <td>\n"
+ " Nicotine induces drug high only in <em>significantly nicotine-deprived smokers</em>. \n"
+ " </td>\n"
+ " </tr>\n"
+ "</table>\n"
+ "\n"
+ "Note:\n"
+ "We all know nicotine is higly addicitive. However, unlikely other addicive sustances, it does not produce strong euhphorian. Not only that, it also has has strong aversive properties. This aversiveness is especially promimant in non-smokers, or in otherwords, for people start experimenting with tobacco. New smokers experience diziness, sickness \n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nicotine conditioned taste aversion in rats\n"
+ "\n"
+ "<table><tr><td>\n"
+ "\n"
+ "<img src=\"./images/nicotien_cta.png\">\n"
+ "</td></tr><tr><td>\n"
+ "<center>\n"
+ "<img src=\"./images/nicotine_cta_bjpharm1983.png\" width=70%>\n"
+ "</center>\n"
+ "</td></tr></table>\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Kumar, et. al., Br J Pharmac 1983</span>\n"
+ "\n"
+ "Note: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2044849/?page=3\n"
+ "flavors: sodium sacchaine vs sodium chloride\n"
+ "water access were limited to 1 h per day. flavors were presented every other day, followed by nicotine vs saline injection. \n"
+ "\n"
+ "Here is an early nicotine conditioned taste aversion experiment.\n"
+ "\n"
+ "The dose here, 0.08mg/kg, is about 3 infusions in most nicotine self-admionistration studies using rats. But rats also self-administer iv nicotine. One question is then do rats also experience the aversive response when nicotine is self-administered. \n"
+ "\n"
+ "---\n"
+ "\n"
+ "<span id=\"solo\">\n"
+ "\n"
+ "## Flavor cues conditioned to self-administered nicotine is aversive \n"
+ "\n"
+ "<a href=\"#/demo\">\n"
+ "<img height:auto width=90% src=\"images/p50/flavorcue_conditioned_aversion.png\">\n"
+ "</a>\n"
+ "\n"
+ "<p align=\"left\">\n"
+ "<span id=\"cite\"> Chen, et al., Neuropsychopharmacology, 2011 </span>\n"
+ "\n"
+ "\n"
+ "Note:\n"
+ "One way you can study this is by combining conditioned taste aversion with i.v. self-administraion. \n"
+ "adolescent rats developed conditioned aversion to an appetitive flavor cue (saccharine + grape odor) associated with self-administered i.v. nicotine. In this operant <i>licking</i> model, oral flavor cue and <strong>i.v.</strong> nicotine were delivered simultaneously upon the completion of a fixed-ratio 5 reinforcement schedule. \n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "<section id=\"cta0\">\n"
+ "\n"
+ "## Flavor cues conditioned to self-administered nicotine is aversive \n"
+ "\n"
+ "<a href=\"#/cta1\">\n"
+ "<img height:auto width=90% src=\"images/p50/nicotine_cta.png\">\n"
+ "</a>\n"
+ "\n"
+ "<p align=left> \n"
+ "<span id=\"cite\"> Chen, et al., Neuropsychopharmacology, 2011 </span>\n"
+ "\n"
+ "Note: \n"
+ "To further confirm that nicotine is aversive, we tested removing nicotine after three sessions. So this is an extinction procedure, where the cue is presented without the uncontitioned stimulus. In these adolescent SD rats, extinction happened relatively quickly. We'll come back to this extinction procedure shortly. \n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Social influence is a key factor in smoking initiation \n"
+ "\n"
+ "<div id=\"left50\" >\n"
+ "<img width=100% src=\"images/titlepages/hoffman.png\"> \n"
+ "</div>\n"
+ "<div id=\"right50\">\n"
+ "<img width=100% src=\"images/titlepages/jfowler.png\"> \n"
+ "</div>\n"
+ "\n"
+ "Note: \n"
+ "Now that we established self-administered nicotine is aversive, the question then is why do invididuals take it? In humans, a lot of research points out that social environment is a key.\n"
+ "\n"
+ "\n"
+ "---\n"
+ "## Social transmission of food preference in rats\n"
+ "\n"
+ "<img src=\"images/galef.protocol.narrower.png\" width=50%> \n"
+ "\n"
+ "<p align=\"left\">\n"
+ "<span id=\"cite\">Galef, Curr Protoc Neurosci, 2003</span>\n"
+ "\n"
+ "Note:\n"
+ "In rats, there is also a long tradition of studying social learning. The particular procedure is called STFP. It takes advantage to the fact that rats are neophobic when it comes to novel foods. This is a three stage protocol. \n"
+ "\n"
+ "---\n"
+ "\n"
+ "<span id=\"demo\">\n"
+ "\n"
+ "## Social learning enables nicotine self-administration\n"
+ "\n"
+ "<a href=\"#/solo\">\n"
+ "<img height:auto width=100% src=\"images/socially_acquired_nicotine_ivsa.png\">\n"
+ "</a>\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Chen, et al., Neuropsychopharmacology, 2011 </span>\n"
+ "\n"
+ "Note:\n"
+ "However, with the presence of a \"demonstrator\" rat consuming the same flavor cue, nicotine i.v. self-administration was established. \n"
+ "No water or food deprivation or operant pretraining is needed. Thus the model is appropriate for studying smoking initiation in adolescents. \n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Is the appetitive cue driving IVSA? \n"
+ "\n"
+ "<img src=\"./images/p50/fig4.saccGluSolo_flavor.png\">\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Chen, et al., Neuropsychopharmacology, 2011 </span>\n"
+ "\n"
+ "Note: \n"
+ "Obviously, there are many questions in this somewhat complicated model. There is nicotine, there is flavor cue, there is social cue. They key question is what is driving the self-admnistration behavior. We've done a lot of expeirments to show that the operant licking behavior is driven by nicotine. I don't have time to show you all the data but here are some of the key findings. First of all, is a flavor cue with strong appetitiveness sufficient to drive nicotine intake without social factors. \n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Taste vs odor? Social alone? \n"
+ "\n"
+ "<img src=\"./images/Fig1.social.rats.withdemo.svg\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Social learning supports nicotine IVSA with an aversive flavor cue\n"
+ "<table>\n"
+ "<tr><td width=15% valign=\"middle\">Social, Non-learning</td><td rowspan=2>\n"
+ "<img width=90% src=\"images/quinine/ise_nse_aversivecue.png\">\n"
+ "</td></tr>\n"
+ "<tr><td> Social, Learning</td></tr></table>\n"
+ "\n"
+ "\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Wang, et al., Psychopharmacology, 2016 </span>\n"
+ "</p>\n"
+ "\n"
+ "Note:\n"
+ "To further demonstrate that the appetitiveness of flavor cue is driving nicotine intake in our model, we replace the saccyhrine cue with a quinine cue. The bitterness of quinine is often used to show rats with self-administration history that will resist the punishment in order to obtain drug. Here we paired it as a contingent cue at the begining of nicotine self-administration. We also improved our control by adding a demonstration rat on the left side of the operant chamber. \n"
+ "<b>NSE</b>: neutral social environemnt, i.e., the presence of a companion rat. \n"
+ "<b>ISE</b>: indusive social environment, i.e., the presences of a companion rat who has access to the flavor cue. \n"
+ "<b>AV</b>: audiovisual cue \n"
+ "\n"
+ "---\n"
+ "\n"
+ "## IVSA is driven by nicotine \n"
+ "<b> NOT by the subjective value of the flavor cue</b>\n"
+ "\n"
+ "<img width=50% src=\"images/quinine/pres.sacc_quinine.png\">\n"
+ "\n"
+ "Reinforcement schedule: FR10TO20\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Wang, et al., Psychopharmacology, 2016 </span>\n"
+ "</p>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## What is transmitted from the demonstrator? \n"
+ "\n"
+ "<img src=\"./images/Fig1.social.rats.withdemo.svg\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Social learning is mediated by Carbon Disulfide (CS<sub>2</sub>) in rats \n"
+ "\n"
+ "<div id=\"left50\">\n"
+ "<img height:auto width=90% src=\"images/galef.protocol.narrower.png\"> \n"
+ "<br>\n"
+ "</div>\n"
+ "\n"
+ "<div id=\"right50\">\n"
+ "<img height:auto width=90% src=\"images/titlepages/cs2.png\">\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Both CS<sub>2</sub> and flavor cue are necessary for socially acquired nicotine IVSA \n"
+ "\n"
+ "<img width=100% height=\"auto\" src=\"images/p50/cs2_1rat.png\">\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Wang, et al., PLoS One, 2014 </span>\n"
+ "</p>\n"
+ "\n"
+ "Note:\n"
+ "We confirmed that neither nicotine associated flavor cue nor carbon disulfide alone supported nicotine IVSA. However, their combination was sufficient to replicate the behavior induced by live demonstrator rats. \n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Is CS<sub>2</sub> relevant to human?\n"
+ "\n"
+ "<img src=\"./images/p50/ota_icv.png\">\n"
+ "\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Chen, unpublished data</span>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nicotine intake is heritable \n"
+ "\n"
+ "### h<sup>2</sup>=0.54-0.65 estimated using 12 isogenic strains across two doses \n"
+ "\n"
+ "<img src=\"./images/social_nicotine_dose_isogenic_strain.png\" width=80%>\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Han, et al., Sci Report, 2017 </span>\n"
+ "</p>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"cta1\">\n"
+ "\n"
+ "## Social learning facilitates the extinction of conditioned nicotine aversion\n"
+ "\n"
+ "<a href=\"#/cta0\">\n"
+ "<img src=\"./images/p50/correlation_ext_cta_nicotine.png\" >\n"
+ "</a>\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Han, et al., Sci Report, 2017 </span>\n"
+ "</p>\n"
+ "\n"
+ "Note:\n"
+ "With these inbred rats, we wanted to ask another question, which is the relationship between the aversive response and nicotine intake. One obvious hypothesis was that rats with stronger conditioned aversion to nicotine will self-administer less. To measure CTA, we have two groups, one recives nicotine and one recives iv nicotine. We did three days of nicotine becasuse we knew it was sufficient. After day 4, both groups recived saline. The difference in number of rewards between nicotine and saline on day 4 is an index for CFA. I really hated to discard the rats away after only getting four days data, especailly we went through all the trouble in during jugular surgery. So we added five extinction sessions. we use the number of rewards on the last session as an index of extion. So CFA and Extion of CFA are on the y-axis, the x-axis of these plots are number of nicotine infusions. It turns out, there was no correlations between CFA and intake but extinction of CFA is a predictor of nicotine intake. So this suggests, that the way social learning works is by facilite the extinction, or the dissociation between the flavor and the aversive effect of nicotine. \n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "### Summary \n"
+ "## Socially acquired nicotine IVSA in adolescent rats\n"
+ "<ul>\n"
+ "<li class=\"fragment\"> This model incorporates the aversive and reinforcing properties of nicotine\n"
+ "</li>\n"
+ "<li class=\"fragment\"> Flavor cues are associated with the aversive property of nicotine \n"
+ "</li>\n"
+ "<li class=\"fragment\"> Operant responding is driven by the reinforcing property of nicotine </li>\n"
+ "<ul>\n"
+ "	<li class=\"fragment\"> nicotine can be self-administered with an aversive flavor cue </li>\n"
+ "</ul>\n"
+ "<li class=\"fragment\"> Social learning facilitates nicotine intake by enhancing the extinction of conditioned aversion</li>\n"
+ "<li class=\"fragment\"> Nicotine IVSA is heritable in this model.</li>\n"
+ "<li class=\"fragment\"> Familiar rats as demonstrator increase learning rate.</li>\n"
+ "<li class=\"fragment\"> Social signals are not needed to maintain nicotine intake, but nevertheless, they still promoting intake. </li>\n"
+ "\n"
+ "</ul>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Heterogeneous stock rats\n"
+ "\n"
+ "<table><tr><td width=20%>\n"
+ "<img src=\"https://school.wakehealth.edu/-/media/WakeForest/Global/System/Person-Images/l/Leah-Catherine-Solberg-Woods.jpg\">\n"
+ "<b>Leah Solberg Woods, Wake Forest School of Medicine \n"
+ "</b>\n"
+ "</td>\n"
+ "<td width=80%>\n"
+ "<img src=\"./images/p50/hs_rats.png\" width=80%>\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Garret and Korstanje, Trends Genet, 2020</span>\n"
+ "</td>\n"
+ "</tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## HS progenitors contain ~80% of the genetic variants in lab rats\n"
+ "\n"
+ "<img src=\"./images/p50/hrdp_phylo_hs_horizontal.png\" width=90%>\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> de Jong et al., Cell Genomics, In Press</span>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Genotyping and GWAS\n"
+ "\n"
+ "<table> <tr>\n"
+ "	<td width=50%>\n"
+ "		<p align=\"center\"> <img src=\"./images/p50/AGileta_G3.png\" width=60%> </p>\n"
+ "		<p align=left>\n"
+ "		<span id=\"cite\"> Gileta et al., G3, 2020. </span>\n"
+ "		</p>\n"
+ "	</td>\n"
+ "	<td width=50%>\n"
+ "		<p align=center>\n"
+ "		<img src=\"https://pbs.twimg.com/profile_images/775453143559581697/ECeItK57.jpg\" width=30%>\n"
+ "		<br>\n"
+ "		<b>Abraham Palmer, UCSD</b>\n"
+ "		</p>\n"
+ "		<p>\n"
+ "		<ul>	\n"
+ "			<li> 3.5 million SNPs per individual (estimated error rate <1%)\n"
+ "			<li> GCTA with liner mixed model\n"
+ "			<li> Leave one chromosome out procedure\n"
+ "			<li> Genome-wide significance level set by permuation: -log<sub>10</sub>(p) > 5.6 \n"
+ "		</ul>\n"
+ "	</td>\n"
+ "</tr>\n"
+ "</table>\n"
+ "\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Socially acquired nicotine self-administration in HS rats\n"
+ "\n"
+ "### 52 adult males and 48 adult females\n"
+ "\n"
+ "<div id=\"left50\">\n"
+ "<img width=90% height=\"auto\" src=\"images/p50/fig4.g2b.figure.male.vs.female.nicSA.cummulative.png\">\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Wang, et al., Gene Brain Behav, 2014</span>\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "<div id=\"right50\">\n"
+ "<img width=83% height=\"auto\" src=\"images/p50/fig_demo.lick.by.sex.png\">\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<div id=\"ofdiagram\">\n"
+ "\n"
+ "## Behavioral Test Schedule \n"
+ "\n"
+ "\n"
+ "<table> <tr><td width=30%>\n"
+ "\n"
+ "<a href=\"#/ethovision_v4_v15\">\n"
+ "<img src=\"./images/p50/openfields_verticle.png\">\n"
+ "</a>\n"
+ "\n"
+ "</td><td>\n"
+ "\n"
+ "<font size=4>\n"
+ "\n"
+ "| Age | Test |\n"
+ "|---|---|\n"
+ "|PND21|Wean, Body weight|\n"
+ "|PND31|Open field test (20min)|\n"
+ "|PND32|Novel object interaction (20min)|\n"
+ "|PND33|Social interaction test (20 min) |\n"
+ "|PND34|Elevated plus maze (6min)|\n"
+ "|PND38|Surgery|\n"
+ "|PND39 -- 41| Recovery|\n"
+ "|PND42 -- 51|Socially acquired nicotine IVSA|\n"
+ "|PND52| Progressive ratio test |\n"
+ "|PND53 -- 56 |Extinction|\n"
+ "|PND57|Contextual cue induced reinstatement|\n"
+ "|PND59|Tissue Collection for the IVSA rats|\n"
+ "\n"
+ "</font>\n"
+ "\n"
+ "\n"
+ "</td></tr></table>\n"
+ "\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Can behavioral traits predict nicotine IVSA? \n"
+ "\n"
+ "<div id=\"left\">\n"
+ "\n"
+ "\n"
+ "\n"
+ "<center>\n"
+ "\n"
+ "#### Loading of PCA\n"
+ "\n"
+ "<img src=\"images/p50/retreat2018/pca_loading.png\" width=70%> \n"
+ "</center>\n"
+ "\n"
+ "<p>\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Wang, et al., Scientific Report, 2018 </span>\n"
+ "</p>\n"
+ "\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "<div id=\"right\">\n"
+ "\n"
+ "<center>\n"
+ "\n"
+ "\n"
+ "\n"
+ "#### PCA regression summary \n"
+ "\n"
+ "<font size=4>\n"
+ "\n"
+ "|Phenotype | Sex| Variance Explained| \n"
+ "|---|---|---|\n"
+ "|Infusion, first 3 d| F| 0.18| \n"
+ "|Infusion, first 3 d| M| 0.17| \n"
+ "|Infusion, last 3 d | F | 0.12| \n"
+ "|Infusion, last 3 d | M | 0.20| \n"
+ "|Infusion, progressive ratio | F | 0.14| \n"
+ "|Infusion, progressive ratio | M | 0.18| \n"
+ "|Active spout lick, reinstatement | F | 0.08| \n"
+ "|Active spout lick, reinstatement | M | 0.19| \n"
+ "</font>\n"
+ "</center>\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "\n"
+ "## Phenotype: Open Field Test\n"
+ "\n"
+ "<img src=\"images/p50/hs_phenotype_openfield.png\" width=70%>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "## Manhattan plot: open field center duration, 18 min bin \n"
+ "\n"
+ "<img src=\"images/p50/gwas_openfield_center_duation_18min.png\" width=80%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## GWAS: Open Field Test\n"
+ "\n"
+ "n=1857\n"
+ "\n"
+ "<img src=\"images/p50/hs_gwas_openfield_porcupine.png\" width=70%>\n"
+ "<img src=\"images/p50/hs_gwas_openfield_qtlCnt.png\" width=70%>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Phenotype: Novel Object Test\n"
+ "\n"
+ "<img src=\"images/p50/hs_phenotype_novelobject.png\" width=70%>\n"
+ "---\n"
+ "\n"
+ "## GWAS: Novel Object Interaction\n"
+ "\n"
+ "n=1963\n"
+ "\n"
+ "<img src=\"images/p50/hs_gwas_novel_porcupine.png\" width=70%>\n"
+ "<img src=\"images/p50/hs_gwas_novel_qtlCnt.png\" width=70%>\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Phenotype: Social Interaction Test\n"
+ "\n"
+ "<img src=\"images/p50/hs_phenotype_social.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "## GWAS: Social Interaction\n"
+ "\n"
+ "n=1835\n"
+ "\n"
+ "<img src=\"images/p50/hs_gwas_social_porcupine.png\" width=70%>\n"
+ "<img src=\"images/p50/hs_gwas_social_qtlCnt.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Phenotype: Elevated Plus Maze\n"
+ "\n"
+ "<img src=\"images/p50/hs_phenotype_epm.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## GWAS: Elevated Plus Maze \n"
+ "\n"
+ "n=1875\n"
+ "\n"
+ "<img src=\"images/p50/hs_gwas_epm_porcupine.png\" width=70%>\n"
+ "<img src=\"images/p50/hs_gwas_epm_qtlCnt.png\" width=70%>\n"
+ "\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Phenotype: Socially Acquired Nicotine IVSA \n"
+ "\n"
+ "<img src=\"images/p50/hs_phenotype_nicsa.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## GWAS: Socially Acquired Nicotine IVSA\n"
+ "\n"
+ "n=1995\n"
+ "\n"
+ "<img src=\"images/p50/hs_gwas_nicsa_porcupine.png\" width=70%>\n"
+ "\n"
+ "<img src=\"images/p50/hs_gwas_nicsa_qtlCnt.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Many QTL are Very Narrow\n"
+ "\n"
+ "<table><tr><td width=50%>\n"
+ "<center>\n"
+ "<br>\n"
+ "<img src=\"./images/p50/hs_gwas_nicsa_day2_infusion.png\"> \n"
+ "\n"
+ "</center>\n"
+ "</td><td>\n"
+ "<center>\n"
+ "<br>\n"
+ "<img src=\"./images/p50/hs_gwas_nicsa_day5_infusion.png\"> \n"
+ "</center>\n"
+ "\n"
+ "</td></tr></table>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## A Few QTL are Wide\n"
+ "\n"
+ "<img src=\"./images/p50/hs_gwas_nicsa_day1_chr1.png\" width=60%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<center>\n"
+ "<a href=\"https://ratgtex.org/\" target=_new> <img src=\"https://ratgtex.org/images/RatGTExPortal.png\" width=30%> </a>\n"
+ "\n"
+ "<table> <tr>\n"
+ "<td width=30%>\n"
+ "	<center>\n"
+ "	<img src=\"./images/p50/expression_level_of_nic_candiate_genes.svg\" width=100%>\n"
+ "	</center>\n"
+ "</td>\n"
+ "<td width=50%>\n"
+ "	<img src=\"./images/p50/violinplot0-cyp26b1.svg\" width=100% >\n"
+ "</td>\n"
+ "<td width=20%>\n"
+ "	<img src=\"https://avatars.githubusercontent.com/u/5875477?v=4\" width=100%>\n"
+ "	<p>\n"
+ "	<b> Dan Munro, UCSD</b>\n"
+ "</td>\n"
+ "</tr></table>\n"
+ "\n"
+ "</center>\n"
+ "\n"
+ "<span id=\"cite\"> Munro, et al., Nucleic Acids Res 2022</span>\n"
+ "\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Candidate genes for OFT, NOIT, SIT \n"
+ "\n"
+ "<div id=\"left\">\n"
+ "<img src=\"./images/p50/openfieldtablep1.png\">\n"
+ "</div>\n"
+ "<div id=\"right\">\n"
+ "<img src=\"./images/p50/openfieldtablep2.png\">\n"
+ "\n"
+ "<p align=\"left\">\n"
+ "<span id=\"cite\">Gunturkun, et.al., Front Psychiatry, 2022</a>\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Multiple Causal Genes in One QTL?\n"
+ "\n"
+ "<img src=\"./images/p50/GCF_015227675.21-GCF_000001405.4010.png\" width=99%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "\n"
+ "## PheWAS: Social Interaction & Socially Acquired Nicotine IVSA\n"
+ "\n"
+ "<table><tr>\n"
+ "<td width=33%> <img src=\"images/p50/hs_gwas_nicsa_day1_active.png\"> </td>\n"
+ "<td width=33%> <img src=\"images/p50/hs_gwas_nicsa_first3day_infusion.png\"></td>\n"
+ "<td width=33%><img src=\"images/p50/hs_gwas_insocdurat.png\"></td>\n"
+ "</tr></table>\n"
+ "\n"
+ "|SNP PheDb|-Log10(p)PheDb|R2|DP|trait PheDb|\n"
+ "|---|---|---|---|---|\n"
+ "|4:151349337|5.04|0.959|0.982|nicsa day1 infusion|\n"
+ "|4:151240226|4.057|0.798|0.995|nicsa day1 active inactive ratio|\n"
+ "|4:151324325|6.15|0.966|0.987|nicsa first three days activelick total|\n"
+ "|4:151324325|4.78|0.966|0.987|nicsa first three days infusion total|\n"
+ "|4:151964479|4.329|0.408|0.953|social 0 to 3 insoczonedura|\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Top Smoking Phenotypes in GWAS Catalogue \n"
+ "\n"
+ "|Trait| Number of Sig. SNPs <sup>1</sup> | Note|\n"
+ "|---|---|---|\n"
+ "|Smoking initiation <sup>2</sup> | 5498 | 5269 from Saunders, et al. PMID: 36477530 and Liu et al., PMID: 30643251|\n"
+ "|Cigarettes smoked per day | 610 | | \n"
+ "|Smoking status <sup>3 </sup> | 481 | 218 were from Karlsson Linnér et al. PMID: 30643258. |\n"
+ "|Smoking cessation <sup>4 </sup> | 452 | 335 were from Saunders, et al., PMID: 36477530.|\n"
+ "|Age of smoking initiation | 243 ||\n"
+ "\n"
+ "<table><tr><td>\n"
+ "<p align=\"left\">\n"
+ "1. p-val < 5E-8, replicated finding not filtered out\n"
+ "<br>\n"
+ "2. Ever being a regular smoker in their life (current or former) vs never being a regular smoker in their life \n"
+ "<br>\n"
+ "3. Ever vs nerver smoker\n"
+ "<br>\n"
+ "4. Current smokers vs former smokers \n"
+ "</p>\n"
+ "</td></tr></table>\n"
+ "\n"
+ "</p>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Overlap Between Genes Under Rat NicIVSA QTL \n"
+ "## and Human Smoking Initiation \n"
+ "\n"
+ "<img src=\"images/p50/hs_gwas_nicsa_smoking_init_genes.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Overlap Between Genes Under Rat NicIVSA QTL \n"
+ "## and Cigarettes per Day \n"
+ "\n"
+ "<img src=\"images/p50/hs_gwas_nicsa_cig_per_day_genes.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Tex29\n"
+ "\n"
+ "Human GWAS: Pack years \n"
+ "\n"
+ "PackYears: Cigarettes per day divided by 20, multiplied by number of years smoking \n"
+ "\n"
+ "Rat GWAS: Total nicotine infusion\n"
+ "\n"
+ "Common: total overall exposure to tobacco/nicotine. \n"
+ "\n"
+ "<table> <tr> <td width=50%>\n"
+ "<img src=\"./images/p50/arhgef7_locuszoom.png\" width=100%>\n"
+ "\n"
+ "</td>\n"
+ "<td>\n"
+ "\n"
+ "![](./images/gwasv3/tex29_gwas_pack_years.png)\n"
+ "\n"
+ "<a href=\"https://www.ebi.ac.uk/gwas/variants/rs2026174\" target=_new> New annotation: LINC02337 </a> \n"
+ "\n"
+ "<a href=\"http://genome.ucsc.edu/cgi-bin/hgTracks?db=hg38&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr13%3A110979763%2D112075449&hgsid=1385374851_DFWqHgcyTThiDJV0a0SLgElBbEDP\" target=_new> Is Arhgef7 more likely?</a> Arhgef7 expression is FPKM=30 in our dataset. It is involed in spine morphogenesis. Loss of Arhgef7 results in extensive loss of axons (PMID:30683798, PMID:29891904)\n"
+ "\n"
+ "<p align=left>\n"
+ "Exome Chip Meta-analysis Fine Maps Causal Variants and Elucidates the Genetic Architecture of Rare Coding Variants in Smoking and Alcohol Use \n"
+ "<span id=\"cite\">Brazel, et. al., Biol Psychiatry 2019</span>\n"
+ "\n"
+ "\n"
+ "</td></tr></table>\n"
+ "\n"
+ "Note:\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Gene Ontology Enrichment of Overlapping Rat and Human Genes\n"
+ "\n"
+ "<img src=\"images/p50/goprofiler_GO_enrichemnt_for_smoking_genes.png\" width=60%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Candidate Genes Based on eQTL and Variant Impact\n"
+ "### filtering by literatuer using GeneCup.org\n"
+ "\n"
+ "<img src=\"./images/p50/genecup_graph_all_rat_only_nicsa_genes.svg\" width=45%>\n"
+ "\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Gunturkun, et. al., G3 2022</span>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Novel Candidate Genes for Nicotine IVSA not Reported in Human GWAS\n"
+ "\n"
+ "<a href=\"https://genecup.org/cytoscape/?rnd=tmpxUiwWs&genequery=Camk1_Tlr9_Grm2_Trim32_Akap2_Scn3b_Col4a1\">\n"
+ "\n"
+ "<img src=\"./images/p50/genecup_novel_nicotine_genes.png\" width=50%>\n"
+ "\n"
+ "</a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Large Language Model Reads the Papers \n"
+ "\n"
+ "<table><tr><td>\n"
+ "<img src=\"./images/p50/RAG.png\">\n"
+ "<small>credit: https://www.youtube.com/watch?app=desktop&v=ctzDFIINSrI</small>\n"
+ " </td>\n"
+ " <td>\n"
+ " <b>User:</b> What are the potential molecular pathways where Camk1 may affect nicotine addiction?\n"
+ " <hr>\n"
+ " <b>Arithmo-Mistral-7B: </b> \n"
+ " One possible mechanism by which CamK1 may affect nicotine addiction is\n"
+ " through the regulation of glutamate release in the VTA. Glutamate is the\n"
+ " primary excitatory neurotransmitter in the brain, and its release in the\n"
+ " VTA is thought to play a key role in the reinforcement process of nicotine\n"
+ " addiction. CamK1 may regulate glutamate release by phosphorylating specific\n"
+ " proteins involved in exocytosis, such as syntaxin1 and SNAP-25.\n"
+ " </td></tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Gria4 Western blot\n"
+ "\n"
+ "<table><tr><td width=60%>\n"
+ "\n"
+ "<img src=\"./images/p50/wes_slope_sample_characteristics.png\">\n"
+ "\n"
+ "<img src=\"./images/p50/wes_gria4_lanes.png\">\n"
+ "</td>\n"
+ "<td width=40% valign=\"middle\"> \n"
+ "<img src=\"./images/p50/ampa4_gria4_western_barplot.png\" >\n"
+ "</td></tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Gria4 null mutation abolishes nicotine CCP in C.elegans \n"
+ "\n"
+ "<table><tr><td width=15%>\n"
+ "<img src=\"https://www.uthsc.edu/pharmacology/faculty/images/jee-changhoon.jpg\">\n"
+ "<b> Dr. Changhoon Jee </br> Assistant Prof, UTHSC</b>\n"
+ "\n"
+ "</td><td width=85%>\n"
+ "<img src=\"./images/p50/celegans2.png\">\n"
+ "</td></tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Zebrafish Nicotine Conditioned Place Preference Test\n"
+ "\n"
+ "<table><tr><td width=50%>\n"
+ "\n"
+ "<img src=\"./images/zebrafish_chamber.png\">\n"
+ "\n"
+ "</td><td>\n"
+ "\n"
+ "<img src=\"./images/zebrafish_nicotine_cpp_30um_3day.png\">\n"
+ "\n"
+ "</td></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Base Editing Zebrafish Genome \n"
+ "\n"
+ "<table><tr><td width=50%>\n"
+ "\n"
+ "<img src=\"./images/zebrafishknockout_vs_wildtype.png\">\n"
+ "\n"
+ "</td>\n"
+ "<td width=50%>\n"
+ "<img src=\"./images/p50/zebrafish_pamless.png\">\n"
+ "</td></tr>\n"
+ "\n"
+ "</td></table>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## In vivo genome editing in rats \n"
+ "\n"
+ "<img src=\"./images/p50/cas9_NAcSH_mutation.png\" width=60%>\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Sharp, et. al., Scientific Report, 2024 </span>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Acknowledgements\n"
+ "\n"
+ "<table><tr align=center>\n"
+ "\n"
+ "<td width=16.7%>\n"
+ "<img src=\"./images/lab/angel.jpg\">\n"
+ "Angel G Martinez\n"
+ "</td>\n"
+ "<td width=16.7%>\n"
+ "<img src=\"./images/lab/shuangying.jpg\">\n"
+ "Shuangying Leng\n"
+ "</td>\n"
+ "<td width=16.7%>\n"
+ "<img src=\"./images/lab/caroline.png\">\n"
+ "Caroline Jones\n"
+ "</td>\n"
+ "<td width=1>\n"
+ "\n"
+ "<td width=16.7%>\n"
+ "<img src=\"./images/lab/tomi.jpeg\">\n"
+ "Tomomi Green\n"
+ "</td>\n"
+ "\n"
+ "\n"
+ "<td width=16.7%>\n"
+ "<img src=\"./images/lab/rachel.jpg\">\n"
+ "Rachel Ward\n"
+ "</td>\n"
+ "\n"
+ "<td width=16.7%>\n"
+ "<img src=\"./images/lab/jun.jpg\">\n"
+ "Jun Huang\n"
+ "</td>\n"
+ "\n"
+ "</tr>\n"
+ "</table>\n"
+ "\n"
+ "\n"
+ "* Past technicians and analysts \n"
+ "	* *Xia Hong* | *Jie Shen* | *Wenyan Han* | *Pawandeep Kaur* | *Yanyan Lin* | *Xinyu Fan* | *Mallory Udell* | *Gwen Johnson* | *Hakan Gunturkun* | *Tengfei Wang* |\n"
+ "* REHU students \n"
+ "	* Abigale Salinero (2015) | Cindy Tay (2016) | Raven David (2017) | Christian Hurt (2018) | Gwen Johnson (2021) | Olivia Harrison (2022, 2023) | \n"
+ "Ryan Luib (2023)\n"
+ "* P50 collaborators \n"
+ "	* Abraham Palmer | Oksana Polesskaya | Sanches, Thiago | Apurva Chitre | Shae Ziegler | Leah Solberg-Woods \n"
+ "* UTHSC collaborators\n"
+ "	* Changhoon Jee | Burt Sharp | Thirumalini Vaithianathan | Rob Williams | and others\n"
+ "---\n"
+ "\n"
+ "## Nicotine metabolism\n"
+ "\n"
+ "<img width=60% height=\"auto\" src=\"images/p50/AllCotinine_NicotineHSRats.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## SNP heritability\n"
+ "\n"
+ "<img src=\"./images/p50/heritability_for_all_traits.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"manh_d5\">\n"
+ "\n"
+ "## GWAS: Nicotine infusion on session 5 \n"
+ "\n"
+ "<img src=\"images/p50/gwas_day5_infusion.jpg\">\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Porcupine plot: socially acquired nicotine IVSA\n"
+ "\n"
+ "<img src=\"./images/p50/porcupine_plot_nicotine.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Slope of nicotine intake chr8:4459578 \n"
+ "\n"
+ "<div id=\"left50\">\n"
+ "<img src=\"./images/p50/gria4_locuszoom.png\">\n"
+ "\n"
+ "There are 32 known genes in this 5.1 Mb interval. Gria4 is a candidate gene.\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "<div id=\"right50\">\n"
+ "\n"
+ "* Prioritizing candidate genes\n"
+ "	* mis-sense variants\n"
+ "	* cis-eQTL\n"
+ "	* expressed in relevant brain regions\n"
+ "	* relevant biological function \n"
+ "	* associated with related traits in human GWAS\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## <a href=\"http://genecup.org\" target=_new> GeneCup.org </a>\n"
+ "\n"
+ "<a href=\"https://genecup.org/cytoscape/?rnd=tmpDYEQAw&genequery=Shtn1_Gria4_Arhgef7_Alg8\" target=_new>\n"
+ "<img src=\"./images/p50/genecup_4_candidates.svg\" width=90%>\n"
+ "</a>\n"
+ "\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Gunturkun, et. al., G3, 2022</span>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "#### Summary of nicotine GWAS \n"
+ "\n"
+ "## Number of licks on the active spout\n"
+ "\n"
+ "|ID |Session|Loc| Genes (n) | Overlapping with human smoking GWAS|\n"
+ "|---|:---:|---|---|---|\n"
+ "|12.20 | day 1 | chr1:278524299| 99 | [Shtn1](http://rats.pub/cytoscape/?rnd=tmpJiHXFf&genequery=KIAA1598_SHOOTIN-1_SHOOTIN1_SHTN1)<font color=\"darkslateblue\">&spades;</font>&diams;, [Nrap](http://rats.pub/cytoscape/?rnd=tmpaUzTZp&genequery=N-RAP_NEBULIN-RELATED-ANCHORING-PROTEIN_NRAP)<font color=\"darkslateblue\">&spades;</font>, [Vti1a](http://rats.pub/cytoscape/?rnd=tmpUpzbbT&genequery=VTI1A)<font color=\"darkslateblue\">&spades;</font>, Gpam&clubs;&diams;, Casp7&diams; Nhlrc2&clubs;&diams; Adrb1&clubs; Tcf7l2&diams; Hspa12a |\n"
+ "|12.29 | day 2 | chr8:22496077| 29| Carm1|\n"
+ "|12.24 | day 4 | chr4:145377793| 20| Emc3 |\n"
+ "|12.12 | day 5 | chr16:83955432| 23| LINC02337| \n"
+ "|12.08 | day 7 | chr16:83489214| 23| LINC02337| \n"
+ "|12.02 | day 9 | chr10:32845925| 90| | \n"
+ "|12.22 | day 10 | chr2:247766389|20| Pkn2, Gtf2b |\n"
+ "|12.16 | Reinstatment | chr1:161226950| 28|Usp35&dagger;, Gab2&dagger;, Tenm4&dagger;, [Alg8](http://rats.pub/cytoscape/?rnd=tmpJKLgcJ&genequery=Usp35_Gab2_Nars2_Tenm4_Alg8)&diams;&hearts;&dagger; |\n"
+ "\n"
+ "\n"
+ "<font color=\"darkslateblue\">&spades;</font>: Smoking initiation \n"
+ "&clubs;: Alcohol GWAS \n"
+ "&diams;: cis-eQTL\n"
+ "&hearts; missense variants\n"
+ "&dagger; Psychiatric GWAS\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Vti1a, Shtn1 and/or Nrap \n"
+ "\n"
+ "Human GWAS: smoking initiation \n"
+ "\n"
+ "SmkInit: ever being a regular smoker (e.g., 100 cigarettes, or smoked every day for a month) \n"
+ "\n"
+ "Rat GWAS: number of licks on active spout on day 1 \n"
+ "\n"
+ "Common: Initial response to tobacco/nicotine?\n"
+ "\n"
+ "![](./images/gwasv3/smoking_initiation_vti1a_nrap_shtn1.png)\n"
+ "\n"
+ "<p align=left>\n"
+ "Association studies of up to 1.2 million individuals yield new insights into the genetic etiology of tobacco and alcohol use\n"
+ "<span id=\"cite\">\n"
+ "Liu, et. al., Nature Genetics 2019\n"
+ "</cite>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Summary of nicotine GWAS\n"
+ "\n"
+ "## Number of nicotine infusions\n"
+ "\n"
+ "|ID |Session|Loc| Genes (n) | Overlapping with human smoking GWAS|\n"
+ "|---|:---:|---|---|---|\n"
+ "|12.09 | day 5 | chr16:83500180| 23| LINC02337 |\n"
+ "|12.13 | day 5 | chr17:17103044| 1| ID4 |\n"
+ "|12.11 | day 7 | chr16:83500180| 23| LINC02337|\n"
+ "|12.23 | day 7 | chr3:104723116| 8| Hmgn4, Fmn1 |\n"
+ "|12.15 | day 8 | chr19:26396258| 1| |\n"
+ "|12.03 | median of last 3 days | chr11:17834164|27| | \n"
+ "|12.10 |total infusion | <a href=\"#/manh_d5\">chr16:83500180</a>| 23| LINC02337|\n"
+ "|12.30 |slope of regression | chr8:4459578| 74| Gria4&diams;, Pdgfd&diams;, Mmp12 |\n"
+ "\n"
+ "&diams;: cis-eQTL\n"
+ "\n"
+ "---\n"
+ "## Potential targets for validation \n"
+ "\n"
+ "* Shtn1 (active lick on day 1)\n"
+ "* Gria4 (progression of intake)\n"
+ "* Arhgef7 (total intake)\n"
+ "* Alg8 (reinstatement) \n"
+ "\n"
+ "---\n"
+ "\n"
+ "## C.elegans model of nicotine conditioned cue preference\n"
+ "\n"
+ "### Dr. Changhoon Jee, Assistant Prof, UTHSC\n"
+ "\n"
+ "<table><tr><td>\n"
+ "<img src=\"https://www.uthsc.edu/pharmacology/faculty/images/jee-changhoon.jpg\">\n"
+ "</td><td>\n"
+ "\n"
+ "<img src=\"./images/p50/celegans1.png\">\n"
+ "</td></tr></table>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Gria4 null mutation abolishes nicotine CCP \n"
+ "\n"
+ "### Dr. Changhoon Jee, Assistant Prof, UTHSC\n"
+ "\n"
+ "<img src=\"./images/p50/celegans2.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Acknowledgements\n"
+ "\n"
+ "\n"
+ "<table><tr>\n"
+ "<td width=12.5%>\n"
+ "<img src=\"http://www.chenlab.one/img/team/twang18.jpg\">\n"
+ "Tengfei Wang\n"
+ "</td>\n"
+ "<td width=12.5%>\n"
+ "<img src=\"http://www.chenlab.one/img/team/angel.jpg\">\n"
+ "Angel Garcia Martinez\n"
+ "</td>\n"
+ "<td width=12.5%>\n"
+ "<img src=\"http://www.chenlab.one/img/team/shuangying.jpg\">\n"
+ "Shuangying Leng\n"
+ "</td>\n"
+ "\n"
+ "<td width=12.5%>\n"
+ "<img src=\"http://www.chenlab.one/img/team/Caroline.png\">\n"
+ "Caroline Jones\n"
+ "</td>\n"
+ "\n"
+ "<td width=12.5%>\n"
+ "<img src=\"http://www.chenlab.one/img/team/gwen.png\">\n"
+ "Gwen Johnson\n"
+ "</td>\n"
+ "\n"
+ "<td width=12.5%>\n"
+ "<img src=\"http://www.chenlab.one/img/team/rachel.jpg\">\n"
+ "Rachel Ward\n"
+ "</td>\n"
+ "<td width=12.5%>\n"
+ "<img src=\"http://www.chenlab.one/img/team/jun.jpg\">\n"
+ "Jun Huang \n"
+ "</td>\n"
+ "<td width=12.5%>\n"
+ "<img src=\"http://www.chenlab.one/img/team/tristan.jpg\">\n"
+ "Tristan de Jong\n"
+ "</td>\n"
+ "</tr>\n"
+ "</table>\n"
+ "\n"
+ "\n"
+ "<b>Past lab members </b>: Jie Shen | Wenyan Han | Pawandeep Kaur | Yanyan Lin | Xinyu Fan | Hukan Gunturkun \n"
+ "\n"
+ "* UCSD: Abraham Palmer | Oksana Polaskaya | Apurva Chitre \n"
+ "* Wake Forest: Leah Solberg-Woods \n"
+ "* UTHSC: Changhoon Jee | Rob Williams\n"
+ "\n"
+ "Funding: NIH/NIDA P50DA037844\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Social interaction is not required to maintain nicotine intake\n"
+ "\n"
+ "\n"
+ "<img src=\"./images/p50/fig7.demo2solo.png\" width=50%>\n"
+ "\n"
+ "<p align=left> \n"
+ "<span id=\"cite\"> Chen, et al., Neuropsychopharmacology, 2011 </span>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nicotine IVSA with aversive flavor cue containing CS<sub>2</sub>\n"
+ "\n"
+ "Adolescent heterogeneous rats \n"
+ "\n"
+ "<div span=\"left\">\n"
+ "\n"
+ "<img width=75% height=\"auto\" src=\"images/p50/p50_quinine.png\">\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Summary of nicotine GWAS, part 3/4\n"
+ "\n"
+ "## Number of licks on the inactive spout \n"
+ "\n"
+ "\n"
+ "|ID |Session|Loc| Genes (n) | Overlapping with human smoking GWAS|\n"
+ "|---|:---:|---|---|---|\n"
+ "|12.18 | day 3 | chr1:253523411| 10| |\n"
+ "|12.04 | day 7 | chr14:108854633|23| XPO1, USP34, BCL11A |\n"
+ "|12.06 | day 9 | chr16:5256755|1| Cacna2d3 |\n"
+ "|12.21 | day 9 | chr1:74927958| 195| U2af2, KMT5C, FAM71E2, TMEM238, COX6B2, TMEM190, Il11, Lilrb4| \n"
+ "|12.26 | day 9 | chr6:71588778| 46| Foxg1, Heatr5a&hearts;, Prkd1 |\n"
+ "|12.27 | day 9 | chr7:110658276| 7| |\n"
+ "|12.07 | day 10 | chr16:5288954|1 | Cacna2d3 |\n"
+ "|12.17 | total | chr1:239058463| 7||\n"
+ "|12.19 | total | chr1:253766837| 10||\n"
+ "\n"
+ "&hearts;:protein coding variant\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Summary of nicotine GWAS, part 4/4\n"
+ "\n"
+ "## Ratio of licks on the active/inactive spouts\n"
+ "\n"
+ "\n"
+ "|ID |Session|Loc| Genes (n) | Overlapping with human smoking GWAS|\n"
+ "|---|:---:|---|---|---|\n"
+ "|12.28 | day 2 | chr8:22201332| 37| Carm1 | \n"
+ "|12.14 | day 3 | chr18:50265173| 13| |\n"
+ "|12.05 | day 4 | chr16:43380960|7 | |\n"
+ "|12.01 | day 10 | chr10:104395310| 54|Tsen54 |\n"
+ "|12.25 | day 11 | chr6:21268257| 5| TTC27 |\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Is self-administration driven by nicotine or flavor cue?\n"
+ "\n"
+ "<img src=\"./images/p50/fig5.sansFlavor.png\" width=80%>\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Chen, et al., Neuropsychopharmacology, 2011 </span>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Overlapping genes between rat nicotine and human addiction/psychiatric GWAS \n"
+ "\n"
+ "\n"
+ "| Trait| Number of human genes* | Overlap expected by random | Actual overlap| Difference| \n"
+ "|---|---:|---:|---:|---:|\n"
+ "|Smoking | 1772| 32|39| 7| \n"
+ "|Body height| 2467| 46| 36| -10|\n"
+ "|Body mass|2920|54 |46|-8 |\n"
+ "|Education |1214 |23 | 13|-10 |\n"
+ "\n"
+ "<p>\n"
+ "\n"
+ "<div id=\"twocols\">\n"
+ " There are a total of 16913 genes symbols common between human and rat. There are 315 genes under nicotine QTL share the symbol with human genes. Chance of human/rat gene involved in smoking: 1772/16913=10%. For 315 genes, we expect to find 32 genes. The actual overlap is 39. Although this is a small enrichment, calculation conducted on other traits shows that this is an under-estimation. This is likely because the nicotine QTL contained many genes. *: reported in <a href=\"https://pubmed.ncbi.nlm.nih.gov/30584246/\">GWAS catalog</a>\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Correlations among open field, novel object, social interaction, and elevated plus maze\n"
+ "\n"
+ "<img src=\"./images/p50/retreat2018/behav_cor_r_p.png\" width=60% class=\"plain\">\n"
+ "\n"
+ "<p>\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Wang, et al., Scientific Report, 2018 </span>\n"
+ "</p>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
;
var script = document.querySelector('script[src="genNicSoc.js"]');
var section = document.createElement('section');
script.parentNode.appendChild(section);
section.appendChild(document.createTextNode(markdownContent));
[].forEach.call(script.attributes, function (attr) {
    section.setAttribute(attr.name, script.getAttribute(attr.name));
});
section.setAttribute('data-markdown', '');
})();
