(function () {
'strict'
var markdownContent = ''
+ "# A community effort in comparing Rnor6 v mRatBN7.2 \n"
+ "\n"
+ "<hr>\n"
+ "\n"
+ "## Hao Chen, Ph.D.\n"
+ "\n"
+ "### University of Tennessee Health Science Center\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## International Rat Omic Consortium \n"
+ "\n"
+ "* Open to all, free to attend\n"
+ "* Monthly Zoom meeting\n"
+ "* 12 PM CDT, last Tuesday of each month\n"
+ "* Recorded and archived\n"
+ "* Contact: hchen@uthsc.edu\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Ongoing data collection \n"
+ "\n"
+ "### Whole genome sequencing data\n"
+ "* Mindy Dwinell, Anne Kwitek, MCW\n"
+ "	* Illumina short reads of close to 50 inbred strains\n"
+ "* Jun Li, Univ Michigan\n"
+ "	* Illumina short reads of 8 inbred strains (founders of the HS) \n"
+ "	* Illumina short reads of 20 outbred rats\n"
+ "	* Bionano data of two inbred strain (founder of the HXB RI panel)\n"
+ "* Hao Chen, Burt Sharp, Rob Williams, UTHSC \n"
+ "	* 10X Chromium linked reads (40 inbred strains analyzed, 40 more in progress) (with Li's group)  \n"
+ "	* Nanopore on two inbred strains\n"
+ "	* PacBio HiFi on two inbred strains\n"
+ "	* Hi-C on two inbred strains (more to come)\n"
+ "* Peter Doris (Univ Texas at Houston) \n"
+ "	* Nine inbred strains planned (including BN)\n"
+ "	* PacBio HIFI/CLR/IsoSeq\n"
+ "	* Hi-C \n"
+ "	* Bionano\n"
+ "* Abraham Palmer, Jonathan Sebat, Mellissa Gymrek,  UCSD \n"
+ "	* PacBio on more than 80 inbreds \n"
+ "\n"
+ "---\n"
+ "\n"
+ "### RNA-seq data\n"
+ "* Laura Saba, Boris Tabakoff, Univ Corolado\n"
+ "	* Illumina data of brain and liver of 50 inbred strain	\n"
+ "	* Iso-seq data \n"
+ "* Hao Chen, Laura Saba,  Abraham Palmer (UCSD),\n"
+ "	* five brain regions per brain, 88 HS brains\n"
+ "	* more than 400 HS brains in process by many labs\n"
+ "* Francesca Telese, UCSD\n"
+ "	* snRNAseq\n"
+ "	* ATACseq\n"
+ "	* csRNAseq\n"
+ "\n"
+ "Monthly Zoom meeting organized by Laura Saba\n"
+ "\n"
+ "---\n"
+ "\n"
+ "### Proteomics data\n"
+ "\n"
+ "* Victor Guryev (Univ Groningen) \n"
+ "	* liver from two rats, transcriptome and proteome\n"
+ "* Xusheng Wang (Univ North Dakota)\n"
+ "	* Whole brain (12 brains)  \n"
+ "	* RNA-seq data from the same strains from Laura Saba\n"
+ "\n"
+ "---\n"
+ "\n"
+ "### mRatBN7.2\n"
+ "\n"
+ "<div id=\"left50\">\n"
+ "\n"
+ "<p>\n"
+ "\n"
+ "* Using DNA from a BN/NHsdMcwi male rat\n"
+ "* Multiple sequencing technologies   \n"
+ "	* PacBio\n"
+ "	* 10X chromim\n"
+ "	* Hi-C\n"
+ "	* Bionano\n"
+ "* Assembled by Kerstin Howe, et al.\n"
+ "* Genome Note is just [published by Wellcome Open Research ](https://wellcomeopenresearch.org/articles/6-118/v1)\n"
+ "\n"
+ "</div>\n"
+ "<div id=\"right50\">\n"
+ "<img src=\"images/ratGenome/genomenotemratbn72.png\" width=80% > \n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Rnor6 vs mRatBN7.2 \n"
+ "\n"
+ "|| mRatBN7.2 |Rnor6 | \n"
+ "|---|---|---|\n"
+ "|Total sequence length | 2,647,915,728| 2,870,184,193|\n"
+ "|Total ungapped length| 2,626,580,772| 2,729,985,504|\n"
+ "|Gaps between scaffolds| 0| 440|\n"
+ "|Number of scaffolds| 176| 1,395|\n"
+ "|Scaffold N50| 135,012,528| 14,986,627|\n"
+ "|Scaffold L50| 8| 65|\n"
+ "|Number of contigs| 757| 75,697|\n"
+ "|Contig N50| 29,198,295| 100,461|\n"
+ "|Contig L50| 27| 7,356|\n"
+ "|Total number of chromosomes and plasmids| 23| 23|\n"
+ "|Number of component sequences (WGS or clone)| 757| 75,996|\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Inversion in Chr6\n"
+ "\n"
+ "<div id=\"left50\">\n"
+ "<img src=\"images/ratGenome/dotplot_mratbn72_vs_rnor6_chr6.png\" width=90%>\n"
+ "</div>\n"
+ "<div id=\"right50\">\n"
+ "<img src=\"images/ratGenome/dotplot_chr6_pasi.png\" width=90%>\n"
+ "</div>\n"
+ "\n"
+ "<img src=\"images/ratGenome/chr6_bionano.png\">\n"
+ "\n"
+ "Courtesy of Pasi Rastas (Univ Helsinki), Abraham Palmer (UCSD) Yanchao Pan, Jun Li (Univ Mich)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "##  10x Chromium Linked reads WGS data \n"
+ "\n"
+ "* 36 inbred strains\n"
+ "	* Four BN/NHsdMcwi samples (including the one used for mRatBN7.2)\n"
+ "	* BN-Lx/Cub and SHR/OlaIpcv\n"
+ "	* 30 HXB and BXH strains \n"
+ "* Most strains have about 60x coverage\n"
+ "* Longranger 2.2.2 against Rnor6 and mRatBN72 for mapping and SV\n"
+ "* Deepvariant/GLnexus for joint SNP and Indel analysis \n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Linked-reads data \n"
+ "\n"
+ "## Mapping stats \n"
+ "\n"
+ "<iframe src=\"pdfs/longranger_mapping_stats_mRatBN7_v_Rnor6_selected.pdf\" width=\"100%\" height=600px>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Linked-reads data \n"
+ "## Type of SV and their locations  \n"
+ "\n"
+ "<iframe src=\"pdfs/hxb_location_of_sv_rn6_v_bn7.pdf\" width=\"100%\" height=600px>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Linked-reads data \n"
+ "## Type of SNPs and indels  \n"
+ "\n"
+ " Joint calling by Deepvariant/GLNexus \n"
+ "\n"
+ "\n"
+ "<iframe src=\"pdfs/deepvariant_36_samples_rn6_v_bn7.pdf\" width=\"100%\" height=600px>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Oxford nanopore WGS data for BN-Lx/Cub and SHR/OlaIpcv \n"
+ "\n"
+ "* about 20x coverage \n"
+ "* N50 of the reads is 15-20kb\n"
+ "* Winnowmap for mapping	against both refs\n"
+ "* Sniffles for SV detection\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Nanopore data \n"
+ "## Read depth per chromosome\n"
+ "\n"
+ "mRatBN7.2 increase read depth by 7-8% compare to Rnor6\n"
+ "\n"
+ "<iframe src=\"pdfs/nanopore_per_chr_coverage_bnlx_shrola_rn6_v_mRatBN7.pdf\" width=\"100%\" height=600px>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Nanopore data\n"
+ "\n"
+ "## SV calls by Sniffles\n"
+ "\n"
+ "<iframe src=\"pdfs/bnlx-shrolaipcv_nanopore_sniffle_size.pdf\" width=\"100%\" height=600px>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Brain RNA-seq\n"
+ "\n"
+ "* 352 Samples from 88 HS rats\n"
+ "* median number of paired-end reads: 26.8 million  \n"
+ "* average % of reads that aligned to the Ensembl transcriptome\n"
+ "	* Rnor6: 67.6%\n"
+ "	* mRatBN72:  74.8%\n"
+ "* mapping of eQTL\n"
+ "	* a total of ~ 90 trans-eQTL were found with p<1e-8 in Rnor6\n"
+ "	* 8 of them become cis-eQTL in mRatBN72\n"
+ "	* 8 of them are still trans-eQTL but the regulatory region moved to a different chr.\n"
+ "\n"
+ "Courtesy of Laura Saba (Univ Colorado), Dan Munro (UCSD, Palmer lab)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Potential errors in mRatBN7.2? \n"
+ "\n"
+ "94 whole genome sequencing data (Illumina + 10X chromimum), including multiple BN/NHsdMcwi samples, and the samples used for mRatBN7.2. Mapped to mRatBN7.2 using `bwa mem`, variant called using `deepvariant/GLNexus`\n"
+ "\n"
+ "<img src=\"images/ratGenome/snpindels_shared_by92outof94samples_in_mratbn72.png\" width=90%>\n"
+ "\n"
+ "13k 1/1 SNPs/Indels across autosomes\n"
+ "\n"
+ "117k 0/1 SNPs/Indels across autosomes\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"table\">\n"
+ "\n"
+ "#### Linked-reads data \n"
+ "\n"
+ "## SV shared by more than 30 of the 36 samples on mRatBN7.2\n"
+ "\n"
+ "|Chr|Begin|End|SV Type|Length|Strains|\n"
+ "|---|---|---|---|---|---|\n"
+ "|chr1|54119451|54946980|Translocation|827529|32|\n"
+ "|chr1|138882092|138934698|<a href=\"#/chr1_138\">Deletion</a>|52606|36|\n"
+ "|chr2|148864168|148911755|<a href=\"#/chr2_148\">Duplication</a>|47587|36| \n"
+ "|chr4|100799349|100865002|Deletion|65653|31|\n"
+ "|chr9|113817704|114048709|Duplication|231005|34|\n"
+ "|chr17|37794956|37852590|<a href=\"#/chr17_37\">Duplication</a>|57634|32|\n"
+ "|chr19|22724887|22881779|Deletion|156892|33|\n"
+ "\n"
+ "#### Same criteria found 177 DEL, 59 DUP, 47 INV and 1 TRANS on Rnor6\n"
+ "\n"
+ "---\n"
+ "\n"
+ "# Thanks to the IROC community!\n"
+ "# Thanks to the GRC for adopting the rat!\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"chr1_138\">\n"
+ "\n"
+ "## chr1 138 Mb Duplication\n"
+ "\n"
+ "<a href=\"#/table\"> <img src=\"./images/ratGenome/chr1_138mb_del_40_samples.png\"> </a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"chr2_148\">\n"
+ "\n"
+ "## chr2 148 Mb Duplication\n"
+ "\n"
+ "<a href=\"#/table\"> <img src=\"./images/ratGenome/chr2_148mb_dup_mRatBN7_small.png\"> </a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"chr17_37\">\n"
+ "\n"
+ "## chr17 37 Mb Duplication\n"
+ "\n"
+ "<a href=\"#/table\"> <img src=\"./images/ratGenome/chr17_37mb_dup.png\"> </a>\n"
+ "\n"
+ "\n"
;
var script = document.querySelector('script[src="grc2021.js"]');
var section = document.createElement('section');
script.parentNode.appendChild(section);
section.appendChild(document.createTextNode(markdownContent));
[].forEach.call(script.attributes, function (attr) {
    section.setAttribute(attr.name, script.getAttribute(attr.name));
});
section.setAttribute('data-markdown', '');
})();
