(function () {
'strict'
var markdownContent = ''
+ "# 3D Genomic Interactions Identifies Candidate Genes from HS GWAS\n"
+ "\n"
+ "<hr>\n"
+ "\n"
+ "## Hao Chen\n"
+ "\n"
+ "### University of Tennessee Health Science Center\n"
+ "\n"
+ "#### P50 retreat, 2024\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## The genome is full of 3D interactions\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Hi-C is a method to find 3D interactions\n"
+ "\n"
+ "heat map, TAD, and Loop\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Loops and promoter-enhancer interactions\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Loops from PFC of 10 inbred rats\n"
+ "\n"
+ "<img src=\"./images/hic/hao_loop_size_after_remove_duplicate_loops.png\">\n"
+ "\n"
+ "5K: 6680 / 10K: 12,162 / 25K: 12,931\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Overlap between loop & CTCF\n"
+ "\n"
+ "<img src=\"./images/hic/hao_ctcf.hist.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Overlap between loop & TSS\n"
+ "\n"
+ "<img src=\"./images/hic/hao_absolute_position_of_tss_to_loop.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Overlap between loop & Promoter\n"
+ "\n"
+ "<img src=\"./images/hic/hao_position_of_promoter_to_loop.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Loops supported by CTCF and has TSS or Promoter\n"
+ "\n"
+ "<img src=\"./images/hic/hao_loops_common_venn_diagram.png\" width=60%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Location of these loops\n"
+ "\n"
+ "<img src=\"./images/hic/loops_circos.png\" width=60%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Loops help identify candidate genes\n"
+ "\n"
+ "<img src=\"./images/hic/ist1_with_loop.png\" width=70%>\n"
+ "\n"
+ "Both Ist1 and Dhodh has cis-eQTL. Ist1 is a human smoking initiation gene. Ist1 is involved in endosomal sorting.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Loops help identify candidate genes\n"
+ "\n"
+ "<img src=\"./images/hic/epb41.png\" width=70%>\n"
+ "\n"
+ "Epb41l4b is a human smoking initiation gene. Many genes in this region has coding variants, including Epb41l4b\n"
+ "\n"
+ "---\n"
;
var script = document.querySelector('script[src="hic.js"]');
var section = document.createElement('section');
script.parentNode.appendChild(section);
section.appendChild(document.createTextNode(markdownContent));
[].forEach.call(script.attributes, function (attr) {
    section.setAttribute(attr.name, script.getAttribute(attr.name));
});
section.setAttribute('data-markdown', '');
})();
