(function () {
'strict'
var markdownContent = ''
+ "\n"
+ "# Genetic factors influencing individual differences in vulnerability to Oxycodone in rats\n"
+ "\n"
+ "<hr color=orange>\n"
+ "\n"
+ "## Hao Chen, Ph.D.\n"
+ "### Professor\n"
+ "\n"
+ "### Department of Pharmacology, Addiction Science and Toxicology, University of Tennessee Health Science Center\n"
+ "\n"
+ "\n"
+ "---\n"
+ "## Oxycodone is highly addictive \n"
+ "\n"
+ "* Prescription oral oxycodone is a major contributor to the current opioid abuse epidemic.\n"
+ "* In general, rapid intravenous infusion of abused drugs produces greater positive subjective effects than slow infusion.\n"
+ "* It has been claimed that delayed absorption of oxycodone reduces its abuse liability.\n"
+ "* Oxycodone has strong addiction liability even when it is delivered orally in controlled-release formulation.\n"
+ "\n"
+ "---\n"
+ "## Early prevention is key \n"
+ "\n"
+ "* Early diagnosis and prevention is critical for stemming opioid abuse epidemic.\n"
+ "* Readily available and easy to use test for many chronic diseases has been successful.\n"
+ "* Identifying early behavioral phenotypes that predict drug abuse and their genetic contribution will have high impact. \n"
+ "\n"
+ "---\n"
+ "## Oral self-administration of oxycodone in rats\n"
+ "\n"
+ "<table> <tr><td width=50%>\n"
+ "<img src=\"./images/oxycodone/oxycodone_operant_chamber.png\">\n"
+ "</td>\n"
+ "<td>\n"
+ "\n"
+ "<li> drug\n"
+ "<li> dd\n"
+ "</td>\n"
+ "</tr></table>\n"
+ "\n"
+ "\n"
+ "\n"
+ "---\n"
+ "## Genetic factors influnce vulnerability to opioid addiction \n"
+ "\n"
+ "---\n"
+ "## Hybrid rat diversity panel\n"
+ "\n"
+ "\n"
+ "---\n"
+ "## Whole genome sequencing of the HRDP\n"
+ "\n"
+ "---\n"
+ "## Phenotypic variance of oxycodone self-administartion in HRDP\n"
+ "\n"
+ "---\n"
+ "## Correlations between oxycodone and other behavioral traits\n"
+ "\n"
+ "---\n"
+ "## Genetic mapping of substance use related traits in rats\n"
+ "### Socialy acquired nicotine intravenous self-admistration\n"
+ "\n"
+ "---\n"
+ "## Using literature mining to indentify biologically relevant candidate genes\n"
+ "\n"
+ "---\n"
+ "## Using snRNA-seq to identify cell types involved behavioral traits\n"
+ "\n"
+ "---\n"
+ "## Using in-vivo genome editing to confirm causal relationships \n"
+ "\n"
+ "---\n"
+ "## Validating causal relationship using cell-type specific genome editing\n"
+ "\n"
+ "---\n"
+ "## Summary\n"
+ "\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Acknowledgements\n"
+ "\n"
+ "* Current lab members working on this project \n"
+ "\n"
+ "<table><tr>\n"
+ "\n"
+ "<td width=25%>\n"
+ "<img src=\"images/photos/shuangying.jpg\">\n"
+ "Shuangying Leng\n"
+ "</td>\n"
+ "\n"
+ "\n"
+ "<td width=25%>\n"
+ "<img src=\"images/photos/angel.jpg\">\n"
+ "Angel Garcia Martinez\n"
+ "</td>\n"
+ "\n"
+ "<td width=25%>\n"
+ "<img src=\"images/photos/caroline.jpg\">\n"
+ "Caroline Jones \n"
+ "</td>\n"
+ "\n"
+ "</tr>\n"
+ "</table>\n"
+ "\n"
+ "Funding: \n"
+ "\n"
+ "NIDA U01 DA\n"
+ "\n"
;
var script = document.querySelector('script[src="hrdp_oxy.js"]');
var section = document.createElement('section');
script.parentNode.appendChild(section);
section.appendChild(document.createTextNode(markdownContent));
[].forEach.call(script.attributes, function (attr) {
    section.setAttribute(attr.name, script.getAttribute(attr.name));
});
section.setAttribute('data-markdown', '');
})();
