(function () {
'strict'
var markdownContent = ''
+ "\n"
+ "\n"
+ "# Genetic Factors Influencing Individual Differences in Vulnerability to Oxycodone in Rats\n"
+ "\n"
+ "<hr color=orange>\n"
+ "\n"
+ "## Hao Chen, Ph.D.\n"
+ "### Professor\n"
+ "\n"
+ "### Department of Pharmacology, Addiction Science and Toxicology, University of Tennessee Health Science Center\n"
+ "\n"
+ "\n"
+ "---\n"
+ "## Oxycodone is highly addictive \n"
+ "### even when it is not injected\n"
+ "\n"
+ "---\n"
+ "## Early prevention is key \n"
+ "\n"
+ "Preaddiction\n"
+ "\n"
+ "---\n"
+ "## Oral self-administration of oxycodone in rats\n"
+ "\n"
+ "\n"
+ "---\n"
+ "## Genetic factors influnce vulnerability to opioid addiction \n"
+ "\n"
+ "---\n"
+ "## Hybrid rat diversity panel\n"
+ "\n"
+ "\n"
+ "---\n"
+ "## Whole genome sequencing of the HRDP\n"
+ "\n"
+ "---\n"
+ "## Phenotypic variance of oxycodone self-administartion in HRDP\n"
+ "\n"
+ "---\n"
+ "## Correlations between oxycodone and other behavioral traits\n"
+ "\n"
+ "---\n"
+ "## Genetic mapping of substance use related traits in rats\n"
+ "### Socialy acquired nicotine intravenous self-admistration\n"
+ "\n"
+ "---\n"
+ "## Using literature mining to indentify biologically relevant candidate genes\n"
+ "\n"
+ "---\n"
+ "## Using snRNA-seq to identify cell types involved behavioral traits\n"
+ "\n"
+ "---\n"
+ "## Using in-vivo genome editing to confirm causal relationships \n"
+ "\n"
+ "---\n"
+ "## Validating causal relationship using cell-type specific genome editing\n"
+ "\n"
+ "---\n"
+ "## Summary\n"
+ "\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Acknowledgements\n"
+ "\n"
+ "* Current lab members working on this project \n"
+ "\n"
+ "<table><tr>\n"
+ "\n"
+ "<td width=25%>\n"
+ "<img src=\"images/photos/shuangying.jpg\">\n"
+ "Shuangying Leng\n"
+ "</td>\n"
+ "\n"
+ "\n"
+ "<td width=25%>\n"
+ "<img src=\"images/photos/angel.jpg\">\n"
+ "Angel Garcia Martinez\n"
+ "</td>\n"
+ "\n"
+ "<td width=25%>\n"
+ "<img src=\"images/photos/caroline.jpg\">\n"
+ "Caroline Jones \n"
+ "</td>\n"
+ "\n"
+ "</tr>\n"
+ "</table>\n"
+ "\n"
+ "Funding: \n"
+ "\n"
+ "NIDA U01 DA\n"
+ "\n"
;
var script = document.querySelector('script[src="hrdp_oxy.js"]');
var section = document.createElement('section');
script.parentNode.appendChild(section);
section.appendChild(document.createTextNode(markdownContent));
[].forEach.call(script.attributes, function (attr) {
    section.setAttribute(attr.name, script.getAttribute(attr.name));
});
section.setAttribute('data-markdown', '');
})();
