(function () {
'strict'
var markdownContent = ''
+ "\n"
+ "# Genetic factors influencing individual differences in vulnerability to oxycodone in rats\n"
+ "\n"
+ "<hr color=orange>\n"
+ "\n"
+ "## Hao Chen, Ph.D.\n"
+ "#### Professor\n"
+ "\n"
+ "#### Department of Pharmacology, Addiction Science and Toxicology, University of Tennessee Health Science Center\n"
+ "\n"
+ "March 21, 2024\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Oxycodone is highly addictive \n"
+ "\n"
+ "* Rapid intravenous infusion of abused drugs produces greater subjective effects than slow infusion.\n"
+ "* It has been claimed that delayed absorption of oxycodone reduces its abuse liability.\n"
+ "* Oxycodone has strong addiction liability even when it is delivered orally in controlled-release formulation.\n"
+ "* Prescription oral oxycodone is a major contributor to the current opioid abuse epidemic.\n"
+ "\n"
+ "Note:\n"
+ "\n"
+ "In both animal and human studies, it has been found that, for abused substances, the route of administration is one of the  determining factors of their abuse liability. Strong euphoria is usually produced by the rapid pharmacokinetics in the brain following intravenous injection or inhalation. \n"
+ "Pharmaceutical companies have argued that the controlled release of oxycodone delivered orally is very safe and widely promoted its clinical use for pain management, which led to the current opioid epidemic.\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Early intervention is critical for ending an epidemic\n"
+ "\n"
+ "* Individual differences in vulnerability to opioids.\n"
+ "* Both genetic and environmental factor contribute to vulnerability to opioids.\n"
+ "* Animal models can help identifying genetic vulnerability to opioid abuse.   \n"
+ "\n"
+ "Note:\n"
+ "\n"
+ "There is large individual differences in the progression from opioid use to abuse. Not all individuals receive prescription oxycodone become addicted to opioids. Only some of them transition to compulsive use and addiction. Both genetic and environmental factor contribute to vulnerability to opioids.\n"
+ "While the study of substance use in human is bounded by many ethical considerations, animal models can help identify individuals carry genetic vulnerability to opioids and environmental factors exacerbate these vulnerabilities. Animal studies can also identify causal molecular mechanisms. \n"
+ "These knowledge can contribute to the early intervention that is needed for ending this epidemic\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Oral self-administration of oxycodone in rats\n"
+ "\n"
+ "<table> <tr><td width=40%>\n"
+ "<img src=\"./images/oxycodone/oxycodone_operant_chamber.png\">\n"
+ "</td>\n"
+ "<td>\n"
+ "\n"
+ "<li> Operant licking procedure, one session per day\n"
+ "<li> Gradual increase in session length and oxycodone dose \n"
+ "<li> No water or food restrictions, no drug pre-exposure\n"
+ "\n"
+ "<img src=\"./images/oxycodone/oxycodone_hrdp_schedule.png\">\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Sharp et. al., Genes Brain Behav, 2021</span>\n"
+ "\n"
+ "\n"
+ "</td>\n"
+ "</tr></table>\n"
+ "\n"
+ "Note:\n"
+ "To model voluntary oxycodone use in rats, we developed an oral oxycodone self-administration procedure. \n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Hybrid rat diversity panel\n"
+ "<img src=\"./images/ratGenome/HRDP_1000x357.png\">\n"
+ "\n"
+ "RI panels provide mapping power | Classic inbreds provide mapping resolution\n"
+ "<p align=center>\n"
+ "<span id=\"cite\"> Tabakoff, Saba, et al.  Methods Mol Biol. 2019 </span>\n"
+ "<br>\n"
+ "Available from Medical College of Wisconsin\n"
+ "\n"
+ "\n"
+ "\n"
+ "---\n"
+ "## Whole genome sequencing of the HRDP\n"
+ "<table><tr>\n"
+ "\n"
+ "<td width=60%>\n"
+ "<img src=\"./images/ratGenome/Figure6_phylogenetic_tree_color.svg\"> \n"
+ "</td>\n"
+ "\n"
+ "<td>\n"
+ "<img src=\"./images/ratGenome/hrdp_variant_stat.png\" width=60%>\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> de Jong et. al., Cell Genomics, in press</span>\n"
+ "\n"
+ "\n"
+ "</td>\n"
+ "</tr></table>\n"
+ "\n"
+ "---\n"
+ "#### Oxycodone self-administration in rats\n"
+ "## Number of licks, all strains combined by sex \n"
+ "\n"
+ "<img src=\"./images/oxycodone/hrdp_oxycodone_oral_operant_self-admin_summary_plot-0.png\">\n"
+ "\n"
+ "---\n"
+ "#### Oxycodone self-administration in rats\n"
+ "## Rewards and intake, all strains combined by sex \n"
+ "\n"
+ "<img src=\"./images/oxycodone/hrdp_oxycodone_oral_operant_self-admin_summary_plot-1.png\">\n"
+ "\n"
+ "\n"
+ "---\n"
+ "#### Oxycodone self-administration in rats\n"
+ "## Individual differences in initiation \n"
+ "\n"
+ "<img src=\"./images/oxycodone/hrdp_oxycodone_oral_operant_self-admin_summary_plot-2.png\">\n"
+ "\n"
+ "\n"
+ "---\n"
+ "#### Oxycodone self-administration in rats\n"
+ "## Individual differences in stable intake, 4h \n"
+ "\n"
+ "<img src=\"./images/oxycodone/hrdp_oxycodone_oral_operant_self-admin_summary_plot-3.png\">\n"
+ "\n"
+ "\n"
+ "---\n"
+ "#### Oxycodone self-administration in rats\n"
+ "## Individual differences in escalated intake with extended availability, 16h \n"
+ "\n"
+ "<img src=\"./images/oxycodone/hrdp_oxycodone_oral_operant_self-admin_summary_plot-4.png\">\n"
+ "\n"
+ "---\n"
+ "#### Oxycodone self-administration in rats\n"
+ "## Individual differences in motivation for oxycodone \n"
+ "\n"
+ "<img src=\"./images/oxycodone/hrdp_oxycodone_oral_operant_self-admin_summary_plot-5.png\">\n"
+ "\n"
+ "\n"
+ "---\n"
+ "#### Oxycodone self-administration in rats\n"
+ "## Individual differences in cue-induced relapse \n"
+ "<img src=\"./images/oxycodone/hrdp_oxycodone_oral_operant_self-admin_summary_plot-8.png\">\n"
+ "---\n"
+ "\n"
+ "## Correlations between sexes \n"
+ "\n"
+ "<img src=\"./images/oxycodone/oxyu01_correlation_between_sexes_progressreport.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Correlations between oxycodone and other behavioral traits\n"
+ "\n"
+ "<b>females</b>\n"
+ "<br>\n"
+ "<img src=\"./images/oxycodone/oxy_nic_ethovision_corrrelation_females.png\" width=120%>\n"
+ "\n"
+ "<p>\n"
+ "\n"
+ "<b>males</b>\n"
+ "<br>\n"
+ "<img src=\"./images/oxycodone/oxy_nic_ethovision_corrrelation_males.png\">\n"
+ "\n"
+ "---\n"
+ "## Genetic mapping of substance use related traits in rats\n"
+ "### Socially acquired <font color=\"red\">nicotine</font> intravenous self-administration\n"
+ "\n"
+ "<img src=\"./images/p50/porcupine_plot_nicotine.png\">\n"
+ "\n"
+ "\n"
+ "<p align=center>\n"
+ "<span id=\"cite\"> Chitre, Palmer et. al., unpublished</span>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "##  Literature mining for biologically relevant candidate genes |  https://genecup.org \n"
+ "\n"
+ "<a href=\"https://genecup.org/cytoscape/?rnd=tmpDYEQAw&genequery=Shtn1_Gria4_Arhgef7_Alg8\" target=_new>\n"
+ "<img src=\"./images/p50/genecup_4_candidates.svg\" width=80%>\n"
+ "</a>\n"
+ "\n"
+ "<p align=center>\n"
+ "<span id=\"cite\"> Gunturkun, et. al., G3, 2022</span>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Combining brain region or cell type specific gene expression to identify candidate genes\n"
+ "\n"
+ "<table> <tr>\n"
+ "<td width=50% align=\"right\">\n"
+ "<img src=\"./images/p50/violinplot0-save.svg\">\n"
+ "\n"
+ "<p align=right>\n"
+ "<span id=\"cite\"> Munro, Palmer et. al., Nucleic Acid Res. 2022</span>\n"
+ "\n"
+ "\n"
+ "\n"
+ "</td>\n"
+ "\n"
+ "<td width=50%>\n"
+ "<img src=\"./images/deep_learning/snRNAseq_PFC_cell_type.png\" width=60%>\n"
+ "</td>\n"
+ "</table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Validating causal relationship using cell-type specific genome editing\n"
+ "\n"
+ "<table><tr>\n"
+ "\n"
+ "<td width=50%>\n"
+ "<img src=\"./images/pde4b/percent_mutation_pde4b_gRNA.png\">\n"
+ "</td>\n"
+ "<td>\n"
+ "<img src=\"./images/pde4b/pde4b_aav_nac.png\">\n"
+ "</td>\n"
+ "\n"
+ "</tr></table>\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Sharp et. al., BioRxiv, 2023</span>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Summary\n"
+ "\n"
+ "* Oral oxycodone self-administration captures some key features of opioid use disorder \n"
+ "* Large phenotypic differences in oxycodone between inbred strains \n"
+ "* The rat is a powerful model organism to dissect the molecular mechanisms underlying SUD \n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Acknowledgements\n"
+ "\n"
+ "####  Current lab members working on this project \n"
+ "\n"
+ "<table><tr>\n"
+ "\n"
+ "<td width=20%>\n"
+ "<img src=\"images/photos/shuangying.jpg\">\n"
+ "Shuangying Leng\n"
+ "</td>\n"
+ "\n"
+ "\n"
+ "<td width=20%>\n"
+ "<img src=\"images/photos/Caroline.png\">\n"
+ "Caroline Jones \n"
+ "</td>\n"
+ "\n"
+ "\n"
+ "<td width=20%>\n"
+ "<img src=\"images/photos/angel.jpg\">\n"
+ "Angel Garcia Martinez\n"
+ "</td>\n"
+ "\n"
+ "\n"
+ "\n"
+ "<td width=20%>\n"
+ "<img src=\"images/photos/tristan.jpg\">\n"
+ "Tristan de Jong\n"
+ "</td>\n"
+ "\n"
+ "\n"
+ "</tr>\n"
+ "</table>\n"
+ "\n"
+ "<p>\n"
+ "\n"
+ "#### Collaborators\n"
+ "\n"
+ "\n"
+ "* Burt M Sharp | Megan K Mulligan | Robert W Williams (UTHSC)\n"
+ "* Abraham A Palmer  (UCSD)\n"
+ "\n"
+ "Funding: NIDA U01DA053672 | U01U01DA047638 |   1U01DA057530 | P50DA037844 |  R01DA048017 \n"
+ " \n"
+ "\n"
;
var script = document.querySelector('script[src="hrdp_oxy.js"]');
var section = document.createElement('section');
script.parentNode.appendChild(section);
section.appendChild(document.createTextNode(markdownContent));
[].forEach.call(script.attributes, function (attr) {
    section.setAttribute(attr.name, script.getAttribute(attr.name));
});
section.setAttribute('data-markdown', '');
})();
