(function () {
'strict'
var markdownContent = ''
+ "# Socially acquired nicotine self-administration\n"
+ "\n"
+ "## moving from GWAS to molecular and circuit mechanisms\n"
+ "\n"
+ "<hr color=orange >\n"
+ "\n"
+ "### Hao Chen, Ph.D.\n"
+ "\n"
+ "#### Department of Pharmacology, Addiction Science and Toxicology\n"
+ "\n"
+ "#### University of Tennessee Health Science Center\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Outline\n"
+ "\n"
+ "- Behavior features of the model\n"
+ "- Highlight a few GWAS findings\n"
+ "- Planned molecular and circuits studies\n"
+ "\n"
+ "Note:\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Initial experience of tobacco is primarily <font color=\"firebrick\">aversive</a>\n"
+ "\n"
+ "### and occurred in small groups\n"
+ "\n"
+ "<img src=\"./images/hs/smoking_initial_response.png\" width=60%>\n"
+ "\n"
+ "<div id=\"cite\"> Hahn, Addictive behaviors, 1990</div,\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nicotine conditioned taste <font color=\"firebrick\">aversion</font> in rats\n"
+ "\n"
+ "<img src=\"./images/hs/nicotine_cta_bjpharm1983.png\" width=70%>\n"
+ "\n"
+ "<span id=\"cite\"> Kumar, et. al., Br J Pharmac 1983</span>\n"
+ "\n"
+ "Note: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2044849/?page=3\n"
+ "flavors: sodium sacchaine vs sodium chloride\n"
+ "water access were limited to 1 h per day. flavors were presented every other day, followed by nicotine vs saline injection.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nicotine is <font color=\"firebrick\"> reinforcing </font>\n"
+ "\n"
+ "<img src=\"./images/hs/corrigall_1989_nicotine.png\" width =60% >\n"
+ "\n"
+ "<div id=\"cite\"> Corrigall, Psychopharm, 1989</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<span id=\"solo\">\n"
+ "\n"
+ "## Flavor cues conditioned to self-administered nicotine is aversive\n"
+ "\n"
+ "<a href=\"#/demo\">\n"
+ "<img height:auto width=90% src=\"images/hs/flavorcue_conditioned_aversion.png\">\n"
+ "</a>\n"
+ "\n"
+ "<span id=\"cite\"> Chen, et al., Neuropsychopharmacology, 2011 </span>\n"
+ "\n"
+ "Note:\n"
+ "One way you can study this is by combining conditioned taste aversion with i.v. self-administraion.\n"
+ "adolescent rats developed conditioned aversion to an appetitive flavor cue (saccharine + grape odor) associated with self-administered i.v. nicotine. In this operant <i>licking</i> model, oral flavor cue and <strong>i.v.</strong> nicotine were delivered simultaneously upon the completion of a fixed-ratio 5 reinforcement schedule.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<span id=\"demo\">\n"
+ "\n"
+ "## Social learning enables nicotine self-administration\n"
+ "\n"
+ "### in adolescent <font color=\"firebrick\">Sprague-Dawley </a> rats\n"
+ "\n"
+ "<a href=\"#/solo\">\n"
+ "<img height:auto width=100% src=\"images/hs/socially_acquired_nicotine_ivsa.png\">\n"
+ "</a>\n"
+ "\n"
+ "<span id=\"cite\"> Chen, et al., Neuropsychopharmacology, 2011 </span>\n"
+ "\n"
+ "Note:\n"
+ "However, with the presence of a \"demonstrator\" rat consuming the same flavor cue, nicotine i.v. self-administration was established.\n"
+ "No water or food deprivation or operant pretraining is needed. Thus the model is appropriate for studying smoking initiation in adolescents.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Social learning supports nicotine IVSA with an <font color=\"firebrick\"> aversive </font> flavor cue\n"
+ "\n"
+ "<table style=\"border-collapse: collapse; border: none;\" >\n"
+ "<tr><td width=15% valign=\"middle\" style=\"border: none;\">Social, Non-learning</td>\n"
+ "                        <td rowspan=2>\n"
+ "<img width=90% src=\"images/hs/ise_nse_aversivecue.png\">\n"
+ "</td></tr>\n"
+ "<tr><td width=15% valign=\"middle\" style=\"border: none;\">Social, Learning</td></tr></table>\n"
+ "\n"
+ "<span id=\"cite\"> Wang, et al., Psychopharmacology, 2016 </span>\n"
+ "\n"
+ "</p>\n"
+ "\n"
+ "Note:\n"
+ "To further demonstrate that the appetitiveness of flavor cue is driving nicotine intake in our model, we replace the saccyhrine cue with a quinine cue. The bitterness of quinine is often used to show rats with self-administration history that will resist the punishment in order to obtain drug. Here we paired it as a contingent cue at the begining of nicotine self-administration. We also improved our control by adding a demonstration rat on the left side of the operant chamber.\n"
+ "<b>NSE</b>: neutral social environemnt, i.e., the presence of a companion rat.\n"
+ "<b>ISE</b>: indusive social environment, i.e., the presences of a companion rat who has access to the flavor cue.\n"
+ "<b>AV</b>: audiovisual cue\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Operant behavior is driven by <font color=\"firebrick\"> nicotine </font>\n"
+ "\n"
+ "<b> NOT by the subjective value of the flavor cue</b>\n"
+ "\n"
+ "<img width=50% src=\"images/hs/pres.sacc_quinine.png\">\n"
+ "\n"
+ "<span id=\"cite\"> Wang, et al., Psychopharmacology, 2016 </span>\n"
+ "\n"
+ "</p>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## What is the <font color=\"firebrick\"> social signal </font>?\n"
+ "\n"
+ "<img width=50% src=\"./images/hs/Fig1.social.rats.withdemo.svg\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## <font color=\"firebrick\"> Carbon disulfide</font> and flavor cue are both required\n"
+ "\n"
+ "<img width=100% height=\"auto\" src=\"images/hs/cs2_1rat.png\">\n"
+ "\n"
+ "<span id=\"cite\"> Wang, et al., PLoS One, 2014 </span>\n"
+ "\n"
+ "</p>\n"
+ "\n"
+ "Note:\n"
+ "We confirmed that neither nicotine associated flavor cue nor carbon disulfide alone supported nicotine IVSA. However, their combination was sufficient to replicate the behavior induced by live demonstrator rats.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nicotine intake is heritable\n"
+ "\n"
+ "### <font color=\"firebrick\">isogenic strains </font> across two doses\n"
+ "\n"
+ "### h<sup>2</sup>=0.54-0.65\n"
+ "\n"
+ "<img src=\"./images/hs/social_nicotine_dose_isogenic_strain.png\" width=80%>\n"
+ "\n"
+ "<span id=\"cite\"> Han, et al., Sci Report, 2017 </span>\n"
+ "\n"
+ "</p>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"cta1\">\n"
+ "\n"
+ "## Social learning facilitates the <font color=\"firebrick\">extinction</font>\n"
+ "\n"
+ "### of conditioned nicotine aversion\n"
+ "\n"
+ "<img src=\"./images/hs/correlation_ext_cta_nicotine.png\" width=80% >\n"
+ "\n"
+ "<span id=\"cite\"> Han, et al., Sci Report, 2017 </span>\n"
+ "\n"
+ "</p>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Social learning enhanced the <font color=\"firebrick\"> hedonic value </font> of nicotine\n"
+ "\n"
+ "<img src=\"./images/hs/lick_timing_clusers.png\" width=60%>\n"
+ "\n"
+ "<img src=\"./images/hs/sansa_cluster_size.png\" width=60%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Socially acquired nicotine IVSA in adolescent rats\n"
+ "\n"
+ "### Summary\n"
+ "\n"
+ "<ul>\n"
+ "<li> This model incorporates the aversive and reinforcing properties of nicotine\n"
+ "<li> Operant responding is driven by the reinforcing property of nicotine \n"
+ "<li> Flavor cue is associated with the aversive properties of nicotine\n"
+ "<li> Social learning facilitates the extinction of conditioned aversion and reverses the hedonic value of nicotine\n"
+ "</ul>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Heterogeneous stock rats\n"
+ "\n"
+ "<img src=\"./images/hs/hs_ratgenesorg.png\" width=60%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<div id=\"ofdiagram\">\n"
+ "\n"
+ "## Phenotyping pipeline\n"
+ "\n"
+ "### adolescent <font color=\"firebrick\"> heterogeneous stock rats</font>\n"
+ "\n"
+ "<table> <tr><td width=30%>\n"
+ "\n"
+ "<img src=\"./images/hs/openfields_verticle.png\">\n"
+ "\n"
+ "</td><td>\n"
+ "\n"
+ "<font size=4>\n"
+ "\n"
+ "| Age         | Test                                 |\n"
+ "| ----------- | ------------------------------------ |\n"
+ "| PND21       | Wean, Body weight                    |\n"
+ "| PND31       | Open field test (20min)              |\n"
+ "| PND32       | Novel object interaction (20min)     |\n"
+ "| PND33       | Social interaction test (20 min)     |\n"
+ "| PND34       | Elevated plus maze (6min)            |\n"
+ "| PND38       | Surgery                              |\n"
+ "| PND39 -- 41 | Recovery                             |\n"
+ "| PND42 -- 51 | Socially acquired nicotine IVSA      |\n"
+ "| PND52       | Progressive ratio test               |\n"
+ "| PND53 -- 56 | Extinction                           |\n"
+ "| PND57       | Contextual cue induced reinstatement |\n"
+ "| PND59       | Tissue Collection for the IVSA rats  |\n"
+ "\n"
+ "</font>\n"
+ "\n"
+ "</td></tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Social interaction test\n"
+ "\n"
+ "<img src=\"./images/hs/social_interaction_chamber.png\" width=60%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## GWAS in social interaction test\n"
+ "\n"
+ "<img src=\"./images/hs/socal_gwas_porcupine_v6.png\" width=90%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## GWAS: duration on social zone\n"
+ "\n"
+ "<table> <tr> <td width=50%>\n"
+ "<p align=\"center\">\n"
+ "\n"
+ "<img src=\"./images/hs/social_zone_duration_manh_0-9.png\" width=90%>\n"
+ "\n"
+ "</p>\n"
+ "</td>\n"
+ "<td>\n"
+ "<p align=\"center\">\n"
+ "<img src=\"./images/hs/social_zone_duration_locuszome_0-3.png\" width=100%>\n"
+ "</p>\n"
+ "</td>\n"
+ "</tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## GWAS: nicotine self-administration\n"
+ "\n"
+ "<img src=\"./images/hs/nicotine_porcupine_2025.png\" width=80%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Human orthologs significant for smoking behavior\n"
+ "\n"
+ "<table> <tr><td width=50%>\n"
+ "\n"
+ "### total licks on active spout\n"
+ "\n"
+ "<p align=\"center\">\n"
+ "<img src=\"./images/hs/total_active_10days_chr5.png\" width=100%>\n"
+ "</p>\n"
+ "</td>\n"
+ "<td width=50%>\n"
+ "\n"
+ "### breakpoint\n"
+ "\n"
+ "<p align=\"center\">\n"
+ "<img src=\"./images/hs/pr_infusion_5.png\" width=100%>\n"
+ "</p>\n"
+ "\n"
+ "</td>\n"
+ "</tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Regression of nicotine intake by session\n"
+ "\n"
+ "<table> <tr><td width=53%>\n"
+ "\n"
+ "<p align=\"center\">\n"
+ "<img src=\"./images/hs/intercept_chr4_manhattan.png\" width=100%>\n"
+ "                            </p>\n"
+ "                        </td>\n"
+ "<td width=47%>\n"
+ "\n"
+ "<p align=\"center\">\n"
+ "\n"
+ "<img src=\"./images/hs/nicotine_analysis_combined.png\" width=100%>\n"
+ "\n"
+ "</p>\n"
+ "\n"
+ "</td>\n"
+ "</tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Locus zoom plot showing <font color=\"firebrick\"> <i>Cacna1c</i></font>\n"
+ "\n"
+ "<p align=\"center\">\n"
+ "<img src=\"./images/hs/intercept_chr4_cacna1c.png\" width=70%>\n"
+ "   </p>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Literature on candidate genes\n"
+ "\n"
+ "### https://genecup.org\n"
+ "\n"
+ "<p align=\"center\">\n"
+ "\n"
+ "<img src=\"./images/hs/genecup_graph.svg\" width=60%>\n"
+ "</p>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Cacna1c haploinsufficiency causes deficits in social reward\n"
+ "\n"
+ "Males <img src=\"./images/hs/dmm-11-034116-g2.jpg\" width=70%>\n"
+ "<br>\n"
+ "Females <img src=\"./images/hs/cacna1c_hapin_social.png\" width=70%>\n"
+ "\n"
+ "<span id=\"cite\">\n"
+ "Kisko, et al, GBB 2018; DMM 2018\n"
+ "</span>\n"
+ "---\n"
+ "\n"
+ "## Pharmacological blocking Cav1.2\n"
+ "\n"
+ "### isradipine 1.2 mg/kg, i.p. 10 min before the session\n"
+ "\n"
+ "### Sprague-Dawley rats\n"
+ "\n"
+ "<p align=\"center\">\n"
+ "<img src=\"./images/hs/isradipine_nicotine.png\" width=50%>\n"
+ "    </p>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## <font color=\"firebrick\"> Oxytocin </font> signaling\n"
+ "\n"
+ "### mediates socially acquired nicotine self-administration.\n"
+ "\n"
+ "<img src=\"./images/hs/ota_icv.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Where in the brain can Cacna1c and Oxtr interact?\n"
+ "\n"
+ "<img src=\"./images/hs/sagital_view_olf_amy_pvn_bnst_mhb.svg\" width=80%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## CeA GABAergic neurons underlie social extinction of nicotine aversion\n"
+ "\n"
+ "<p align=\"center\">\n"
+ "\n"
+ "<img src=\"./images/hs/snRNA_cacna1c_gaba.png\" width=50%>\n"
+ "\n"
+ "</p>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## CeA GABAergic neurons express Cacna1c and Oxtr\n"
+ "\n"
+ "<img src=\"./images/hs/dean_oxtr_gad_cacna1c.png\" width=70%>\n"
+ "\n"
+ "<div id=\"cite\"> Dean Kirson, unpublished</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Social environment determines the hedonic value of nicotine via molecular and cellular networks in the amygdala\n"
+ "\n"
+ "#### Aim 1: To test the hypothesis that Cacna1c is required for SANSA (Chen)\n"
+ "\n"
+ "Behavior/snRNA-seq\n"
+ "\n"
+ "#### Aim 2: To test the hypothesis that oxytocin signaling is required for SANSA (Tunstall)\n"
+ "\n"
+ "Fiberphotometry/Optogenetics\n"
+ "\n"
+ "#### Aim 3: To establish the role of cellular and molecular interaction between hypothalamic oxytocin neurons and CeA GABAergic neurons in facilitating SANSA (Kirson)\n"
+ "\n"
+ "E-phyis/RNA-scope\n"
+ "\n"
+ "<img src=\"./images/hs/sansa_exp_design.png\" width=60%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## <font color=\"firebrick\"> Bluetooth optogenetics</font> testing unit\n"
+ "\n"
+ "<div class=\"video-container rounded-lg \">\n"
+ "        <iframe\n"
+ "            src=\"https://drive.google.com/file/d/1p7bIONUhk24vpkPBEahnvDFHGTBhrS8l/preview\" \n"
+ "            allowfullscreen \n"
+ "            title=\"Blueberry\"\n"
+ "        ></iframe>\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nicotine CPP in juvenile <font color=\"firebrick\"> Zebrafish </font>\n"
+ "\n"
+ "### in a social setting\n"
+ "\n"
+ "<table> <tr><td width=50%>\n"
+ "<img src=\"./images/hs/zebrafish_juvi_cpp.png\">\n"
+ "</td><td>\n"
+ "\n"
+ "<img src=\"./images/hs/zebrafish_cpp.png\">\n"
+ "\n"
+ "</td></tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Acknowledgements\n"
+ "\n"
+ "<table><tr align=center>\n"
+ "\n"
+ "<td width=16.7%>\n"
+ "<img src=\"./images/lab/twang18.jpg\">\n"
+ "Tengfei Wang\n"
+ "</td>\n"
+ "\n"
+ "<td width=16.7%>\n"
+ "<img src=\"./images/lab/angel.jpg\">\n"
+ "Angel G Martinez\n"
+ "</td>\n"
+ "\n"
+ "<td width=16.7%>\n"
+ "<img src=\"./images/lab/caroline.png\">\n"
+ "Caroline Jones\n"
+ "\n"
+ "</td>\n"
+ "\n"
+ "<td width=16.7%>\n"
+ "<img src=\"./images/lab/shuangying.jpg\">\n"
+ "Shuangying Leng\n"
+ "</td>\n"
+ "\n"
+ "<td width=16.7%>\n"
+ "<img src=\"./images/lab/rachel.jpg\">\n"
+ "Rachel Ward\n"
+ "</td>\n"
+ "\n"
+ "<td width=16.7%>\n"
+ "<img src=\"./images/lab/jun.jpg\">\n"
+ "Jun Huang\n"
+ "</td>\n"
+ "\n"
+ "</tr>\n"
+ "</table>\n"
+ "\n"
+ "- Technicians, analysts over the years\n"
+ "  - _Xia Hong_ | _Jie Shen_ | _Wenyan Han_ | _Pawandeep Kaur_ | _Yanyan Lin_ | _Xinyu Fan_ | _Mallory Udell_ | _Gwen Johnson_ | _Hakan Gunturkun_ | Tomomi Green\n"
+ "  - REHU students \\* Abigale Salinero (2015) | Cindy Tay (2016) | Raven David (2017) | Christian Hurt (2018) | Gwen Johnson (2021) | Olivia Harrison (2022, 2023) |\n"
+ "    Ryan Luib (2023)\n"
+ "- P50/P30 collaborators\n"
+ "  - Abraham Palmer | Oksana Polesskaya | Sanches, Thiago | Apurva Chitre | Leah Solberg-Woods\n"
+ "- UTHSC collaborators\n"
+ "  - Branden Tunstall | Dean Kirson | Thirumalini Vaithianathan | Burt Sharp | Rob Williams | and others\n"
+ "\n"
+ "#### Funding: P50DA037844 R01DA063199 U01DA053672 U01DA057530\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## <font color=\"firebrick\"> Consumption vs Seeking </font> licks\n"
+ "\n"
+ "562,000 clusters from oral oxycodone self-administration using inbred rats\n"
+ "\n"
+ "<img src=\"./images/hs/oxy_cluster_consumption_vs_seeking.png\" width=60%>\n"
+ "\n"
+ "Enhanced \"liking\" leads to increased \"wanting\" in individuals with greater increase in inake during long access.\n"
+ "\n"
+ "<div id=\"cite\"> Sharp, Chen, BioRxiv, 2025</div>\n"
+ "\n"
+ "---\n"
;
var script = document.querySelector('script[src="hs11.js"]');
var section = document.createElement('section');
script.parentNode.appendChild(section);
section.appendChild(document.createTextNode(markdownContent));
[].forEach.call(script.attributes, function (attr) {
    section.setAttribute(attr.name, script.getAttribute(attr.name));
});
section.setAttribute('data-markdown', '');
})();
