(function () {
'strict'
var markdownContent = ''
+ "# Socially Acquired Nicotine Self-administration in Rats Identifies Candidate Genes Shared with Human Smoking GWAS\n"
+ "\n"
+ "<hr color=orange >\n"
+ "\n"
+ "## Hao Chen, Ph.D.\n"
+ "\n"
+ "### Department of Pharmacology, Addiction Science and Toxicology\n"
+ "\n"
+ "### University of Tennessee Health Science Center\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nicotine is primarily aversive in non-smokers\n"
+ "\n"
+ "<table>\n"
+ " <tr>\n"
+ " <td width=50%>\n"
+ " <img width=100% src=\"images/titlepages/eissenberg.png\">\n"
+ " </td>\n"
+ " <td width=90%>\n"
+ " <img width=100% src=\"images/titlepages/dkalman.png\">\n"
+ " </td>\n"
+ " </tr>\n"
+ " <tr>\n"
+ " <td>\n"
+ " Nausea, dizziness, sickness, headache, etc..\n"
+ " </td>\n"
+ " <td>\n"
+ " Nicotine induces drug high only in <em>significantly nicotine-deprived smokers</em>. \n"
+ " </td>\n"
+ " </tr>\n"
+ "</table>\n"
+ "\n"
+ "Note:\n"
+ "We all know nicotine the principal psychoactive compn of tabacco products and smoking ciagrettes is higly addicitive. However, unlikely other addicive sustances, nicotine does not produce strong euhphorian. Not only that, it also has has strong aversive properties. This aversiveness is especially promimant in non-smokers, or in otherwords, for people start experimenting with tobacco. New smokers experience diziness, sickness\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nicotine conditioned taste aversion in rats\n"
+ "\n"
+ "<img src=\"./images/nicotine_cta_bjpharm1983.png\" width=60%>\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Kumar, et. al., Br J Pharmac 1983</span>\n"
+ "\n"
+ "Note: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2044849/?page=3\n"
+ "flavors: sodium sacchaine vs sodium chloride\n"
+ "water access were limited to 1 h per day. flavors were presented every other day, followed by nicotine vs saline injection.\n"
+ "\n"
+ "Here is a rat study published 30 years ago. These authors give rats access to flavord solutions after give them nicotine or saline injectios. After the injection and flavor are paired four times, they then tested the rats for preference between the two flavors. At the low does tested, rats did not show a preference. But at the middle and high dose, rats showed strong avoidance to the flavor paird with nicotine, not only during the test session, but even during the training sessins. These data clearly demonstrated that nicotine has aversive properies in rats. And these does, espeically the middle does, is not a high. In fact, that amout of nicotine equals to three infusins in most self-administration stuides. So one question is if self-administred nicotine also procues aversive response.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<span id=\"solo\">\n"
+ "\n"
+ "## Flavor cues conditioned to self-administered nicotine is aversive\n"
+ "\n"
+ "<a href=\"#/demo\">\n"
+ "<img height:auto width=90% src=\"images/p50/flavorcue_conditioned_aversion.png\">\n"
+ "</a>\n"
+ "\n"
+ "Adolescent Sprague Dawley females\n"
+ "\n"
+ "<p align=\"left\">\n"
+ "<span id=\"cite\"> Chen, et al., Neuropsychopharmacology, 2011 </span>\n"
+ "\n"
+ "Note:\n"
+ "One way you can study this is by combining conditioned taste aversion with i.v. self-administraion.\n"
+ "adolescent rats developed conditioned aversion to an appetitive flavor cue (saccharine + grape odor) associated with self-administered i.v. nicotine. In this operant licking model, oral flavor cue and iv nicotine were delivered simultaneously upon the completion of a fixed-ratio 10 reinforcement schedule.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Social influence is a key factor in smoking initiation\n"
+ "\n"
+ "<div id=\"left50\" >\n"
+ "<img width=100% src=\"images/titlepages/hoffman.png\"> \n"
+ "</div>\n"
+ "<div id=\"right50\">\n"
+ "<img width=100% src=\"images/titlepages/jfowler.png\"> \n"
+ "</div>\n"
+ "\n"
+ "Note:\n"
+ "Now that we established self-administered nicotine is aversive, the question then is why do invididuals take it? In humans, a lot of research points out that social environment is a key.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Social transmission of food preference in rats\n"
+ "\n"
+ "<img src=\"images/galef.protocol.narrower.png\" width=50%>\n"
+ "\n"
+ "<p align=\"left\">\n"
+ "<span id=\"cite\">Galef, Curr Protoc Neurosci, 2003</span>\n"
+ "\n"
+ "Note:\n"
+ "In rats, there is also a long tradition of studying social learning. The particular procedure is called STFP. It takes advantage to the fact that rats are neophobic when it comes to novel foods. This is a three stage protocol.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<span id=\"demo\">\n"
+ "\n"
+ "## Social learning enables nicotine self-administration\n"
+ "\n"
+ "<a href=\"#/solo\">\n"
+ "<img height:auto width=100% src=\"images/socially_acquired_nicotine_ivsa.png\">\n"
+ "</a>\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Chen, et al., Neuropsychopharmacology, 2011 </span>\n"
+ "\n"
+ "Note:\n"
+ "However, with the presence of a \"demonstrator\" rat consuming the same flavor cue, nicotine i.v. self-administration was established.\n"
+ "No water or food deprivation or operant pretraining is needed. Thus the model is appropriate for studying smoking initiation in adolescents.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## IVSA is driven by nicotine\n"
+ "\n"
+ "#### NOT by the subjective value of the flavor cue\n"
+ "\n"
+ "<img width=35% src=\"images/p50/4.sacc.v.quinine_only.png\">\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Wang, et al., Psychopharmacology, 2016 </span>\n"
+ "</p>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## IVSA is driven by nicotine\n"
+ "\n"
+ "#### NOT by the subjective value of the flavor cue\n"
+ "\n"
+ "<img width=35% src=\"images/p50/4.sacc.v.quinine.png\">\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Wang, et al., Psychopharmacology, 2016 </span>\n"
+ "</p>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## What is transmitted from the demonstrator?\n"
+ "\n"
+ "<img src=\"./images/Fig1.social.rats.withdemo.svg\" width=40%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Social learning is mediated by Carbon Disulfide (CS<sub>2</sub>) in rats\n"
+ "\n"
+ "<div id=\"left50\">\n"
+ "            <center>\n"
+ "<img height:auto width=80% src=\"images/galef.protocol.narrower.png\">\n"
+ "            </center>\n"
+ "<br>\n"
+ "</div>\n"
+ "\n"
+ "<div id=\"right50\">\n"
+ "<img height:auto width=80% src=\"images/titlepages/cs2.png\">\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Both CS<sub>2</sub> and flavor cue are necessary for socially acquired nicotine IVSA\n"
+ "\n"
+ "<img height=\"auto\" src=\"images/p50/cs2_1rat.png\" width=70%>\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Wang, et al., PLoS One, 2014 </span>\n"
+ "</p>\n"
+ "\n"
+ "Note:\n"
+ "We confirmed that neither nicotine associated flavor cue nor carbon disulfide alone supported nicotine IVSA. However, their combination was sufficient to replicate the behavior induced by live demonstrator rats.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Heterogeneous stock rats\n"
+ "\n"
+ "<table><tr><td width=80%>\n"
+ "<center> <img src=\"./images/p50/hs_rats.png\" width=60%> </center> <p align=left>\n"
+ "<span id=\"cite\"> Garret and Korstanje, Trends Genet, 2020</span>\n"
+ "\n"
+ "</td>\n"
+ "<td width=20%>\n"
+ "\n"
+ "<img src=\"https://school.wakehealth.edu/-/media/WakeForest/Global/System/Person-Images/l/Leah-Catherine-Solberg-Woods.jpg\">\n"
+ "<b>Leah Solberg Woods <br>Wake Forest School of Medicine </b>\n"
+ "\n"
+ "</td>\n"
+ "</tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<div id=\"ofdiagram\">\n"
+ "\n"
+ "## Behavioral Test Schedule\n"
+ "\n"
+ "<table> <tr><td width=30%>\n"
+ "\n"
+ "<a href=\"#/ethovision_v4_v15\">\n"
+ "<img src=\"./images/p50/openfields_verticle.png\" width=80%> \n"
+ "</a>\n"
+ "\n"
+ "</td><td>\n"
+ "\n"
+ "<font size=4>\n"
+ "\n"
+ "| Age         | Test                                 |\n"
+ "| ----------- | ------------------------------------ |\n"
+ "| PND21       | Wean, Body weight                    |\n"
+ "| PND31       | Open field test (20min)              |\n"
+ "| PND32       | Novel object interaction (20min)     |\n"
+ "| PND33       | Social interaction test (20 min)     |\n"
+ "| PND34       | Elevated plus maze (6min)            |\n"
+ "| PND38       | Surgery                              |\n"
+ "| PND39 -- 41 | Recovery                             |\n"
+ "| PND42 -- 51 | Socially acquired nicotine IVSA      |\n"
+ "| PND52       | Progressive ratio test               |\n"
+ "| PND53 -- 56 | Extinction                           |\n"
+ "| PND57       | Contextual cue induced reinstatement |\n"
+ "| PND59       | Tissue Collection for the IVSA rats  |\n"
+ "\n"
+ "</font>\n"
+ "\n"
+ "</td></tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Genotyping and GWAS\n"
+ "\n"
+ "<table> <tr>\n"
+ "	<td width=50%>\n"
+ "		<p align=\"center\"> <img src=\"./images/p50/AGileta_G3.png\" width=40%> </p>\n"
+ "		<p align=left>\n"
+ "		<span id=\"cite\"> Gileta et al., G3, 2020. </span>\n"
+ "		</p>\n"
+ "	</td>\n"
+ "	<td width=50%>\n"
+ "		<p align=center>\n"
+ "		<img src=\"https://pbs.twimg.com/profile_images/775453143559581697/ECeItK57.jpg\" width=30%>\n"
+ "		<br>\n"
+ "		<b>Abraham Palmer, UCSD</b>\n"
+ "		</p>\n"
+ "		<p>\n"
+ "		<ul>	\n"
+ "			<li> 3.5 million SNPs per individual (estimated error rate <1%)\n"
+ "			<li> GCTA with liner mixed model\n"
+ "			<li> Leave one chromosome out procedure\n"
+ "			<li> Genome-wide significance level set by permuation: -log<sub>10</sub>(p) > 5.6 \n"
+ "		</ul>\n"
+ "	</td>\n"
+ "</tr>\n"
+ "</table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## GWAS: Open Field Test\n"
+ "\n"
+ "n=1857\n"
+ "\n"
+ "<img src=\"images/p50/hs_gwas_openfield_porcupine.png\" width=70%>\n"
+ "<img src=\"images/p50/hs_gwas_openfield_qtlCnt.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## GWAS: Social Interaction\n"
+ "\n"
+ "n=1835\n"
+ "\n"
+ "<img src=\"images/p50/hs_gwas_social_porcupine.png\" width=70%>\n"
+ "<img src=\"images/p50/hs_gwas_social_qtlCnt.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## GWAS: Socially Acquired Nicotine IVSA\n"
+ "\n"
+ "n=1995\n"
+ "\n"
+ "<img src=\"images/p50/hs_gwas_nicsa_porcupine.png\" width=70%>\n"
+ "\n"
+ "<img src=\"images/p50/hs_gwas_nicsa_qtlCnt.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## PheWAS: Social Interaction & Socially Acquired Nicotine IVSA\n"
+ "\n"
+ "<table><tr>\n"
+ "<td width=33%><img src=\"images/p50/hs_gwas_insocdurat.png\"></td>\n"
+ "<td width=33%> <img src=\"images/p50/hs_gwas_nicsa_day1_active.png\"> </td>\n"
+ "<td width=33%> <img src=\"images/p50/hs_gwas_nicsa_first3day_infusion.png\"></td>\n"
+ "</tr></table>\n"
+ "\n"
+ "| SNP PheDb   | -Log10(p)PheDb | R2    | DP    | trait                                                       |\n"
+ "| ----------- | -------------- | ----- | ----- | ----------------------------------------------------------- |\n"
+ "| 4:151964479 | 4.329          | 0.408 | 0.953 | <b>social interaction: in social zone duration, 0-3 min</b> |\n"
+ "| 4:151349337 | 5.04           | 0.959 | 0.982 | nicsa day1 infusion                                         |\n"
+ "| 4:151240226 | 4.057          | 0.798 | 0.995 | nicsa day1 active inactive ratio                            |\n"
+ "| 4:151324325 | 6.15           | 0.966 | 0.987 | nicsa first three days activelick total                     |\n"
+ "| 4:151324325 | 4.78           | 0.966 | 0.987 | nicsa first three days infusion total                       |\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Many QTL are Very Narrow\n"
+ "\n"
+ "<table><tr><td width=50%>\n"
+ "<center>\n"
+ "<br>\n"
+ "<img src=\"./images/p50/hs_gwas_nicsa_day2_infusion.png\">\n"
+ "\n"
+ "</center>\n"
+ "</td><td>\n"
+ "<center>\n"
+ "<br>\n"
+ "<img src=\"./images/p50/hs_gwas_nicsa_day5_infusion.png\"> \n"
+ "</center>\n"
+ "\n"
+ "</td></tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## A Few QTL are Wide\n"
+ "\n"
+ "<img src=\"./images/p50/hs_gwas_nicsa_day1_chr1.png\" width=60%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Multiple Causal Genes in One QTL?\n"
+ "\n"
+ "<img src=\"./images/p50/GCF_015227675.21-GCF_000001405.4010.png\" width=99%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Overlap Between Genes Under Rat Nictotine IVSA QTL\n"
+ "\n"
+ "## and Human Smoking Initiation\n"
+ "\n"
+ "48 unique genes\n"
+ "\n"
+ "<img src=\"images/p50/hs_gwas_nicsa_smoking_init_genes.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Overlap Between Genes Under Rat Nicotine IVSA QTL\n"
+ "\n"
+ "## and Cigarettes per Day\n"
+ "\n"
+ "9 unique genes\n"
+ "\n"
+ "<img src=\"images/p50/hs_gwas_nicsa_cig_per_day_genes.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## LINC02337/TEX29\n"
+ "\n"
+ "Human GWAS: Pack years (Cigarettes per day divided by 20, multiplied by number of years smoking)\n"
+ "\n"
+ "Rat GWAS: Total nicotine infusion\n"
+ "\n"
+ "Common: total overall exposure to tobacco/nicotine.\n"
+ "\n"
+ "<table> <tr> <td width=50%>\n"
+ "<img src=\"./images/p50/arhgef7_locuszoom.png\" width=100%>\n"
+ "\n"
+ "</td>\n"
+ "<td>\n"
+ "\n"
+ "![](./images/gwasv3/tex29_gwas_pack_years.png)\n"
+ "\n"
+ "<!--\n"
+ "<a href=\"https://www.ebi.ac.uk/gwas/variants/rs2026174\" target=_new> New annotation: LINC02337 </a>\n"
+ "\n"
+ "<a href=\"http://genome.ucsc.edu/cgi-bin/hgTracks?db=hg38&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr13%3A110979763%2D112075449&hgsid=1385374851_DFWqHgcyTThiDJV0a0SLgElBbEDP\" target=_new> Is Arhgef7 more likely?</a> Arhgef7 expression is FPKM=30 in our dataset. It is involed in spine morphogenesis. Loss of Arhgef7 results in extensive loss of axons (PMID:30683798, PMID:29891904)\n"
+ "        --->\n"
+ "\n"
+ "<p align=left>\n"
+ "Exome Chip Meta-analysis Fine Maps Causal Variants and Elucidates the Genetic Architecture of Rare Coding Variants in Smoking and Alcohol Use \n"
+ "<span id=\"cite\">Brazel, et. al., Biol Psychiatry 2019</span>\n"
+ "\n"
+ "</td></tr></table>\n"
+ "\n"
+ "Note:\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Novel Candidate Genes for Nicotine IVSA not Reported in Human GWAS\n"
+ "\n"
+ "#### literature search conducted using https://GeneCup.org\n"
+ "\n"
+ "<a href=\"https://genecup.org/cytoscape/?rnd=tmpxUiwWs&genequery=Camk1_Tlr9_Grm2_Trim32_Akap2_Scn3b_Col4a1\">\n"
+ "\n"
+ "<img src=\"./images/p50/genecup_novel_nicotine_genes.png\" width=40%>\n"
+ "\n"
+ "</a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Zebrafish Nicotine Conditioned Place Aversion/Preference Test\n"
+ "\n"
+ "<table><tr><td width=50%>\n"
+ "\n"
+ "<img src=\"./images/zebrafish_chamber.png\">\n"
+ "\n"
+ "</td><td>\n"
+ "\n"
+ "<img src=\"./images/zebrafish_nicotine_cpp_30um_3day.png\">\n"
+ "\n"
+ "</td></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Generating gene knockout zebrafish using base editor\n"
+ "\n"
+ "<img src=\"./images/zebrafish_cbe_tyr_15dpf.png\" width=50%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Acknowledgements\n"
+ "\n"
+ "<table><tr align=center>\n"
+ "\n"
+ "<td width=16.7%>\n"
+ "<img src=\"./images/lab/angel.jpg\">\n"
+ "Angel G Martinez\n"
+ "</td>\n"
+ "<td width=16.7%>\n"
+ "<img src=\"./images/lab/shuangying.jpg\">\n"
+ "Shuangying Leng\n"
+ "</td>\n"
+ "<td width=16.7%>\n"
+ "<img src=\"./images/lab/caroline.png\">\n"
+ "Caroline Jones\n"
+ "</td>\n"
+ "<td width=1>\n"
+ "\n"
+ "<td width=16.7%>\n"
+ "<img src=\"./images/lab/tomi.jpeg\">\n"
+ "Tomomi Green\n"
+ "</td>\n"
+ "\n"
+ "<td width=16.7%>\n"
+ "<img src=\"./images/lab/rachel.jpg\">\n"
+ "Rachel Ward\n"
+ "</td>\n"
+ "\n"
+ "<td width=16.7%>\n"
+ "<img src=\"./images/lab/jun.jpg\">\n"
+ "Jun Huang\n"
+ "</td>\n"
+ "\n"
+ "</tr>\n"
+ "</table>\n"
+ "\n"
+ "- Past technicians and analysts\n"
+ "  - _Xia Hong_ | _Jie Shen_ | _Wenyan Han_ | _Pawandeep Kaur_ | _Yanyan Lin_ | _Xinyu Fan_ | _Mallory Udell_ | _Gwen Johnson_ | _Hakan Gunturkun_ | _Tengfei Wang_ |\n"
+ "  <!--- REHU students Abigale Salinero (2015) | Cindy Tay (2016) | Raven David (2017) | Christian Hurt (2018) | Gwen Johnson (2021) | Olivia Harrison (2022, 2023) | Ryan Luib (2023)\n"
+ "    --->\n"
+ "- P50 collaborators\n"
+ "  - Abraham Palmer | Oksana Polesskaya | Sanches, Thiago | Apurva Chitre | Shae Ziegler | Leah Solberg-Woods\n"
+ "- UTHSC collaborators\n"
+ "  - Changhoon Jee | Burt Sharp | Thirumalini Vaithianathan | Rob Williams | and others\n"
+ "\n"
+ "Funding: NIH/NIDA P50DA037844\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nicotine metabolism\n"
+ "\n"
+ "<img width=60% height=\"auto\" src=\"images/p50/AllCotinine_NicotineHSRats.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"cta0\">\n"
+ "\n"
+ "## Flavor cues conditioned to self-administered nicotine is aversive\n"
+ "\n"
+ "<a href=\"#/cta1\">\n"
+ "<img height:auto width=90% src=\"images/p50/nicotine_cta.png\">\n"
+ "</a>\n"
+ "\n"
+ "<p align=left> \n"
+ "<span id=\"cite\"> Chen, et al., Neuropsychopharmacology, 2011 </span>\n"
+ "\n"
+ "Note:\n"
+ "To further confirm that nicotine is aversive, we tested removing nicotine after three sessions. So this is an extinction procedure, where the cue is presented without the uncontitioned stimulus. In these adolescent SD rats, extinction happened relatively quickly. We'll come back to this extinction procedure shortly.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Is CS<sub>2</sub> relevant to human?\n"
+ "\n"
+ "<img src=\"./images/p50/ota_icv.png\" width=60%>\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Chen, unpublished data</span>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nicotine intake is heritable\n"
+ "\n"
+ "### h<sup>2</sup>=0.54-0.65 estimated using 12 isogenic strains across two doses\n"
+ "\n"
+ "<img src=\"./images/social_nicotine_dose_isogenic_strain.png\" width=80%>\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Han, et al., Sci Report, 2017 </span>\n"
+ "</p>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"cta1\">\n"
+ "\n"
+ "## Social learning facilitates the extinction of conditioned nicotine aversion\n"
+ "\n"
+ "<a href=\"#/cta0\">\n"
+ "<img src=\"./images/p50/correlation_ext_cta_nicotine.png\" >\n"
+ "</a>\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Han, et al., Sci Report, 2017 </span>\n"
+ "</p>\n"
+ "\n"
+ "Note:\n"
+ "With these inbred rats, we wanted to ask another question, which is the relationship between the aversive response and nicotine intake. One obvious hypothesis was that rats with stronger conditioned aversion to nicotine will self-administer less. To measure CTA, we have two groups, one recives nicotine and one recives iv nicotine. We did three days of nicotine becasuse we knew it was sufficient. After day 4, both groups recived saline. The difference in number of rewards between nicotine and saline on day 4 is an index for CFA. I really hated to discard the rats away after only getting four days data, especailly we went through all the trouble in during jugular surgery. So we added five extinction sessions. we use the number of rewards on the last session as an index of extion. So CFA and Extion of CFA are on the y-axis, the x-axis of these plots are number of nicotine infusions. It turns out, there was no correlations between CFA and intake but extinction of CFA is a predictor of nicotine intake. So this suggests, that the way social learning works is by facilite the extinction, or the dissociation between the flavor and the aversive effect of nicotine.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Social learning supports nicotine IVSA with an aversive flavor cue\n"
+ "\n"
+ "<table>\n"
+ "<tr><td width=15% valign=\"middle\">Social, Non-learning</td><td rowspan=2>\n"
+ "<img width=90% src=\"images/quinine/ise_nse_aversivecue.png\">\n"
+ "</td></tr>\n"
+ "<tr><td> Social, Learning</td></tr></table>\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Wang, et al., Psychopharmacology, 2016 </span>\n"
+ "</p>\n"
+ "\n"
+ "Note:\n"
+ "To further demonstrate that the appetitiveness of flavor cue is driving nicotine intake in our model, we replace the saccyhrine cue with a quinine cue. The bitterness of quinine is often used to show rats with self-administration history that will resist the punishment in order to obtain drug. Here we paired it as a contingent cue at the begining of nicotine self-administration. We also improved our control by adding a demonstration rat on the left side of the operant chamber.\n"
+ "<b>NSE</b>: neutral social environemnt, i.e., the presence of a companion rat.\n"
+ "<b>ISE</b>: indusive social environment, i.e., the presences of a companion rat who has access to the flavor cue.\n"
+ "<b>AV</b>: audiovisual cue\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Socially acquired nicotine self-administration in HS rats\n"
+ "\n"
+ "### 52 adult males and 48 adult females\n"
+ "\n"
+ "<div id=\"left50\">\n"
+ "<img width=90% height=\"auto\" src=\"images/p50/fig4.g2b.figure.male.vs.female.nicSA.cummulative.png\">\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Wang, et al., Gene Brain Behav, 2014</span>\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "<div id=\"right50\">\n"
+ "<img width=83% height=\"auto\" src=\"images/p50/fig_demo.lick.by.sex.png\">\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Can behavioral traits predict nicotine IVSA?\n"
+ "\n"
+ "<div id=\"left\">\n"
+ "\n"
+ "<center>\n"
+ "\n"
+ "#### Loading of PCA\n"
+ "\n"
+ "<img src=\"images/p50/retreat2018/pca_loading.png\" width=70%> \n"
+ "</center>\n"
+ "\n"
+ "<p>\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Wang, et al., Scientific Report, 2018 </span>\n"
+ "</p>\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "<div id=\"right\">\n"
+ "\n"
+ "<center>\n"
+ "\n"
+ "#### PCA regression summary\n"
+ "\n"
+ "<font size=4>\n"
+ "\n"
+ "| Phenotype                        | Sex | Variance Explained |\n"
+ "| -------------------------------- | --- | ------------------ |\n"
+ "| Infusion, first 3 d              | F   | 0.18               |\n"
+ "| Infusion, first 3 d              | M   | 0.17               |\n"
+ "| Infusion, last 3 d               | F   | 0.12               |\n"
+ "| Infusion, last 3 d               | M   | 0.20               |\n"
+ "| Infusion, progressive ratio      | F   | 0.14               |\n"
+ "| Infusion, progressive ratio      | M   | 0.18               |\n"
+ "| Active spout lick, reinstatement | F   | 0.08               |\n"
+ "| Active spout lick, reinstatement | M   | 0.19               |\n"
+ "\n"
+ "</font>\n"
+ "</center>\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Gria4 Western blot\n"
+ "\n"
+ "<table><tr><td width=60%>\n"
+ "\n"
+ "<img src=\"./images/p50/wes_slope_sample_characteristics.png\">\n"
+ "\n"
+ "<img src=\"./images/p50/wes_gria4_lanes.png\">\n"
+ "</td>\n"
+ "<td width=40% valign=\"middle\"> \n"
+ "<img src=\"./images/p50/ampa4_gria4_western_barplot.png\" >\n"
+ "</td></tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Gria4 null mutation abolishes nicotine CCP in C.elegans\n"
+ "\n"
+ "<table><tr><td width=15%>\n"
+ "<img src=\"https://www.uthsc.edu/pharmacology/faculty/images/jee-changhoon.jpg\">\n"
+ "<b> Dr. Changhoon Jee </br> Assistant Prof, UTHSC</b>\n"
+ "\n"
+ "</td><td width=85%>\n"
+ "<img src=\"./images/p50/celegans2.png\">\n"
+ "</td></tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Base Editing Zebrafish Genome\n"
+ "\n"
+ "<table><tr><td width=50%>\n"
+ "\n"
+ "<img src=\"./images/zebrafishknockout_vs_wildtype.png\">\n"
+ "\n"
+ "</td>\n"
+ "<td width=50%>\n"
+ "<img src=\"./images/p50/zebrafish_pamless.png\">\n"
+ "</td></tr>\n"
+ "\n"
+ "</td></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## HS progenitors contain ~80% of the genetic variants in lab rats\n"
+ "\n"
+ "<img src=\"./images/p50/hrdp_phylo_hs_horizontal.png\" width=70%>\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> de Jong et al., Cell Genomics, 2024 </span>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Is the appetitive cue driving IVSA?\n"
+ "\n"
+ "<img src=\"./images/p50/fig4.saccGluSolo_flavor.png\" width=70%>\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Chen, et al., Neuropsychopharmacology, 2011 </span>\n"
+ "\n"
+ "Note:\n"
+ "Obviously, there are many questions in this somewhat complicated model. There is nicotine, there is flavor cue, there is social cue. They key question is what is driving the self-admnistration behavior. We've done a lot of expeirments to show that the operant licking behavior is driven by nicotine. I don't have time to show you all the data but here are some of the key findings. First of all, is a flavor cue with strong appetitiveness sufficient to drive nicotine intake without social factors.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Top Smoking Phenotypes in GWAS Catalogue\n"
+ "\n"
+ "| Trait                           | Number of Sig. SNPs <sup>1</sup> | Note                                                                     |\n"
+ "| ------------------------------- | -------------------------------- | ------------------------------------------------------------------------ |\n"
+ "| Smoking initiation <sup>2</sup> | 5498                             | 5269 from Saunders, et al. PMID: 36477530 and Liu et al., PMID: 30643251 |\n"
+ "| Cigarettes smoked per day       | 610                              |                                                                          |\n"
+ "| Smoking status <sup>3 </sup>    | 481                              | 218 were from Karlsson Linnér et al. PMID: 30643258.                     |\n"
+ "| Smoking cessation <sup>4 </sup> | 452                              | 335 were from Saunders, et al., PMID: 36477530.                          |\n"
+ "| Age of smoking initiation       | 243                              |                                                                          |\n"
+ "\n"
+ "<table><tr><td>\n"
+ "<p align=\"left\">\n"
+ "1. p-val < 5E-8, replicated finding not filtered out\n"
+ "<br>\n"
+ "2. Ever being a regular smoker in their life (current or former) vs never being a regular smoker in their life \n"
+ "<br>\n"
+ "3. Ever vs nerver smoker\n"
+ "<br>\n"
+ "4. Current smokers vs former smokers \n"
+ "</p>\n"
+ "</td></tr></table>\n"
+ "\n"
+ "</p>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Social learning changes the subjective value of the reward\n"
+ "\n"
+ "<img src=\"./images/p50/socially_acquired_nicotine_IVSA_lick_cluster_size.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## In vivo genome editing in rats\n"
+ "\n"
+ "<img src=\"./images/p50/cas9_NAcSH_mutation.png\" width=60%>\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Sharp, et. al., Scientific Report, 2024 </span>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## GWAS: Elevated Plus Maze\n"
+ "\n"
+ "n=1875\n"
+ "\n"
+ "<img src=\"images/p50/hs_gwas_epm_porcupine.png\" width=70%>\n"
+ "<img src=\"images/p50/hs_gwas_epm_qtlCnt.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## GWAS: Novel Object Interaction\n"
+ "\n"
+ "n=1963\n"
+ "\n"
+ "<img src=\"images/p50/hs_gwas_novel_porcupine.png\" width=70%>\n"
+ "<img src=\"images/p50/hs_gwas_novel_qtlCnt.png\" width=70%>\n"
+ "---\n"
;
var script = document.querySelector('script[src="ibangs2024.js"]');
var section = document.createElement('section');
script.parentNode.appendChild(section);
section.appendChild(document.createTextNode(markdownContent));
[].forEach.call(script.attributes, function (attr) {
    section.setAttribute(attr.name, script.getAttribute(attr.name));
});
section.setAttribute('data-markdown', '');
})();
