(function () {
'strict'
var markdownContent = ''
+ "# The Linux Command line \n"
+ "\n"
+ "#### Just enough to get you started \n"
+ "\n"
+ "<hr style=\"color:royalblue\">\n"
+ "\n"
+ "### Hao Chen\n"
+ "\n"
+ "hchen@uthsc.edu \n"
+ "\n"
+ "Department of Pharmacology, UTHSC\n"
+ "\n"
+ "December 13, 2018\n"
+ "\n"
+ "https://chen42.github.io/slides/linux.html\n"
+ "\n"
+ "<small>\n"
+ "\n"
+ "Written using [Reveal.js](https://github.com/hakimel/reveal.js) and [markdown](https://help.github.com/categories/writing-on-github/)\n"
+ "\n"
+ "</small>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Outline\n"
+ "\n"
+ "* Getting around (shell, more specifically, Bash) \n"
+ "* Working with text files and directories \n"
+ "* Cut, sort, uniq, pipes\n"
+ "* Put commands in text files (shell scripts)\n"
+ "* Run many programs on many sets of files (cluster)\n"
+ "* Download and install programs (as a user)\n"
+ "---\n"
+ "\n"
+ "\n"
+ "### Login a remote server\n"
+ "\n"
+ "On Windows, you can use [putty](https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html)\n"
+ "\n"
+ "On Mac, there is a *terminal* app\n"
+ "\n"
+ "```\n"
+ "ssh user@sub.domain.edu # secure shell\n"
+ "\n"
+ "ssh one@128.169.5.89 # pass: userone\n"
+ "ssh two@128.169.5.89 # pass: usertwo\n"
+ "ssh three@128.169.5.89 # pass: userthree\n"
+ "\n"
+ "```\n"
+ "\n"
+ "---\n"
+ "\n"
+ "### Find out where you are and move around\n"
+ "\n"
+ "```\n"
+ "pwd # current directory\n"
+ "\n"
+ "ls # list files and dirs in the current directory\n"
+ "\n"
+ "ls -l # long format\n"
+ "\n"
+ "ls -t # sort by time\n"
+ "\n"
+ "ls -a # see the dot and dots?\n"
+ "\n"
+ "```\n"
+ "---\n"
+ "\n"
+ "#### Working with Directories (folders)\n"
+ "\n"
+ "```\n"
+ "\n"
+ "mkdir hg19 # make a new directory called hg19 \n"
+ "\n"
+ "cd hg19 # change to the hg19 directory \n"
+ "\n"
+ "cd .. # move to the parent dir\n"
+ " \n"
+ "cd ~ # go home\n"
+ "\n"
+ "rmdir hg19 # remove dir hg19 (only when the dir is empty)\n"
+ "\n"
+ "rmdir -rf hg19 # remove dir hg19 (recrusive and force)\n"
+ "\n"
+ "```\n"
+ "\n"
+ "---\n"
+ "\n"
+ "### Copy and  delete files\n"
+ "\n"
+ "```	\n"
+ "cp /home/share/test1.vcf .\n"
+ "cp /home/share/test2.vcf .\n"
+ "ls\n"
+ "mv test2.vcf test3.vcf  # move, but actually rename\n"
+ "ls \n"
+ "rm test3.vcf # remove, i.e. delete !! there is no undo !!\n"
+ "ls -l\n"
+ "\n"
+ "```\n"
+ "---\n"
+ "### read text files\n"
+ "\n"
+ "```\n"
+ "cat test1.vcf \n"
+ "\n"
+ "more test1.vcf\n"
+ "\n"
+ "less test1.vcf\n"
+ "\n"
+ "cat test1.vcf | head # this is a pipe, you'll see a lot of it\n"
+ "\n"
+ "```\n"
+ "\n"
+ "---\n"
+ "\n"
+ "### Edit text files\n"
+ "```\n"
+ "pico test1.vcf \n"
+ "\n"
+ "nano test1.vcf\n"
+ "\n"
+ "vi test1.vcf\n"
+ "\n"
+ "vim test1.vcf # may not be available on all linux systems\n"
+ "\n"
+ "emacs test1.vcf # may not be available \n"
+ "```\n"
+ "\n"
+ "Choosing a text editor is one the most important things of your life \n"
+ "\n"
+ "---\n"
+ "\n"
+ "### grep  (find)\n"
+ "\n"
+ "```\n"
+ "grep word one_text_file\n"
+ "grep word text_file1 text_file2\n"
+ "grep \"word1|word2\" text_file # word1 or word2  # the bar is OR\n"
+ "grep word1 text_file | grep text2 # word1 and word2 # the bar is a pipe\n"
+ "grep \"^word1\" text_file # line starts with word1\n"
+ "grep \"word1$\" text_file # line ends with word1\n"
+ "grep \"word1\\t\" text_file # line contains word1 followd by a tab \n"
+ "```\n"
+ "---\n"
+ "### wc  \n"
+ "\n"
+ "```\n"
+ "wc -l test1.vcf # number of lines \n"
+ "grep -v \"^#\" test1.vcf |wc -l # -v  exclude the comments of a vcf file before counting lines\n"
+ "\n"
+ "```\n"
+ "---\n"
+ "\n"
+ "### cut, sort, uniq, pipes\n"
+ "\n"
+ "```\n"
+ "head test.vcf\n"
+ "\n"
+ "cut -f 2,4 test.vcf \n"
+ "cut -f 2,4 test.vcf |sort |less\n"
+ "cut -f 4 test.vcf |sort | uniq \n"
+ "cut -f 4 test.vcf |sort | uniq  -c \n"
+ "cut -f 4 test.vcf |sort | uniq  -c |sort -rn |head \n"
+ "cut -f 4 test.vcf |sort | uniq  -c |sort -rn |tail\n"
+ "```\n"
+ "\n"
+ "---\n"
+ "\n"
+ "### File compression\n"
+ "\n"
+ "```\n"
+ "gzip test1.vcf\n"
+ "ls \n"
+ "less test1.vcf.gz\n"
+ "zcat test1.vcf.gz\n"
+ "gunzip test1.vcf.gz\n"
+ "\n"
+ "bzip2 test1.vcf \n"
+ "ls\n"
+ "bunzip2  test1.vcf.bz2\n"
+ "```\n"
+ "\n"
+ "---\n"
+ "### Redirect output  (save to file)\n"
+ "\n"
+ "```\n"
+ "head test.vcf\n"
+ "\n"
+ "head -n 20 test.vcf  >first20lines.vcf\n"
+ "\n"
+ "echo \"tail -n 20 test.vcf\" \n"
+ "\n"
+ "echo \"tail -n 20 test.vcf\" >a_program # redirect into a text file\n"
+ "\n"
+ "bash a_program  # run the text file as a command\n"
+ " \n"
+ "echo \"tail -n 20 test.vcf > last20lines.vcf\" >a_program\n"
+ "\n"
+ "bash a_program\n"
+ "\n"
+ "ls \n"
+ "\n"
+ "```\n"
+ "\n"
+ "---\n"
+ "\n"
+ "### Redirect output (use as input)\n"
+ "run a program on many files\n"
+ "\n"
+ "```\n"
+ "cp /home/share/*.vcf .\n"
+ "ls *.vcf\n"
+ "```\n"
+ "\n"
+ "put the following in a text file named \"test.sh\"\n"
+ "```\n"
+ "#!/bin/bash\n"
+ "for i in `ls *.vcf` ; do \\  # note the backtick,  not single quote\n"
+ "head $i >$i\\_first10lines.vcf \\\n"
+ "done\n"
+ "\n"
+ "```\n"
+ "Run the following command \n"
+ "\n"
+ "```\n"
+ "ls -l test.sh\n"
+ "chmod a+x test.sh # \"all\" can run (eXecute) the program\n"
+ "ls -l test.sh\n"
+ "./test.sh\n"
+ "ls\n"
+ "```\n"
+ "---\n"
+ "\n"
+ "### Screen, worthy of  its own slide\n"
+ "\n"
+ "```\n"
+ "screen \n"
+ "\n"
+ "```\n"
+ "\n"
+ "Ctrl-ac # create a virtual teriminal \n"
+ "\n"
+ "Ctrl-a1 # switch to virtural terminal 1\n"
+ "\n"
+ "Ctrl-ad # dissociate from this session\n"
+ "\n"
+ "```\n"
+ "screen -RD # force reconnect to a running session \n"
+ "```\n"
+ "\n"
+ "---\n"
+ "### On to the ACF \n"
+ "\n"
+ "<a href=\"https://www.jics.utk.edu/acf\">\n"
+ "<img src=\"https://www.jics.utk.edu/files/images/ACFDiagram.png\" width=60%>\n"
+ "</a>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "### Run many programs on many files (on a cluster)\n"
+ "\n"
+ "* Do not run the programs directly on headmaster!!!  Put the commands into a shell program and submit it.\n"
+ "\n"
+ "```\n"
+ "qsub job_file\n"
+ "\n"
+ "qstat \n"
+ "\n"
+ "qhost\n"
+ "\n"
+ "pbsnodes\n"
+ "\n"
+ "```\n"
+ "* Requesting multiple cores (threads) are common, request multiple nodes are rare. This depends on the software you are using.\n"
+ "\n"
+ "* put the following in a file, name it sam2bam.sh\n"
+ "```\n"
+ "#PBS -l nodes=1:ppn=1,cput=00:00:40\n"
+ "cd /home/user/\n"
+ "/home/user/bin/samtools view -bS test.sam >test.bam \n"
+ "```\n"
+ "\n"
+ "* then run\n"
+ "\n"
+ "```\n"
+ "qsub sam2bam.sh\n"
+ "\n"
+ "ls sam2bam* \n"
+ "```\n"
+ "\n"
+ "---\n"
+ "\n"
+ "### Install software (Samtools)\n"
+ "\n"
+ "Get the source code\n"
+ "```\n"
+ "# easiest but may fail due to authentication \n"
+ "wget https://github.com/samtools/samtools/releases/download/1.6/samtools-1.6.tar.bz2\n"
+ "# using a text browser, worth a try \n"
+ "links www.htslib.org/download \n"
+ "# transfer from local machine\n"
+ "scp samtools-1.6.tar.bz2  user@server.com:/home/user\n"
+ "\n"
+ "```\n"
+ "Install\n"
+ "```\n"
+ "tar xvf samtools-1.6.tar.bz2\n"
+ "ls\n"
+ "cd samtools-1.6\n"
+ "./configure --prefix=/home/username/bin\n"
+ "make \n"
+ "make install\n"
+ "\n"
+ "```\n"
+ "---\n"
+ "\n"
+ "### PATH \n"
+ "\n"
+ "Bash looks through many places to find your software\n"
+ "\n"
+ "```\n"
+ "echo $PATH # this is the earch path\n"
+ "\n"
+ "# add a directory to your search path\n"
+ "export PATH=/home/username/bin:$PATH\n"
+ "\n"
+ "# run with absolute path\n"
+ "/home/user/install_dir/software_name\n"
+ "\n"
+ "# this may get you \n"
+ "./samtools # when you are in the directory where the software is installed, add ./ \n"
+ "```\n"
+ "---\n"
+ "### git and GitHub\n"
+ "\n"
+ "* git for version control\n"
+ "* github for code sharing and collaboration\n"
+ "\n"
+ "```\n"
+ "git add file_1 # add a file to the repo\n"
+ "git commit -m \"finally working\" # save a version, with comments\n"
+ "git push origin master  # let everyone see your mistakes \n"
+ "\n"
+ "git clone # get a copy of the code \n"
+ "git log # what have I done? \n"
+ "git checkout # go back history\n"
+ "git diff # what's changed?\n"
+ "```\n"
+ "\n"
;
var script = document.querySelector('script[src="linux.js"]');
var section = document.createElement('section');
script.parentNode.appendChild(section);
section.appendChild(document.createTextNode(markdownContent));
[].forEach.call(script.attributes, function (attr) {
    section.setAttribute(attr.name, script.getAttribute(attr.name));
});
section.setAttribute('data-markdown', '');
})();
