(function () {
'strict'
var markdownContent = ''
+ "\n"
+ "\n"
+ "## GWAS on socially acquired nicotine IVSA in heterogeneous stock rats highlights genes implicated in human smoking behavior\n"
+ "\n"
+ "<hr color=orange>\n"
+ "\n"
+ "\n"
+ "Tengfei Wang<sup>1</sup>, Apurva S. Chitre<sup>2</sup>, Angel Garcia Martinez<sup>1</sup>, Oksana Polesskaya<sup>2</sup>, Leah C. Solberg-Woods<sup>3</sup>, Abraham A. Palmer<sup>2</sup>, Hao Chen<sup>1</sup>\n"
+ "\n"
+ "\n"
+ "<sup>1</sup>Department of Pharmacology, Addiction Science and Toxicology, University of Tennessee Health Science Center; <sup>2</sup>Department of Psychiatry, University of California San Diego; <sup>3</sup>Department of Molecular Medicine, Wake Forest School of Medicine\n"
+ "\n"
+ "---\n"
+ "## Abstract\n"
+ "\n"
+ "<div id=\"twocols\"> \n"
+ "Cigarette smoking remains the leading cause of preventable disease and death in the United States. We previously established socially acquired nicotine intravenous self-administration in adolescent rats as a model of voluntary nicotine consumption. Stable intravenous nicotine infusion required the social transmission of a nicotine associated odor cue in this model. Further, multiple lines of evidence indicated that nicotine was the primary reinforcer. Using over 1400 heterogeneous stock rats, we conducted a genome-wide association study using this model. We analyzed over 60 traits and found 30 QTL that reached genome-wide significance, including seven for the number of licks on the active spout, eight for nicotine infusion, and one for reinstatement of nicotine seeking. We compared these results with those from human smoking-related GWAS, which identified 33 genes implicated in both species. Many of these overlapped genes were associated with similar phenotypes. For example, a locus on rat chr1 (278.5 Mb) was associated with the number of licks on the active spout in the first session. Four out of 99 genes under this loci (Shtn1, Vti1a, Hspa12a, and Nrap) had homologs associated with smoking initiation in human GWAS. One locus on rat chr16 (83.9Mb) was associated with the number of licks on the active spout and nicotine infusion for sessions 5 and 7, and the total number of nicotine infusions. One gene in this region, Tex29, has a human homolog that was associated with life-time cigarette consumption. These overlapping genes may help elucidate the molecular mechanism of nicotine addiction. \n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Flavor cues do <font color=\"darkred\">not</font> support nicotine self-administration\n"
+ "\n"
+ "<img height:auto width=90% src=\"images/p50/retreat2018/flavorcue.png\">\n"
+ "\n"
+ "<div id=\"twocols\">\n"
+ "We previously reported that \n"
+ "adolescent rats developed conditioned aversion to an appetitive flavor cue (saccharine + grape odor) associated with self-administered i.v. nicotine. In this operant <i>licking</i> model, oral flavor cue and <strong>i.v.</strong> nicotine were delivered simultaneously upon the completion of a fixed-ratio 5 reinforcement schedule. \n"
+ "\n"
+ "<a href=https://pubmed.ncbi.nlm.nih.gov/21796102/> \n"
+ "(PMID: 21796102)\n"
+ "</a>\n"
+ "</div>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "\n"
+ "## Social learning enables nicotine self-administration\n"
+ "\n"
+ "<img height:auto width=90% src=\"images/socially_acquired_nicotine_ivsa.png\">\n"
+ "\n"
+ "\n"
+ "<div id=\"twocols\">\n"
+ "However, with the presence of a \"demonstrator\" rat consuming the same flavor cue, nicotine i.v. self-administration was established. \n"
+ "No water or food deprivation or operant pretraining is needed. Thus the model is appropriate for studying smoking initiation in adolescents. \n"
+ "\n"
+ "<a href=https://pubmed.ncbi.nlm.nih.gov/21796102/> \n"
+ "(PMID: 21796102)\n"
+ "</a>\n"
+ "\n"
+ "\n"
+ "</div>\n"
+ "---\n"
+ "\n"
+ "## Social learning supports nicotine IVSA with an aversive cue\n"
+ "\n"
+ "<img width=40% src=\"images/quinine/pres.sacc_quinine.png\">\n"
+ "\n"
+ "<div id=\"twocols\">\n"
+ "We further reported that even when an aversive (i.e. quinine) flavor was used in place of the appetitive flavor, adolescent rats obtained nicotine IVSA, with the presence of a demonstrator consuming a flavor cue containing the same odor as the nicotine cue (i.e. inducive social environemnt (<b>ISE</b>). The number of nicotine infusions were almost identical between the two cues.  <b>Therefore, licking on the active spout is most likely motivated by nicotine in this model</b> The reduced licks on the active spout was due to the reduction of licking during the timeout period following nicotine and cue delivery.  <a href=\"https://pubmed.ncbi.nlm.nih.gov/26911379/\"> (PMID: 26911379)</a>. \n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Socially acquired nicotine IVSA is hertiable\n"
+ "\n"
+ "<img src=\"https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5556091/bin/41598_2017_8291_Fig3_HTML.jpg\">\n"
+ "\n"
+ "<div id=\"twocols\">\n"
+ "Using 12 isogenic strains of rats, we confirmed that nicotine intake obtined in our model is heritable (h<sup>2</sup>=0.54-0.65). The dose responses among all strains further confirmed that active licking was primarily motivated by nicotine.  <a href=\"https://pubmed.ncbi.nlm.nih.gov/28808247/\"> PMID: 28808247</a>\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Social learning is mediated by Carbon Disulfide (CS<sub>2</sub>) in rats \n"
+ "\n"
+ "<div id=\"left50\">\n"
+ "<img height:auto width=90% src=\"images/galef.protocol.narrower.png\"> \n"
+ "<br>\n"
+ "</div>\n"
+ "\n"
+ "<div id=\"right50\">\n"
+ "<img height:auto width=90% src=\"images/titlepages/cs2.png\">\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Both CS<sub>2</sub> and flavor cue are necessary for socially acquired nicotine IVSA \n"
+ "\n"
+ "<img width=100% height=\"auto\" src=\"images/p50/cs2_1rat.png\">\n"
+ "\n"
+ "<div id=\"twocols\">\n"
+ "We confirmed that neither nicotine associated flavor cue nor carbon disulfide alone supported nicotine IVSA. However, their combination was sufficient to replicate the behavior induced by live demonstrator rats.  \n"
+ "<a href=\"https://pubmed.ncbi.nlm.nih.gov/25532105/\">PMID: 25532105</a>\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Experimental design\n"
+ "<div id=\"left50\">\n"
+ "<font size=3>\n"
+ "\n"
+ "| Age | Test |\n"
+ "|---|---|\n"
+ "|PND21|Wean, Body weight|\n"
+ "|PND31|Open field (60min)|\n"
+ "|PND32|Novel object (20min)|\n"
+ "|PND33|Social interaction in the same arena as openfield (20 min) |\n"
+ "|PND34|Elevated plus maze (6min)|\n"
+ "|PND38|Surgery|\n"
+ "|PND39 - 41| Recovery|\n"
+ "|PND42 - 51|Socially acquired nicotine IVSA|\n"
+ "|PND52| Progressive ratio test |\n"
+ "|PND53 - 56 |Extinction|\n"
+ "|PND57|Contextual cue induced reinstatement|\n"
+ "|PND59|Tissue Collection|\n"
+ "\n"
+ "</font>\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "\n"
+ "<div id=\"right50\">\n"
+ "<center>\n"
+ "<table width=80%><tr><td>\n"
+ "We phenotyped 1600 adolescent heterogeneous stock rats on socially acquired nicotine IVSA using an flavor cue containing  CS<sub>2</sub>. We also collected other behavioral traits before nicotine IVSA was started. Spleen from each rat was collected for genotyping once behavioral tests were completed.  \n"
+ "</td></tr></table>\n"
+ "</center>\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Socially acquired nicotine IVSA \n"
+ "\n"
+ "Adolescent heterogeneous rats (711 F, 711 M)\n"
+ "\n"
+ "<img width=75% height=\"auto\" src=\"images/gwasv3/nicotine_fr10_phaseone_all_data.png\">\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## GWAS summary\n"
+ "\n"
+ "|Behavior | Sample size | N traits |  N sig. QTL| \n"
+ "|---|---|---:|---:|\n"
+ "| open field | 626 M, 620 F | 6 |  9 | \n"
+ "| novel object interaction|623 M, 622 F| 6 |  7|\n"
+ "| social interaction | 664 M, 664 F | 11|  14| \n"
+ "| elevated plus maze | 659 M, 658 F | 10| 8| \n"
+ "| socially acquired nicotine IVSA| 711 M, 711 F| 63|  30| \n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Number of licks on the active spout in first session: chr1:278524299\n"
+ "\n"
+ "<div id=\"left50\">\n"
+ "<img src=\"./images/gwasv3/locuszoom_day1_active_licks.png\">\n"
+ "\n"
+ "The QLT region is 6.9 Mbp and has 39 known genes. Four genes has missense variants, two genes has cis-eQTL with r2 > 0.6.\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "<div id=\"right50\">\n"
+ "\n"
+ "<a href=\"http://rats.pub/cytoscape/?rnd=tmpzcBObC&genequery=Gfra1_Nhlrc2_Hspa12a_Vti1a_Shtn1_Tcf7l2_Adrb1_Nrap_Gpam_Casp7\" target=_new>\n"
+ "<img src=\"./images/gwasv3/active_lick_gwas_smoking_genes_ratspub.svg\">\n"
+ "</a>\n"
+ "\n"
+ "http://rats.pub is designed to take a list of gene symbols and mine the PubMed and GWAS catalog for sentences pertain to addiction.\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Summary of nicotine GWAS, part 1/4\n"
+ "\n"
+ "## Number of licks on the active spout\n"
+ "\n"
+ "|ID |Session|Loc| Genes (n) | Overlapping with human smoking GWAS|\n"
+ "|---|:---:|---|---|---|\n"
+ "|12.20 | day 1 | chr1:278524299| 99 | Gpam&clubs;&diams;, [Vti1a](http://rats.pub/cytoscape/?rnd=tmpUpzbbT&genequery=VTI1A)<font color=\"darkslateblue\">&spades;</font>, Nhlrc2&clubs;&diams;, Adrb1&clubs;, Tcf7l2, [Hspa12a](http://rats.pub/cytoscape/?rnd=tmpFrhLrJ&genequery=HEAT-SHOCK-PROTEIN-FAMILY-A-HSP70-MEMBER-12A_HSPA12A)<font color=\"darkslateblue\">&spades;</font>, [Shtn1](http://rats.pub/cytoscape/?rnd=tmpJiHXFf&genequery=KIAA1598_SHOOTIN-1_SHOOTIN1_SHTN1)<font color=\"darkslateblue\">&spades;</font>&diams;, [Nrap](http://rats.pub/cytoscape/?rnd=tmpaUzTZp&genequery=N-RAP_NEBULIN-RELATED-ANCHORING-PROTEIN_NRAP)<font color=\"darkslateblue\">&spades;</font>, Casp7&diams; Gfra1|\n"
+ "|12.29 | day 2 | chr8:22496077| 29| [Carm1](http://rats.pub/cytoscape/?rnd=tmpaHVoNJ&genequery=carm1) |\n"
+ "|12.24 | day 4 | chr4:145377793| 20| [Emc3](http://rats.pub/cytoscape/?rnd=tmpQXgUzk&genequery=emc3) |\n"
+ "|12.12 | day 5 | chr16:83955432| 23| Tex29| \n"
+ "|12.08 | day 7 | chr16:83489214| 23| Tex29| \n"
+ "|12.02 | day 9 | chr10:32845925| 90| | \n"
+ "|12.22 | day 10 | chr2:247766389|20| [Pkn2, Gtf2b](http://rats.pub/cytoscape/?rnd=tmpPoBkQf&genequery=Pkn2_Gtf2b) |\n"
+ "|12.16 | Reinstatment | chr1:161226950| 28|Usp35, Gab2, Nars2, Tenm4, [Alg8](http://rats.pub/cytoscape/?rnd=tmpJKLgcJ&genequery=Usp35_Gab2_Nars2_Tenm4_Alg8)&diams;&hearts; |\n"
+ "\n"
+ "\n"
+ "<font color=\"darkslateblue\">&spades;</font>: smoking initiation genes\n"
+ "&clubs;: Alcohol consumption genes\n"
+ "&diams;: cis-eQTL\n"
+ "&hearts; missense variants\n"
+ "\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Vti1a, Shtn1 and Nrap for smoking initiation \n"
+ "\n"
+ "\n"
+ "<font size =2>\n"
+ "Association studies of up to 1.2 million individuals yield new insights into the genetic etiology of tobacco and alcohol use\n"
+ "<br>\n"
+ "Mengzhen Liu, ... Scott Vrieze, <a href=\"https://pubmed.ncbi.nlm.nih.gov/30643251/\">Nature Genetics 2010</a>\n"
+ "</font>\n"
+ "\n"
+ "![](./images/gwasv3/smoking_initiation_vti1a_nrap_shtn1.png)\n"
+ "\n"
+ "\n"
+ "### Phenotypical similarity: Day 1 active lick ~ Smoking initiation \n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "\n"
+ "\n"
+ "#### Summary of nicotine GWAS, part 2/4\n"
+ "\n"
+ "## Number of nicotine infusions\n"
+ "\n"
+ "|ID |Session|Loc| Genes (n) | Overlapping with human smoking GWAS|\n"
+ "|---|:---:|---|---|---|\n"
+ "|12.09 | day 5 | chr16:83500180| 23| Tex29 |\n"
+ "|12.13 | day 5 | chr17:17103044| 1| [ID4](http://rats.pub/cytoscape/?rnd=tmpdaIxug&genequery=ID4) |\n"
+ "|12.11 | day 7 | chr16:83500180| 23| Tex29|\n"
+ "|12.23 | day 7 | chr3:104723116| 8|[Hmgn4, Fmn1](http://rats.pub/cytoscape/?rnd=tmpSBamBX&genequery=Hmgn4_Fmn1) |\n"
+ "|12.15 | day 8 | chr19:26396258| 1| |\n"
+ "|12.03 | median of last 3 days | chr11:17834164|27| | \n"
+ "|12.10 |total infusion | chr16:83500180| 23| [Tex29](http://rats.pub/cytoscape/?rnd=tmpesQlMB&genequery=tex29)|\n"
+ "|12.30 |slope of regression | chr8:4459578| 74| [Gria4](http://rats.pub/cytoscape/?rnd=tmpAjmeXn&genequery=Gria4_Pdgfd_Mmp12)&diams;, Pdgfd&diams;, Mmp12 |\n"
+ "\n"
+ "&diams;: cis-eQTL\n"
+ "\n"
+ "\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Tex29\n"
+ "\n"
+ "<font size =2>\n"
+ "Exome Chip Meta-analysis Fine Maps Causal Variants and Elucidates the Genetic Architecture of Rare Coding Variants in Smoking and Alcohol Use \n"
+ "<br>\n"
+ "David Brazel, ... Scott Vrieze, <a href=\"https://pubmed.ncbi.nlm.nih.gov/30679032/\">Biol Psychiatry 2019</a>\n"
+ "</font>\n"
+ "\n"
+ "![](./images/gwasv3/tex29_gwas_pack_years.png)\n"
+ "\n"
+ "\n"
+ "### Phenotypical similarity: total nicotine infusion ~ pack years  \n"
+ "<div id=\"twocols\">\n"
+ "<b>Pack Years:</b>\n"
+ "Defined in the same way as cigarettes per day but not necessarily binned, divided by 20 (cigarettes in \n"
+ "a pack), and multiplied by number of years smoking. <u>This yielded a measure of total overall exposure to\n"
+ "tobacco </u> and is relevant to disease outcomes for which smoking is a risk factor, such as cancer and \n"
+ "chronic obstructive pulmonary disease risk.\n"
+ "\n"
+ "\n"
+ "Not much literature is available for Tex29. Tex29 is not detected in our RNA-seq dataset (GTEx does report its detection). \n"
+ "The annotation is intergenic. <a href=\n"
+ "\"http://genome.ucsc.edu/cgi-bin/hgTracks?db=hg38&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr13%3A110979763%2D112075449&hgsid=1028729693_QukEveNO4EoDL3hNviIqVJ3lcbnb\"> Is Arhgef7 more likely?</a> Arhgef7 expression is FPKM=30 in our dataset. It is involed in spine morphogenesis. Loss of Arhgef7 results in extensive loss of axons PMID:30683798, PMID:29891904\n"
+ "</div>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Summary of nicotine GWAS, part 3/4\n"
+ "\n"
+ "## Number of licks on the inactive spout \n"
+ "\n"
+ "\n"
+ "|ID |Session|Loc| Genes (n) | Overlapping with human smoking GWAS|\n"
+ "|---|:---:|---|---|---|\n"
+ "|12.18 | day 3 | chr1:253523411| 10| |\n"
+ "|12.04 | day 7 | chr14:108854633|23| XPO1, USP34, BCL11A |\n"
+ "|12.06 | day 9 | chr16:5256755|1| Cacna2d3 |\n"
+ "|12.21 | day 9 | chr1:74927958| 195| U2af2, KMT5C, FAM71E2, TMEM238, COX6B2, TMEM190, Il11, Lilrb4| \n"
+ "|12.26 | day 9 | chr6:71588778| 46| Foxg1, Heatr5a&hearts;, Prkd1 |\n"
+ "|12.27 | day 9 | chr7:110658276| 7| |\n"
+ "|12.07 | day 10 | chr16:5288954|1 | Cacna2d3 |\n"
+ "|12.17 | total | chr1:239058463| 7||\n"
+ "|12.19 | total | chr1:253766837| 10||\n"
+ "\n"
+ "&hearts;:protein coding variant\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Summary of nicotine GWAS, part 4/4\n"
+ "\n"
+ "## Ratio of licks on the active/inactive spouts\n"
+ "\n"
+ "\n"
+ "|ID |Session|Loc| Genes (n) | Overlapping with human smoking GWAS|\n"
+ "|---|:---:|---|---|---|\n"
+ "|12.28 | day 2 | chr8:22201332| 37| Carm1 | \n"
+ "|12.14 | day 3 | chr18:50265173| 13| |\n"
+ "|12.05 | day 4 | chr16:43380960|7 | |\n"
+ "|12.01 | day 10 | chr10:104395310| 54|Tsen54 |\n"
+ "|12.25 | day 11 | chr6:21268257| 5| TTC27 |\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "##  Overlapping genes between rat nicotine and human smoking GWAS \n"
+ "\n"
+ "\n"
+ "| Trait| Number of human genes* | Overlap expected by random | Actual overlap| Difference| \n"
+ "|---|---:|---:|---:|---:|\n"
+ "|Smoking | 1772| 32|39| 7| \n"
+ "|Body height| 2467| 46| 36| -10|\n"
+ "|Body mass|2920|54 |46|-8 |\n"
+ "|Education |1214 |23 | 13|-10 |\n"
+ "\n"
+ "<p>\n"
+ "\n"
+ "<div id=\"twocols\">\n"
+ " There are a total of 16913 genes symbols common between human and rat.  There are 315 genes under nicotine QTL share the symbol with human genes.  Chance of human/rat gene involved in smoking: 1772/16913=10%. For 315 genes, we expect to find 32 genes. The actual overlap is 39. Although this is a small enrichment, calculation conducted on other traits shows that this is an under-estimation. This is likely because the nicotine QTL contained many genes. *: reported in <a href=\"https://pubmed.ncbi.nlm.nih.gov/30584246/\">GWAS catalog</a>\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Potential targets for validation \n"
+ "\n"
+ "* Shtn1 (active lick on day 1)\n"
+ "* Gria4 (progression of intake)\n"
+ "* Arhgef7 (total intake)\n"
+ "* Alg8 (reinstatement) \n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Acknowledgements\n"
+ "\n"
+ "\n"
+ "Funding: NIDA P50DA037844\n"
+ "\n"
+ "---\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Nicotine metabolism\n"
+ "\n"
+ "<img width=60% height=\"auto\" src=\"images/p50/AllCotinine_NicotineHSRats.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Correlation among behavioral measures \n"
+ "\n"
+ "open field, novel object, social interaction, and elevated plus maze\n"
+ "\n"
+ "<img src=\"./images/p50/retreat2018/behav_cor_r_p.png\" width=60% class=\"plain\">\n"
+ "\n"
+ "<p>\n"
+ "<hr align=\"right\" width=15%>\n"
+ "<p align=right>\n"
+ "<cite> <a href=\"https://pubmed.ncbi.nlm.nih.gov/30584246/\">PMID: 30584246</a> </cite>\n"
+ "</p>\n"
+ "\n"
+ "\n"
;
var script = document.querySelector('script[src="nicotine_gwas_hs.js"]');
var section = document.createElement('section');
script.parentNode.appendChild(section);
section.appendChild(document.createTextNode(markdownContent));
[].forEach.call(script.attributes, function (attr) {
    section.setAttribute(attr.name, script.getAttribute(attr.name));
});
section.setAttribute('data-markdown', '');
})();
