(function () {
'strict'
var markdownContent = ''
+ "# A guided tour of nuclear receptor pharmacology\n"
+ "\n"
+ "<hr>\n"
+ "\n"
+ "### Hao Chen\n"
+ "\n"
+ "hchen@uthsc.edu\n"
+ "\n"
+ "TSRB Room 209\n"
+ "\n"
+ "Spring 2024\n"
+ "\n"
+ "<h3>\n"
+ "<a href=\"https://chen42.github.io/slides/nucrec2024.html\">\n"
+ "https://chen42.github.io/slides/nucrec2024.html</a>\n"
+ "</h3>\n"
+ "\n"
+ "All figures are linked to the original papers \n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Outline\n"
+ "\n"
+ "* Nuclear receptor family \n"
+ "* Ligands\n"
+ "* Structure\n"
+ "* Signaling\n"
+ "* Diseases  \n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nuclear receptor family \n"
+ "\n"
+ "<a href=\"https://open.lib.umn.edu/pharmacology/chapter/nuclear-receptors/\">\n"
+ "<img src=\"https://open.lib.umn.edu/app/uploads/sites/211/2018/05/100.png\" width=70%>\n"
+ "</a>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<a href=\"https://en.wikipedia.org/wiki/Transcription_factor\">\n"
+ "<img src=\"https://upload.wikimedia.org/wikipedia/commons/8/80/Transcription_Factors.svg\">\n"
+ "</a>\n"
+ "\n"
+ "---\n"
+ "##  Human has 48 NR\n"
+ "\n"
+ "<a href=\"https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8628184/\">\n"
+ "<img src=\"https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8628184/bin/ebc-65-ebc20210020C-g1.jpg\" width=80%>\n"
+ "</a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Four types of NR\n"
+ "\n"
+ "<a href=\"https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6159888/\">\n"
+ "<img src=\"./images/nr/nr_four_types.png\" width=60%>`\n"
+ "</a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## RXR\n"
+ "\n"
+ "<a href=\"https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4097889/\">\n"
+ "<img src=\"https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4097889/bin/nihms341742f1.jpg\" width=70%>\n"
+ "</a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## DNA binding properties of NR\n"
+ "<a href=\"https://academic.oup.com/biolreprod/article/83/1/3/2530060?login=false\">\n"
+ "<img src=\"https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/biolreprod/83/1/10.1095_biolreprod.110.083824/1/m_bire-83-01-19-f02.jpeg?Expires=1709890471&Signature=cXF2nal0lHY1hWq3yu4XlAuuMblvm0NmNqEfVSO3fzEax7td1rzUZKcI7Uq8fmzPa4Aan2T0V~dpCcEsB~EW2nHqErvK9DAMfzqtsNQO-Ak77nwkvFJ2xufRHL6KtzzdSQRadg477gooMm5KfzvlW-Zru-7Pq8c~fpGpoARW07Y~zyPmIwxulmlBdoLFx5Jw5SnNPDZ1yoDNotoOQQoOZt8qA2ve7aWmyIX3UkbSTdLFIpVkcW9NQCmOjRrQKrHXs-bJlqZ7Vwp6BDWno3lQIEmLpecDjQW4YExKtfI7u75S-8~qKlb4gCpTrzC1UvvkttHS3QNMlJ3qT5nWgHqyMA__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA\">\n"
+ "</a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "##  NR mechanism of action\n"
+ "\n"
+ "<a href=\"https://onlinelibrary.wiley.com/doi/full/10.1002/pro.3496\">\n"
+ "<img src=\" https://onlinelibrary.wiley.com/cms/asset/1a261646-ae71-4cb7-83d2-f2c59752b243/pro3496-fig-0008-m.jpg\" width=70%>\n"
+ "</a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Human GR\n"
+ "\n"
+ "<a href=\"https://www.ncbi.nlm.nih.gov/books/NBK279171/\">\n"
+ "<img src=\"https://www.ncbi.nlm.nih.gov/books/NBK279171/bin/glucocort-receptor-Image003.jpg\">\n"
+ "</a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## GR signaling pathways\n"
+ "\n"
+ "<a href=\"https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4084612/\">\n"
+ "<img src=\"https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4084612/bin/nihms584741f3.jpg\">\n"
+ "</a>\n"
+ "\n"
+ "---\n"
+ "## NR signaling\n"
+ "\n"
+ "<a href=\"https://pubmed.ncbi.nlm.nih.gov/8521508/\">\n"
+ "<img src=\"images/nr/rxr_steps.png\">\n"
+ "</a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Coactivator and corepressor complexes and histone acetylation\n"
+ "\n"
+ "<a href=\"https://journals.physiology.org/doi/full/10.1152/physrev.2001.81.3.1269?rfr_dat=cr_pub++0pubmed&url_ver=Z39.88-2003&rfr_id=ori%3Arid%3Acrossref.org\">\n"
+ "<img src=\"https://journals.physiology.org/cms/10.1152/physrev.2001.81.3.1269/asset/images/large/9j0310150009.jpeg\">\n"
+ "</a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Transcriptional activation by GR\n"
+ "<a href=\"https://www.jacionline.org/article/S0091-6749(06)00289-2/fulltext\">\n"
+ "<img src=\"https://www.jacionline.org/cms/attachment/71edf4e5-ea81-4994-a9ee-4213072dafd5/gr3.jpg\">\n"
+ "</a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nuclear receptor and histone modification \n"
+ "\n"
+ "<a href=\"https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4085186/#:~:text=Histone%20modifications%20associated%20with%20transcriptional,of%20H3%20at%20serine%2010.\">\n"
+ "<img src=\"https://www.ncbi.nlm.nih.gov/corecgi/tileshop/tileshop.fcgi?p=PMC3&id=1296734&s=44&r=1&c=1\">\n"
+ "</a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Anti-inflammatory effect of GR\n"
+ "\n"
+ "<a href=\"https://www.dropbox.com/scl/fi/86eid6uondf56pdkwk3uu/barnes2006.pdf?rlkey=w7voj4b6e6fxvg1sb0sgpr9oe&dl=0\">\n"
+ "<img src=\"images/nr/gr_anti-inflammatory.png\" width=80%>\n"
+ "</a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Drugs for prostate cancer\n"
+ "\n"
+ "<a href=\"https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6966469/\">\n"
+ "<img src=\"https://www.ncbi.nlm.nih.gov/corecgi/tileshop/tileshop.fcgi?p=PMC3&id=474002&s=96&r=1&c=1\">\n"
+ "</a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nuclear receptor crosstalk\n"
+ "\n"
+ "<a href=\"https://www.nature.com/articles/s41574-020-0349-5\">\n"
+ "<img src=\"https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41574-020-0349-5/MediaObjects/41574_2020_349_Fig2_HTML.png?as=webp\" width=50%>\n"
+ "</a>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Now you are ready to read this review\n"
+ "\n"
+ "Burris TP, de Vera IMS, Cote I, Flaveny CA, Wanninayake US, Chatterjee A, Walker JK, Steinauer N, Zhang J, Coons LA, Korach KS, Cain DW, Hollenberg AN, Webb P, Forrest D, Jetten AM, Edwards DP, Grimm SL, Hartig S, Lange CA, Richer JK, Sartorius CA, Tetel M, Billon C, Elgendy B, Hegazy L, Griffett K, Peinetti N, Burnstein KL, Hughes TS, Sitaula S, Stayrook KR, Culver A, Murray MH, Finck BN, Cidlowski JA. \n"
+ "<a href=\"https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10595025/\">\n"
+ "International Union of Basic and Clinical Pharmacology CXIII: Nuclear Receptor Superfamily-Update 2023. Pharmacol Rev. 2023 Nov;75(6):1233-1318. doi: 10.1124/pharmrev.121.000436. Epub 2023 Aug 16. PMID: 37586884; PMCID: PMC10595025.</a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "\n"
+ "\n"
;
var script = document.querySelector('script[src="nucrec2024.js"]');
var section = document.createElement('section');
script.parentNode.appendChild(section);
section.appendChild(document.createTextNode(markdownContent));
[].forEach.call(script.attributes, function (attr) {
    section.setAttribute(attr.name, script.getAttribute(attr.name));
});
section.setAttribute('data-markdown', '');
})();
