(function () {
'strict'
var markdownContent = ''
+ "\n"
+ "\n"
+ "## GWAS on socially acquired nicotine IVSA in heterogeneous stock rats\n"
+ "\n"
+ "\n"
+ "<hr color=#cb4b16>\n"
+ "\n"
+ "###	Hao Chen\n"
+ "\n"
+ "### University of Tennessee Health Science center\n"
+ "\n"
+ "#### Feb 12, 2021\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Social learning enables nicotine self-administration\n"
+ "\n"
+ "<img height:auto width=90% src=\"images/socially_acquired_nicotine_ivsa.png\">\n"
+ "\n"
+ "<font size=4> No water or food deprivation or operant pretraining, can be used to model smoking initiation in adolescents. </font>\n"
+ "\n"
+ "<hr align=\"left\" width=15%>\n"
+ "<p align=left>\n"
+ "<cite> Chen, et al., Neuropsychopharmacology, 2011 </cite>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nicotine intake with appetitive vs aversive cues\n"
+ "\n"
+ "<img width=50% src=\"images/quinine/pres.sacc_quinine.png\">\n"
+ "\n"
+ "<hr align=\"left\" width=15%>\n"
+ "<p align=left>\n"
+ "<cite> Wang, et al., Psychopharmacology, 2016 </cite>\n"
+ "</p>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Nicotine self-administration\n"
+ "\n"
+ "### cue: saccharin + grape odor + CS2\n"
+ "\n"
+ "#### Adolescent HS rats (711 F, 711 M)\n"
+ "\n"
+ "<img width=75% height=\"auto\" src=\"images/gwasv3/nicotine_fr10_phaseone_all_data.png\">\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nicotine self-administration\n"
+ "\n"
+ "### cue:  quinine + grape odor + CS2 \n"
+ "\n"
+ "\n"
+ "<img width=75% height=\"auto\" src=\"images/p50/p50_quinine.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "\n"
+ "## GWAS summary, version 3\n"
+ "\n"
+ "|Behavior | Sample size | N traits | N QTL traits | N significant QTL| \n"
+ "|---|---|---:|---:|---:|\n"
+ "| open field | 626 M, 620 F | 6 | 5 | 9 | \n"
+ "| novel object interaction|623 M, 622 F| 6 | 4| 7|\n"
+ "| social interaction | 664 M, 664 F | 11| 10| 14| \n"
+ "| elevated plus maze | 659 M, 658 F | 10| 7| 8| \n"
+ "| socially acquired nicotine IVSA| 711 M, 711 F| 63| 24 | 30| \n"
+ "\n"
+ "One trait mapped to multiple loci; multiple traits mapped to the same loci\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Overlapping QLT between social interaction & socially acquired nicotine IVSA \n"
+ "\n"
+ "<div id=\"left50\">\n"
+ "<center>\n"
+ "In social zone frequency\n"
+ "<img src=\"images/gwasv3/locuszoom_insoczonefreq.png\" width=90%>\n"
+ "<br>\n"
+ "<center>\n"
+ "</div>\n"
+ "<div id=\"right50\">\n"
+ "<center>\n"
+ "Total inactive lick, 10 sessions\n"
+ "<img src=\"images/gwasv3/locuszoom_total_inactive_lick_10days.png\" width=90%>\n"
+ "<br>\n"
+ "<center>\n"
+ "</div>\n"
+ "\n"
+ "<hr>\n"
+ "<p>\n"
+ "\n"
+ "<small>\n"
+ "Pearson correlation r=0.11, p=8.9e-05;\n"
+ "PhWAS: -logP=7.273, r2=0.275, dprime=0.993\n"
+ "\n"
+ "<br>\n"
+ "The QTL region is 266k bp, has two known genes:\n"
+ " <b>Abhd17b</b>, abhydrolase domain containing 17B, is located on the postsynaptic membrane of glutamatergic synapses, and regulates dendritic spine maintenance.\n"
+ " <b>Gda</b>, guanine deaminase, is expressed in cortical and hippocampal neurons and increases dendritic branching in culture. \n"
+ "</small>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Number of licks on the active spout in first session: chr1:278524299\n"
+ "\n"
+ "<img src=\"./images/gwasv3/locuszoom_day1_active_licks.png\" width=60%>\n"
+ "\n"
+ "The QLT region is 6.9 Mbp and has 39 known genes. Four genes has missense variants, two genes has cis-eQTL with r2 > 0.6.\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## http://rats.pub\n"
+ "\n"
+ "<a href=\"http://rats.pub/cytoscape/?rnd=tmpzcBObC&genequery=Gfra1_Nhlrc2_Hspa12a_Vti1a_Shtn1_Tcf7l2_Adrb1_Nrap_Gpam_Casp7\" target=_new>\n"
+ "<img src=\"./images/gwasv3/active_lick_gwas_smoking_genes_ratspub.svg\">\n"
+ "</a>\n"
+ "\n"
+ "Rats.pub is designed to take a list of gene symbols and mine the PubMed and GWAS catalog for sentences pertain to addiction.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "##  Rat GWAS and human smoking overlaps\n"
+ "<pre>\n"
+ " 16913 rat human common gene symbols\n"
+ "  1600 human smoking/copd gene symbol avaialbe in rat\n"
+ "   805 nicsa gene symbols \n"
+ "   315 nicsa gene symbols available in human\n"
+ "    33 gene symbols overlapping nicsa and human smoking \n"
+ "\n"
+ " Chance of human/rat gene involved in smoking/copd: 1600/16913=0.946\n"
+ " For 315 genes, we expect to find 29.8 genes \n"
+ "</pre>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Summary of nicotine GWAS, part 1/4\n"
+ "\n"
+ "## Number of licks on the active spout\n"
+ "\n"
+ "|ID |Session|Location| Genes (n) | Human Smoking GWAS Genes|\n"
+ "|---|:---:|---|---|---|\n"
+ "|12.20 | day 1 | chr1:278524299| 99 | Gpam&clubs;&diams;, [Vti1a](http://rats.pub/cytoscape/?rnd=tmpUpzbbT&genequery=VTI1A)<font color=\"darkslateblue\">&spades;</font>, Nhlrc2&clubs;&diams;, Adrb1&clubs;, Tcf7l2, [Hspa12a](http://rats.pub/cytoscape/?rnd=tmpFrhLrJ&genequery=HEAT-SHOCK-PROTEIN-FAMILY-A-HSP70-MEMBER-12A_HSPA12A)<font color=\"darkslateblue\">&spades;</font>, [Shtn1](http://rats.pub/cytoscape/?rnd=tmpJiHXFf&genequery=KIAA1598_SHOOTIN-1_SHOOTIN1_SHTN1)<font color=\"darkslateblue\">&spades;</font>&diams;, [Nrap](http://rats.pub/cytoscape/?rnd=tmpaUzTZp&genequery=N-RAP_NEBULIN-RELATED-ANCHORING-PROTEIN_NRAP)<font color=\"darkslateblue\">&spades;</font>, Casp7&diams; Gfra1|\n"
+ "|12.29 | day 2 | chr8:22496077| 29| [Carm1](http://rats.pub/cytoscape/?rnd=tmpaHVoNJ&genequery=carm1) |\n"
+ "|12.24 | day 4 | chr4:145377793| 20| [Emc3](http://rats.pub/cytoscape/?rnd=tmpQXgUzk&genequery=emc3) |\n"
+ "|12.12 | day 5 | chr16:83955432| 23| Tex29| \n"
+ "|12.08 | day 7 | chr16:83489214| 23| Tex29| \n"
+ "|12.02 | day 9 | chr10:32845925| 90| | \n"
+ "|12.22 | day 10 | chr2:247766389|20| [Pkn2, Gtf2b](http://rats.pub/cytoscape/?rnd=tmpPoBkQf&genequery=Pkn2_Gtf2b) |\n"
+ "|12.16 | Reinstatment | chr1:161226950| 28|Usp35, Gab2, Nars2, Tenm4, [Alg8](http://rats.pub/cytoscape/?rnd=tmpJKLgcJ&genequery=Usp35_Gab2_Nars2_Tenm4_Alg8)&diams;&hearts; |\n"
+ "\n"
+ "\n"
+ "<font color=\"darkslateblue\">&spades;</font>: smoking initiation genes\n"
+ "&clubs;: Alcohol consumption genes\n"
+ "&diams;: cis-eQTL\n"
+ "&hearts; missense variants\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Vti1a, Shtn1 and Nrap for smoking initiation \n"
+ "\n"
+ "<font size =2>\n"
+ "Association studies of up to 1.2 million individuals yield new insights into the genetic etiology of tobacco and alcohol use\n"
+ "<br>\n"
+ "Mengzhen Liu, ... Scott Vrieze, Nature Genetics 2019\n"
+ "</font>\n"
+ "\n"
+ "![](./images/gwasv3/smoking_initiation_vti1a_nrap_shtn1.png)\n"
+ "<p align=left>\n"
+ "<b>Vti1a</b> is expressed in all 440 RNAseq samples from 5 brain regions, FPKM:30.    Vti1a regulates synaptic vesicle and dense core vesicle secretion via protein sorting at the Golgi. PMID:30143604, 10908612. Vti1a has no cis-eQTL\n"
+ "<br>\n"
+ "<b>Nrap</b> is not well detected in most RNAseq samples (FPKM: 0.1-0.2), involved in ribosome biogenesis (PMID11895476).<br> \n"
+ "<b>Shtn1</b> expression is about FPKM:19. Shtn1 accumulates in the neurite tips and is a key regulator of axon outgrowth (PMID:20664640) Shtn1 has a cis-eQTL (but may not be in LD with top behavioral SNP).\n"
+ "</p>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Summary of nicotine GWAS, part 2/4\n"
+ "\n"
+ "## Number of infusions\n"
+ "\n"
+ "|ID|Session|Location| Genes (n)| Human Smoking GWAS Genes|\n"
+ "|---|:---:|---|---|---|\n"
+ "|12.09 | day 5 | chr16:83500180| 23| Tex29 |\n"
+ "|12.13 | day 5 | chr17:17103044| 1| [ID4](http://rats.pub/cytoscape/?rnd=tmpdaIxug&genequery=ID4) |\n"
+ "|12.11 | day 7 | chr16:83500180| 23| Tex29|\n"
+ "|12.23 | day 7 | chr3:104723116| 8|[Hmgn4, Fmn1](http://rats.pub/cytoscape/?rnd=tmpSBamBX&genequery=Hmgn4_Fmn1) |\n"
+ "|12.15 | day 8 | chr19:26396258| 1| |\n"
+ "|12.03 | median of last 3 days | chr11:17834164|27| | \n"
+ "|12.10 |total infusion | chr16:83500180| 23| [Tex29](http://rats.pub/cytoscape/?rnd=tmpesQlMB&genequery=tex29)|\n"
+ "|12.30 |slope of regression | chr8:4459578| 74| [Gria4](http://rats.pub/cytoscape/?rnd=tmpAjmeXn&genequery=Gria4_Pdgfd_Mmp12)&diams;, Pdgfd&diams;, Mmp12 |\n"
+ "\n"
+ "&diams;: cis-eQTL\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Tex29\n"
+ "\n"
+ "<font size =2>\n"
+ "Exome Chip Meta-analysis Fine Maps Causal Variants and Elucidates the Genetic Architecture of Rare Coding Variants in Smoking and Alcohol Use \n"
+ "<br>\n"
+ "David Brazel, ... Scott Vrieze, Biol Psychiatry 2019\n"
+ "</font>\n"
+ "\n"
+ "![](./images/gwasv3/tex29_gwas_pack_years.png)\n"
+ "\n"
+ "<pre>\n"
+ "\n"
+ "2. Pack Years (PckYr).\n"
+ "Defined in the same way as cigarettes per day but not necessarily binned, divided by 20 (cigarettes in \n"
+ "a pack), and multiplied by number of years smoking. This yielded a measure of total overall exposure to\n"
+ "tobacco and is relevant to disease outcomes for which smoking is a risk factor, such as cancer and \n"
+ "chronic obstructive pulmonary disease risk\n"
+ "\n"
+ "</pre>\n"
+ "\n"
+ "Not much literature on this gene and expression level in the brain is almost 0. But GTex reports its detection. \n"
+ "The annotation is intergenic! <a href=\n"
+ "\"http://genome.ucsc.edu/cgi-bin/hgTracks?db=hg38&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr13%3A110979763%2D112075449&hgsid=1028729693_QukEveNO4EoDL3hNviIqVJ3lcbnb\"> What else is here?</a>\n"
+ "\n"
+ "\n"
+ "Could it be Arhgef7? Brain expression FPKM=30. Involed in spine morphogenesis. Loss of Arhgef7 results in extensive loss of axons PMID:30683798, PMID:29891904\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Summary of nicotine GWAS, part 3/4\n"
+ "\n"
+ "## Number of licks on the inactive spout \n"
+ "\n"
+ "|ID|Session|Location| Genes (n)|Human Smoking GWAS Genes|\n"
+ "|---|:---:|---|---|---|\n"
+ "|12.18 | day 3 | chr1:253523411| 10| |\n"
+ "|12.04 | day 7 | chr14:108854633|23| XPO1, USP34, BCL11A |\n"
+ "|12.06 | day 9 | chr16:5256755|1| Cacna2d3 |\n"
+ "|12.21 | day 9 | chr1:74927958| 195| U2af2, KMT5C, FAM71E2, TMEM238, COX6B2, TMEM190, Il11, Lilrb4| \n"
+ "|12.26 | day 9 | chr6:71588778| 46| Foxg1, Heatr5a&hearts;, Prkd1 |\n"
+ "|12.27 | day 9 | chr7:110658276| 7| |\n"
+ "|12.07 | day 10 | chr16:5288954|1 | Cacna2d3 |\n"
+ "|12.17 | total | chr1:239058463| 7||\n"
+ "|12.19 | total | chr1:253766837| 10||\n"
+ "\n"
+ "&hearts;:protein coding variant\n"
+ "\n"
+ "<b>Cacna2d3</b> is associated with nicotine dependence, smoking status, lung cancer, and COPD in five studies. FPKM 100 in Accumbens, 30-40 in cortex\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Summary of nicotine GWAS, part 4/4\n"
+ "\n"
+ "## Ratio of licks on the active/inactive spouts\n"
+ "\n"
+ "|ID|Session|Location| Genes (n) | Human Smoking GWAS Genes|\n"
+ "|---|:---:|---|---|---|\n"
+ "|12.28 | day 2 | chr8:22201332| 37| Carm1 | \n"
+ "|12.14 | day 3 | chr18:50265173| 13| |\n"
+ "|12.05 | day 4 | chr16:43380960|7 | |\n"
+ "|12.01 | day 10 | chr10:104395310| 54|Tsen54 |\n"
+ "|12.25 | day 11 | chr6:21268257| 5| TTC27 |\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Acknowledgements\n"
+ "\n"
+ "* Current lab members working on this project \n"
+ "\n"
+ "<table><tr>\n"
+ "<td width=20%>\n"
+ "<img src=\"images/photos/tengfei.jpg\">\n"
+ "\n"
+ "Tengfei Wang\n"
+ "\n"
+ "</td>\n"
+ "<td width=20%>\n"
+ "<img src=\"images/photos/angel.jpg\">\n"
+ "\n"
+ "Angel Garcia Martinez\n"
+ "\n"
+ "</td>\n"
+ "<td width=20%>\n"
+ "<img src=\"images/photos/shuangying.jpg\">\n"
+ "\n"
+ "Shuangying Leng\n"
+ "\n"
+ "</td>\n"
+ "<td width=20%>\n"
+ "<img src=\"images/photos/Sarah.png\">\n"
+ "\n"
+ "Sarah Cartwright\n"
+ "\n"
+ "</td>\n"
+ "<td width=20%>\n"
+ "<img src=\"images/photos/hakan.jpg\">\n"
+ "\n"
+ "Hakan Gunturkun\n"
+ "\n"
+ "</td>\n"
+ "\n"
+ "</tr>\n"
+ "</table>\n"
+ "\n"
+ "\n"
+ "* Past technicians \n"
+ "	* *Xia Hong* | *Jie Shen* | *Wenyan Han* | *Pawandeep Kaur* | *Yanyan Lin* | *Xinyu Fan* | *Mallory Udell*|\n"
+ "* Summer students \n"
+ "	* Abigale Salinero (REHU 2015) | Cindy Tay (REHU 2016) | Raven David (REHU 2017) | Christian Hurt (REHU 2018) \n"
+ "* P50 collaborators \n"
+ "	* Abraham Palmer | Oksana Polaskaya | Apurva Chitre | Leah-Solberg Woods \n"
+ "* P30 collaborators\n"
+ " * Laura Saba | Rob Williams | Pjotr Prins \n"
+ "* UTHSC\n"
+ " * Chang Hoon Jee \n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nicotine metabolism\n"
+ "\n"
+ "<img width=60% height=\"auto\" src=\"images/p50/AllCotinine_NicotineHSRats.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Changes proposed in the renewal \n"
+ "\n"
+ "<iframe width=80% height=\"550\" src=\"https://www.youtube.com/embed/Lwfg2t9nXcI?start=45\" frameborder=\"0\" allow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n"
+ "\n"
+ "---\n"
;
var script = document.querySelector('script[src="p50_feb_2021.js"]');
var section = document.createElement('section');
script.parentNode.appendChild(section);
section.appendChild(document.createTextNode(markdownContent));
[].forEach.call(script.attributes, function (attr) {
    section.setAttribute(attr.name, script.getAttribute(attr.name));
});
section.setAttribute('data-markdown', '');
})();
