(function () {
'strict'
var markdownContent = ''
+ "## Project 2 \n"
+ "\n"
+ "<hr color=orange >\n"
+ "\n"
+ "# Socially acquired nicotine \n"
+ "# self-administration \n"
+ "\n"
+ "<hr color=orange >\n"
+ "\n"
+ "##	Hao Chen\n"
+ "\n"
+ "### University of Tennessee Health Science center\n"
+ "\n"
+ "P50 retreat, November 17th, 2022\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Specific Aims \n"
+ "<center>\n"
+ "<table> <tr><td width=50%>\n"
+ "<h3 style=\"color:#069; text-align:left\">\n"
+ "Aim 1. Phenotype adolescent HS rats on socially acquired nicotine IVSA. </h3>\n"
+ "<h3 style=\"color:#069; text-align:left\">\n"
+ "Aim 2. Analyze the relationships between behavioral traits using regression, phenome-wide association (PheWAS), and genetic correlation.\n"
+ "\n"
+ "</h3>\n"
+ "<h3 style=\"color:#069; text-align:left\">\n"
+ "Aim 3. Obtain naïve brain tissues for transcriptome sequencing.\n"
+ "</h3>\n"
+ "<p align=\"left\">\n"
+ "</small>\n"
+ "</p>\n"
+ "\n"
+ "</td></tr></table>\n"
+ "</center>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<span id=\"demo\">\n"
+ "\n"
+ "## Socially acquired nicotine intravenous self-administration\n"
+ "\n"
+ "<a href=\"#/solo\">\n"
+ "<img height:auto width=90% src=\"images/socially_acquired_nicotine_ivsa.png\">\n"
+ "</a>\n"
+ "\n"
+ "<hr align=\"left\" width=15%>\n"
+ "<p align=left> \n"
+ "<cite> Chen, et al., Neuropsychopharmacology, 2011 </cite>\n"
+ "\n"
+ "Note:\n"
+ "However, with the presence of a \"demonstrator\" rat consuming the same flavor cue, nicotine i.v. self-administration was established. \n"
+ "No water or food deprivation or operant pretraining is needed. Thus the model is appropriate for studying smoking initiation in adolescents. \n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nicotine IVSA with an aversive flavor cue\n"
+ "\n"
+ "\n"
+ "<img width=40% src=\"images/quinine/pres.sacc_quinine.png\">\n"
+ "\n"
+ "<hr align=\"left\" width=15%>\n"
+ "<p align=left>\n"
+ "<cite> Wang, et al., Psychopharmacology, 2016 </cite>\n"
+ "</p>\n"
+ "\n"
+ "Note:\n"
+ "We further reported that even when an aversive (i.e. quinine) flavor was used in place of the appetitive flavor, adolescent rats obtained nicotine IVSA, with the presence of a demonstrator consuming a flavor cue containing the same odor as the nicotine cue (i.e. inducive social environemnt (<b>ISE</b>). The number of nicotine infusions were almost identical between the two cues. <b>Therefore, licking on the active spout is most likely motivated by nicotine in this model</b> The reduced licks on the active spout was due to the reduction of licking during the timeout period following nicotine and cue delivery. \n"
+ "\n"
+ "---\n"
+ "\n"
+ "<div id=\"ofdiagram\">\n"
+ "\n"
+ "## Timetable for behavioral tests\n"
+ "\n"
+ "\n"
+ "<table> <tr><td width=30%>\n"
+ "\n"
+ "<a href=\"#/ethovision_v4_v15\">\n"
+ "<img src=\"./images/p50/openfields_verticle.png\">\n"
+ "</a>\n"
+ "\n"
+ "</td><td>\n"
+ "\n"
+ "<font size=4>\n"
+ "\n"
+ "| Age | Test |\n"
+ "|---|---|\n"
+ "|PND21|Wean, Body weight|\n"
+ "|PND31|Open field test (20min)|\n"
+ "|PND32|Novel object interaction (20min)|\n"
+ "|PND33|Social interaction test (20 min) |\n"
+ "|PND34|Elevated plus maze (6min)|\n"
+ "|PND35|Free moving social (15 min habituation + 15 min video recording)|\n"
+ "|PND38|Surgery|\n"
+ "|PND39 -- 41| Recovery|\n"
+ "|PND42 -- 51|Socially acquired nicotine IVSA|\n"
+ "|PND52| Progressive ratio test |\n"
+ "|PND53 -- 56 |Extinction|\n"
+ "|PND57|Contextual cue induced reinstatement|\n"
+ "|PND59|Tissue Collection for the IVSA rats|\n"
+ "\n"
+ "</font>\n"
+ "\n"
+ "\n"
+ "</td></tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## GWAS summary\n"
+ "\n"
+ "|Behavior | Sample size | N traits | N QTL traits | N significant QTL| \n"
+ "|---|---|---:|---:|---:|\n"
+ "| Open field test (OFT) | 626 M, 620 F | 6 | 5 | 9 | \n"
+ "| Novel object interaction (NOIT) |623 M, 622 F| 6 | 4| 7|\n"
+ "| Social interaction test (SIT) | 664 M, 664 F | 11| 10| 14| \n"
+ "| Elevated plus maze (EPM) | 659 M, 658 F | 10| 7| 8| \n"
+ "| Socially acquired nicotine IVSA| 711 M, 711 F| 63| 24 | 30| \n"
+ "\n"
+ "One trait mapped to multiple loci; multiple traits mapped to the same loci\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Aim 1\n"
+ "\n"
+ "## Progress in reanalysis of video data\n"
+ "\n"
+ "* Previous data were analyzed using Ethovision version 4.\n"
+ "	* Does not allow exporting of time bins\n"
+ "* We are now using Ethovision version 15. \n"
+ "* We have reanalyzed over 3,000 recordings \n"
+ " * open field: 60 min, novel object interaction: 20 min\n"
+ " * social interaction and elevated plus maze will be completed next. \n"
+ "\n"
+ "---\n"
+ "\n"
+ "<div id=\"ethovision_v4_v15\">\n"
+ "\n"
+ "#### Aim 1\n"
+ "\n"
+ "\n"
+ "## Ethovision data reanalysis\n"
+ "### Batches 1-16\n"
+ "\n"
+ "<a href=\"#/ofdiagram\">\n"
+ "<img src=\"./images/p50/ethovision_v4_v15.png\" width=70%> \n"
+ "</a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Aim 1\n"
+ "\n"
+ "## Open field and novel object interaction data\n"
+ "### Batches 1-25\n"
+ "<img src=\"./images/p50/p50_behavior_tests_batch1-25-0.png\" width=55%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Aim 1\n"
+ "\n"
+ "## Social interaction and elevaed plus maze data \n"
+ "### Batches 1-25\n"
+ "\n"
+ "<img src=\"./images/p50/p50_behavior_tests_batch1-25-1.png\" width=55%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Aim 1\n"
+ "\n"
+ "## Socially acquired nicotine IVSA\n"
+ "### Batches 1-25\n"
+ "\n"
+ "<img src=\"./images/p50/p50_total_infusion_by_batch.png\" width=60%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Aim 2\n"
+ "\n"
+ "## Correlations between nicotine and behavioral traits\n"
+ "\n"
+ "<table><tr>\n"
+ "<td width=50%>\n"
+ "\n"
+ "<center><b>\n"
+ "250 variables x 1490 female rats\n"
+ "</b></center>\n"
+ "\n"
+ "<img src=\"./images/p50/nic_ethovision_corrrelation_females_full.png\" width=90%>\n"
+ "</td>\n"
+ "<td>\n"
+ "\n"
+ "<center><b>\n"
+ "250 variables x 1357 male rats\n"
+ "</b></center>\n"
+ "\n"
+ "<img src=\"./images/p50/nic_ethovision_corrrelation_males_full.png\" width=90%>\n"
+ "</td>\n"
+ "</tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Fun excursion \n"
+ "\n"
+ "## Let's cluster\n"
+ "\n"
+ "250 variables x 2847 rats \n"
+ "\n"
+ "<img src=\"./images/p50/umap_fun.png\" width=80%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Aim 2\n"
+ "\n"
+ "## Correlations between nicotine and behavioral traits\n"
+ "### summary\n"
+ "\n"
+ "<img src=\"./images/p50/nicotine_corrrelation_counts.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Aim 2\n"
+ "\n"
+ "## Example correlations \n"
+ "### in females\n"
+ "<img src=\"./images/p50/selected_correlations_nic_behavior.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Aim 2\n"
+ "\n"
+ "## The benefit of time bins \n"
+ "<img src=\"./images/p50/nic_infusion_soczone_duration_bin.png\" width=60%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Aim 2\n"
+ "\n"
+ "## The benefit of time bins \n"
+ "<div id=\"left\">\n"
+ "<img src=\"./images/p50/nic_infusion_epm_open_freq.png\">\n"
+ "</div>\n"
+ "\n"
+ "<div id=\"right\">\n"
+ "<img src=\"./images/p50/nic_infusion_epm_closed_duration_bin.png\">\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Aim 3\n"
+ "\n"
+ "## RNA extraction from naive HS rats \n"
+ "### 133 rats, 384 samples\n"
+ "<img src=\"./images/p50/RNA-QC_133_brains_384samples.png\" width=90%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Extracurricular \n"
+ "\n"
+ "## Validation of GWAS targets\n"
+ "\n"
+ "Slope for the progression of nicotine infusion across sessions\n"
+ "\n"
+ "<img src=\"./images/p50/p50_gwas_slope_of_nicotine_infusion_locus_zoom.png\" width=40%>\n"
+ "\n"
+ "Gria4 has <a href=\"https://ratgtex.org/gene-eqtl-visualizer/#gria4\">cis-eQTL in many brain regions</a>, and is associated with comorbid nicotine dependence and major depression in humans <a href=\"https://pubmed.ncbi.nlm.nih.gov/30287806/\" target=_new>PMID: 30287806</a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Extracurricular \n"
+ "\n"
+ "## Gria4 null mutation abolishes nicotine CCP \n"
+ "\n"
+ "### Dr. Changhoon Jee, Assistant Prof, UTHSC\n"
+ "\n"
+ "<img src=\"./images/p50/celegans2.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Extracurricular \n"
+ "\n"
+ "## Select samples for Gria4 Western blot\n"
+ "\n"
+ "<img src=\"./images/p50/wes_slope_sample_characteristics.png\">\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Extracurricular \n"
+ "\n"
+ "## Gria4 Western blot\n"
+ "\n"
+ "<table><tr><td width=75%>\n"
+ "\n"
+ "<img src=\"./images/p50/wes_gria4_lanes.png\">\n"
+ "</td>\n"
+ "<td width=25%> \n"
+ "<img src=\"./images/p50/ampa4_gria4_western_barplot.png\">\n"
+ "</td></tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Publications in 2022 \n"
+ "\n"
+ "* Gunturkun MH, Flashner E, Wang T, Mulligan MK, Williams RW, Prins P, Chen H. GeneCup: mining PubMed and GWAS catalog for gene-keyword relationships. G3 (Bethesda). 2022 May 6;12(5):jkac059. doi: 10.1093/g3journal/jkac059. PMID: 35285473; PMCID: PMC9073678.\n"
+ "* Gunturkun MH, Wang T, Chitre AS, Garcia Martinez A, Holl K, St Pierre C, Bimschleger H, Gao J, Cheng R, Polesskaya O, Solberg Woods LC, Palmer AA, Chen H. Genome-Wide Association Study on Three Behaviors Tested in an Open Field in Heterogeneous Stock Rats Identifies Multiple Loci Implicated in Psychiatric Disorders. Front Psychiatry. 2022 Feb 14;13:790566. doi: 10.3389/fpsyt.2022.790566. PMID: 35237186; PMCID: PMC8882588.\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Acknowledgements\n"
+ "\n"
+ "* Lab members working on this project \n"
+ "\n"
+ "<table><tr>\n"
+ "<td width=14.3%>\n"
+ "<img src=\"./images/lab/twang18.jpg\">\n"
+ "Tengfei Wang\n"
+ "</td>\n"
+ "<td width=14.3%>\n"
+ "<img src=\"./images/lab/angel.jpg\">\n"
+ "Angel Garcia Martinez\n"
+ "</td>\n"
+ "<td width=14.3%>\n"
+ "<img src=\"./images/lab/shuangying.jpg\">\n"
+ "Shuangying Leng\n"
+ "</td>\n"
+ "\n"
+ "<td width=14.3%>\n"
+ "<img src=\"./images/lab/caroline.png\">\n"
+ "Caroline Jones\n"
+ "</td>\n"
+ "\n"
+ "<td width=14.3%>\n"
+ "<img src=\"./images/lab/gwen.png\">\n"
+ "Gwen Johnson\n"
+ "</td>\n"
+ "\n"
+ "<td width=14.3%>\n"
+ "<img src=\"./images/lab/rachel.jpg\">\n"
+ "Rachel Ward\n"
+ "</td>\n"
+ "<td width=14.3%>\n"
+ "<img src=\"./images/lab/hakan.jpg\">\n"
+ "Hakan Gunturkun\n"
+ "</td>\n"
+ "</tr>\n"
+ "</table>\n"
+ "\n"
+ "\n"
+ "* Past technicians \n"
+ "	* *Xia Hong* | *Jie Shen* | *Wenyan Han* | *Pawandeep Kaur* | *Yanyan Lin* | *Xinyu Fan* | *Mallory Udell* |\n"
+ "* Summer students \n"
+ "	* Abigale Salinero (REHU 2015) | Cindy Tay (REHU 2016) | Raven David (REHU 2017) | Christian Hurt (REHU 2018) | Gwen Johnson (REHU 2021) | Olivia Harrison (REHU 2022)\n"
+ "* P50 collaborators \n"
+ "	* Abraham Palmer | Oksana Polaskaya | Apurva Chitre | Leah-Solberg Woods \n"
+ "* UTHSC collaborators\n"
+ "	* Changhoon Jee | Wenlin Sun| Rob Williams\n"
+ "---\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nicotine metabolism\n"
+ "\n"
+ "<img width=60% height=\"auto\" src=\"images/p50/AllCotinine_NicotineHSRats.png\">\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nicotine IVSA with an aversive flavor cue\n"
+ "\n"
+ "<img width=60% src=\"images/quinine/ise_nse_aversivecue.png\">\n"
+ "\n"
+ "<b>NSE</b>: neutral social environemnt, i.e., the presence of a companion rat. \n"
+ "<b>ISE</b>: indusive social environment, i.e., the presences of a companion rat who has access to the flavor cue. \n"
+ "<b>AV</b>: audiovisual cue \n"
+ "\n"
+ "<hr align=\"left\" width=15%>\n"
+ "<p align=left>\n"
+ "<cite> Wang, et al., Psychopharmacology, 2016 </cite>\n"
+ "</p>\n"
+ "\n"
+ "---\n"
+ "\n"
;
var script = document.querySelector('script[src="p50_2022.js"]');
var section = document.createElement('section');
script.parentNode.appendChild(section);
section.appendChild(document.createTextNode(markdownContent));
[].forEach.call(script.attributes, function (attr) {
    section.setAttribute(attr.name, script.getAttribute(attr.name));
});
section.setAttribute('data-markdown', '');
})();
