(function () {
'strict'
var markdownContent = ''
+ "## Project 2 \n"
+ "\n"
+ "<hr color=orange >\n"
+ "\n"
+ "# Socially acquired nicotine \n"
+ "# self-administration \n"
+ "\n"
+ "<hr color=orange >\n"
+ "\n"
+ "##	Hao Chen\n"
+ "\n"
+ "### University of Tennessee Health Science center\n"
+ "\n"
+ "P50 virtual retreat, Nov 2nd, 2020\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Specific Aims \n"
+ "\n"
+ "<h3 style=\"color:#069; text-align:left\">\n"
+ " Aim 1. Phenotype adolescent HS rats on socially acquired nicotine IVSA. </h3>\n"
+ "<h4 style=\"text-align:left; text-indent:40px\">\n"
+ " Aim 1A. Breed adolescent HS rats at UTHSC. \n"
+ "</h4>\n"
+ "<h4 style=\"text-align:left; text-indent:40px\">\n"
+ " Aim 1B. Phenotype HS rats on social and emotional traits. \n"
+ "</h4>\n"
+ "<h4 style=\"text-align:left; text-indent:40px\">\n"
+ " Aim 1C. Phenotype HS rats using the socially acquired nicotine IVSA model. \n"
+ "</h4>\n"
+ "<h3 style=\"color:#069; text-align:left\">\n"
+ "Aim 2. Analyze the relationships between behavioral traits using regression, phenome-wide association (PheWAS), and genetic correlation.\n"
+ "</h3>\n"
+ "<h3 style=\"color:#069; text-align:left\">\n"
+ "Aim 3. Obtain naïve brain tissues for transcriptome sequencing.\n"
+ "</h3>\n"
+ "<p align=\"left\">\n"
+ "<small>We already have 88 samples each includes five brain regsions (IL, PL, OF, NAcc, LHb). We will collect samples (pVTA, mHb, vHIP, IC, and LH) from 500 additional brains provided by the Solberg Wood's lab.\n"
+ "</small>\n"
+ "</p>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Social learning enables nicotine self-administration\n"
+ "\n"
+ "<img height:auto width=90% src=\"images/socially_acquired_nicotine_ivsa.png\">\n"
+ "\n"
+ "<font size=4> No water or food deprivation or operant pretraining, can be used to model smoking initiation in adolescents. </font>\n"
+ "\n"
+ "<hr align=\"left\" width=15%>\n"
+ "<p align=left>\n"
+ "<cite> Chen, et al., Neuropsychopharmacology, 2011 </cite>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Flavor cues do <a href=\"#/stfp\">not</a> support nicotine self-administration\n"
+ "\n"
+ "<img height:auto width=90% src=\"images/p50/retreat2018/flavorcue.png\">\n"
+ "\n"
+ "<hr align=\"left\" width=15%>\n"
+ "<p align=left>\n"
+ "<cite> Chen, et al., Neuropsychopharmacology, 2011</cite>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nicotine intake with appetitive vs aversive cues\n"
+ "\n"
+ "<img width=50% src=\"images/quinine/pres.sacc_quinine.png\">\n"
+ "\n"
+ "<hr align=\"left\" width=15%>\n"
+ "<p align=left>\n"
+ "<cite> Wang, et al., Psychopharmacology, 2016 </cite>\n"
+ "</p>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Socially acquired nicotine self-administration\n"
+ "\n"
+ "### HS rats\n"
+ "\n"
+ "<div id=\"left50\">\n"
+ "<img width=90% height=\"auto\" src=\"images/p50/fig4.g2b.figure.male.vs.female.nicSA.cummulative.png\">\n"
+ "\n"
+ "<hr align=\"left\" width=15%>\n"
+ "<p align=left>\n"
+ "<cite> Wang, et al., Gene Brain Behav, 2014</cite>\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "<div id=\"right50\">\n"
+ "<img width=83% height=\"auto\" src=\"images/p50/fig_demo.lick.by.sex.png\">\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Modeling social learning in rats\n"
+ "\n"
+ "<div id=\"left50\">\n"
+ "<img height:auto width=90% src=\"images/galef.protocol.narrower.png\"> \n"
+ "<br>\n"
+ "\n"
+ "<hr align=\"left\" width=15%>\n"
+ "<p align=left>\n"
+ "<cite>Galef, Dev Psychobiol., 1982 </cite>\n"
+ "</div>\n"
+ "\n"
+ "<div id=\"right50\">\n"
+ "<img height:auto width=90% src=\"images/Fig1.social.rats.withdemo.svg\">\n"
+ "	<br>\n"
+ "	<hr align=\"left\" width=15%>\n"
+ "	<p align=left>\n"
+ "	<cite> Wang, et al., Gene Brain Behav 2014 </cite>\n"
+ "	</p>\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "\n"
+ "## What is the social signal?\n"
+ "\n"
+ "<img width=100% height=\"auto\" src=\"images/p50/social_3panel.png\">\n"
+ "\n"
+ "<p>\n"
+ "<hr align=\"right\" width=15%>\n"
+ "<p align=right>\n"
+ "<cite> Wang, et al., Psychopharmacology, 2016 </cite>\n"
+ "</p>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Timetable for behavioral tests\n"
+ "\n"
+ "<font size=4>\n"
+ "\n"
+ "| Age | Test |\n"
+ "|---|---|\n"
+ "|PND21|wean, Body weight|\n"
+ "|PND31|Open field (20min)|\n"
+ "|PND32|Novel object (20min)|\n"
+ "|PND33|Social interaction in the same arena as openfield (20 min)       |\n"
+ "|PND34|Elevated plus maze (6min)|\n"
+ "|PND35|Free moving social (15 min habituation + 15 min video recording)|\n"
+ "|PND38|Surgery|\n"
+ "|PND39 -- 41| Recovery|\n"
+ "|PND42 -- 51|Socially acquired nicotine IVSA|\n"
+ "|PND52| Progressive ratio test |\n"
+ "|PND53 -- 56 |Extinction|\n"
+ "|PND57|Contextual cue induced reinstatement|\n"
+ "|PND59|Tissue Collection for the IVSA rats|\n"
+ "|PND84|Tissue Collection for the naive RNAseq rats|\n"
+ "\n"
+ "</font>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nicotine self-administration\n"
+ "\n"
+ "<img width=75% height=\"auto\" src=\"images/p50/retreat2018/nicotine_fr.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Correlations among open field, novel object, social interaction, and elevated plus maze\n"
+ "\n"
+ "<img src=\"./images/p50/retreat2018/behav_cor_r_p.png\" width=60% class=\"plain\">\n"
+ "\n"
+ "\n"
+ "<p>\n"
+ "<hr align=\"right\" width=15%>\n"
+ "<p align=right>\n"
+ "<cite> Wang, et al., Scientific Report, 2018 </cite>\n"
+ "</p>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Can behavioral traits predict nicotine SA? \n"
+ "\n"
+ "<div id=\"left50\">\n"
+ "\n"
+ "<center>\n"
+ "\n"
+ "#### Loading of PCA\n"
+ "\n"
+ "<img src=\"images/p50/retreat2018/pca_loading.png\" width=90%> \n"
+ "\n"
+ "</center> \n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "<div id=\"right50\">\n"
+ "\n"
+ "<center>\n"
+ "\n"
+ "#### PCA regression summary \n"
+ "\n"
+ "</center>\n"
+ "\n"
+ "<font size=4>\n"
+ "\n"
+ "|Phenotype | Sex| Variance Explained| \n"
+ "|---|---|---|\n"
+ "|Infusion, first 3 d| F| 0.18| \n"
+ "|Infusion, first 3 d| M| 0.17| \n"
+ "|Infusion, last 3 d | F | 0.12| \n"
+ "|Infusion, last 3 d | M | 0.20| \n"
+ "|Infusion, progressive ratio | F | 0.14| \n"
+ "|Infusion, progressive ratio | M | 0.18| \n"
+ "|Active spout lick, reinstatement | F | 0.08| \n"
+ "|Active spout lick, reinstatement | M | 0.19| \n"
+ "\n"
+ "\n"
+ "</font>\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## GWAS summary, version 3\n"
+ "\n"
+ "|Behavior |  Sample size | N traits | N QTL traits | N significant QTL| \n"
+ "|---|:---:|:---:|:---:|:---:|\n"
+ "| open field | 626 M, 620 F |  6 | 5 | 9 | \n"
+ "| novel object interaction|623 M, 622 F|  6 | 4| 7|\n"
+ "| social interaction | 664 M, 664 F | 11| 10|  14| \n"
+ "| elevated plus maze |  659 M, 658 F | 10| 7| 8| \n"
+ "| socially acquired nicotine IVSA| 711 M, 711 F| 63| 24 | 30| \n"
+ "\n"
+ "one trait mapped to multiple loci; multiple traits mapped to the same loci\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Overlapping QLT between social interaction & socially acquired nicotine IVSA  \n"
+ "\n"
+ "<div id=\"left50\">\n"
+ "<center>\n"
+ "<img src=\"images/gwasv3/locuszoom_insoczonefreq.png\" width=90%>\n"
+ "<br>\n"
+ "In social zone frequency\n"
+ "<center>\n"
+ "</div>\n"
+ "<div id=\"right50\">\n"
+ "<center>\n"
+ "<img src=\"images/gwasv3/locuszoom_total_inactive_lick_10days.png\" width=90%>\n"
+ "<br>\n"
+ "Total inactive lick, 10 sessions\n"
+ "<center>\n"
+ "</div>\n"
+ "\n"
+ "<hr>\n"
+ "<p>\n"
+ "\n"
+ "<small>\n"
+ "pearson correlation r=0.11, p=8.9e-05\n"
+ "<br>\n"
+ "<b>The QTL region is 266k bp, has one known gene Abhd17b</b>, abhydrolase domain containing 17B, localizes  postsynaptic  membrane of glutamatergic synapse, regulates dendritic spine maintenance.\n"
+ "</small>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Number of licks on the active spout in first session: chr1:278524299\n"
+ "\n"
+ "<div id=\"left50\">\n"
+ "<img src=\"./images/gwasv3/locuszoom_day1_active_licks.png\">\n"
+ "\n"
+ "The QLT region is 6.9 Mbp and has 39 known genes. Four genes has missense variants, two genes has cis-eQTL with r2 > 0.6.\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "<div id=\"right50\">\n"
+ "\n"
+ "<a href=\"http://rats.pub/cytoscape/?rnd=tmpzcBObC&genequery=Gfra1_Nhlrc2_Hspa12a_Vti1a_Shtn1_Tcf7l2_Adrb1_Nrap_Gpam_Casp7\" target=_new>\n"
+ "<img src=\"./images/gwasv3/active_lick_gwas_smoking_genes_ratspub.svg\">\n"
+ "</a>\n"
+ "\n"
+ "http://rats.pub is designed to take a list of gene symbols and mine the PubMed and GWAS catalog for sentences pertain to addiction.\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Summary of nicotine GWAS, part 1/4\n"
+ "\n"
+ "## Number of licks on the active spout\n"
+ "\n"
+ "|ID |Session|Location| Genes (n) | Human Smoking GWAS Genes|\n"
+ "|---|:---:|---|---|---|\n"
+ "|12.20 | day 1 | chr1:278524299| 99 | Gpam&clubs;&diams;, [Vti1a](http://rats.pub/cytoscape/?rnd=tmpUpzbbT&genequery=VTI1A)<font color=\"darkslateblue\">&spades;</font>, Nhlrc2&clubs;&diams;, Adrb1&clubs;, Tcf7l2, [Hspa12a](http://rats.pub/cytoscape/?rnd=tmpFrhLrJ&genequery=HEAT-SHOCK-PROTEIN-FAMILY-A-HSP70-MEMBER-12A_HSPA12A)<font color=\"darkslateblue\">&spades;</font>, [Shtn1](http://rats.pub/cytoscape/?rnd=tmpJiHXFf&genequery=KIAA1598_SHOOTIN-1_SHOOTIN1_SHTN1)<font color=\"darkslateblue\">&spades;</font>&diams;, [Nrap](http://rats.pub/cytoscape/?rnd=tmpaUzTZp&genequery=N-RAP_NEBULIN-RELATED-ANCHORING-PROTEIN_NRAP)<font color=\"darkslateblue\">&spades;</font>, Casp7&diams; Gfra1|\n"
+ "|12.29 | day 2 | chr8:22496077| 29| [Carm1](http://rats.pub/cytoscape/?rnd=tmpaHVoNJ&genequery=carm1) |\n"
+ "|12.24 | day 4 | chr4:145377793| 20| [Emc3](http://rats.pub/cytoscape/?rnd=tmpQXgUzk&genequery=emc3) |\n"
+ "|12.12 | day 5 | chr16:83955432| 23| Tex29| \n"
+ "|12.08 | day 7 | chr16:83489214| 23| Tex29| \n"
+ "|12.02 | day 9 | chr10:32845925| 90|  | \n"
+ "|12.22 | day 10 | chr2:247766389|20| [Pkn2, Gtf2b](http://rats.pub/cytoscape/?rnd=tmpPoBkQf&genequery=Pkn2_Gtf2b) |\n"
+ "|12.16 | Reinstatment | chr1:161226950| 28|Usp35, Gab2,  Nars2, Tenm4, [Alg8](http://rats.pub/cytoscape/?rnd=tmpJKLgcJ&genequery=Usp35_Gab2_Nars2_Tenm4_Alg8)&diams;&hearts; |\n"
+ "\n"
+ "\n"
+ "<font color=\"darkslateblue\">&spades;</font>: smoking initiation genes\n"
+ "&clubs;: Alcohol consumption genes\n"
+ "&diams;: cis-eQTL\n"
+ "&hearts; missense variants\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Vti1a, Shtn1 and Nrap for smoking initiation \n"
+ "\n"
+ "\n"
+ "<font size =2>\n"
+ "Association studies of up to 1.2 million individuals yield new insights into the genetic etiology of tobacco and alcohol use\n"
+ "<br>\n"
+ "Mengzhen Liu, ... Scott Vrieze, Nature Genetics 2019\n"
+ "</font>\n"
+ "\n"
+ "![](./images/gwasv3/smoking_initiation_vti1a_nrap_shtn1.png)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "\n"
+ "\n"
+ "#### Summary of nicotine GWAS, part 2/4\n"
+ "\n"
+ "## Number of infusions\n"
+ "\n"
+ "|ID|Session|Location| Genes (n)| Human Smoking GWAS Genes|\n"
+ "|---|:---:|---|---|---|\n"
+ "|12.09 | day 5  | chr16:83500180| 23| Tex29  |\n"
+ "|12.13 | day 5  | chr17:17103044| 1| [ID4](http://rats.pub/cytoscape/?rnd=tmpdaIxug&genequery=ID4) |\n"
+ "|12.11 | day 7  | chr16:83500180| 23| Tex29|\n"
+ "|12.23 | day 7  | chr3:104723116| 8|[Hmgn4, Fmn1](http://rats.pub/cytoscape/?rnd=tmpSBamBX&genequery=Hmgn4_Fmn1) |\n"
+ "|12.15 | day 8  | chr19:26396258| 1| |\n"
+ "|12.03 | median of last 3 days  |  chr11:17834164|27| | \n"
+ "|12.10 |total infusion  | chr16:83500180| 23| [Tex29](http://rats.pub/cytoscape/?rnd=tmpesQlMB&genequery=tex29)|\n"
+ "|12.30 |slope of regression  | chr8:4459578| 74| [Gria4](http://rats.pub/cytoscape/?rnd=tmpAjmeXn&genequery=Gria4_Pdgfd_Mmp12)&diams;, Pdgfd&diams;, Mmp12 |\n"
+ "\n"
+ "&diams;: cis-eQTL\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Tex29\n"
+ "\n"
+ "<font size =2>\n"
+ "Exome Chip Meta-analysis Fine Maps Causal Variants and Elucidates the Genetic Architecture of Rare Coding Variants in Smoking and Alcohol Use \n"
+ "<br>\n"
+ "David Brazel, ... Scott Vrieze, Biol Psychiatry 2019\n"
+ "</font>\n"
+ "\n"
+ "![](./images/gwasv3/tex29_gwas_pack_years.png)\n"
+ "\n"
+ "<pre>\n"
+ "\n"
+ "2. Pack Years (PckYr).\n"
+ "Defined in the same way as cigarettes per day but not necessarily binned, divided by 20 (cigarettes in \n"
+ "a pack), and multiplied by number of years smoking. This yielded a measure of total overall exposure to\n"
+ "tobacco and is relevant to disease outcomes for which smoking is a risk factor, such as cancer and \n"
+ "chronic obstructive pulmonary disease risk\n"
+ "\n"
+ "</pre>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Summary of nicotine GWAS, part 3/4\n"
+ "\n"
+ "## Number of licks on the inactive spout \n"
+ "\n"
+ "|ID|Session|Location| Genes (n)|Human Smoking GWAS Genes|\n"
+ "|---|:---:|---|---|---|\n"
+ "|12.18  |  day 3  |  chr1:253523411| 10| |\n"
+ "|12.04  |  day 7  |  chr14:108854633|23| XPO1, USP34, BCL11A |\n"
+ "|12.06  |  day 9  |  chr16:5256755|1| Cacna2d3 |\n"
+ "|12.21  |  day 9  |  chr1:74927958| 195| U2af2, KMT5C, FAM71E2, TMEM238, COX6B2, TMEM190, Il11, Lilrb4| \n"
+ "|12.26  |  day 9  |  chr6:71588778| 46| Foxg1, Heatr5a&hearts;, Prkd1 |\n"
+ "|12.27  |  day 9  |  chr7:110658276| 7| |\n"
+ "|12.07  |  day 10 |  chr16:5288954|1 |  Cacna2d3  |\n"
+ "|12.17  |  total  |  chr1:239058463| 7||\n"
+ "|12.19  |  total  |  chr1:253766837| 10||\n"
+ "\n"
+ "&hearts;:protein coding variant\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Summary of nicotine GWAS, part 4/4\n"
+ "\n"
+ "## Ratio of licks on the active/inactive spouts\n"
+ "\n"
+ "|ID|Session|Location| Genes (n) | Human Smoking GWAS Genes|\n"
+ "|---|:---:|---|---|---|\n"
+ "|12.28  |  day 2  | chr8:22201332| 37| Carm1 | \n"
+ "|12.14  |  day 3  | chr18:50265173| 13| |\n"
+ "|12.05  |  day 4  | chr16:43380960|7 | |\n"
+ "|12.01  |  day 10  |   chr10:104395310| 54|Tsen54 |\n"
+ "|12.25  |  day 11  | chr6:21268257| 5| TTC27 |\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Current Progress \n"
+ "\n"
+ "### Behavior phenotyping\n"
+ "\n"
+ "| Batch | Breeders received on | Rats phenotyped |\n"
+ "|---|---|---|\n"
+ "|17|2019-09-18  | 51 M,  52 F |\n"
+ "|18|2020-01-15  | 46 M,  46 F |\n"
+ "|19|batch 18 offspring  | 19 M,  18 F |\n"
+ "|20|2020-10-20  | |\n"
+ "\n"
+ "<font size=3>\n"
+ "COVID abruptly shutting down the lab on March 24th 2020. Limited Work resumed on June 1st, 2020. Social distancing rules remain in effect. \n"
+ "</font>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Pharmacological validation of GWAS target\n"
+ "\n"
+ "* Gria4: slope of nicotine infusion ~ session \n"
+ "* Gria4 has cis-eQTL in infralimbic cortex\n"
+ "* SNP:rs68081839, P value: 2E-8, Mapped trait: nicotine dependence symptom count, depressive symptom measurement [Zhou,...Gelernter, Transl Psychiatry 2018](https://pubmed.ncbi.nlm.nih.gov/30287806/)\n"
+ "* TOPIRAMATE is an AMPA/Kainate antagonist. It has been tested clinically for smoking cessation.\n"
+ "* No data on nicotine self-administration \n"
+ "* We are testing topiramate on socially-acquired nicotine IVSA\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Using CRISPR/Cas9 knockin rat for validation\n"
+ "\n"
+ "### P50 pilot award\n"
+ "\n"
+ "<div id =\"left50\">\n"
+ "\n"
+ "<center>\n"
+ "\n"
+ "#### NAc\n"
+ "\n"
+ "<img src=\"images/gwasv3/aav-gRNA-nacc.jpg\" width=60%>\n"
+ "\n"
+ "</center>\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "<div id =\"right50\">\n"
+ "\n"
+ "<center>\n"
+ "\n"
+ "#### PFC\n"
+ "\n"
+ "<img src=\"images/gwasv3/aav-gRNA-pfc.jpg\" width=60%>\n"
+ "\n"
+ "</center>\n"
+ "</div>\n"
+ "\n"
+ "\n"
+ "<b>Rosa26 transgene</b>: LoxP-Stop-LoxP-Cas9\n"
+ "\n"
+ "<b>AAV</b>: hSyn-Kozak-iCre-P2A-mRuby2-U6-sgRNA\n"
+ "\n"
+ "\n"
+ "<br>\n"
+ "<hr align=\"left\" width=15%>\n"
+ "<p align=left>\n"
+ "<cite> Back,... Harvey, et al., Neuron 2019 </cite>\n"
+ "</p>\n"
+ "\n"
+ "\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Validation of in vivo genome editing \n"
+ "\n"
+ "\n"
+ "<img src=\"./images/gwasv3/gRNA-sequencing-igv.png\">\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Potential targets for in vivo genome editing\n"
+ "\n"
+ "* Shtn1 (active lick on day 1)\n"
+ "* Gria4 (progression of intake)\n"
+ "* Tex29 (total intake)\n"
+ "* Alg8 (reinstatement) \n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Acknowledgements\n"
+ "* Current lab members working on this project \n"
+ "	* **Tengfei Wang**, Research Associate \n"
+ "	* **Angel Garcia Martinez**, Sr. Research Assistant \n"
+ "	* **Shuangying Leng**, Sr. Research Assistant\n"
+ "	* **Sarah Cartwright**, Research Assistant\n"
+ "	* **Hakan Gunturkun**, Data Analyst\n"
+ "* Past lab members \n"
+ "	* *Xia Hong* | *Jie Shen* | *Wenyan Han* | *Pawandeep Kaur* | *Yanyan Lin* | *Xinyu Fan*  \n"
+ "* Summer students \n"
+ "	* Abigale Salinero (REHU 2015) | Cindy Tay (REHU 2016) | Raven David (REHU 2017) | Christian Hurt (REHU 2018) \n"
+ "* P50 collaborators \n"
+ "	* Abraham Palmer | Oksana Polaskaya | Apurva Chitre | Leah-Solberg Woods \n"
+ "* P30 collaborators\n"
+ " * Laura Saba | Rob Williams \n"
+ "* UTHSC\n"
+ " * Burt Sharp\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nicotine metabolism\n"
+ "\n"
+ "<img width=60% height=\"auto\" src=\"images/p50/AllCotinine_NicotineHSRats.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Changes proposed in the renewal \n"
+ "\n"
+ "<iframe width=80% height=\"550\" src=\"https://www.youtube.com/embed/Lwfg2t9nXcI?start=45\" frameborder=\"0\" allow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n"
+ "\n"
+ "---\n"
;
var script = document.querySelector('script[src="p50_2020.js"]');
var section = document.createElement('section');
script.parentNode.appendChild(section);
section.appendChild(document.createTextNode(markdownContent));
[].forEach.call(script.attributes, function (attr) {
    section.setAttribute(attr.name, script.getAttribute(attr.name));
});
section.setAttribute('data-markdown', '');
})();
