(function () {
'strict'
var markdownContent = ''
+ "# Genetic mapping of socially-acquired nicotine self-administration in adolescent outbred rats \n"
+ "\n"
+ "## Hao Chen, Ph.D.\n"
+ "### Associate Professor\n"
+ "\n"
+ "### Department of Pharmacology, Addiction Science and Toxicology\n"
+ "### University of Tennessee Health Science Center\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Outline\n"
+ "\n"
+ "* Socially-acquired nicotine i.v. self-administration\n"
+ "* Genetic mapping using heterogeneous stock rats\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nicotine is primarily aversive in non-smokers \n"
+ "\n"
+ "<table>\n"
+ " <tr>\n"
+ " <td width=50%>\n"
+ " <img width=100% src=\"images/titlepages/eissenberg.png\">\n"
+ " </td>\n"
+ " <td width=90%>\n"
+ " <img width=100% src=\"images/titlepages/dkalman.png\">\n"
+ " </td>\n"
+ " </tr>\n"
+ " <tr>\n"
+ " <td>\n"
+ "  Nausea, dizziness, sickness, headache, burning throat, coughing, etc..\n"
+ " </td>\n"
+ " <td>\n"
+ " Nicotine induces drug high only in <em>significantly nicotine-deprived smokers</em>. \n"
+ " </td>\n"
+ " </tr>\n"
+ "</table>\n"
+ "\n"
+ "Note:\n"
+ "Nicotine is the main psychoactive ingredient in tobacco products. It is higly addicitive. However, its subjective experience is primarily aversive in non-smokers. New smokers experience diziness, sickness  \n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nicotine conditioned taste aversion in rats\n"
+ "\n"
+ "<img src=\"./images/nicotine_cta_bjpharm1983.png\" width=70%>\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Kumar, et. al., Br J Pharmac 1983</span>\n"
+ "\n"
+ "Note: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2044849/?page=3\n"
+ "flavors: sodium sacchaine vs sodium chloride\n"
+ "water access were limited to 1 h per day. flavors were presented every other day, followed by nicotine vs saline injection \n"
+ "\n"
+ "---\n"
+ "\n"
+ "<span id=\"solo\">\n"
+ "\n"
+ "## Flavor cues conditioned to self-administered nicotine is aversive \n"
+ "\n"
+ "<a href=\"#/demo\">\n"
+ "<img height:auto width=90% src=\"images/p50/flavorcue_conditioned_aversion.png\">\n"
+ "</a>\n"
+ "\n"
+ "<p align=\"left\">\n"
+ "<span id=\"cite\"> Chen, et al., Neuropsychopharmacology, 2011 </span>\n"
+ "\n"
+ "\n"
+ "Note:\n"
+ "We previously reported that \n"
+ "adolescent rats developed conditioned aversion to an appetitive flavor cue (saccharine + grape odor) associated with self-administered i.v. nicotine. In this operant <i>licking</i> model, oral flavor cue and <strong>i.v.</strong> nicotine were delivered simultaneously upon the completion of a fixed-ratio 5 reinforcement schedule. \n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"cta0\">\n"
+ "\n"
+ "## Flavor cues conditioned to self-administered nicotine is aversive \n"
+ "\n"
+ "<a href=\"#/cta1\">\n"
+ "<img height:auto width=90% src=\"images/p50/nicotine_cta.png\">\n"
+ "</a>\n"
+ "\n"
+ "<p align=left> \n"
+ "<span id=\"cite\"> Chen, et al., Neuropsychopharmacology, 2011 </span>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Social influence is a key factor in smoking initiation \n"
+ "\n"
+ "<div id=\"left50\" >\n"
+ "<img width=100% src=\"images/titlepages/hoffman.png\"> \n"
+ "</div>\n"
+ "<div id=\"right50\">\n"
+ "<img width=100% src=\"images/titlepages/jfowler.png\"> \n"
+ "</div>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "## Social transmission of food preference  in rats\n"
+ "\n"
+ "<img src=\"images/galef.protocol.narrower.png\" width=50%> \n"
+ "\n"
+ "<p align=\"left\">\n"
+ "<span id=\"cite\">Galef,  Curr Protoc Neurosci, 2003</span>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<span id=\"demo\">\n"
+ "\n"
+ "## Social learning enables nicotine self-administration\n"
+ "\n"
+ "<a href=\"#/solo\">\n"
+ "<img height:auto width=100% src=\"images/socially_acquired_nicotine_ivsa.png\">\n"
+ "</a>\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Chen, et al., Neuropsychopharmacology, 2011 </span>\n"
+ "\n"
+ "Note:\n"
+ "However, with the presence of a \"demonstrator\" rat consuming the same flavor cue, nicotine i.v. self-administration was established. \n"
+ "No water or food deprivation or operant pretraining is needed. Thus the model is appropriate for studying smoking initiation in adolescents. \n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Flavor cue with greater appetitiveness does not support nicotine IVSA\n"
+ "\n"
+ "<img src=\"./images/p50/fig4.saccGluSolo_flavor.png\">\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Chen, et al., Neuropsychopharmacology, 2011 </span>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Social learning supports nicotine IVSA with an aversive flavor cue\n"
+ "\n"
+ "<img width=90% src=\"images/quinine/ise_nse_aversivecue.png\">\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Wang, et al., Psychopharmacology, 2016 </span>\n"
+ "</p>\n"
+ "\n"
+ "\n"
+ "Note:\n"
+ "We further reported that even when an aversive (i.e. quinine) flavor was used in place of the appetitive flavor, adolescent rats obtained nicotine IVSA, with the presence of a demonstrator consuming a flavor cue containing the same odor as the nicotine cue (i.e. inducive social environemnt (<b>ISE</b>). The number of nicotine infusions were almost identical between the two cues. <b>Therefore, licking on the active spout is most likely motivated by nicotine in this model</b> The reduced licks on the active spout was due to the reduction of licking during the timeout period following nicotine and cue delivery. \n"
+ "\n"
+ "<b>NSE</b>: neutral social environemnt, i.e., the presence of a companion rat. \n"
+ "<b>ISE</b>: indusive social environment, i.e., the presences of a companion rat who has access to the flavor cue. \n"
+ "<b>AV</b>: audiovisual cue \n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "##  Aversive vs appetitive flavor cue\n"
+ "\n"
+ "<img width=50% src=\"images/quinine/pres.sacc_quinine.png\">\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Wang, et al., Psychopharmacology, 2016 </span>\n"
+ "</p>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Social learning is mediated by Carbon Disulfide (CS<sub>2</sub>) in rats \n"
+ "\n"
+ "<div id=\"left50\">\n"
+ "<img height:auto width=90% src=\"images/galef.protocol.narrower.png\"> \n"
+ "<br>\n"
+ "</div>\n"
+ "\n"
+ "<div id=\"right50\">\n"
+ "<img height:auto width=90% src=\"images/titlepages/cs2.png\">\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Both CS<sub>2</sub> and flavor cue are necessary for socially acquired nicotine IVSA \n"
+ "\n"
+ "<img width=100% height=\"auto\" src=\"images/p50/cs2_1rat.png\">\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Wang, et al., PLoS One, 2014 </span>\n"
+ "</p>\n"
+ "\n"
+ "Note:\n"
+ "We confirmed that neither nicotine associated flavor cue nor carbon disulfide alone supported nicotine IVSA. However, their combination was sufficient to replicate the behavior induced by live demonstrator rats. \n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Nicotine intake is heritable \n"
+ "\n"
+ "### h<sup>2</sup>=0.54-0.65 estimated using 12 isogenic strains across two doses \n"
+ "\n"
+ "<img src=\"./images/social_nicotine_dose_isogenic_strain.png\" width=80%>\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Han, et al., Sci Report, 2017 </span>\n"
+ "</p>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<section id=\"cta1\">\n"
+ "\n"
+ "## Social learning facilitates the extinction of conditioned nicotine aversion\n"
+ "\n"
+ "<a href=\"#/cta0\">\n"
+ "<img src=\"./images/p50/correlation_ext_cta_nicotine.png\" >\n"
+ "</a>\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Han, et al., Sci Report, 2017 </span>\n"
+ "</p>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "### Summary \n"
+ "## Socially acquired nicotine IVSA in adolescent rats\n"
+ "\n"
+ "* Nicotine has both aversive and reinforcing properties\n"
+ "* Flavor cues are associated with the aversive property of nicotine \n"
+ "* Social learning facilitates nicotine intake by\n"
+ "	* enhancing the extinction of nicotine CFA, and not by  \n"
+ "	* increasing the appetitiveness of the flavor cue \n"
+ "* Operant responding is driven by the rewarding property of nicotine \n"
+ "	* dose response to nicotine across multiple strains\n"
+ "	* nicotine can be self-administered with an aversive flavor cue \n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Heterogeneous stock rats\n"
+ "\n"
+ "<table><tr><td width=20%>\n"
+ "<img src=\"https://school.wakehealth.edu/-/media/WakeForest/Global/System/Person-Images/l/Leah-Catherine-Solberg-Woods.jpg\">\n"
+ "<b>Leah Solberg Woods, Wake Forest School of Medicine \n"
+ "</b>\n"
+ "</td>\n"
+ "<td width=80%>\n"
+ "<img src=\"./images/p50/hs_rats.png\" width=80%>\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Garret and Korstanje, Trends Genet, 2020</span>\n"
+ "</td>\n"
+ "</tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Socially acquired nicotine self-administration in HS rats\n"
+ "\n"
+ "### 52 adult males and 48 adult females\n"
+ "\n"
+ "<div id=\"left50\">\n"
+ "<img width=90% height=\"auto\" src=\"images/p50/fig4.g2b.figure.male.vs.female.nicSA.cummulative.png\">\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Wang, et al., Gene Brain Behav, 2014</span>\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "<div id=\"right50\">\n"
+ "<img width=83% height=\"auto\" src=\"images/p50/fig_demo.lick.by.sex.png\">\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Experimental design\n"
+ "<div id=\"left50\">\n"
+ "<font size=3>\n"
+ "\n"
+ "| Age | Test |\n"
+ "|---|---|\n"
+ "|PND21|Wean, Body weight|\n"
+ "|PND31|Open field |\n"
+ "|PND32|Novel object |\n"
+ "|PND33|Social interaction in the same arena as openfield |\n"
+ "|PND34|Elevated plus maze |\n"
+ "|PND38|Surgery|\n"
+ "|PND39 - 41| Recovery|\n"
+ "|PND42 - 51|Socially acquired nicotine IVSA|\n"
+ "|PND52| Progressive ratio test |\n"
+ "|PND53 - 56 |Extinction|\n"
+ "|PND57|Contextual cue induced reinstatement|\n"
+ "|PND59|Tissue Collection|\n"
+ "\n"
+ "</font>\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "\n"
+ "<div id=\"right50\">\n"
+ "<center>\n"
+ "<table width=80%><tr><td>\n"
+ "We phenotyped 1600 adolescent heterogeneous stock rats on socially acquired nicotine IVSA using an flavor cue containing CS<sub>2</sub>. We also collected other behavioral traits before nicotine IVSA was started. Spleen from each rat was collected for genotyping once behavioral tests were completed. \n"
+ "</td></tr></table>\n"
+ "</center>\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Correlations among open field, novel object, social interaction, and elevated plus maze\n"
+ "\n"
+ "<img src=\"./images/p50/retreat2018/behav_cor_r_p.png\" width=60% class=\"plain\">\n"
+ "\n"
+ "<p>\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Wang, et al., Scientific Report, 2018 </span>\n"
+ "</p>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Can behavioral traits predict nicotine IVSA? \n"
+ "\n"
+ "<div id=\"left\">\n"
+ "\n"
+ "\n"
+ "\n"
+ "<center>\n"
+ "\n"
+ "#### Loading of PCA\n"
+ "\n"
+ "<img src=\"images/p50/retreat2018/pca_loading.png\" width=70%> \n"
+ "</center>\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "<div id=\"right\">\n"
+ "\n"
+ "<center>\n"
+ "\n"
+ "#### PCA regression summary \n"
+ "\n"
+ "<font size=4>\n"
+ "\n"
+ "|Phenotype | Sex| Variance Explained| \n"
+ "|---|---|---|\n"
+ "|Infusion, first 3 d| F| 0.18| \n"
+ "|Infusion, first 3 d| M| 0.17| \n"
+ "|Infusion, last 3 d | F | 0.12| \n"
+ "|Infusion, last 3 d | M | 0.20| \n"
+ "|Infusion, progressive ratio | F | 0.14| \n"
+ "|Infusion, progressive ratio | M | 0.18| \n"
+ "|Active spout lick, reinstatement | F | 0.08| \n"
+ "|Active spout lick, reinstatement | M | 0.19| \n"
+ "</font>\n"
+ "</center>\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Nicotine self-administration\n"
+ "\n"
+ "Adolescent HS rats (711 F,  711 M)\n"
+ "\n"
+ "<img width=75% height=\"auto\" src=\"images/gwasv3/nicotine_fr10_phaseone_all_data.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nicotine metabolism\n"
+ "\n"
+ "<img width=60% height=\"auto\" src=\"images/p50/AllCotinine_NicotineHSRats.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Genotyping  and GWAS\n"
+ "\n"
+ "<table> <tr>\n"
+ "	<td width=50%>\n"
+ "		<p align=\"center\"> <img src=\"./images/p50/AGileta_G3.png\" width=60%> </p>\n"
+ "		<p align=left>\n"
+ "		<span id=\"cite\"> Gileta et al., G3, 2020. </span>\n"
+ "		</p>\n"
+ "	</td>\n"
+ "	<td width=50%>\n"
+ "		<p align=center>\n"
+ "		<img src=\"https://pbs.twimg.com/profile_images/775453143559581697/ECeItK57.jpg\" width=30%>\n"
+ "		<br>\n"
+ "		<b>Abraham Palmer, UCSD</b>\n"
+ "		</p>\n"
+ "		<p>\n"
+ "		<ul>	\n"
+ "			<li> 3.5 million SNPs per individual (estimated error rate <1%)\n"
+ "			<li> GCTA with liner mixed model\n"
+ "			<li> Leave one chromosome out procedure\n"
+ "			<li> Genome-wide significance level set by permuation: -log10(p) > 5.6 \n"
+ "		</ul>\n"
+ "	</td>\n"
+ "</tr>\n"
+ "</table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## GWAS reports\n"
+ "\n"
+ "<table ></tr><td width=70%>\n"
+ "\n"
+ "<a href=\"https://palmerlab.s3.sdsc.edu/p50_reports/open_field.html\" target=_new>\n"
+ "\n"
+ "<img src=\"./images/p50/gwas_report.png\">\n"
+ "</a>\n"
+ "\n"
+ "</td>\n"
+ "<td>\n"
+ "<center>\n"
+ "<img src=\"https://i1.rgstatic.net/ii/profile.image/408091221872646-1474307937807_Q512/Apurva-Chitre.jpg\" width=60%><br>\n"
+ "\n"
+ "<b>\n"
+ "Apurva Chitre, UCSD\n"
+ "</b>\n"
+ "</center>\n"
+ "</td>\n"
+ "</tr>\n"
+ "</table>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## SNP heritability\n"
+ "\n"
+ "<img src=\"./images/p50/heritability_for_all_traits.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Summary of GWAS \n"
+ "\n"
+ "|Behavior | Sample size | N traits | N sig. QTL| \n"
+ "|---|---|---:|---:|\n"
+ "| open field | 626 M, 620 F | 6 | 9 | \n"
+ "| novel object interaction|623 M, 622 F| 6 | 7|\n"
+ "| social interaction | 664 M, 664 F | 11| 14| \n"
+ "| elevated plus maze | 659 M, 658 F | 10| 7| \n"
+ "| socially acquired nicotine IVSA| 711 M, 711 F| 63| 30| \n"
+ "\n"
+ "---\n"
+ "<section id=\"manh_d5\">\n"
+ "\n"
+ "## GWAS: Nicotine infusion on session 5 \n"
+ "\n"
+ "<img src=\"images/p50/gwas_day5_infusion.jpg\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Porcupine plot: open field & novel object interaction \n"
+ "\n"
+ "<div id=\"left\">\n"
+ "<img src=\"./images/p50/porcupine_plot_OFT.png\">\n"
+ "</div>\n"
+ "\n"
+ "<div id=\"right\">\n"
+ "<img src=\"./images/p50/porcupine_plot_NOIT.png\">\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Porcupine plot: social interaction & elevated plus maze  \n"
+ "\n"
+ "<div id=\"left\">\n"
+ "<img src=\"./images/p50/porcupine_plot_SIT.png\">\n"
+ "</div>\n"
+ "\n"
+ "<div id=\"right\">\n"
+ "<img src=\"./images/p50/porcupine_plot_EPM.png\">\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Porcupine plot: socially acquired nicotine self-administration\n"
+ "\n"
+ "<img src=\"./images/p50/porcupine_plot_nicotine.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Slope of nicotine intake chr8:4459578 \n"
+ "\n"
+ "<div id=\"left50\">\n"
+ "<img src=\"./images/p50/gria4_locuszoom.png\">\n"
+ "\n"
+ "There are 32 known genes in this 5.1 Mb interval. Gria4 is a candidate gene.\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "<div id=\"right50\">\n"
+ "\n"
+ "<a href=\"http://rats.pub/cytoscape/?rnd=tmpzcBObC&genequery=Gfra1_Nhlrc2_Hspa12a_Vti1a_Shtn1_Tcf7l2_Adrb1_Nrap_Gpam_Casp7\" target=_new>\n"
+ "<img src=\"./images/gwasv3/active_lick_gwas_smoking_genes_ratspub.svg\">\n"
+ "</a>\n"
+ "\n"
+ "http://genecup.org is designed to take a list of gene symbols and mine the PubMed and GWAS catalog for sentences pertain to addiction.\n"
+ "\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Gunturkun, et. al., BioRxiv, 2021</span>\n"
+ "\n"
+ "</div>\n"
+ "---\n"
+ "\n"
+ "## Candidate genes for OFT, NOIT, SIT \n"
+ "\n"
+ "<div id=\"left\">\n"
+ "<img src=\"./images/p50/openfieldtablep1.png\">\n"
+ "</div>\n"
+ "<div id=\"right\">\n"
+ "<img src=\"./images/p50/openfieldtablep2.png\">\n"
+ "\n"
+ "<p align=\"left\">\n"
+ "<span id=\"cite\">Gunturkun, et.al., BioRxiv 2021</a>\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "#### Summary of nicotine GWAS \n"
+ "\n"
+ "## Number of licks on the active spout\n"
+ "\n"
+ "|ID |Session|Loc| Genes (n) | Overlapping with human smoking GWAS|\n"
+ "|---|:---:|---|---|---|\n"
+ "|12.20 | day 1 | chr1:278524299| 99 | Gpam&clubs;&diams;, [Vti1a](http://rats.pub/cytoscape/?rnd=tmpUpzbbT&genequery=VTI1A)<font color=\"darkslateblue\">&spades;</font>, Nhlrc2&clubs;&diams;, Adrb1&clubs;, Tcf7l2, [Hspa12a](http://rats.pub/cytoscape/?rnd=tmpFrhLrJ&genequery=HEAT-SHOCK-PROTEIN-FAMILY-A-HSP70-MEMBER-12A_HSPA12A)<font color=\"darkslateblue\">&spades;</font>, [Shtn1](http://rats.pub/cytoscape/?rnd=tmpJiHXFf&genequery=KIAA1598_SHOOTIN-1_SHOOTIN1_SHTN1)<font color=\"darkslateblue\">&spades;</font>&diams;, [Nrap](http://rats.pub/cytoscape/?rnd=tmpaUzTZp&genequery=N-RAP_NEBULIN-RELATED-ANCHORING-PROTEIN_NRAP)<font color=\"darkslateblue\">&spades;</font>, Casp7&diams; Gfra1|\n"
+ "|12.29 | day 2 | chr8:22496077| 29| [Carm1](http://rats.pub/cytoscape/?rnd=tmpaHVoNJ&genequery=carm1) |\n"
+ "|12.24 | day 4 | chr4:145377793| 20| [Emc3](http://rats.pub/cytoscape/?rnd=tmpQXgUzk&genequery=emc3) |\n"
+ "|12.12 | day 5 | chr16:83955432| 23| Tex29| \n"
+ "|12.08 | day 7 | chr16:83489214| 23| Tex29| \n"
+ "|12.02 | day 9 | chr10:32845925| 90| | \n"
+ "|12.22 | day 10 | chr2:247766389|20| [Pkn2, Gtf2b](http://rats.pub/cytoscape/?rnd=tmpPoBkQf&genequery=Pkn2_Gtf2b) |\n"
+ "|12.16 | Reinstatment | chr1:161226950| 28|Usp35, Gab2, Nars2, Tenm4, [Alg8](http://rats.pub/cytoscape/?rnd=tmpJKLgcJ&genequery=Usp35_Gab2_Nars2_Tenm4_Alg8)&diams;&hearts; |\n"
+ "\n"
+ "\n"
+ "<font color=\"darkslateblue\">&spades;</font>: smoking initiation genes\n"
+ "&clubs;: Alcohol consumption genes\n"
+ "&diams;: cis-eQTL\n"
+ "&hearts; missense variants\n"
+ "\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Vti1a, Shtn1 and Nrap \n"
+ "\n"
+ "Human GWAS: smoking initiation \n"
+ "\n"
+ "Rat GWAS: number of licks on active spout on day 1 \n"
+ "\n"
+ "![](./images/gwasv3/smoking_initiation_vti1a_nrap_shtn1.png)\n"
+ "\n"
+ "\n"
+ "<p align=left>\n"
+ "Association studies of up to 1.2 million individuals yield new insights into the genetic etiology of tobacco and alcohol use\n"
+ "<span id=\"cite\">\n"
+ "Liu, et. al., Nature Genetics 2010\n"
+ "</cite>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Summary of nicotine GWAS\n"
+ "\n"
+ "## Number of nicotine infusions\n"
+ "\n"
+ "|ID |Session|Loc| Genes (n) | Overlapping with human smoking GWAS|\n"
+ "|---|:---:|---|---|---|\n"
+ "|12.09 | day 5 | chr16:83500180| 23| Tex29 |\n"
+ "|12.13 | day 5 | chr17:17103044| 1| [ID4](http://rats.pub/cytoscape/?rnd=tmpdaIxug&genequery=ID4) |\n"
+ "|12.11 | day 7 | chr16:83500180| 23| Tex29|\n"
+ "|12.23 | day 7 | chr3:104723116| 8|[Hmgn4, Fmn1](http://rats.pub/cytoscape/?rnd=tmpSBamBX&genequery=Hmgn4_Fmn1) |\n"
+ "|12.15 | day 8 | chr19:26396258| 1| |\n"
+ "|12.03 | median of last 3 days | chr11:17834164|27| | \n"
+ "|12.10 |total infusion | <a href=\"#/manh_d5\">chr16:83500180| 23| [Tex29](http://rats.pub/cytoscape/?rnd=tmpesQlMB&genequery=tex29)|\n"
+ "|12.30 |slope of regression | chr8:4459578| 74| [Gria4](http://rats.pub/cytoscape/?rnd=tmpAjmeXn&genequery=Gria4_Pdgfd_Mmp12)&diams;, Pdgfd&diams;, Mmp12 |\n"
+ "\n"
+ "&diams;: cis-eQTL\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Tex29\n"
+ "\n"
+ "Human GWAS: pack years (a measure of total overall exposure to tobacco)\n"
+ "\n"
+ "Rat GWAS: total nicotine infusion\n"
+ "\n"
+ "\n"
+ "![](./images/gwasv3/tex29_gwas_pack_years.png)\n"
+ "\n"
+ "<p align=left>\n"
+ "Exome Chip Meta-analysis Fine Maps Causal Variants and Elucidates the Genetic Architecture of Rare Coding Variants in Smoking and Alcohol Use \n"
+ "<span id=\"cite\">Brazel, et. al., Biol Psychiatry 2019</span>\n"
+ "\n"
+ "Tex29 is not detected in our RNA-seq dataset (GTEx does report its detection). \n"
+ "The annotation is intergenic. <a href=\n"
+ "\"http://genome.ucsc.edu/cgi-bin/hgTracks?db=hg38&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr13%3A109022606%2D114032605&hgsid=1232470411_QzKuZnzUNHmfkCAmyLKwR2bMLn8c\" target=_new>\n"
+ "Is Arhgef7 more likely?</a> Arhgef7 expression is FPKM=30 in our dataset. It is involed in spine morphogenesis. Loss of Arhgef7 results in extensive loss of axons (PMID:30683798, PMID:29891904)\n"
+ "</div>\n"
+ "\n"
+ "\n"
+ "Note:\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Potential targets for validation \n"
+ "\n"
+ "* Shtn1 (active lick on day 1)\n"
+ "* Gria4 (progression of intake)\n"
+ "* Arhgef7/Tex29 (total intake)\n"
+ "* Alg8 (reinstatement) \n"
+ "\n"
+ "---\n"
+ "\n"
+ "## C.elegans model of nicotine conditioned cue preference\n"
+ "\n"
+ "### Dr. Changhoon Jee, Assistant Prof, UTHSC\n"
+ "\n"
+ "<table><tr><td>\n"
+ "<img src=\"https://www.uthsc.edu/pharmacology/faculty/images/jee-changhoon.jpg\">\n"
+ "</td><td>\n"
+ "\n"
+ "<img src=\"./images/p50/celegans1.png\">\n"
+ "</td></tr></table>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Gria4 null mutation abolishes nicotine CCP \n"
+ "\n"
+ "### Dr. Changhoon Jee, Assistant Prof, UTHSC\n"
+ "\n"
+ "<img src=\"./images/p50/celegans2.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Acknowledgements\n"
+ "\n"
+ "\n"
+ "<table><tr>\n"
+ "<td width=12.5%>\n"
+ "<img src=\"http://www.chenlab.one/img/team/twang18.jpg\">\n"
+ "Tengfei Wang\n"
+ "</td>\n"
+ "<td width=12.5%>\n"
+ "<img src=\"http://www.chenlab.one/img/team/angel.jpg\">\n"
+ "Angel Garcia Martinez\n"
+ "</td>\n"
+ "<td width=12.5%>\n"
+ "<img src=\"http://www.chenlab.one/img/team/shuangying.jpg\">\n"
+ "Shuangying Leng\n"
+ "</td>\n"
+ "\n"
+ "<td width=12.5%>\n"
+ "<img src=\"http://www.chenlab.one/img/team/Caroline.png\">\n"
+ "Caroline Jones\n"
+ "</td>\n"
+ "\n"
+ "<td width=12.5%>\n"
+ "<img src=\"http://www.chenlab.one/img/team/gwen.png\">\n"
+ "Gwen Johnson\n"
+ "</td>\n"
+ "\n"
+ "<td width=12.5%>\n"
+ "<img src=\"http://www.chenlab.one/img/team/rachel.jpg\">\n"
+ "Rachel Ward\n"
+ "</td>\n"
+ "<td width=12.5%>\n"
+ "<img src=\"http://www.chenlab.one/img/team/jun.jpg\">\n"
+ "Jun Huang \n"
+ "</td>\n"
+ "<td width=12.5%>\n"
+ "<img src=\"http://www.chenlab.one/img/team/tristan.jpg\">\n"
+ "Tristan de Jong\n"
+ "</td>\n"
+ "</tr>\n"
+ "</table>\n"
+ "\n"
+ "\n"
+ "<b>Past lab members </b>: Jie Shen | Wenyan Han | Pawandeep Kaur | Yanyan Lin | Xinyu Fan  | Hukan Gunturkun \n"
+ "\n"
+ "* UCSD:  Abraham Palmer | Oksana Polaskaya | Apurva Chitre \n"
+ "* Wake Forest:  Leah Solberg-Woods \n"
+ "* UTHSC: Changhoon Jee | Rob Williams\n"
+ "\n"
+ "Funding: NIH/NIDA P50DA037844\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Social interaction is not required to maintain nicotine intake\n"
+ "\n"
+ "\n"
+ "<img src=\"./images/p50/fig7.demo2solo.png\" width=50%>\n"
+ "\n"
+ "<p align=left> \n"
+ "<span id=\"cite\"> Chen, et al., Neuropsychopharmacology, 2011 </span>\n"
+ "\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nicotine IVSA with aversive flavor cue containing CS<sub>2</sub>\n"
+ "\n"
+ "Adolescent heterogeneous rats \n"
+ "\n"
+ "<div span=\"left\">\n"
+ "\n"
+ "<img width=75% height=\"auto\" src=\"images/p50/p50_quinine.png\">\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Summary of nicotine GWAS, part 3/4\n"
+ "\n"
+ "## Number of licks on the inactive spout \n"
+ "\n"
+ "\n"
+ "|ID |Session|Loc| Genes (n) | Overlapping with human smoking GWAS|\n"
+ "|---|:---:|---|---|---|\n"
+ "|12.18 | day 3 | chr1:253523411| 10| |\n"
+ "|12.04 | day 7 | chr14:108854633|23| XPO1, USP34, BCL11A |\n"
+ "|12.06 | day 9 | chr16:5256755|1| Cacna2d3 |\n"
+ "|12.21 | day 9 | chr1:74927958| 195| U2af2, KMT5C, FAM71E2, TMEM238, COX6B2, TMEM190, Il11, Lilrb4| \n"
+ "|12.26 | day 9 | chr6:71588778| 46| Foxg1, Heatr5a&hearts;, Prkd1 |\n"
+ "|12.27 | day 9 | chr7:110658276| 7| |\n"
+ "|12.07 | day 10 | chr16:5288954|1 | Cacna2d3 |\n"
+ "|12.17 | total | chr1:239058463| 7||\n"
+ "|12.19 | total | chr1:253766837| 10||\n"
+ "\n"
+ "&hearts;:protein coding variant\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Summary of nicotine GWAS, part 4/4\n"
+ "\n"
+ "## Ratio of licks on the active/inactive spouts\n"
+ "\n"
+ "\n"
+ "|ID |Session|Loc| Genes (n) | Overlapping with human smoking GWAS|\n"
+ "|---|:---:|---|---|---|\n"
+ "|12.28 | day 2 | chr8:22201332| 37| Carm1 | \n"
+ "|12.14 | day 3 | chr18:50265173| 13| |\n"
+ "|12.05 | day 4 | chr16:43380960|7 | |\n"
+ "|12.01 | day 10 | chr10:104395310| 54|Tsen54 |\n"
+ "|12.25 | day 11 | chr6:21268257| 5| TTC27 |\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Is self-administration driven by nicotine or flavor cue?\n"
+ "\n"
+ "<img src=\"./images/p50/fig5.sansFlavor.png\" width=80%>\n"
+ "\n"
+ "\n"
+ "<p align=left>\n"
+ "<span id=\"cite\"> Chen, et al., Neuropsychopharmacology, 2011 </span>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Overlapping genes between rat nicotine and human smoking GWAS \n"
+ "\n"
+ "\n"
+ "| Trait| Number of human genes* | Overlap expected by random | Actual overlap| Difference| \n"
+ "|---|---:|---:|---:|---:|\n"
+ "|Smoking | 1772| 32|39| 7| \n"
+ "|Body height| 2467| 46| 36| -10|\n"
+ "|Body mass|2920|54 |46|-8 |\n"
+ "|Education |1214 |23 | 13|-10 |\n"
+ "\n"
+ "<p>\n"
+ "\n"
+ "<div id=\"twocols\">\n"
+ " There are a total of 16913 genes symbols common between human and rat. There are 315 genes under nicotine QTL share the symbol with human genes. Chance of human/rat gene involved in smoking: 1772/16913=10%. For 315 genes, we expect to find 32 genes. The actual overlap is 39. Although this is a small enrichment, calculation conducted on other traits shows that this is an under-estimation. This is likely because the nicotine QTL contained many genes. *: reported in <a href=\"https://pubmed.ncbi.nlm.nih.gov/30584246/\">GWAS catalog</a>\n"
+ "\n"
+ "</div>\n"
+ "---\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
;
var script = document.querySelector('script[src="p50_nic_nida.js"]');
var section = document.createElement('section');
script.parentNode.appendChild(section);
section.appendChild(document.createTextNode(markdownContent));
[].forEach.call(script.attributes, function (attr) {
    section.setAttribute(attr.name, script.getAttribute(attr.name));
});
section.setAttribute('data-markdown', '');
})();
