(function () {
'strict'
var markdownContent = ''
+ "## Project 2 \n"
+ "\n"
+ "<hr color=orange >\n"
+ "\n"
+ "# Socially Acquired Nicotine \n"
+ "# Self-administration \n"
+ "\n"
+ "<hr color=orange >\n"
+ "\n"
+ "##	Hao Chen\n"
+ "\n"
+ "### University of Tennessee Health Science Center\n"
+ "\n"
+ "P50 Retreat, Oct 27th, 2023\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Specific Aims \n"
+ "<center>\n"
+ "<table> <tr><td width=50%>\n"
+ "<h3 style=\"color:#069; text-align:left\">\n"
+ "Aim 1. Phenotype adolescent HS rats on socially acquired nicotine IVSA. </h3>\n"
+ "<h3 style=\"color:#069; text-align:left\">\n"
+ "Aim 2. Analyze the relationships between behavioral traits using regression, phenome-wide association (PheWAS), and genetic correlation.\n"
+ "\n"
+ "</h3>\n"
+ "<h3 style=\"color:#069; text-align:left\">\n"
+ "Aim 3. Obtain naïve brain tissues for transcriptome sequencing.\n"
+ "</h3>\n"
+ "<p align=\"left\">\n"
+ "</small>\n"
+ "</p>\n"
+ "\n"
+ "</td></tr></table>\n"
+ "</center>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## RNA Extraction from Naive HS Rats \n"
+ "### 198 Rats, 575 samples\n"
+ "<img src=\"./images/p50/RNA-QC_198_brains_575samples.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "<span id=\"demo\">\n"
+ "\n"
+ "## Socially Acquired Nicotine Intravenous Self-administration\n"
+ "\n"
+ "<a href=\"#/solo\">\n"
+ "<img height:auto width=90% src=\"images/socially_acquired_nicotine_ivsa.png\">\n"
+ "</a>\n"
+ "\n"
+ "<hr align=\"left\" width=15%>\n"
+ "<p align=left> \n"
+ "<cite> Chen, et al., Neuropsychopharmacology, 2011 </cite>\n"
+ "\n"
+ "Note:\n"
+ "However, with the presence of a \"demonstrator\" rat consuming the same flavor cue, nicotine i.v. self-administration was established. \n"
+ "No water or food deprivation or operant pretraining is needed. Thus the model is appropriate for studying smoking initiation in adolescents. \n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nicotine IVSA with an Aversive Flavor Cue\n"
+ "\n"
+ "\n"
+ "<img width=40% src=\"images/quinine/pres.sacc_quinine.png\">\n"
+ "\n"
+ "<hr align=\"left\" width=15%>\n"
+ "<p align=left>\n"
+ "<cite> Wang, et al., Psychopharmacology, 2016 </cite>\n"
+ "</p>\n"
+ "\n"
+ "Note:\n"
+ "We further reported that even when an aversive (i.e. quinine) flavor was used in place of the appetitive flavor, adolescent rats obtained nicotine IVSA, with the presence of a demonstrator consuming a flavor cue containing the same odor as the nicotine cue (i.e. inducive social environemnt (<b>ISE</b>). The number of nicotine infusions were almost identical between the two cues. <b>Therefore, licking on the active spout is most likely motivated by nicotine in this model</b> The reduced licks on the active spout was due to the reduction of licking during the timeout period following nicotine and cue delivery. \n"
+ "\n"
+ "---\n"
+ "\n"
+ "<div id=\"ofdiagram\">\n"
+ "\n"
+ "## Behavioral Test Schedule \n"
+ "\n"
+ "\n"
+ "<table> <tr><td width=30%>\n"
+ "\n"
+ "<a href=\"#/ethovision_v4_v15\">\n"
+ "<img src=\"./images/p50/openfields_verticle.png\">\n"
+ "</a>\n"
+ "\n"
+ "</td><td>\n"
+ "\n"
+ "<font size=4>\n"
+ "\n"
+ "| Age | Test |\n"
+ "|---|---|\n"
+ "|PND21|Wean, Body weight|\n"
+ "|PND31|Open field test (20min)|\n"
+ "|PND32|Novel object interaction (20min)|\n"
+ "|PND33|Social interaction test (20 min) |\n"
+ "|PND34|Elevated plus maze (6min)|\n"
+ "|PND38|Surgery|\n"
+ "|PND39 -- 41| Recovery|\n"
+ "|PND42 -- 51|Socially acquired nicotine IVSA|\n"
+ "|PND52| Progressive ratio test |\n"
+ "|PND53 -- 56 |Extinction|\n"
+ "|PND57|Contextual cue induced reinstatement|\n"
+ "|PND59|Tissue Collection for the IVSA rats|\n"
+ "\n"
+ "</font>\n"
+ "\n"
+ "\n"
+ "</td></tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Phenotype: Open Field Test\n"
+ "\n"
+ "<img src=\"images/p50/hs_phenotype_openfield.png\" width=70%>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "## GWAS: Open Field Test\n"
+ "<img src=\"images/p50/hs_gwas_openfield_porcupine.png\" width=70%>\n"
+ "<img src=\"images/p50/hs_gwas_openfield_qtlCnt.png\" width=70%>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Phenotype: Novel Object  Test\n"
+ "\n"
+ "<img src=\"images/p50/hs_phenotype_novelobject.png\" width=70%>\n"
+ "---\n"
+ "\n"
+ "## GWAS: Novel Object Interaction\n"
+ "\n"
+ "<img src=\"images/p50/hs_gwas_novel_porcupine.png\" width=70%>\n"
+ "<img src=\"images/p50/hs_gwas_novel_qtlCnt.png\" width=70%>\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Phenotype: Social Interaction Test\n"
+ "\n"
+ "<img src=\"images/p50/hs_phenotype_social.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "## GWAS: Social Interaction\n"
+ "\n"
+ "<img src=\"images/p50/hs_gwas_social_porcupine.png\" width=70%>\n"
+ "<img src=\"images/p50/hs_gwas_social_qtlCnt.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Phenotype: Elevated Plus Maze\n"
+ "\n"
+ "<img src=\"images/p50/hs_phenotype_epm.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "## GWAS: Elevated Plus Maze \n"
+ "\n"
+ "<img src=\"images/p50/hs_gwas_epm_porcupine.png\" width=70%>\n"
+ "<img src=\"images/p50/hs_gwas_epm_qtlCnt.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "## Phenotype: Socially Acquired Nicotine IVSA  \n"
+ "\n"
+ "<img src=\"images/p50/hs_phenotype_nicsa.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## GWAS: Socially Acquired Nicotine IVSA\n"
+ "\n"
+ "<img src=\"images/p50/hs_gwas_nicsa_porcupine.png\" width=70%>\n"
+ "<img src=\"images/p50/hs_gwas_nicsa_qtlCnt.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Many QTL are Very Narrow\n"
+ "\n"
+ "<table><tr><td width=50%>\n"
+ "<center>\n"
+ "<br>\n"
+ "<img src=\"./images/p50/hs_gwas_nicsa_day2_infusion.png\"> \n"
+ "\n"
+ "</center>\n"
+ "</td><td>\n"
+ "<center>\n"
+ "<br>\n"
+ "<img src=\"./images/p50/hs_gwas_nicsa_day5_infusion.png\"> \n"
+ "</center>\n"
+ "\n"
+ "</td></tr></table>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## A Few QTL are Wide\n"
+ "\n"
+ "<img src=\"./images/p50/hs_gwas_nicsa_day1_chr1.png\" width=60%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Multiple Causal Genes in One QTL?\n"
+ "\n"
+ "<img src=\"./images/p50/GCF_015227675.21-GCF_000001405.4010.png\" width=90%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Multiple Causal Genes in One QTL?\n"
+ "\n"
+ "<img src=\"./images/p50/GCF_015227675.216-GCF_000001405.4013.png\" width=90%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Top Smoking Phenotypes in GWAS Catalogue \n"
+ "\n"
+ "|Trait| Number of Sig. SNPs <sup>1</sup> | Note|\n"
+ "|---|---|---|\n"
+ "|Smoking initiation <sup>2</sup>              |   5498  | 5269 from Saunders, et al. PMID: 36477530 and Liu et al.,  PMID: 30643251|\n"
+ "|Cigarettes smoked per day       |   610   | | \n"
+ "|Smoking status <sup>3 </sup>                 |   481  | 218 were from Karlsson Linnér  et al. PMID: 30643258. |\n"
+ "|Smoking cessation <sup>4 </sup>             |   452  | 335 were from Saunders, et al.,  PMID: 36477530.|\n"
+ "|Age of smoking initiation       |   243  ||\n"
+ "\n"
+ "<table><tr><td>\n"
+ "<p align=\"left\">\n"
+ "1 p-val < 5E-8\n"
+ "<br>\n"
+ "2 ever being a regular smoker in their life (current or former) vs  never being a regular smoker in their life \n"
+ "<br>\n"
+ "3 Ever vs nerver smoker\n"
+ "<br>\n"
+ "4 Current smokers vs  former smokers \n"
+ "</p>\n"
+ "</td></tr></table>\n"
+ "\n"
+ "</p>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Overlap Between Genes Under Rat NicIVSA QTL \n"
+ "## and Human Smoking Initiation \n"
+ "\n"
+ "<img src=\"images/p50/hs_gwas_nicsa_smoking_init_genes.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Overlap Between Genes Under Rat NicIVSA QTL \n"
+ "## and Cigarettes per Day \n"
+ "\n"
+ "<img src=\"images/p50/hs_gwas_nicsa_cig_per_day_genes.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Gene Ontology Enrichment of Overlapping Rat and Human Genes\n"
+ "\n"
+ "<img src=\"images/p50/goprofiler_GO_enrichemnt_for_smoking_genes.png\" width=60%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Candidate Genes Based on eQTL and Variant Impact\n"
+ "### filtering by literatuer using GeneCup.org\n"
+ "\n"
+ "<img src=\"./images/p50/genecup_graph_all_rat_only_nicsa_genes.svg\" width=45%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Large Language Model Reads the Papers \n"
+ "\n"
+ "<table><tr><td>\n"
+ "<img src=\"./images/p50/RAG.png\">\n"
+ "<small>credit: https://www.youtube.com/watch?app=desktop&v=ctzDFIINSrI</small>\n"
+ " </td>\n"
+ " <td>\n"
+ " <b>User:</b> What are the potential molecular pathways where Camk1 may affect nicotine addiction?\n"
+ " <hr>\n"
+ " <b>Arithmo-Mistral-7B: </b> \n"
+ "    One possible mechanism by which CamK1 may affect nicotine addiction is\n"
+ "    through the regulation of glutamate release in the VTA. Glutamate is the\n"
+ "    primary excitatory neurotransmitter in the brain, and its release in the\n"
+ "    VTA is thought to play a key role in the reinforcement process of nicotine\n"
+ "    addiction. CamK1 may regulate glutamate release by phosphorylating specific\n"
+ "    proteins involved in exocytosis, such as syntaxin1 and SNAP-25.\n"
+ "    </td></tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Novel Candidate Genes for Nicotine IVSA not Reported in Human GWAS\n"
+ "\n"
+ "<a href=\"https://genecup.org/cytoscape/?rnd=tmpxUiwWs&genequery=Camk1_Tlr9_Grm2_Trim32_Akap2_Scn3b_Col4a1\">\n"
+ "\n"
+ "<img src=\"./images/p50/genecup_novel_nicotine_genes.png\" width=50%>\n"
+ "\n"
+ "</a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Zebrafish Nicotine Conditioned Place Preference Test\n"
+ "\n"
+ "<table><tr><td width=50%>\n"
+ "\n"
+ "<img src=\"./images/p50/fish_sleap.jpg\">\n"
+ "\n"
+ "</td><td>\n"
+ "\n"
+ "<img src=\"./images/p50/zebrafish_nicotine_cpp.png\">\n"
+ "</td></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Base Editing Zebrafish Genome \n"
+ "\n"
+ "<table><tr><td width=37%>\n"
+ "\n"
+ "<img src=\"./images/p50/fish_inj3.jpg\">\n"
+ "\n"
+ "</td><td width=63%>\n"
+ "\n"
+ "<img src=\"./images/p50/zebrafish_pamless.png\">\n"
+ "\n"
+ "</td></table>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Acknowledgements\n"
+ "\n"
+ "\n"
+ "<table width=70%><tr>\n"
+ "\n"
+ "<td width=20%>\n"
+ "<img src=\"./images/lab/angel.jpg\">\n"
+ "Angel Garcia Martinez\n"
+ "</td>\n"
+ "<td width=20%>\n"
+ "<img src=\"./images/lab/shuangying.jpg\">\n"
+ "Shuangying Leng\n"
+ "</td>\n"
+ "<td width=20%>\n"
+ "<img src=\"./images/lab/caroline.png\">\n"
+ "Caroline Jones\n"
+ "</td>\n"
+ "<td width=20%>\n"
+ "<img src=\"./images/lab/rachel.jpg\">\n"
+ "Rachel Ward\n"
+ "</td>\n"
+ "\n"
+ "</tr>\n"
+ "</table>\n"
+ "\n"
+ "\n"
+ "* Past technicians and analysts \n"
+ "	* *Xia Hong* | *Jie Shen* | *Wenyan Han* | *Pawandeep Kaur* | *Yanyan Lin* | *Xinyu Fan* | *Mallory Udell* | *Gwen Johnson* |  *Hakan Gunturkun* | *Tengfei Wang* |\n"
+ "* REHU students \n"
+ "	* Abigale Salinero (2015) | Cindy Tay (2016) | Raven David (2017) | Christian Hurt (2018) | Gwen Johnson (2021) | Olivia Harrison (2022, 2023) | \n"
+ "Ryan Luib (2023)\n"
+ "* P50 collaborators \n"
+ "	* Abraham Palmer | Oksana  Polesskaya | Sanches, Thiago | Apurva Chitre | Shae Ziegler | Leah Solberg-Woods \n"
+ "* UTHSC collaborators\n"
+ "	* Changhoon Jee | Wenlin Sun| Thirumalini Vaithianathan | Rob Williams\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Nicotine metabolism\n"
+ "\n"
+ "<img width=60% height=\"auto\" src=\"images/p50/AllCotinine_NicotineHSRats.png\">\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nicotine IVSA with an aversive flavor cue\n"
+ "\n"
+ "<img width=60% src=\"images/quinine/ise_nse_aversivecue.png\">\n"
+ "\n"
+ "<b>NSE</b>: neutral social environemnt, i.e., the presence of a companion rat. \n"
+ "<b>ISE</b>: indusive social environment, i.e., the presences of a companion rat who has access to the flavor cue. \n"
+ "<b>AV</b>: audiovisual cue \n"
+ "\n"
+ "<hr align=\"left\" width=15%>\n"
+ "<p align=left>\n"
+ "<cite> Wang, et al., Psychopharmacology, 2016 </cite>\n"
+ "</p>\n"
+ "\n"
+ "---\n"
+ "\n"
;
var script = document.querySelector('script[src="p50_2023.js"]');
var section = document.createElement('section');
script.parentNode.appendChild(section);
section.appendChild(document.createTextNode(markdownContent));
[].forEach.call(script.attributes, function (attr) {
    section.setAttribute(attr.name, script.getAttribute(attr.name));
});
section.setAttribute('data-markdown', '');
})();
