(function () {
'strict'
var markdownContent = ''
+ "### Project 2 \n"
+ "<hr color=orange >\n"
+ "# Socially acquired nicotine \n"
+ "# self-administration \n"
+ "<hr color=orange >\n"
+ "##	Hao Chen\n"
+ "### University of Tennessee Health Science center\n"
+ "\n"
+ "Rat GWAS retreat, June 15, 2018\n"
+ "\n"
+ "---\n"
+ "## Specific Aims \n"
+ "\n"
+ "\n"
+ "<h3 style=\"color:#069; text-align:left\" >Aim 1. Breed adolescent HS rats at UTHSC </h3>\n"
+ "<h3 style=\"color:#069; text-align:left\">Aim 2. Phenotype adolescent HS rats on socially acquired nicotine self-administration </h3>\n"
+ "<h4 style=\"text-align:left; text-indent:40px\">2A. Phenotype HS rats on social and emotional traits </h4>\n"
+ "<h4 style=\"text-align:left; text-indent:40px\">2B. Phenotype HS rats using the socially acquired nicotine self-administration paradigm </h4>\n"
+ "<h4 style=\"text-align:left; text-indent:40px\">2C. Analyze the relationships between behavioral traits obtained in Aims 2A and 2B </h4>\n"
+ "<h3 style=\"color:#069; text-align:left\">Aim 3. Extract RNA from five brain regions in naive HS rats for transcriptome sequencing </h3>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Flavor cue does <a href=\"#/stfp\">not</a> support nicotine self-administration\n"
+ "<img height:auto width=90% src=\"images/p50/retreat2018/flavorcue.png\">\n"
+ "\n"
+ "<hr align=\"left\" width=15%>\n"
+ "<p align=left>\n"
+ "<cite> Chen, et al., Neuropsychopharmacology, 2011</cite>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Modeling social learning in rats\n"
+ "\n"
+ "<div id=\"left50\">\n"
+ "<img height:auto width=80% src=\"images/galef.protocol.narrower.png\"> \n"
+ "<br>\n"
+ "\n"
+ "\n"
+ "<hr align=\"left\" width=15%>\n"
+ "<p align=left>\n"
+ "<cite>Galef, Dev Psychobiol., 1982 </cite>\n"
+ "</div>\n"
+ "\n"
+ "<div id=\"right50\">\n"
+ "<img height:auto width=80% src=\"images/Fig1.social.rats.withdemo.svg\">\n"
+ "	<br>\n"
+ "	<hr align=\"left\" width=15%>\n"
+ "	<p align=left>\n"
+ "	<cite> Wang, et al., Gene Brain Behav 2014 </cite>\n"
+ "	</p>\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Social learning induces nicotine \n"
+ "## self-administration\n"
+ "<img height:auto width=90% src=\"images/npp/fig2.demo.dose2.png\">\n"
+ "<hr align=\"left\" width=15%>\n"
+ "<p align=left>\n"
+ "<cite> Chen, et al., Neuropsychopharmacology, 2011 </cite>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nicotine intake with appetitive vs aversive cues\n"
+ "\n"
+ "\n"
+ "<div id=\"left50\">\n"
+ "	<img width=90% src=\"images/quinine/pres.sacc_quinine.png\" class=\"plain\">\n"
+ "	<br>\n"
+ "	<hr align=\"left\" width=15%>\n"
+ "	<p align=left>\n"
+ "	<cite> Wang, et al., Psychopharmacology, 2016 </cite>\n"
+ "	</p>\n"
+ "</div>\n"
+ "\n"
+ "<div id=\"right50\">\n"
+ "	<img width=90% height=90% src=\"images/Fig1.social.rats.withdemo.svg\" class=\"plain\">\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Socially acquired nicotine self-administration in 12 isogenic strains of rats\n"
+ "\n"
+ "![](./images/p50/retreat2018/inbred_intake_last3d.png)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Socially acquired nicotine self-administration\n"
+ "\n"
+ "### HS rats, pilot data\n"
+ "\n"
+ "<div id=\"left50\">\n"
+ "<img width=90% height=\"auto\" src=\"images/p50/fig4.g2b.figure.male.vs.female.nicSA.cummulative.png\">\n"
+ "\n"
+ "<hr align=\"left\" width=15%>\n"
+ "<p align=left>\n"
+ "<cite> Wang, et al., Gene Brain Behav, 2014</cite>\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "<div id=\"right50\">\n"
+ "<img width=83% height=\"auto\" src=\"images/p50/fig_demo.lick.by.sex.png\">\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## What is the social signal?\n"
+ "<div id=\"full\">\n"
+ "<img width=100% height=\"auto\" src=\"images/p50/social_3panel.png\">\n"
+ "<p>\n"
+ "<hr align=\"right\" width=15%>\n"
+ "	<p align=right>\n"
+ "	<cite> Wang, et al., Psychopharmacology, 2016 </cite>\n"
+ "	</p>\n"
+ "\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Phenotyping pipeline \n"
+ "* Breed adolescent HS rats\n"
+ "	* Generate ~ 400 adolescent rats per year \n"
+ "	* Use four rats (2 &#9794; + 2 &#9792;) in the behavioral studies and one rat for RNA-seq per litter \n"
+ "* Phenotype social and emotional traits\n"
+ "	* Open field / Novel object / Social interaction / Elevated plus maze / Marble Bury\n"
+ "* Socially acquired nicotine self-administration\n"
+ "	* Acquisition, 10 daily sessions\n"
+ "	* Progressive ratio, 1 session\n"
+ "	* Cotinine assay, 1 time \n"
+ "	* Extinction, 3-7 sessions\n"
+ "	* Reinstatement, 1 session\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Timetable for behavioral tests\n"
+ "<table style=\"border-collapse: collapse;\">\n"
+ "		<tr style=\"border-bottom:1px solid #000;\"> \n"
+ "			<th >Age</th>\n"
+ "			<th>Test</th>\n"
+ "		</tr>\n"
+ "			<tr><td>21</td><td>Wean </td></tr> \n"
+ "			<tr><td>30</td><td>Open field: 1m x 1m x 0.5m (1 h)</td></tr>\n"
+ "			<tr><td>31</td><td>Novelty: a cylindrical cage in the center (20 min)</td></tr>\n"
+ "			<tr><td>32</td><td>Social interaction: an unfamiliar rat in the cage (20 min)</td></tr>\n"
+ "			<tr><td>33</td><td>Elevated plus maze (6 min)</td></tr>\n"
+ "\n"
+ "			<tr ><td>34</td><td>Marble Bury</td></tr>\n"
+ "			<tr ><td>35-37</td><td>Surgery and recovery</td></tr>\n"
+ "			<tr><td>38-48</td><td>Nicotine SA </td></tr>\n"
+ "			<tr><td>49</td><td>Cotinine assay</td></tr>\n"
+ "			<tr style=\"border-bottom:1px solid #000;\"><td>50-58</td><td>Extinction, Reinstatement </td></tr>\n"
+ "</table>\n"
+ "\n"
+ "\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Project progress \n"
+ "\n"
+ "|Batch|Arrival Date | Status|Batch|Arrival Date | Status|\n"
+ "|---|---|---|---|--|---|\n"
+ "| 00 | 2014-07-14| Completed |09 | 2016-11-30| Completed |\n"
+ "| 01 | 2014-10-27| Completed |10 | 2017-02-08| Completed |\n"
+ "| 02 | 2015-02-25| Completed |11 | 2017-05-10| Completed |\n"
+ "| 03 | 2015-06-01| Completed |12 | 2017-08-09| Completed |\n"
+ "| 04 | 2015-08-05| Completed |13 | 2018-11-07| Completed |\n"
+ "| 05 | 2015-10-27| Completed |14 | 2018-02-04| In progress |\n"
+ "| 06 | 2016-02-02| Completed |15 | 2018-05-08| Released from quarantine |\n"
+ "| 07 | 2016-06-07| Completed |16 | 2018-08-10| To be shipped |\n"
+ "| 08 | 2016-08-16| Completed | |||\n"
+ "||||||\n"
+ "\n"
+ "---\n"
+ "<p align=\"left\">Aim 2A</p>\n"
+ "\n"
+ "##  Open field test\n"
+ "![](./images/p50/retreat2018/ms_openfield.png)\n"
+ "---\n"
+ "## Novel object interaction \n"
+ "![](./images/p50/retreat2018/ms_novelobject.png)\n"
+ "---\n"
+ "## Social interaction \n"
+ "\n"
+ "![](./images/p50/retreat2018/ms_social.png)\n"
+ "---\n"
+ "## Elevated plus maze\n"
+ "![](./images/p50/retreat2018/ms_plusmaze.png)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Marble bury\n"
+ "\n"
+ "![](./images/p50/retreat2018/ms_marblebury.png)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Sex differences \n"
+ "\n"
+ "![](./images/p50/retreat2018/p50_behav_sex_diff.png)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<p align=\"left\">Aim 2B</p>\n"
+ "## Nicotine self-administration\n"
+ "<img width=75% height=\"auto\" src=\"images/p50/retreat2018/nicotine_fr.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<p align=\"left\">Aim 2C</p>\n"
+ "\n"
+ "## Behavior correlations\n"
+ "\n"
+ "<img src=\"./images/p50/retreat2018/behav_cor_r_p.png\" width=70% class=\"plain\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Interesting insights\n"
+ "\n"
+ "![](./images/p50/retreat2018/correlation_scatters.png)\n"
+ "\n"
+ "---\n"
+ "## Can behavioral traits predict nicotine SA? \n"
+ "\n"
+ "Loading of PCA\n"
+ "\n"
+ "<img src=\"images/p50/retreat2018/pca_loading.png\" width=55%> \n"
+ "\n"
+ "---\n"
+ "## PCA regression summary \n"
+ "\n"
+ "|Phenotype | Sex| Variance Explained| \n"
+ "|---|---|---|---|\n"
+ "|Infusion, first 3 d| F| 0.18| \n"
+ "|Infusion, first 3 d| M| 0.17| \n"
+ "|Infusion, last 3 d | F | 0.12| \n"
+ "|Infusion, last 3 d | M | 0.20| \n"
+ "|Infusion, progressive ratio | F | 0.14| \n"
+ "|Infusion, progressive ratio | M | 0.18| \n"
+ "|Active spout lick, reinstatement | F | 0.08| \n"
+ "|Active spout lick, reinstatement | F | 0.19| \n"
+ "|||||\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Preliminary GWAS\n"
+ "\n"
+ "<table width=90%><tr><td with=33%>\n"
+ "<h3> Infusion first 3 sessions </h3>\n"
+ "<img width=85% src=\"images/p50/retreat2018/infusion_first3d.png\">\n"
+ "</td> <td width=33%>\n"
+ "<h3> Infusion all sessions </h3>\n"
+ "<img width=90% src=\"images/p50/retreat2018/infusion_alldays.png\">\n"
+ "</td><td width=33%>\n"
+ "<h3> Prog. from session 1 to 10 </h3>\n"
+ "<img width=90% src=\"images/p50/retreat2018/injectionSlop.png\">\n"
+ "\n"
+ "</td>\n"
+ "</tr>\n"
+ "</table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nicotine metabolism\n"
+ "<img width=60% height=\"auto\" src=\"images/p50/AllCotinine_NicotineHSRats.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<p align=\"left\">Aim 3</p>\n"
+ "\n"
+ "## Brain dissection for RNA purification\n"
+ "\n"
+ "<img width=70% height=\"auto\" src=\"images/p50retreat2017/RNAQuality.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Accomplishments \n"
+ "\n"
+ "* Tengfei Wang, Wenyan Han, Bin Wang, Qing Jiang, Leah C Solberg-Woods, Abraham A Palmer, Hao Chen. Propensity for social interaction predicts nicotine-reinforced behaviors in outbred rats. Genes Brain Behav. 2014 Feb;13(2):202. \n"
+ "\n"
+ "* Tengfei Wang, Wenyan Han, Hao Chen. Socially acquired nicotine self-administration with an aversive flavor cue in adolescent female rats. Psychopharmacology. 2016 May;233(10):1837\n"
+ "\n"
+ "* Matthew Longley, Ethan L Willis, Cindy X Tay, Hao Chen. An open source device for operant licking in rats. PeerJ 2017 Feb 14;5:e2981. \n"
+ "\n"
+ "* Wenyan Han, Tengfei Wang, Hao Chen. Extinction of conditioned aversion contributes to socially acquired nicotine self-administration in isogenic strains of adolescent rats. Sci Rep 2017 Aug 14;7(1):8052. \n"
+ "\n"
+ "* Tengfei Wang, Wenyan Han, Apurva Chitre, Oksana Polesskaya, Leah C. Solberg-Woods, Abraham A. Palmer, and Hao Chen. Social behavior and anxiety contributes to nicotine self-administration in adolescent outbred rats. Sci Rep. 2018 Resubmission\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Acknowledgements\n"
+ "* Current lab members \n"
+ "	* **Tengfei Wang**, Research Associate \n"
+ "	* **Xinyu Fan**, Research Assistant\n"
+ "	* **Angel Garcia Martinez**, Research Assistant \n"
+ "* Past lab members \n"
+ "	* *Xia Hong* | *Jie Shen* | *Wenyan Han* | *Pawandeep Kaur* | *Yanyan Lin* \n"
+ "* Summer students \n"
+ "	* Abigale Salinero (REHU 2015) | Cindy Tay (REHU 2016) | Raven David (REHU 2017) | Christian Hurt (REHU 2018) \n"
+ "* P50 collaborators \n"
+ "	* Abraham Palmer | Oksana Polaskaya | Apurva Chitre | Leah-Solberg Woods | Barry Aprison \n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Yorodent: using ConvNet to quantify rat social interactions\n"
+ "\n"
+ "<img src=\"https://cdn-images-1.medium.com/max/1300/1*d4Eg17IVJ0L41e7CTWLLSg.png\" width=80%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Yorodent Method\n"
+ "\n"
+ "* Recognizes five body parts per rat\n"
+ "	* Heads are labeled based on the color of the ear tag\n"
+ "	* Five colors trained, more can be added\n"
+ "* Training data\n"
+ "	* 8,000 manually labeled images\n"
+ "* Network Training\n"
+ "	* 16,000 epocs using dual NVIDIA GTX 1080 Ti GPUs\n"
+ "	* about 3 days\n"
+ "* Validation using new images\n"
+ "\n"
+ "![](./images/p50/retreat2018/yorodent_validation.png)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Putting everything together \n"
+ "\n"
+ "<iframe width=80% height=\"550\" src=\"https://www.youtube.com/embed/Lwfg2t9nXcI?start=45\" frameborder=\"0\" allow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Recording home cage behavior under infrared light\n"
+ "\n"
+ "<iframe width=\"520\" height=\"345\" src=\"https://www.youtube.com/embed/bqu2IaS6RSA?rel=0\" frameborder=\"0\" allow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n"
+ "\n"
+ "<iframe width=\"520\" height=\"345\" src=\"https://www.youtube.com/embed/QPuth-mTEOs?rel=0\" frameborder=\"0\" allow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Significant PCs\n"
+ "<table width=80%>\n"
+ "<tr ><td width=80%> <img width=80% src=\"images/p50/retreat2018/pca_loading.png\"> </td>\n"
+ "<td align=\"left\" width=20%> \n"
+ "\n"
+ "<table><tr><td><b>PC</b></td><td> <b>Counts</b></td></tr>\n"
+ "<tr><td>PC2</td><td>2</td></tr>\n"
+ "<tr><td>PC5</td><td>3</td></tr>\n"
+ "<tr><td>PC6</td><td>4</td></tr>\n"
+ "<tr><td>PC8</td><td>2</td></tr>\n"
+ "<tr><td>PC12</td><td>2</td></tr>\n"
+ "<tr><td>PC19</td><td>4</td></tr>\n"
+ "<tr><td>PC25</td><td>3</td></tr>\n"
+ "<tr><td>PC26</td><td>2</td></tr>\n"
+ "<tr><td>PC29</td><td>2</td></tr>\n"
+ "</table>\n"
+ "\n"
+ "\n"
+ "</td></tr>\n"
+ "</table>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
;
var script = document.querySelector('script[src="p50_2018.js"]');
var section = document.createElement('section');
script.parentNode.appendChild(section);
section.appendChild(document.createTextNode(markdownContent));
[].forEach.call(script.attributes, function (attr) {
    section.setAttribute(attr.name, script.getAttribute(attr.name));
});
section.setAttribute('data-markdown', '');
})();
