(function () {
'strict'
var markdownContent = ''
+ "## Project 2 \n"
+ "\n"
+ "<hr color=orange >\n"
+ "\n"
+ "# Socially acquired nicotine \n"
+ "# self-administration \n"
+ "\n"
+ "<hr color=orange >\n"
+ "\n"
+ "##	Hao Chen\n"
+ "\n"
+ "### University of Tennessee Health Science center\n"
+ "\n"
+ "P50 virtual retreat, Nov 4nd, 2021\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Specific Aims \n"
+ "\n"
+ "<h3 style=\"color:#069; text-align:left\">\n"
+ "Aim 1. Phenotype adolescent HS rats on socially acquired nicotine IVSA. </h3>\n"
+ "<h3 style=\"color:#069; text-align:left\">\n"
+ "Aim 2. Analyze the relationships between behavioral traits using regression, phenome-wide association (PheWAS), and genetic correlation.\n"
+ "</h3>\n"
+ "<h3 style=\"color:#069; text-align:left\">\n"
+ "Aim 3. Obtain naïve brain tissues for transcriptome sequencing.\n"
+ "</h3>\n"
+ "<p align=\"left\">\n"
+ "<small>We already have 88 samples each includes five brain regsions (IL, PL, OF, NAcc, LHb). We will collect samples (pVTA, mHb, vHIP, IC, and LH) from 500 additional brains provided by the Solberg Wood's lab.\n"
+ "</small>\n"
+ "</p>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Nicotine is primarily aversive in non-smokers \n"
+ "<table>\n"
+ " <tr>\n"
+ " <td width=50%>\n"
+ " <img width=100% src=\"images/titlepages/eissenberg.png\">\n"
+ " </td>\n"
+ " <td width=90%>\n"
+ " <img width=100% src=\"images/titlepages/dkalman.png\">\n"
+ " </td>\n"
+ " </tr>\n"
+ " <tr>\n"
+ " <td>\n"
+ " Coughing, nausea, dizziness, sickness, burning throat, headache.\n"
+ " </td>\n"
+ " <td>\n"
+ " Nicotine induces drug high only in <em>significantly nicotine-deprived smokers</em>. \n"
+ " </td>\n"
+ " </tr>\n"
+ "</table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "<span id=\"solo\">\n"
+ "\n"
+ "## Flavor cues do <font color=\"darkred\">not</font> support nicotine self-administration\n"
+ "\n"
+ "\n"
+ "<a href=\"#/demo\">\n"
+ "<img height:auto width=90% src=\"images/p50/flavorcue_conditioned_aversion.png\">\n"
+ "</a>\n"
+ "\n"
+ "<hr align=\"left\" width=15%>\n"
+ "<p align=left> \n"
+ "<cite> Chen, et al., Neuropsychopharmacology, 2011 </cite>\n"
+ "\n"
+ "\n"
+ "Note:\n"
+ "We previously reported that \n"
+ "adolescent rats developed conditioned aversion to an appetitive flavor cue (saccharine + grape odor) associated with self-administered i.v. nicotine. In this operant <i>licking</i> model, oral flavor cue and <strong>i.v.</strong> nicotine were delivered simultaneously upon the completion of a fixed-ratio 5 reinforcement schedule. \n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Intravenous nicotine paired with a flavor cue is aversive \n"
+ "\n"
+ "<img height:auto width=90% src=\"images/p50/nicotine_cta.png\">\n"
+ "\n"
+ "<hr align=\"left\" width=15%>\n"
+ "<p align=left> \n"
+ "<cite> Chen, et al., Neuropsychopharmacology, 2011 </cite>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Social influence is a key factor in smoking initiation \n"
+ "\n"
+ "<div id=\"left50\" >\n"
+ "<img width=100% src=\"images/titlepages/hoffman.png\"> \n"
+ "</div>\n"
+ "<div id=\"right50\">\n"
+ "<img width=100% src=\"images/titlepages/jfowler.png\"> \n"
+ "</div>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "<span id=\"demo\">\n"
+ "\n"
+ "## Social learning enables nicotine self-administration\n"
+ "\n"
+ "<a href=\"#/solo\">\n"
+ "<img height:auto width=90% src=\"images/socially_acquired_nicotine_ivsa.png\">\n"
+ "</a>\n"
+ "\n"
+ "<hr align=\"left\" width=15%>\n"
+ "<p align=left> \n"
+ "<cite> Chen, et al., Neuropsychopharmacology, 2011 </cite>\n"
+ "\n"
+ "Note:\n"
+ "However, with the presence of a \"demonstrator\" rat consuming the same flavor cue, nicotine i.v. self-administration was established. \n"
+ "No water or food deprivation or operant pretraining is needed. Thus the model is appropriate for studying smoking initiation in adolescents. \n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Stable nicotine intake at two doses across 12 isogeneic strains \n"
+ "\n"
+ "### Nicotine intake is heritable (h<sup>2</sup>=0.54-0.65).\n"
+ "\n"
+ "<img src=\"https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5556091/bin/41598_2017_8291_Fig3_HTML.jpg\">\n"
+ "\n"
+ "<hr align=\"left\" width=15%>\n"
+ "<p align=left>\n"
+ "<cite> Han, et al., Sci Report, 2017 </cite>\n"
+ "</p>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Social learning facilitates the extinction of conditioned nicotine aversion\n"
+ "\n"
+ "<img src=\"./images/p50/correlation_ext_cta_nicotine.png\" >\n"
+ "<hr align=\"left\" width=15%>\n"
+ "<p align=left>\n"
+ "<cite> Han, et al., Sci Report, 2017 </cite>\n"
+ "</p>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nicotine IVSA with an aversive flavor cue\n"
+ "\n"
+ "<img width=60% src=\"images/quinine/2.quinine.redued.yscale.6grps.png\">\n"
+ "\n"
+ "<hr align=\"left\" width=15%>\n"
+ "<p align=left>\n"
+ "<cite> Wang, et al., Psychopharmacology, 2016 </cite>\n"
+ "</p>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nicotine IVSA with an aversive flavor cue\n"
+ "\n"
+ "<img width=40% src=\"images/quinine/pres.sacc_quinine.png\">\n"
+ "\n"
+ "<hr align=\"left\" width=15%>\n"
+ "<p align=left>\n"
+ "<cite> Wang, et al., Psychopharmacology, 2016 </cite>\n"
+ "</p>\n"
+ "\n"
+ "Note:\n"
+ "We further reported that even when an aversive (i.e. quinine) flavor was used in place of the appetitive flavor, adolescent rats obtained nicotine IVSA, with the presence of a demonstrator consuming a flavor cue containing the same odor as the nicotine cue (i.e. inducive social environemnt (<b>ISE</b>). The number of nicotine infusions were almost identical between the two cues. <b>Therefore, licking on the active spout is most likely motivated by nicotine in this model</b> The reduced licks on the active spout was due to the reduction of licking during the timeout period following nicotine and cue delivery. \n"
+ "\n"
+ "---\n"
+ "\n"
+ "### Summary \n"
+ "## Socially acquired nicotine IVSA in adolescent rats\n"
+ "\n"
+ "* Nicotine has both aversive and reinforcing properties\n"
+ "* Flavor cues are associated with the aversive property of nicotine \n"
+ "* Social learning facilitates the extinction of conditioned nicotine flavor aversion \n"
+ "* Operant responding is driven by the rewarding property of nicotine \n"
+ "	* dose response to nicotine across multiple strains\n"
+ "	* nicotine can be self-administered with an aversive flavor cue \n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "## Timetable for behavioral tests\n"
+ "\n"
+ "<font size=4>\n"
+ "\n"
+ "| Age | Test |\n"
+ "|---|---|\n"
+ "|PND21|Wean, Body weight|\n"
+ "|PND31|Open field (20min)|\n"
+ "|PND32|Novel object (20min)|\n"
+ "|PND33|Social interaction in the same arena as openfield (20 min)       |\n"
+ "|PND34|Elevated plus maze (6min)|\n"
+ "|PND35|Free moving social (15 min habituation + 15 min video recording)|\n"
+ "|PND38|Surgery|\n"
+ "|PND39 -- 41| Recovery|\n"
+ "|PND42 -- 51|Socially acquired nicotine IVSA|\n"
+ "|PND52| Progressive ratio test |\n"
+ "|PND53 -- 56 |Extinction|\n"
+ "|PND57|Contextual cue induced reinstatement|\n"
+ "|PND59|Tissue Collection for the IVSA rats|\n"
+ "|PND84|Tissue Collection for the naive RNAseq rats|\n"
+ "\n"
+ "</font>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Current phenotyping progress \n"
+ "\n"
+ "<img src=\"./images/p50/proj2_nicotine_summary.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Current RNA extraction progress \n"
+ "### 33 rats about 100 samples\n"
+ "<img src=\"./images/p50/p50_RNA_extractio_RIN.png\" width=60%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## GWAS summary\n"
+ "\n"
+ "|Behavior |  Sample size | N traits | N QTL traits | N significant QTL| \n"
+ "|---|---|---:|---:|---:|\n"
+ "| open field | 626 M, 620 F |  6 | 5 | 9 | \n"
+ "| novel object interaction|623 M, 622 F|  6 | 4| 7|\n"
+ "| social interaction | 664 M, 664 F | 11| 10|  14| \n"
+ "| elevated plus maze |  659 M, 658 F | 10| 7| 8| \n"
+ "| socially acquired nicotine IVSA| 711 M, 711 F| 63| 24 | 30| \n"
+ "\n"
+ "One trait mapped to multiple loci; multiple traits mapped to the same loci\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Candidate genes  \n"
+ "###  open field test (OFT), novel object test (NOIT), and social interaction (SIT) \n"
+ "\n"
+ "<div id=\"left\">\n"
+ "<img src=\"./images/p50/openfieldtablep1.png\">\n"
+ "</div>\n"
+ "<div id=\"right\">\n"
+ "<img src=\"./images/p50/openfieldtablep2.png\">\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Summary of nicotine GWAS\n"
+ "\n"
+ "## Number of licks on the active spout\n"
+ "\n"
+ "|ID |Session|Location| Genes (n) | Human Smoking GWAS Genes|\n"
+ "|---|:---:|---|---|---|\n"
+ "|12.20 | day 1 | chr1:278524299| 99 | Gpam&clubs;&diams;, [Vti1a](http://rats.pub/cytoscape/?rnd=tmpUpzbbT&genequery=VTI1A)<font color=\"darkslateblue\">&spades;</font>, Nhlrc2&clubs;&diams;, Adrb1&clubs;, Tcf7l2, [Hspa12a](http://rats.pub/cytoscape/?rnd=tmpFrhLrJ&genequery=HEAT-SHOCK-PROTEIN-FAMILY-A-HSP70-MEMBER-12A_HSPA12A)<font color=\"darkslateblue\">&spades;</font>, [Shtn1](http://rats.pub/cytoscape/?rnd=tmpJiHXFf&genequery=KIAA1598_SHOOTIN-1_SHOOTIN1_SHTN1)<font color=\"darkslateblue\">&spades;</font>&diams;, [Nrap](http://rats.pub/cytoscape/?rnd=tmpaUzTZp&genequery=N-RAP_NEBULIN-RELATED-ANCHORING-PROTEIN_NRAP)<font color=\"darkslateblue\">&spades;</font>, Casp7&diams; Gfra1|\n"
+ "|12.29 | day 2 | chr8:22496077| 29| [Carm1](http://rats.pub/cytoscape/?rnd=tmpaHVoNJ&genequery=carm1) |\n"
+ "|12.24 | day 4 | chr4:145377793| 20| [Emc3](http://rats.pub/cytoscape/?rnd=tmpQXgUzk&genequery=emc3) |\n"
+ "|12.12 | day 5 | chr16:83955432| 23| Tex29| \n"
+ "|12.08 | day 7 | chr16:83489214| 23| Tex29| \n"
+ "|12.02 | day 9 | chr10:32845925| 90|  | \n"
+ "|12.22 | day 10 | chr2:247766389|20| [Pkn2, Gtf2b](http://rats.pub/cytoscape/?rnd=tmpPoBkQf&genequery=Pkn2_Gtf2b) |\n"
+ "|12.16 | Reinstatment | chr1:161226950| 28|Usp35, Gab2,  Nars2, Tenm4, [Alg8](http://rats.pub/cytoscape/?rnd=tmpJKLgcJ&genequery=Usp35_Gab2_Nars2_Tenm4_Alg8)&diams;&hearts; |\n"
+ "\n"
+ "<font color=\"darkslateblue\">&spades;</font>: smoking initiation genes\n"
+ "&clubs;: Alcohol consumption genes\n"
+ "&diams;: cis-eQTL\n"
+ "&hearts; missense variants\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Summary of nicotine GWAS\n"
+ "\n"
+ "## Number of infusions\n"
+ "\n"
+ "|ID|Session|Location| Genes (n)| Human Smoking GWAS Genes|\n"
+ "|---|:---:|---|---|---|\n"
+ "|12.09 | day 5  | chr16:83500180| 23| Tex29  |\n"
+ "|12.13 | day 5  | chr17:17103044| 1| [ID4](http://rats.pub/cytoscape/?rnd=tmpdaIxug&genequery=ID4) |\n"
+ "|12.11 | day 7  | chr16:83500180| 23| Tex29|\n"
+ "|12.23 | day 7  | chr3:104723116| 8|[Hmgn4, Fmn1](http://rats.pub/cytoscape/?rnd=tmpSBamBX&genequery=Hmgn4_Fmn1) |\n"
+ "|12.15 | day 8  | chr19:26396258| 1| |\n"
+ "|12.03 | median of last 3 days  |  chr11:17834164|27| | \n"
+ "|12.10 |total infusion  | chr16:83500180| 23| [Tex29](http://rats.pub/cytoscape/?rnd=tmpesQlMB&genequery=tex29)|\n"
+ "|12.30 |slope of regression  | chr8:4459578| 74| [Gria4](http://rats.pub/cytoscape/?rnd=tmpAjmeXn&genequery=Gria4_Pdgfd_Mmp12)&diams;, Pdgfd&diams;, Mmp12 |\n"
+ "\n"
+ "&diams;: cis-eQTL\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Potential targets for validation \n"
+ "\n"
+ "* Shtn1 (active lick on day 1)\n"
+ "* Gria4 (progression of intake)\n"
+ "* Tex29 (total intake)\n"
+ "* Alg8 (reinstatement) \n"
+ "\n"
+ "---\n"
+ "\n"
+ "##  Validation of GWAS targets\n"
+ "\n"
+ "* Using CRISPR/Cas9 knockin rat for validation\n"
+ "* PCR/Western blotting on rats with high vs low nicotine intake \n"
+ "\n"
+ "---\n"
+ "\n"
+ "## C.elegans model of nicotine conditioned cue preference\n"
+ "\n"
+ "### Dr. Changhoon Jee, Assistant Prof, UTHSC\n"
+ "\n"
+ "<table><tr><td>\n"
+ "<img src=\"https://www.uthsc.edu/pharmacology/faculty/images/jee-changhoon.jpg\">\n"
+ "</td><td>\n"
+ "\n"
+ "<img src=\"./images/p50/celegans1.png\">\n"
+ "</td></tr></table>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Gria4 null mutation abolishes nicotine CCP \n"
+ "\n"
+ "### Dr. Changhoon Jee, Assistant Prof, UTHSC\n"
+ "\n"
+ "<img src=\"./images/p50/celegans2.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Publications so far\n"
+ "\n"
+ "* Published\n"
+ "	* Wang T, Han W, Wang B, Jiang Q, Solberg-Woods LC, Palmer AA, Chen H. Propensity for social interaction predicts nicotine-reinforced behaviors in outbred rats. Genes Brain Behav. 2014 Feb;13(2):202–212. PMCID: PMC3934210\n"
+ "	* Wang T, Han W, Chitre AS, Polesskaya O, Solberg Woods LC, Palmer AA, Chen H. Social and anxiety-like behaviors contribute to nicotine self-administration in adolescent outbred rats. Sci Rep. 2018 Dec 24;8(1):18069. PMCID: PMC6305389\n"
+ "	* Han W, Wang T, Chen H. Social learning promotes nicotine self-administration by facilitating the extinction of conditioned aversion in isogenic strains of rats. Sci Rep. Nature Publishing Group; 2017 Aug 14;7(1):8052. PMCID: PMC5556091\n"
+ "\n"
+ "* BioRxiv (also under review)\n"
+ "	* Gunturkun MH, Flashner E, Wang T, Mulligan MK, Williams RW, Prins P, Chen H. GeneCup: mine PubMed for gene relationships using custom ontology and deep learning. bioRxiv. 2021. p. 2020.09.17.297358. Available from: https://www.biorxiv.org/content/10.1101/2020.09.17.297358v5\n"
+ "	* Gunturkun MH, Wang T, Chitre AS, Martinez AG, Holl K, St. Pierre C, Bimschleger H, Gao J, Cheng R, Polesskaya O, Solberg-Woods LC, Palmer AA, Chen H. Genome-wide association study of open field behavior in outbred heterogeneous stock rats identifies multiple loci implicated in psychiatric disorders. bioRxiv. 2021. p. 2021.10.18.464872. Available from: https://www.biorxiv.org/content/10.1101/2021.10.18.464872v1\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Acknowledgements\n"
+ "\n"
+ "* Current lab members working on this project \n"
+ "\n"
+ "<table><tr>\n"
+ "<td width=20%>\n"
+ "<img src=\"http://www.chenlab.one/img/team/twang18.jpg\">\n"
+ "\n"
+ "Tengfei Wang\n"
+ "\n"
+ "</td>\n"
+ "<td width=20%>\n"
+ "<img src=\"http://www.chenlab.one/img/team/angel.jpg\">\n"
+ "\n"
+ "Angel Garcia Martinez\n"
+ "\n"
+ "</td>\n"
+ "<td width=20%>\n"
+ "<img src=\"http://www.chenlab.one/img/team/shuangying.jpg\">\n"
+ "\n"
+ "Shuangying Leng\n"
+ "\n"
+ "</td>\n"
+ "<td width=20%>\n"
+ "<img src=\"http://www.chenlab.one/img/team/rachel.jpg\">\n"
+ "\n"
+ "Rachel Ward\n"
+ "\n"
+ "</td>\n"
+ "<td width=20%>\n"
+ "<img src=\"http://www.chenlab.one/img/team/hakan.jpg\">\n"
+ "\n"
+ "Hakan Gunturkun\n"
+ "\n"
+ "</td>\n"
+ "</tr>\n"
+ "</table>\n"
+ "\n"
+ "\n"
+ "* Past technicians \n"
+ "	* *Xia Hong* | *Jie Shen* | *Wenyan Han* | *Pawandeep Kaur* | *Yanyan Lin* | *Xinyu Fan*   | *Mallory Udell*|\n"
+ "* Summer students \n"
+ "	* Abigale Salinero (REHU 2015) | Cindy Tay (REHU 2016) | Raven David (REHU 2017) | Christian Hurt (REHU 2018) \n"
+ "* P50 collaborators \n"
+ "	* Abraham Palmer | Oksana Polaskaya | Apurva Chitre | Leah-Solberg Woods \n"
+ "* UTHSC collaborators\n"
+ "	* Changhoon Jee | Rob Williams\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nicotine metabolism\n"
+ "\n"
+ "<img width=60% height=\"auto\" src=\"images/p50/AllCotinine_NicotineHSRats.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
;
var script = document.querySelector('script[src="p50_2021.js"]');
var section = document.createElement('section');
script.parentNode.appendChild(section);
section.appendChild(document.createTextNode(markdownContent));
[].forEach.call(script.attributes, function (attr) {
    section.setAttribute(attr.name, script.getAttribute(attr.name));
});
section.setAttribute('data-markdown', '');
})();
