(function () {
'strict'
var markdownContent = ''
+ "# Annotation difference between RefSeq and Ensembl\n"
+ "\n"
+ "### Hao Chen\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Steps to find different Gene annotations between RefSeq and Ensembl\n"
+ "\n"
+ "1. Download annotation from Ensembl BioMart, including the following fields\n"
+ "	1. Stable GeneID \n"
+ "	2. Chr\n"
+ "	3. Strand\n"
+ "	4. Start\n"
+ "	5. End\n"
+ "	6. Gene Name\n"
+ "	7. NCBI GeneID\n"
+ "2. Extract lines annotated as \"gene\" from RefSeq GTF file using shell script, include the following fields\n"
+ "	1. Accession\n"
+ "	2. Chr\n"
+ "	3. Strand\n"
+ "	4. Start\n"
+ "	5. End\n"
+ "	6. Gene Name\n"
+ "	7. GeneID\n"
+ "3. Merge the two data sets based on GeneID\n"
+ "	1. extract genes with different annotations\n"
+ "        Same name, but different chr / strand / start / end \n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Questions\n"
+ "* What is the process of assigning GeneID to Ensembl genes\n"
+ "    * one GeneID matches to multiple ENSRNOG stable IDs (226)\n"
+ "    * one ENSRNOG stable IDs matches to multipe GeneIDs (493)\n"
+ "* What kind of correction will be carried over to the next annotation \n"
+ " \n"
+ "---\n"
+ "\n"
+ "## Steps taken to count number of Exons annotated by RefSeq vs Ensembl\n"
+ "\n"
+ "1. Download from BioMart ExonStableID, together with other fields (similar to above)\n"
+ "2. Extract from RefSeq GTF all the lines annotated as \"exon\"\n"
+ "3. Count the number of lines associated with GeneID in each annotation file\n"
+ "4. merge the counts based on GeneID\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Something is missing\n"
+ "\n"
+ "<img src=\"./images/ratGenome/RefSeq_v_Ensembl_exon_cnt.png\" width=40%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Same gene structure\n"
+ "\n"
+ "Exon Count for Acp1, RefSeq=23, Ensembl=16\n"
+ "\n"
+ "<img src=\"./images/ratGenome/acp1_annot.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Question\n"
+ "\n"
+ "1. What is the proper way to find \"exons\"\n"
+ "2. What is needed to obtain consensus CDS (CCDS) for the rat?\n"
+ "\n"
+ "https://www.ncbi.nlm.nih.gov/projects/CCDS/CcdsBrowse.cgi\n"
+ "\n"
+ "---\n"
+ "\n"
;
var script = document.querySelector('script[src="Questions_on_Genen_Annotation.js"]');
var section = document.createElement('section');
script.parentNode.appendChild(section);
section.appendChild(document.createTextNode(markdownContent));
[].forEach.call(script.attributes, function (attr) {
    section.setAttribute(attr.name, script.getAttribute(attr.name));
});
section.setAttribute('data-markdown', '');
})();
