(function () {
'strict'
var markdownContent = ''
+ "# Oxycodone, Behavioral Cues from Rats, Genomes, and Machine Intelligence\n"
+ "\n"
+ "### Hao Chen, Ph.D.\n"
+ "\n"
+ "### Department of Pharmacology, Addiction Science and Toxicology, UTHSC\n"
+ "\n"
+ "#### May 28th, 2026\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Acknowledgements\n"
+ "\n"
+ "<img src=\"./images/quest/team_sunray.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Outline\n"
+ "\n"
+ "<img src=\"./images/quest/rat_wordcloud.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## The Opioid Overdose: National Scope\n"
+ "\n"
+ "<img src=\"images/quest/us_overdose_by_drug_type.png\" width=70%>\n"
+ "\n"
+ "##### Projected 1.2 million additional deaths by 2029 (US & Canada)\n"
+ "\n"
+ "##### Data: [CDC](https://www.tn.gov/health/health-program-areas/pdo/pdo/facts-figures.html)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Opioid Overdose Deaths: TN vs US\n"
+ "\n"
+ "<div style=\"display: flex; align-items: center;\">\n"
+ "<div style=\"flex: 1;\">\n"
+ "\n"
+ "![TN Overdose Map](images/quest/TN_overdose_map.png)\n"
+ "\n"
+ "</div>\n"
+ "<div style=\"flex: 1;\">\n"
+ "\n"
+ "![TN Overdose Map](images/quest/TN_overdose_national.png)\n"
+ "\n"
+ "</div>\n"
+ "</div>\n"
+ "\n"
+ "##### Data: [TN Dept of Health](https://www.tn.gov/health/health-program-areas/pdo/pdo/facts-figures.html)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## TN Drug Overdose: Race and Gender\n"
+ "\n"
+ "<div style=\"display: flex; align-items: center; gap: 20px;\">\n"
+ "<div style=\"flex: 1;\">\n"
+ "\n"
+ "![TN Overdose Race](images/quest/TN_overdose_race.png)\n"
+ "\n"
+ "</div>\n"
+ "<div style=\"flex: 1;\">\n"
+ "\n"
+ "![TN Overdose Gender](images/quest/TN_overdose_gender.png)\n"
+ "\n"
+ "</div>\n"
+ "</div>\n"
+ "\n"
+ "##### Data: [TN Dept of Health](https://www.tn.gov/health/health-program-areas/pdo/pdo/facts-figures.html)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Opioid Use Disorder in Tennessee\n"
+ "\n"
+ "<div style=\"display: flex; align-items: center; gap: 20px;\">\n"
+ "<div style=\"flex: 1;\">\n"
+ "\n"
+ "![TN OUD Map](images/quest/TN_OUD_number_one.png)\n"
+ "\n"
+ "</div>\n"
+ "<div style=\"flex: 1;\">\n"
+ "\n"
+ "![TN OUD Trends](images/quest/TN_OUD_rising_2024.png)\n"
+ "\n"
+ "</div>\n"
+ "</div>\n"
+ "\n"
+ "##### Data: [Axios](https://www.axios.com/2025/09/30/opioid-use-disorder-cases-jump)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## US Opioid Dispensing Rate\n"
+ "\n"
+ "<table> <tr><td width=68%>\n"
+ "\n"
+ "![US Opioid Dispensing](images/quest/us_opioids_dispense.png)\n"
+ "\n"
+ "</td><td width=32%>\n"
+ "\n"
+ "![Number of Opioids Dispensed](images/quest/us_opioids_dispended.png)\n"
+ "\n"
+ "</td></tr></table>\n"
+ "\n"
+ "##### TN: 56.1 prescriptions per 100 persons in 2024 (4.26 Million Prescriptions)\n"
+ "\n"
+ "##### 13% develop OUD within one year of first use; ~50% transition within 12 years (PMID: 30439610)\n"
+ "\n"
+ "##### Data: [CDC](https://www.tn.gov/health/health-program-areas/pdo/pdo/facts-figures.html) [TN Dept Health](https://www.tn.gov/health/health-program-areas/pdo/pdo/facts-figures.html)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## OUD Diagnosis\n"
+ "\n"
+ "| Check | Diagnostic Criteria                                                                                                                                                                                                                        |\n"
+ "| ----- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |\n"
+ "|       | Opioids are often taken in larger amounts or over a longer period of time than intended.                                                                                                                                                   |\n"
+ "|       | There is a persistent desire or unsuccessful efforts to cut down or control opioid use.                                                                                                                                                    |\n"
+ "|       | A great deal of time is spent in activities necessary to obtain the opioid, use the opioid, or recover from its effects.                                                                                                                   |\n"
+ "|       | Craving, or a strong desire to use opioids. Recurrent opioid use resulting in failure to fulfill major role obligations at work, school or home.                                                                                           |\n"
+ "|       | Continued opioid use despite having persistent or recurrent social or interpersonal problems caused or exacerbated by the effects of opioids.                                                                                              |\n"
+ "|       | Important social, occupational or recreational activities are given up or reduced because of opioid use.                                                                                                                                   |\n"
+ "|       | Recurrent opioid use in situations in which it is physically hazardous Continued use despite knowledge of having a persistent or recurrent physical or psychological problem that is likely to have been caused or exacerbated by opioids. |\n"
+ "|       | Tolerance, as defined by either of the following: (a) a need for markedly increased amounts of opioids to achieve intoxication or desired effect (b) markedly diminished effect with continued use of the same amount of an opioid         |\n"
+ "|       | Withdrawal, as manifested by either of the following: (a) the characteristic opioid withdrawal syndrome (b) the same (or a closely related) substance are taken to relieve or avoid withdrawal symptoms                                    |\n"
+ "\n"
+ "##### Severity: Mild: 2-3 symptoms. Moderate: 4-5 symptoms. Severe: 6 or more symptoms\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Individual Differences in OUD Risk\n"
+ "\n"
+ "- Why do some individuals escalate to compulsive use while others remain resilient?\n"
+ "- Genetic factors account for 38-61% of OUD risk (twin studies)\n"
+ "- Human <a href=\"https://pmc.ncbi.nlm.nih.gov/articles/PMC9718667/\" target=_new> GWAS</a> is making great progress but remain underpowered\n"
+ "  - sample size is limited.\n"
+ "  - difficult to capture longitudinal data\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Unmet Need\n"
+ "\n"
+ "<hr>\n"
+ "\n"
+ "#### Genetic underpinning for OUD\n"
+ "\n"
+ "#### Objective Biomarkers for Early Detection of Misuse Risk\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## <font color=\"firebrick\"> Oral Oxycodone Self-administration in Rats </font>\n"
+ "\n"
+ "- Oxycodone is primarily prescribed as oral tablets\n"
+ "- Oral route: first-pass metabolism, gradual brain uptake (vs. rapid IV onset)\n"
+ "- No surgery, no food/water restriction required\n"
+ "- Rats: well-established operant procedure for voluntary drug intake\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## The Operant Chamber Setup\n"
+ "\n"
+ "<div style=\"display: flex; align-items: center;\">\n"
+ "<div style=\"flex: 1;\">\n"
+ "\n"
+ "![Figure 1](./images/quest/rat_licking_oxy.svg)\n"
+ "\n"
+ "</div>\n"
+ "<div style=\"flex: 1;\">\n"
+ "\n"
+ "- Active spout (oxycodone), inactive spout (control), water spout\n"
+ "- RFID tags for automated animal identification\n"
+ "- 12:12h reversed light cycle; dark-phase testing\n"
+ "- Reinforcement schedule\n"
+ "  - Fixed ratio 5: every 5th lick on active spout delivers 60 µL oxycodone + visual cue (LED flash)\n"
+ "  - 20-second timeout after each reward - Licks during timeout recorded but no drug delivered\n"
+ "\n"
+ "  </div>\n"
+ "  </div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## The Behavioral Protocol\n"
+ "\n"
+ "![schedule](images/quest/MS_PLOS_Oxy_final_clean_copy__Figure_1.png)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Does Genetics Influence a Trait?\n"
+ "\n"
+ "- Within-strain: genetically identical individuals (VE = environmental variance)\n"
+ "- Between-strain: genetic differences (VA = additive genetic variance)\n"
+ "- h² = VA / (VA + VE) directly estimable\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Heterogeneous Stock Rats\n"
+ "\n"
+ "#### Outbred\n"
+ "\n"
+ "<img src=\"./images/hs/hs_rats.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## The Hybrid Rat (Diversity|Discovery) Panel\n"
+ "\n"
+ "#### Inbred\n"
+ "\n"
+ "<img src=\"./images/quest/HRDP_1000x357.png\">\n"
+ "\n"
+ "Note:\n"
+ "\n"
+ "- ~90 isogenic (fully inbred) rat lines\n"
+ "- Each strain = infinitely reproducible genotype\n"
+ "- Enables multi-lab, multi-phenotype integration over time\n"
+ "- 50 strains phenotyped to date for oral oxycodone SA\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Oral Self-administration Captures Key Features of OUD\n"
+ "\n"
+ "<img src=\"./images/quest/oxyren_alldata_sexdiff.png\">\n"
+ "\n"
+ "<span id=\"cite\">NIDA U01DA0536721, Sharp, Chen, Williams</span>\n"
+ "\n"
+ "Note:\n"
+ "\n"
+ "- Robust voluntary drug consumption without prior exposure\n"
+ "- Strong preference for active over inactive spout\n"
+ "- Large individual variation in intake escalation\n"
+ "- Cue-induced reinstatement (models relapse)\n"
+ "- Hypoalgesia after consumption / hyperalgesia during withdrawal\n"
+ "- Strong sex differences mirroring human patterns\n"
+ "\n"
+ "- Females consume significantly more across all doses and session lengths\n"
+ "- Females: broader reinforcing dose range\n"
+ "- Females: more vigorous reinstatement of drug seeking\n"
+ "- Males: 25-100 fold increase varies dramatically by strain\n"
+ "- Similar pattern to human sex differences in opioid use\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Heritability of Oxycodone Traits\n"
+ "\n"
+ "<div style=\"display: flex; align-items: center;\">\n"
+ "<div style=\"flex: 1;\">\n"
+ "\n"
+ "![Figure 4](images/quest/MS_PLOS_Oxy_final_clean_copy__Figure_4.png)\n"
+ "\n"
+ "</div>\n"
+ "<div style=\"flex: 1;\">\n"
+ "\n"
+ "- Active licks: mean h² = 0.34\n"
+ "- Rewards: mean h² = 0.39\n"
+ "- Intake: mean h² = 0.46 (range 0.18-0.65)\n"
+ "- Inactive licks: mean h² = 0.16\n"
+ "- h² varies by sex and by behavioral stage\n"
+ "- Substantial genetic contribution to vulnerability\n"
+ "\n"
+ "</div>\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## <font color=\"firebrick\"> Augmenter vs. Non-Augmenter Strains </font>\n"
+ "\n"
+ "<img src=\"./images/quest/oxyren_alldata_sexdiff.png\">\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Augmenter vs. Non-Augmenter Strains\n"
+ "\n"
+ "<div style=\"display: flex; align-items: center;\">\n"
+ "<div style=\"flex: 1;\">\n"
+ "\n"
+ "![Figure 6](images/quest/MS_PLOS_Oxy_final_clean_copy__Figure_6.png)\n"
+ "\n"
+ "</div>\n"
+ "<div style=\"flex: 1;\">\n"
+ "\n"
+ "- Extended 16-h access reveals hidden vulnerability\n"
+ "- Augmenters: >3-fold increase in intake at 16-h vs. 4-h\n"
+ "- Non-Augmenters: modest increase\n"
+ "- **Critical**: both groups have identical intake during 4-h sessions\n"
+ "- Identified 7 female and 8 male Augmenter strains\n"
+ "- Cannot predict vulnerability from short-session data alone\n"
+ "\n"
+ "<span id=\"cite\"> Sharp, et al, PLOS One, 2025</a>\n"
+ "\n"
+ "</div>\n"
+ "</div>\n"
+ "\n"
+ "Note:\n"
+ "\n"
+ "## Temporal Pattern of Augmented Intake\n"
+ "\n"
+ "- Hour-by-hour analysis of 16-h sessions\n"
+ "- Augmenters: rapid \"loading-up\" during first 6 hours, steep decline by 7-11h\n"
+ "- Non-Augmenters: peak at hour 1, gradual decline\n"
+ "- By 13-16h, both groups converge\n"
+ "- Suggests difference in reward efficacy, not metabolism\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## No Genetic Evidence that Oxycodone Metabolism is Involved\n"
+ "\n"
+ "- Analyzed 1,263 SNPs in Cyp3a2, Cyp3a9, Cyp2d1\n"
+ "- No significant allele frequency differences between Augmenters and Non-Augmenters\n"
+ "- Pharmacokinetic differences may not contribute to the phenotype\n"
+ "- Points toward CNS reward mechanisms\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Hypotheses\n"
+ "\n"
+ "- The Mechanism: Chronic opioid exposure induces differential molecular responses that are genetically determined via gene-environment (G×E) interactions.\n"
+ "\n"
+ "- The Manifestation: A subset of these genetically encoded molecular adaptations drives neuroplastic changes that facilitate subsequent escalation of opioid intake.\n"
+ "\n"
+ "- The Application: These distinct molecular signatures can serve as predictive biomarkers to identify individuals at high risk for developing OUD during prescription opioid therapy.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Toward Objective Biomarkers for Early Detection of OUD Risk\n"
+ "\n"
+ "- Aim 1: Biomarker discovery\n"
+ "  - Augmenters vs. Non-augmenters after the last 4-h stage.\n"
+ "  - Brain reward regions\n"
+ "  - Blood\n"
+ "  - Proteomics\n"
+ "- Aim 2: Validation in human subjects\n"
+ "\n"
+ "<hr>\n"
+ "\n"
+ "#### Funded by The State of Tennessee Opiate Abatement Fund (2026-2027)\n"
+ "\n"
+ "(Burt Sharp, GGI | Xusheng Wang, Neurology | Karen Derefinko, Preventive Med | Jennifer Tourville, UT SMART Initiative | The McNabb Center)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## <font color=\"firebrick\"> Liking vs. Wanting </font>\n"
+ "\n"
+ "![Figure 1](./images/quest/rat_licking_oxy.svg)\n"
+ "\n"
+ "- Incentive sensitization theory (Robinson & Berridge)\n"
+ "- Hedonic \"liking\" = pleasure upon consumption\n"
+ "- Motivational \"wanting\" = incentive drive to seek drug\n"
+ "- Classical prediction: they uncouple during addiction progression\n"
+ "- Can we measure how much rats like and want using licking behavior?\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Classic Lick Microstructure Analysis\n"
+ "\n"
+ "<img src=\"./images/quest/lick_cluster_number_by_sucrose_concentration.jpg\" width = 60%>\n"
+ "\n"
+ "<span id=\"cite\"> Davis and Smith, Behav Neurosci, 1992</span>\n"
+ "\n"
+ "Note: cluster threshold is 0.5s\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Classic Lick Microstructure Analysis\n"
+ "\n"
+ "<img src=\"./images/quest/Mean-SE-number-of-bursts-for-all-conditions-n-15-The-pause-criterion-is-indicated.png\" width = 60%>\n"
+ "\n"
+ "<span id=\"cite\"> Spector, et al, Behav Neurosci, 1998</span>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Rat Licking on a Spout\n"
+ "\n"
+ "<iframe width=\"430\" height=\"1020\" src=\"https://www.youtube.com/embed/nGrPtfv10s0\" title=\"Slow motion of rat licking on a spout\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Consumption vs seeking\n"
+ "\n"
+ "<div style=\"display: flex; align-items: center;\">\n"
+ "<div style=\"flex: 1;\">\n"
+ "\n"
+ "![Figure 2](images/quest/REV_Lick_Structure_Heightened_Hedonic_Impact_and_Drug_S__Figure_2.png)\n"
+ "\n"
+ "</div>\n"
+ "<div style=\"flex: 1;\">\n"
+ "\n"
+ "- 562,000+ lick clusters analyzed across all rats\n"
+ "- The first three clusters are consumption, the rest are seeking\n"
+ "\n"
+ "<span id=cite> Sharp & Chen, BioRxiv 2025</span>\n"
+ "\n"
+ "</div>\n"
+ "</div>\n"
+ "\n"
+ "Note:\n"
+ "\n"
+ "- 98.1% of all lick clusters occur within the 20-sec timeout\n"
+ "- Consumption clusters (positions 0-2): sharp CS decline, direct reward engagement\n"
+ "- Seeking clusters (positions 3+): stable smaller CS, persistent responding for unavailable drug\n"
+ "- Seeking during timeout = unmasked motivational drive\n"
+ "- 226,752 rewards → 489,845 timeout clusters classified\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Number of clusters\n"
+ "\n"
+ "<img src=\"./images/quest/REV_Lick_Structure_Heightened_Hedonic_Impact_and_Drug_S__Figure_3.png\" width=50%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Cluster Size\n"
+ "\n"
+ "<img src=\"./images/quest/REV_Lick_Structure_Heightened_Hedonic_Impact_and_Drug_S__Figure_4.png\" width=50%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Interlick Interval\n"
+ "\n"
+ "<img src=\"./images/quest/REV_Lick_Structure_Heightened_Hedonic_Impact_and_Drug_S__Suppl_Figure_1.png\" width=50%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Liking Drives Wanting in Vulnerable Strains\n"
+ "\n"
+ "<div style=\"display: flex; align-items: center;\">\n"
+ "<div style=\"flex: 1;\">\n"
+ "\n"
+ "![Figure 5](images/quest/REV_Lick_Structure_Heightened_Hedonic_Impact_and_Drug_S__Figure_5.png)\n"
+ "\n"
+ "</div>\n"
+ "<div style=\"flex: 1;\">\n"
+ "\n"
+ "- Incentive sensitization predicts liking/wanting uncoupling\n"
+ "- **We find the opposite in Augmenters**: hedonic liking during consumption directly predicts motivational wanting\n"
+ "- Strong correlations between consumption CS, seeking CS, and interlick intervals\n"
+ "- Effect is especially pronounced in female Augmenters\n"
+ "- Suggests heightened hedonic impact as a core vulnerability feature\n"
+ "\n"
+ "</div>\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## The Liking→Wanting Coupling\n"
+ "\n"
+ "- Augmenters in both M and F: large consumption clusters → large seeking clusters\n"
+ "- Non-Augmenters: no significant correlation\n"
+ "- Heritability:\n"
+ "\n"
+ "| Sex    | Phase       | 4-h  | 16-h |\n"
+ "| ------ | ----------- | ---- | ---- |\n"
+ "| Female | Consumption | 0.34 | 0.29 |\n"
+ "| Female | Seeking     | 0.04 | 0.11 |\n"
+ "| Male   | Consumption | 0.23 | 0.08 |\n"
+ "| Male   | Seeking     | 0.14 | 0.11 |\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## <font color=\"firebrick\"> The HRDP Genomic Resource </font>\n"
+ "\n"
+ "<div style=\"display: flex; align-items: center;\">\n"
+ "<div style=\"flex: 1;\">\n"
+ "\n"
+ "<img src=\"./images/quest/Figure6_phylogenetic_tree_color.png\">\n"
+ "\n"
+ "</div>\n"
+ "<div style=\"flex: 1;\">\n"
+ "\n"
+ "- Whole genome sequencing of entire panel: ~20 million variants\n"
+ "- Revamped rat reference genome mRatBN7.2 (Cell Genomics, 2024)\n"
+ "- International consortium: corrected structural errors, improved eQTL mapping\n"
+ "- Marker maps: 385K SNPs (classical inbreds), 16K (FXLE), 7K (HXB)\n"
+ "- GRCr8 and telomere-to-telomere assemblies in progress\n"
+ "</div>\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## QTL Mapping Strategy\n"
+ "\n"
+ "<div style=\"display: flex; align-items: center;\">\n"
+ "<div style=\"flex: 1;\">\n"
+ "\n"
+ "![Figure 4](images/quest/OXY_U01_Renewal_Compiled_FINAL_Jan_2026__Figure_4.png)\n"
+ "\n"
+ "</div>\n"
+ "<div style=\"flex: 1;\">\n"
+ "\n"
+ "- Phenotype 50 strains (completed) → 30 additional strains (Aim 1 renewal)\n"
+ "- Map strain means using GEMMA with LOCO procedure\n"
+ "- Separate mapping for classical inbreds, HXB, FXLE families\n"
+ "- Combine linkage scores via Fisher's method\n"
+ "- Sex-stratified and joint analyses for G×S interactions\n"
+ "- Power analysis: n=90 strains provides good power (0.8) at moderate effect sizes\n"
+ "\n"
+ "</div>\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## QTL Mapping Results: 46 Significant Loci\n"
+ "\n"
+ "<div style=\"display: flex; align-items: center;\">\n"
+ "<div style=\"flex: 1;\">\n"
+ "\n"
+ "![Figure 7](images/quest/OXY_U01_Renewal_Compiled_FINAL_Jan_2026__Figure_7.png)\n"
+ "\n"
+ "</div>\n"
+ "<div style=\"flex: 1;\">\n"
+ "\n"
+ "- Mapped across 40 OUD-related behavioral phenotypes\n"
+ "- Mean locus size: ~3.5 Mb (some as narrow as 1 Mb)\n"
+ "- Chromosome 1 locus: LOD ~6.0 for oxycodone intake in females\n"
+ "- Sex-specific QTLs suggest G×S interactions\n"
+ "\n"
+ "</div>\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Zoom in on a Chr 10 locus\n"
+ "\n"
+ "<img src=\"./images/quest/phenooxycodone_oral_self_administration_FR5_0.1mg_4h_Intake_F_chr10_24_locuszoom.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Zoom in on a Chr 20 locus\n"
+ "\n"
+ "<img src=\"./images/quest/phenooxycodone_oral_self_administration_FR5_0.1mg_4h_Intake_F_chr20_36_locuszoom.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Zoom in on a Chr 1 locus\n"
+ "\n"
+ "<img src=\"./images/quest/phenooxycodone_oral_self_administration_FR5_0.025mg_4h_Intake_F_chr1_locuszoom.png\" width=70%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## The Gene Prioritization Pipeline\n"
+ "\n"
+ "- High-impact sequence variants (missense, nonsense, splice site, SVs from pangenome)\n"
+ "  - 18,646 variants, affecting 6,667 genes, including 3,930 protein-coding genes (de Jong, et al, Cell Genomics 2024)\n"
+ "- Cis-eQTL, cis-pQTL\n"
+ "  - Genenetwork.org, Phenogen.org\n"
+ "  - Brain pQTL (Li, et al. iScience, 2025)\n"
+ "- 3D chromatin for enhancer promoter interaction.\n"
+ "  - Hi-C (Kim, Sci Data, 2025, BioRxiv 2026)\n"
+ "- AI-driven neurobiological relation search\n"
+ "  - GeneCup (Gunturken, et al. S3, 2022)\n"
+ "- Cell-type expression concordance (mouse, rat, human)\n"
+ "- DNA methylation changes near candidate genes\n"
+ "- Concordance with human OUD GWAS hits\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## The Chr 1 Locus and Vitamin D\n"
+ "\n"
+ "<a href=\"https://genenetwork.org/search?species=rat&group=HXBBXH&type=Brain+mRNA&dataset=PGenRatBrn_rna_0520&search_terms_or=cyp2r1%0D%0A&search_terms_and=&accession_id=None&FormID=searchResult\" target=_new>cis-eQTL for Cyp2r1</a> |\n"
+ "\n"
+ "<a href=\"https://www.ebi.ac.uk/gwas/genes/CYP2R1\"> Vitamin D </a>\n"
+ "\n"
+ "<a href=\"https://pmc.ncbi.nlm.nih.gov/articles/PMC8195487/\" target=_new> Vitamin D and opioid addiction</a>\n"
+ "\n"
+ "<div style=\"display: flex; align-items: center;\">\n"
+ "<div style=\"flex: 1;\">\n"
+ "\n"
+ "![intake by genotype](./images/quest/oxycodone_intake_by_genotype_square.png)\n"
+ "\n"
+ "</div>\n"
+ "<div style=\"flex: 1;\">\n"
+ "\n"
+ "![neurovascular](./images/quest/neurovascular_unit_vitamin_d.jpg)\n"
+ "\n"
+ "</div>\n"
+ "</div>\n"
+ "\n"
+ "Note:\n"
+ "\n"
+ "- Genome-wide significant for oxycodone intake in females\n"
+ "- Cyp2r1: 25-hydroxylates Vitamin D3 in brain pericytes\n"
+ "- Produces precursor (25-OH D3) for neurosteroid 1,25-OH2 D3\n"
+ "- Oxycodone intake was 3-fold greater in rat strains with Alt SNP compared to wild type (0/0). Heterozygous (0/1) were significantly less than homozygous strains. p<5x10-7 for genotype effect\n"
+ "\n"
+ "The Vitamin D - Opioid Sensitivity Connection\n"
+ "\n"
+ "- 1,25-OH2 D3 is a neurosteroid synthesized within neurons (Cyp27b1)\n"
+ "- Regulates NGF/GDNF synthesis, Ca²⁺ flux, neuroprotection\n"
+ "- Reduced Cyp2r1 → deficient 25-OH D3 → impaired neurosteroid synthesis\n"
+ "- Creates \"opioid sensitivity syndrome\"\n"
+ "- NOT about systemic vitamin D deficiency — it's intraneuronal\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## <font color=\"firebrick\"> Hypothesis Generation </font>\n"
+ "\n"
+ "Found a great QTL, but there are 10 genes under the peak. Need to read all the literature about these genes to generate a hypothesis about the causal gene.\n"
+ "\n"
+ "- Search PubMed\n"
+ "  - Think about a complete list of keywords related to the phenotypes.\n"
+ "  - Search each gene against each of these keywords.\n"
+ "  - Read the abstracts.\n"
+ "  - Take notes on what is relevant.\n"
+ "  - Synthesize the knowledge\n"
+ "  - <a href=\"https://genecup2.genenetwork.org\" target=\"_new\">https://genecup2.genenetwork.org </a>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## GeneCup\n"
+ "\n"
+ "<img src=\"./images/fgf12/genecup_graph.svg\" width=60%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Hypothesis Prompt Structure\n"
+ "\n"
+ "<table> <tr> <td width=\"30%\"> <img src=\"./images/ctc2025/2025-10-22-genecup-llm.png\"></td><td>\n"
+ "\n"
+ "- Research Context\n"
+ "- Goal\n"
+ "- Required Analysis:\n"
+ "  - A. Term Disambiguation\n"
+ "    - MADD = MAP kinase-activating death domain protein ? Mothers against drunk driving\n"
+ "  - B. Synthesis of Function and Experimental Context\n"
+ "  - C. Critical Evaluation of Causal Gene Plausibility (with In-text Citations)\n"
+ "    - Assessment of Functional Plausibility\n"
+ "    - Assessment of Tissue/Cell Type Relevance\n"
+ "    - Assessment of Pathway and Network Involvement\n"
+ "    - Assessment of Existing Disease/Trait Associations:\n"
+ "  - D. Balanced Concluding Assessment\n"
+ "\n"
+ "    </td></tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Using Command-line AI tools\n"
+ "\n"
+ "<table> <tr> <td width=\"50%\"> <img src=\"./images/quest/geminicli.png\"></td><td>\n"
+ "\n"
+ "<img src=\"./images/quest/claudecode.png\"></td></tr>\n"
+ "\n"
+ "</table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Hypothesis Evaluation Results\n"
+ "\n"
+ "### <a href=\"https://docs.google.com/document/d/1c46UYfp3DVfnEMBhSNb_QWXyWP7SQktOTq0QZZGAoPA/edit?usp=sharing\"  target=\"_new\"> Full report</a>\n"
+ "\n"
+ "Reduced 99 pages of relevant sentences into 2.5 pages of structured summary, with likely valid citations.\n"
+ "\n"
+ "**Summary of Supporting Evidence:**\n"
+ "\n"
+ "The evidence supporting CACNA1C as a plausible causal gene for socially acquired nicotine intravenous self-administration is **substantial**. The strongest lines of evidence are: **1.** Its critical role in reward processing, learning, and memory, which are core components of addiction (PMID: 25290268, 28604818). **2.** Its expression and function in key brain regions of the reward pathway, such as the nucleus accumbens (PMID: 28165117). **3.** Its position as a hub gene in addiction-related molecular networks (PMID: 36744178, 36865068). **4**. Existing genetic associations with nicotine dependence and other substance use disorders in humans (PMID: 25555482, 36551763).\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Example Uses of Language Models\n"
+ "\n"
+ "- Grant revision\n"
+ "- Data visualization and analysis\n"
+ "- Grant ideas\n"
+ "- Experimental protocol\n"
+ "- Engineering projects\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## The U01 Renewal\n"
+ "\n"
+ "- Adding 30 more strains (4 inbred + 10 HXB + 16 FXLE)\n"
+ "- snRNA-seq to provide cell-type-specific, oxycodone-driven transcriptional changes\n"
+ "- Validate candidate genes using <a href=\"https://www.nature.com/articles/s41598-024-53037-9\" target=_new> CRISPR/Cas9 </a>\n"
+ "  - AAV-SaCas9-gRNA system (SaCas9 small enough for single AAV)\n"
+ "  - Cell-type-specific promoters: hSyn (neurons), hGFAP (astrocytes)\n"
+ "  - Non-transgenic rats: directly applicable to HRDP strains\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## GeneNetwork.org: The Integrative Platform\n"
+ "\n"
+ "- Open resource for systems genetics (developed by Williams and team)\n"
+ "- Hosts all oxycodone phenotype data (HRP_10237 to HRP_10353)\n"
+ "- Integrates genomic, transcriptomic, proteomic, and phenotype data\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## <font color=\"firebrick\"> The P30 SMART Core: Nexus Panel of Inbred Strains </font>\n"
+ "\n"
+ "<div style=\"display: flex; align-items: center;\">\n"
+ "<div style=\"flex: 1;\">\n"
+ "\n"
+ "![Figure 6](images/quest/P30_SMART_Core__Figure_6.png)\n"
+ "\n"
+ "</div>\n"
+ "<div style=\"flex: 1;\">\n"
+ "\n"
+ "- **Scored NIDA OSGA Center grant (not yet funded)**\n"
+ "- **Nexus Panel**: 10 inbred strains capturing the majority of genetic diversity in lab rats\n"
+ "  - ACI, BN, BUF, F344, M520, MR, WKY, WAG, SHR, LE + Sprague-Dawley\n"
+ "- Strains span full spectrum of SUD phenotypes (low to high oxycodone/nicotine intake)\n"
+ "- Include founders of Heterogeneous Stock and parents of RI panels\n"
+ "- Harbor high-impact variants in genes whose human orthologs reached GWAS significance for OUD, smoking, alcohol, and cannabis use\n"
+ "\n"
+ "</div>\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Oxford Nanopore Long-Read Sequencing Technologies\n"
+ "\n"
+ "<div style=\"display: flex; align-items: center;\">\n"
+ "<div style=\"flex: 1;\">\n"
+ "\n"
+ "![Figure 1](images/quest/P30_SMART_Core__Figure_1.png)\n"
+ "\n"
+ "</div>\n"
+ "<div style=\"flex: 1;\">\n"
+ "\n"
+ "- **DNA methylation profiling**: single-base resolution detection of 5-mC, 5-hmC, 6-mA from native DNA (no bisulfite conversion)\n"
+ "- **Direct RNA-seq**: full-length isoforms, polyA site usage, polyA length, base modifications (m6A, pseudouridine, inosine) — all from a single experiment\n"
+ "- **Adaptive sampling**: real-time enrichment of target regions (e.g., CpG islands) during sequencing\n"
+ "\n"
+ "</div>\n"
+ "</div>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Acknowledgements\n"
+ "\n"
+ "<img src=\"./images/quest/team_sunray.png\">\n"
+ "\n"
+ "---\n"
;
var script = document.querySelector('script[src="quest.js"]');
var section = document.createElement('section');
script.parentNode.appendChild(section);
section.appendChild(document.createTextNode(markdownContent));
[].forEach.call(script.attributes, function (attr) {
    section.setAttribute(attr.name, script.getAttribute(attr.name));
});
section.setAttribute('data-markdown', '');
})();
