(function () {
'strict'
var markdownContent = ''
+ "# Comparing Rnor6 and mRatBN7.1 \n"
+ "##  Nov 24th 2020 \n"
+ "\n"
+ "<hr>\n"
+ "\n"
+ "### Tristan de Jong, Hakan Gunturkun, Hao Chen\n"
+ "\n"
+ "<img src=\"images/little_wizard.png\" width=40%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Chr vs Chr dot plots\n"
+ "\n"
+ "mRatNor1.1 (May 20 2020)  = mRatBN7.1 (NCBI) \n"
+ "\n"
+ "<iframe src=\"pdfs/dotplots_mRatNor1_vs_rn6.pdf\" width=\"100%\" height=600px>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Data sets\n"
+ "\n"
+ "* 10x Chromium Linked reads WGS data from 36 inbred strains\n"
+ "	* most strains have about 60x coverage\n"
+ "	* Four BN samples\n"
+ "	* BN-Lx/Cub and SHR/OlaIpcv\n"
+ "	* 30 HXB and BXH strains \n"
+ "	* Analyzed using Longranger 2.2.2 against both refs\n"
+ "* Oxford nanopore WGS data for BN-Lx/Cub and SHR/OlaIpcv \n"
+ "	* about 20x coverage \n"
+ "	* N50 about 15-20kb\n"
+ "	* Winnowmap for mapping	against both refs\n"
+ "	* Sniffles for SV detection\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Linked-reads data \n"
+ "\n"
+ "## Mapping stats \n"
+ "\n"
+ "<iframe src=\"pdfs/longranger_mapping_stats_mRatBN7_v_Rnor6.pdf\" width=\"100%\" height=600px>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Linked-reads data \n"
+ "\n"
+ "## Summary of mapping stats\n"
+ "\n"
+ "* mRatBN7 decreases \n"
+ "	* SNPs phases \n"
+ "		* likely due to reduced number of Hets \n"
+ "	* estimates of the mean and stddev of input molecular length \n"
+ "		* likely due to removing extra sequences that does not belong \n"
+ "	* areas with zero coverage and short deletion calls\n"
+ "		* likely due to removing extra sequences that does not belong \n"
+ "	* the number of large SV calls \n"
+ "		* likely due to reduced assembly errors\n"
+ "* mRatBN7 increases\n"
+ "	* N50 of linked reads\n"
+ "		* likely due to increased N50 of the reference\n"
+ "	* mean depth of coverage and mapped reads\n"
+ "		* likely due to improved accuracy of the reference \n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Linked-reads data \n"
+ "## Type of SV and their locations  \n"
+ "\n"
+ "<iframe src=\"pdfs/hxb_location_of_sv_rn6_v_bn7.pdf\" width=\"100%\" height=600px>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Linked-reads data \n"
+ "## Type of SNPs and indels  \n"
+ "\n"
+ " Joint calling by Deepvariant/GLNexus \n"
+ "\n"
+ "\n"
+ "<iframe src=\"pdfs/deepvariant_36_samples_rn6_v_bn7.pdf\" width=\"100%\" height=600px>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Linked-reads data \n"
+ "## Summary of SV, SNP, small indel\n"
+ "\n"
+ "* mRatBN7 increases the accuracy of variant detection by  \n"
+ "	* improving assembly accurcy \n"
+ "		* there are likely errors at the assembly level\n"
+ "	* improving accuracy at nucleotide level\n"
+ "		* there are likely errorrs at the nucleotide level \n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Nanopore data \n"
+ "## Coverage per chromosome\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Nanopore data\n"
+ "\n"
+ "## Coverage per 10k\n"
+ "\n"
+ "<iframe src=\"pdfs/bnlx_shrola_nanopore_coverage.pdf\" width=\"100%\" height=600px>\n"
+ "\n"
+ "\n"
+ "---\n"
+ "\n"
+ "#### Nanopore data\n"
+ "\n"
+ "## SV calls by Sniffles\n"
+ "\n"
+ "<iframe src=\"pdfs/bnlx-shrolaipcv_nanopore_sniffle_size.pdf\" width=\"100%\" height=600px>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "\n"
+ "#### Nanopore data\n"
+ "\n"
+ "## Summary\n"
+ "\n"
+ "* mRatBN7 reduces regions with low coverage from nanopore data\n"
+ "* mRatBN7 reduces regions with very high coverage from nanopore data\n"
+ "* mRatBN7 reduces false SV detections from nanopore data \n"
+ "\n"
+ "\n"
;
var script = document.querySelector('script[src="ratGenomeNov2020.js"]');
var section = document.createElement('section');
script.parentNode.appendChild(section);
section.appendChild(document.createTextNode(markdownContent));
[].forEach.call(script.attributes, function (attr) {
    section.setAttribute(attr.name, script.getAttribute(attr.name));
});
section.setAttribute('data-markdown', '');
})();
