(function () {
'strict'
var markdownContent = ''
+ "# Comparison of Ensembl and NCBI GRCr8 Annotations\n"
+ "\n"
+ "<hr color=orange >\n"
+ "\n"
+ "### Hao Chen\n"
+ "\n"
+ "#### University of Tennessee Health Science Center\n"
+ "\n"
+ "Note: This presentation provides a comprehensive comparison between the Ensembl (v115) and NCBI (RefSeq) annotations for the GRCr8 rat reference genome. We will explore structural discrepancies, transcript complexity, and nomenclature conflicts.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Compare gtf files from <a href=\"https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_036323735.1/\" target=_new>NCBI</a> vs <a href=\"https://useast.ensembl.org/Rattus_norvegicus/Info/Index\" target=_new>Ensembl v 115</a>\n"
+ "\n"
+ "- Global feature counts\n"
+ "- Transcript Structure\n"
+ "- Gene Identity\n"
+ "- Nomenclature conflicts\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Feature Counts\n"
+ "\n"
+ "### Column 3 o the GTF file\n"
+ "\n"
+ "<pre> \n"
+ "# Ensembl\n"
+ "1	ensembl	gene	268909413	269079661	.	-	.	gene_id \"ENSRNOG00000009523\"; gene_version \"9\"; gene_name \"Rab11fip2\"; gene_source \"ensembl\"; gene_biotype \"protein_coding\";\n"
+ "# NCBI\n"
+ "NC_086019.1	Gnomon	gene	43201	45926	.	-	.	gene_id \"LOC134485287\"; transcript_id \"\"; db_xref \"GeneID:134485287\"; description \"zinc finger protein 431-like\"; gbkey \"Gene\"; gene \"LOC134485287\"; gene_biotype \"protein_coding\"; partial \"true\"; \n"
+ "\n"
+ "</pre>\n"
+ "<table> <tr><td width=50%>\n"
+ "<img src=\"./images/rn8annot/z01_feature_counts_high.png\" width=100%>\n"
+ "</td><td>\n"
+ "<img src=\"./images/rn8annot/z01_feature_counts_low.png\" width=100%>\n"
+ "</td></tr></table>\n"
+ "\n"
+ "Note:\n"
+ "exon = CDS + UTRs\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Gene Biotype Distribution: Major and Minor Categories\n"
+ "\n"
+ "<table> <tr><td width=50%>\n"
+ "<img src=\"./images/rn8annot/z01_biotypes_high.png\" width=100%>\n"
+ "</td><td>\n"
+ "<img src=\"./images/rn8annot/z01_biotypes_low.png\" width=100%>\n"
+ "</td></tr></table>\n"
+ "\n"
+ "Note:\n"
+ "protein coding: ORF translated into protein\n"
+ "pseudogene: there is premature stop codon or frame shift\n"
+ "processed pseudogene: created via retrotransposition of mRNA\n"
+ "non-processed pseudogene: created via gene duplication\n"
+ "transcribed pseudogene: transcribed but not functional\n"
+ "snRNA: small nuclear RNA: involved in splicing of introns\n"
+ "snoRNA: small nucleolor RNA: guide chemical modifications of RNAs\n"
+ "scaRNA: a subset of snoRNA\n"
+ "lncRNA: longer than 200 nt but are not translated\n"
+ "ncRNA:\n"
+ "miRNA: 19 to 25 nt, post-transcriptional regulation of gene expression\n"
+ "Y RNA: involved in the initiation of chromosomal DNA replication\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Gene Spans and Transcript Lengths\n"
+ "\n"
+ "<table> <tr><td width=33%>\n"
+ "<img src=\"./images/rn8annot/z01_dist_gene_length.png\" width=100%>\n"
+ "</td><td width=33%>\n"
+ "<img src=\"./images/rn8annot/z09_intron_length_per_gene.png\" width=100%>\n"
+ "</td><td width=33%>\n"
+ "<img src=\"./images/rn8annot/z01_dist_transcript_length.png\" width=100%>\n"
+ "</td></tr></table>\n"
+ "\n"
+ "Note:\n"
+ "Ensembl has a longer median gene span (~10.9kb vs 6.5kb).\n"
+ "NCBI has significantly longer mature transcripts (Median: 2,802 bp vs Ensembl 1,778 bp).\n"
+ "The \"Short Gene\" paradox in NCBI is caused by its inclusion of thousands of very short ncRNAs and pseudogenes that pull the median down.\n"
+ "\n"
+ "The Genes around 100 bp are miRNA, snoRNA, and snRNA, tRNA, 5S RNA and short pseudogenes\n"
+ "the shortest in NCBI are mature miRNA products (18 to 25 nt) (ensembl annotates pre-miRNA, about 80bp, NCBI includes both)\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Transcripts and Exons\n"
+ "\n"
+ "<table> <tr><td width=33%>\n"
+ "<img src=\"./images/rn8annot/z01_dist_transcripts_per_gene.png\" width=100%>\n"
+ "</td> <td width=33%>\n"
+ "<img src=\"./images/rn8annot/z01_dist_exons_per_transcript.png\" width=100%>\n"
+ "</td> <td width=33%>\n"
+ "<img src=\"./images/rn8annot/z03_isoform_density.png\" width=100%>\n"
+ "</td></tr></table>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Exons by Biotype Classification\n"
+ "\n"
+ "<img src=\"./images/rn8annot/z03_exon_inventory.png\" width=60%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## UTR Mapping Consistency and Generation Efficiency\n"
+ "\n"
+ "<table> <tr><td width=50%>\n"
+ "<img src=\"./images/rn8annot/z03_utr_location_comparison.png\" width=100%>\n"
+ "</td><td width=50%>\n"
+ "<img src=\"./images/rn8annot/z03_utr_efficiency.png\" width=100%>\n"
+ "</td></tr></table>\n"
+ "\n"
+ "Note:\n"
+ "Left: Only 15% of 5' UTRs match exactly. Boundary consistency is extremely low for 3' UTRs.\n"
+ "Center: Isoform Density (mean transcripts per unique exon). NCBI shows nearly double the overlap (3.8 vs 2.0).\n"
+ "Right: NCBI is more \"efficient,\" generating ~453 UTRs per 1,000 exons vs Ensembl's ~335.\n"
+ "Conclusion: NCBI captures much more structural diversity and alternative splicing boundaries.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Distribution of 5' and 3' UTR Lengths\n"
+ "\n"
+ "<img src=\"./images/rn8annot/z04_utr_length_dist.png\" width=70%>\n"
+ "\n"
+ "Note:\n"
+ "NCBI 5' UTRs are longer on average (~731 bp vs ~333 bp).\n"
+ "Ensembl 3' UTRs show an artificial spike at exactly 1,001 bp (3,356 transcripts) and 5' UTRs at 199 bp (5,920 transcripts).\n"
+ "These are algorithmic placeholders. NCBI models are more evidence-driven.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Gene Count vs Gene Symbol Overlap\n"
+ "\n"
+ "<table> <tr><td width=50%>\n"
+ "<img src=\"./images/rn8annot/z02_total_unique_loci.png\" width=100%>\n"
+ "</td><td>\n"
+ "<img src=\"./images/rn8annot/z02_gene_symbol_overlap.png\" width=100%>\n"
+ "</td></tr></table>\n"
+ "\n"
+ "Note:\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Top Biotypes of Unique Gene Symbols\n"
+ "\n"
+ "<img src=\"./images/rn8annot/z07_unique_symbol_biotypes.png\" width=90%>\n"
+ "\n"
+ "Note:\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Nomenclature Consistency\n"
+ "\n"
+ "#### Genes linked by unique IDs in Ensembl BioMart (22k named genes)\n"
+ "\n"
+ "<img src=\"./images/rn8annot/z05_nomenclature_comparison.png\" width=70%>\n"
+ "\n"
+ "Note:\n"
+ "Nomenclature agreement is high (95%) for shared, well-characterized genes.\n"
+ "The 25k unique NCBI symbols from earlier are largely excluded here because they lack cross-database ID links (mostly small RNAs).\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Consistency of Protein-Coding Models\n"
+ "\n"
+ "<img src=\"./images/rn8annot/z02_cds_consistency_transcript.png\" width=60%>\n"
+ "\n"
+ "Note:\n"
+ "At the transcript level, only ~21k protein-coding models are identical.\n"
+ "NCBI provides nearly double the amount of unique protein isoforms (43k vs 24k), confirming higher transcriptomic resolution even at the protein level.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Consistency of lncRNA Models\n"
+ "\n"
+ "#### only 4 lncRNA genes have exact locations\n"
+ "\n"
+ "<img src=\"./images/rn8annot/z02_lncrna_consistency_transcript.png\" width=60%>\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Physical Genomic Overlap of Annotated Genes\n"
+ "\n"
+ "<img src=\"./images/rn8annot/z06_gene_spatial_overlap.png\" width=60%>\n"
+ "\n"
+ "Note:\n"
+ "Reciprocal overlap analysis. ~75% of Ensembl and ~71% of NCBI genes share physical space.\n"
+ "NCBI has higher absolute shared counts (33.4k vs 32.5k), confirming \"one-to-many\" overlaps where NCBI annotates multiple smaller genes in space Ensembl defines as one.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Evidence Support for Database-Unique Gene Loci\n"
+ "\n"
+ "<img src=\"./images/rn8annot/z08_combined_unique_evidence.png\" width=60%>\n"
+ "\n"
+ "Note:\n"
+ "Nearly 50% of the ~14,000 NCBI-unique loci are supported by explicit experimental evidence (SRA, EST, or Protein data).\n"
+ "100% of Ensembl-unique loci (~10,700) are supported by Ensembl's curation criteria.\n"
+ "Both sources' unique catalogs are biologically grounded and high-confidence.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Identification of Orphan Protein-Coding Genes\n"
+ "\n"
+ "<img src=\"./images/rn8annot/z10_orphan_pc_genes.png\" width=60%>\n"
+ "\n"
+ "Note:\n"
+ "NCBI identifies 1,250 orphan protein-coding loci (no overlap with any Ensembl gene), while Ensembl identifies 419.\n"
+ "These represent the most significant discrepancies in the rat genome—disputed protein-coding loci.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Summary\n"
+ "\n"
+ "| Feature                     | NCBI (RefSeq)   | Ensembl (v115) |\n"
+ "| :-------------------------- | :-------------- | :------------- |\n"
+ "| **Protein-Coding Genes**    | **23,154**      | 22,016         |\n"
+ "| **Isoform Density**         | **3.8** (mean)  | 2.0 (mean)     |\n"
+ "| **Transcripts per Gene**    | **3.02** (mean) | 2.20 (mean)    |\n"
+ "| **Orphan PC Genes**         | **1,250**       | 419            |\n"
+ "| **Unique UTR Locs**         | **129,096**     | 87,012         |\n"
+ "| **lncRNA Transcripts**      | 21,024          | **39,234**     |\n"
+ "| **Unique Non-Coding Exons** | 59,602          | **110,104**    |\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Which one to use?\n"
+ "\n"
+ "- **For Protein-Coding Studies:** **NCBI RefSeq** is the superior choice. It provides 67% more mRNA transcripts and captures a much denser alternative splicing landscape for protein-coding genes.\n"
+ "- **For RNA Biology & lncRNA:** **Ensembl** is preferred. It identifies nearly double the number of lncRNA transcripts and maintains a much larger catalog of unique non-coding exon locations (~110k vs ~60k).\n"
+ "- **For Structural Completeness:** NCBI models generally feature longer UTRs and more complex internal splicing, whereas Ensembl often uses algorithmic placeholders for UTRs (e.g., exactly 1,001 bp).\n"
;
var script = document.querySelector('script[src="rn8_annot.js"]');
var section = document.createElement('section');
script.parentNode.appendChild(section);
section.appendChild(document.createTextNode(markdownContent));
[].forEach.call(script.attributes, function (attr) {
    section.setAttribute(attr.name, script.getAttribute(attr.name));
});
section.setAttribute('data-markdown', '');
})();
