(function () {
'strict'
var markdownContent = ''
+ "# Comparison of Ensembl and NCBI GRCr8 Annotations\n"
+ "\n"
+ "<hr color=orange >\n"
+ "\n"
+ "### Hao Chen\n"
+ "\n"
+ "#### University of Tennessee Health Science Center\n"
+ "\n"
+ "Note: This presentation provides a comprehensive comparison between the Ensembl (v115) and NCBI (RefSeq) annotations for the GRCr8 rat reference genome. We will explore structural discrepancies, transcript complexity, and nomenclature conflicts.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Analysis Workflow\n"
+ "\n"
+ "- **Genomic Overview:** Global feature counts.\n"
+ "- **Gene Overview:** Biotypes, lengths, and splicing complexity.\n"
+ "- **Transcript Structure:** Exon inventory, UTR mapping, and length details.\n"
+ "- **Gene Identity:** Overlap of Symbols, IDs, and Protein models.\n"
+ "- **Nomenclature:** Detailed breakdown of naming conflicts.\n"
+ "\n"
+ "Note: Our goal is to provide a definitive recommendation on which annotation set to prefer for different research objectives.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Unique Feature Counts: High and Low Coverage\n"
+ "\n"
+ "<table> <tr><td width=50%>\n"
+ "<img src=\"./images/rn8annot/z01_feature_counts_high.png\" width=100%>\n"
+ "</td><td>\n"
+ "<img src=\"./images/rn8annot/z01_feature_counts_low.png\" width=100%>\n"
+ "</td></tr></table>\n"
+ "\n"
+ "Note:\n"
+ "Left: High-count features (Exons and CDS). Note that Ensembl has more unique exon locations (~369k vs ~344k).\n"
+ "Right: Low-count features. NCBI has a higher transcript count (~91k vs ~88k) and more unique UTR segments (~129k vs ~87k).\n"
+ "Key finding: The UTR discrepancy is large (42k extra in NCBI) because NCBI identifies many more alternative start/stop codons within the same physical exons.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Gene Biotype Distribution: Major and Minor Categories\n"
+ "\n"
+ "<table> <tr><td width=50%>\n"
+ "<img src=\"./images/rn8annot/z01_biotypes_high.png\" width=100%>\n"
+ "</td><td>\n"
+ "<img src=\"./images/rn8annot/z01_biotypes_low.png\" width=100%>\n"
+ "</td></tr></table>\n"
+ "\n"
+ "Note:\n"
+ "Left: Major biotypes (>100 genes). Protein coding counts are similar (~23k).\n"
+ "Right: Minor biotypes (<=100 genes). NCBI identifies many more small features like tRNAs (771 vs 0 in Ensembl) and lncRNAs (~11k vs ~6k).\n"
+ "Ensembl has a surplus of processed_pseudogenes.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Distribution of Gene Spans and Mature Transcript Lengths\n"
+ "\n"
+ "<table> <tr><td width=50%>\n"
+ "<img src=\"./images/rn8annot/z01_dist_gene_length.png\" width=100%>\n"
+ "</td><td>\n"
+ "<img src=\"./images/rn8annot/z01_dist_transcript_length.png\" width=100%>\n"
+ "</td></tr></table>\n"
+ "\n"
+ "Note:\n"
+ "Left: Ensembl has a longer median gene span (~10.9kb vs 6.5kb).\n"
+ "Right: NCBI has significantly longer mature transcripts (Median: 2,802 bp vs Ensembl 1,778 bp).\n"
+ "The \"Short Gene\" paradox in NCBI is caused by its inclusion of thousands of very short ncRNAs and pseudogenes that pull the median down.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Intron Length Distribution for Shared Genes\n"
+ "\n"
+ "<img src=\"./images/rn8annot/z09_intron_length_per_gene.png\" width=60%>\n"
+ "\n"
+ "Note:\n"
+ "Investigating why Ensembl genomic spans are longer despite shorter mature transcripts.\n"
+ "While medians are similar (~12kb), Ensembl has a much higher mean intron length (243kb vs 43kb).\n"
+ "This confirms that Ensembl is more aggressive in linking distal exons separated by massive intronic gaps into single gene models.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Comparison of Splicing Complexity: Transcripts and Exons\n"
+ "\n"
+ "<table> <tr><td width=50%>\n"
+ "<img src=\"./images/rn8annot/z01_dist_transcripts_per_gene.png\" width=100%>\n"
+ "</td><td>\n"
+ "<img src=\"./images/rn8annot/z01_dist_exons_per_transcript.png\" width=100%>\n"
+ "</td></tr></table>\n"
+ "\n"
+ "Note:\n"
+ "Left: NCBI shows higher transcript-per-gene counts, reflecting denser isoform annotation (3.8 isoforms per unique exon location vs Ensembl 2.0).\n"
+ "Right: NCBI transcripts contain more exons on average (11.2 vs 7.7), confirming higher structural complexity.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Unique Exon Inventory by Biotype Classification\n"
+ "\n"
+ "<img src=\"./images/rn8annot/z03_exon_inventory.png\" width=60%>\n"
+ "\n"
+ "Note:\n"
+ "Deduplicated physical exon locations categorized by usage.\n"
+ "Ensembl's total surplus (~369k) is driven by **Non-Coding** gene features (Orange), which account for ~110k unique locations.\n"
+ "In the **Protein-Coding** category (Green), NCBI actually has more unique physical locations (~285k vs ~259k).\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## UTR Mapping Consistency and Generation Efficiency\n"
+ "\n"
+ "<table> <tr><td width=33%>\n"
+ "<img src=\"./images/rn8annot/z03_utr_location_comparison.png\" width=100%>\n"
+ "</td><td width=33%>\n"
+ "<img src=\"./images/rn8annot/z03_isoform_density.png\" width=100%>\n"
+ "</td><td width=33%>\n"
+ "<img src=\"./images/rn8annot/z03_utr_efficiency.png\" width=100%>\n"
+ "</td></tr></table>\n"
+ "\n"
+ "Note:\n"
+ "Left: Only 15% of 5' UTRs match exactly. Boundary consistency is extremely low for 3' UTRs.\n"
+ "Center: Isoform Density (mean transcripts per unique exon). NCBI shows nearly double the overlap (3.8 vs 2.0).\n"
+ "Right: NCBI is more \"efficient,\" generating ~453 UTRs per 1,000 exons vs Ensembl's ~335.\n"
+ "Conclusion: NCBI captures much more structural diversity and alternative splicing boundaries.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Distribution of 5' and 3' UTR Lengths\n"
+ "\n"
+ "<img src=\"./images/rn8annot/z04_utr_length_dist.png\" width=70%>\n"
+ "\n"
+ "Note:\n"
+ "NCBI 5' UTRs are longer on average (~731 bp vs ~333 bp).\n"
+ "Ensembl 3' UTRs show an artificial spike at exactly 1,001 bp (3,356 transcripts) and 5' UTRs at 199 bp (5,920 transcripts).\n"
+ "These are algorithmic placeholders. NCBI models are more evidence-driven.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Locus Count vs Gene Symbol Overlap\n"
+ "\n"
+ "<table> <tr><td width=50%>\n"
+ "<img src=\"./images/rn8annot/z02_total_unique_loci.png\" width=100%>\n"
+ "</td><td>\n"
+ "<img src=\"./images/rn8annot/z02_gene_symbol_overlap.png\" width=100%>\n"
+ "</td></tr></table>\n"
+ "\n"
+ "Note:\n"
+ "Left: Total annotated loci are similar (~43k vs ~47k).\n"
+ "Right: Shared Symbols are much lower (~22k).\n"
+ "Conclusion: The apparent 25k \"Unique NCBI Symbols\" is a naming artifact. It includes ~11k loci that are shared physically but left unnamed in Ensembl (blank names in GTF), plus ~14k loci that are truly unique to NCBI.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Top Biotypes of Unique Gene Symbols\n"
+ "\n"
+ "<img src=\"./images/rn8annot/z07_unique_symbol_biotypes.png\" width=90%>\n"
+ "\n"
+ "Note:\n"
+ "Biotypes for the ~25k unique NCBI symbols and ~700 Ensembl symbols.\n"
+ "NCBI's surplus is primarily tRNAs and lncRNAs. Many of these appear \"unique\" because Ensembl provides no symbol name for the locus, only a stable ID.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Consistency of Protein-Coding Models\n"
+ "\n"
+ "<img src=\"./images/rn8annot/z02_cds_consistency_transcript.png\" width=60%>\n"
+ "\n"
+ "Note:\n"
+ "At the transcript level, only ~21k protein-coding models are identical.\n"
+ "NCBI provides nearly double the amount of unique protein isoforms (43k vs 24k), confirming higher transcriptomic resolution even at the protein level.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Characterization of Nomenclature Discrepancies\n"
+ "\n"
+ "<img src=\"./images/rn8annot/z05_nomenclature_comparison.png\" width=70%>\n"
+ "\n"
+ "Note:\n"
+ "Conflict analysis for the 22k genes linkable via persistent IDs.\n"
+ "Nomenclature agreement is high (95%) for shared, well-characterized genes.\n"
+ "The 25k unique NCBI symbols from earlier are largely excluded here because they lack cross-database ID links (mostly small RNAs).\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Physical Genomic Overlap of Annotated Genes\n"
+ "\n"
+ "<img src=\"./images/rn8annot/z06_gene_spatial_overlap.png\" width=60%>\n"
+ "\n"
+ "Note:\n"
+ "Reciprocal overlap analysis. ~75% of Ensembl and ~71% of NCBI genes share physical space.\n"
+ "NCBI has higher absolute shared counts (33.4k vs 32.5k), confirming \"one-to-many\" overlaps where NCBI annotates multiple smaller genes in space Ensembl defines as one.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Evidence Support for Database-Unique Gene Loci\n"
+ "\n"
+ "<img src=\"./images/rn8annot/z08_combined_unique_evidence.png\" width=60%>\n"
+ "\n"
+ "Note:\n"
+ "Nearly 50% of the ~14,000 NCBI-unique loci are supported by explicit experimental evidence (SRA, EST, or Protein data).\n"
+ "100% of Ensembl-unique loci (~10,700) are supported by Ensembl's curation criteria.\n"
+ "Both sources' unique catalogs are biologically grounded and high-confidence.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Identification of Orphan Protein-Coding Genes\n"
+ "\n"
+ "<img src=\"./images/rn8annot/z10_orphan_pc_genes.png\" width=60%>\n"
+ "\n"
+ "Note:\n"
+ "NCBI identifies 1,250 orphan protein-coding loci (no overlap with any Ensembl gene), while Ensembl identifies 419.\n"
+ "These represent the most significant discrepancies in the rat genome—disputed protein-coding loci.\n"
+ "\n"
+ "---\n"
+ "\n"
+ "## Final Recommendation: Use NCBI RefSeq\n"
+ "\n"
+ "| Feature                  | NCBI (RefSeq)   | Ensembl (v115) |\n"
+ "| :----------------------- | :-------------- | :------------- |\n"
+ "| **Protein-Coding Genes** | **23,154**      | 22,016         |\n"
+ "| **Isoform Density**      | **3.8** (mean)  | 2.0 (mean)     |\n"
+ "| **Transcripts per Gene** | **3.02** (mean) | 2.20 (mean)    |\n"
+ "| **Unique UTR Locs**      | **129,096**     | 87,012         |\n"
+ "| **Orphan PC Genes**      | **1,250**       | 419            |\n"
+ "\n"
+ "#### _Use Ensembl primarily for regulatory UTR extraction or clinical VEP pipelines._\n"
+ "\n"
+ "Note: Based on all metrics—isoform depth, structural completeness, and gene catalog size—NCBI RefSeq provides a more biologically representative and comprehensive model of the rat transcriptome.\n"
;
var script = document.querySelector('script[src="rn8_annot.js"]');
var section = document.createElement('section');
script.parentNode.appendChild(section);
section.appendChild(document.createTextNode(markdownContent));
[].forEach.call(script.attributes, function (attr) {
    section.setAttribute(attr.name, script.getAttribute(attr.name));
});
section.setAttribute('data-markdown', '');
})();
